package bindgenCheck

import (
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"
	"testing"
)

type ExternFunction struct {
	Name       string
	File       string
	Line       int
	Params     string
	ReturnType string
	FoundInWdk bool
}

type FunctionInfo struct {
	Name       string
	Params     string
	ReturnType string
	Line       int
}

type FunctionSignature struct {
	Name       string
	File       string
	Params     string
	ReturnType string
	Line       int
	RawLine    string
}

type ExternFuncLocation struct {
	File       string
	Line       int
	FoundInWdk bool
}

type TypeMismatch struct {
	FunctionName  string
	RustFile      string
	RustLine      int
	RustSignature string
	WdkSignature  string
	WdkLine       int
	MismatchType  string
}

func TestParseNtddkFunctions(t *testing.T) {
	projectRoot := filepath.Join("..", "..")
	ntddkPath := filepath.Join(projectRoot, "cmd", "bindgenCheck", "ntddk.rs")

	content, err := os.ReadFile(ntddkPath)
	if err != nil {
		t.Fatalf("Failed to read ntddk.rs: %v", err)
	}

	functionPattern := regexp.MustCompile(`pub fn ([A-Z][a-zA-Z0-9]+)\s*\(([^)]*)\)(?:\s*->\s*([^;{]+))?`)

	lines := strings.Split(string(content), "\n")
	functions := make(map[string][]FunctionInfo)

	for i, line := range lines {
		matches := functionPattern.FindStringSubmatch(line)
		if matches == nil {
			continue
		}

		name := matches[1]
		params := strings.TrimSpace(matches[2])
		returnType := "void"
		if len(matches) > 3 && matches[3] != "" {
			returnType = strings.TrimSpace(matches[3])
		}

		prefix := ""
		if len(name) >= 2 {
			for _, p := range []string{"Ps", "Mm", "Io", "Ex", "Ob", "Ke", "Rtl", "Nt", "Dbg"} {
				if strings.HasPrefix(name, p) {
					prefix = p
					break
				}
			}
		}

		if prefix == "" {
			continue
		}

		info := FunctionInfo{
			Name:       name,
			Params:     params,
			ReturnType: returnType,
			Line:       i + 1,
		}

		functions[prefix] = append(functions[prefix], info)
	}

	for prefix, funcs := range functions {
		sort.Slice(funcs, func(i, j int) bool {
			return funcs[i].Name < funcs[j].Name
		})
		functions[prefix] = funcs
	}

	var sb strings.Builder
	sb.WriteString("// Auto-generated from ntddk.rs - DO NOT EDIT\n")
	sb.WriteString("// Generated by TestParseNtddkFunctions\n\n")

	prefixes := make([]string, 0, len(functions))
	for p := range functions {
		prefixes = append(prefixes, p)
	}
	sort.Strings(prefixes)

	for _, prefix := range prefixes {
		funcs := functions[prefix]
		sb.WriteString(fmt.Sprintf("// === %s Functions (%d) ===\n", prefix, len(funcs)))
		for _, f := range funcs {
			sb.WriteString(fmt.Sprintf("// Line %d: pub fn %s(%s)", f.Line, f.Name, f.Params))
			if f.ReturnType != "void" {
				sb.WriteString(fmt.Sprintf(" -> %s", f.ReturnType))
			}
			sb.WriteString("\n")
		}
		sb.WriteString("\n")
	}

	outputPath := filepath.Join(projectRoot, "cmd", "bindgenCheck", "functions_list.txt")
	if err := os.WriteFile(outputPath, []byte(sb.String()), 0644); err != nil {
		t.Fatalf("Failed to write functions_list.txt: %v", err)
	}

	sb.Reset()
	sb.WriteString("// Auto-generated from ntddk.rs - DO NOT EDIT\n\n")
	sb.WriteString("package bindgenCheck\n\n")
	sb.WriteString("// NtddkFunctions contains all function names from ntddk.rs\n")
	sb.WriteString("var NtddkFunctions = map[string]bool{\n")

	allNames := make([]string, 0)
	for _, funcs := range functions {
		for _, f := range funcs {
			allNames = append(allNames, f.Name)
		}
	}
	sort.Strings(allNames)

	for _, name := range allNames {
		sb.WriteString(fmt.Sprintf("\t%q: true,\n", name))
	}
	sb.WriteString("}\n")

	goOutputPath := filepath.Join(projectRoot, "cmd", "bindgenCheck", "functions_gen.go")
	if err := os.WriteFile(goOutputPath, []byte(sb.String()), 0644); err != nil {
		t.Fatalf("Failed to write functions_gen.go: %v", err)
	}

	sb.Reset()
	sb.WriteString("// Auto-generated from ntddk.rs - DO NOT EDIT\n")
	sb.WriteString("// Generated by TestParseNtddkFunctions\n\n")
	sb.WriteString("/// Ntddk function signatures for Rust code validation\n")
	sb.WriteString("/// Use this to check if a function is already defined in wdk_sys\n\n")

	for _, prefix := range prefixes {
		funcs := functions[prefix]
		sb.WriteString(fmt.Sprintf("/// === %s Functions ===\n", prefix))
		for _, f := range funcs {
			sb.WriteString(fmt.Sprintf("/// %s\n", f.Name))
		}
		sb.WriteString("\n")
	}

	rustOutputPath := filepath.Join(projectRoot, "cmd", "bindgenCheck", "functions_doc.txt")
	if err := os.WriteFile(rustOutputPath, []byte(sb.String()), 0644); err != nil {
		t.Fatalf("Failed to write functions_doc.txt: %v", err)
	}

	t.Logf("Generated files:")
	t.Logf("  - functions_list.txt: %d functions", len(allNames))
	t.Logf("  - functions_gen.go: Go map for validation")
	t.Logf("  - functions_doc.txt: Rust documentation")

	for _, prefix := range prefixes {
		t.Logf("  %s: %d functions", prefix, len(functions[prefix]))
	}
}

func TestParseTypes(t *testing.T) {
	projectRoot := filepath.Join("..", "..")
	typesPath := filepath.Join(projectRoot, "cmd", "bindgenCheck", "types.rs")

	content, err := os.ReadFile(typesPath)
	if err != nil {
		t.Fatalf("Failed to read types.rs: %v", err)
	}

	structPattern := regexp.MustCompile(`pub struct ([A-Z_][a-zA-Z0-9_]*)`)
	typePattern := regexp.MustCompile(`pub type ([A-Z_][a-zA-Z0-9_]*)\s*=`)
	enumPattern := regexp.MustCompile(`pub enum ([A-Z_][a-zA-Z0-9_]*)`)

	types := make(map[string][]string)

	for _, line := range strings.Split(string(content), "\n") {
		if matches := structPattern.FindStringSubmatch(line); matches != nil {
			types["struct"] = append(types["struct"], matches[1])
		}
		if matches := typePattern.FindStringSubmatch(line); matches != nil {
			types["type"] = append(types["type"], matches[1])
		}
		if matches := enumPattern.FindStringSubmatch(line); matches != nil {
			types["enum"] = append(types["enum"], matches[1])
		}
	}

	for kind, names := range types {
		sort.Strings(names)
		types[kind] = names
	}

	var sb strings.Builder
	sb.WriteString("// Auto-generated from types.rs - DO NOT EDIT\n\n")
	sb.WriteString("package bindgenCheck\n\n")
	sb.WriteString("// NtddkTypes contains all type names from types.rs\n")
	sb.WriteString("var NtddkTypes = map[string]bool{\n")

	seen := make(map[string]bool)
	allNames := make([]string, 0)
	for _, names := range types {
		for _, name := range names {
			if !seen[name] {
				seen[name] = true
				allNames = append(allNames, name)
			}
		}
	}
	sort.Strings(allNames)

	for _, name := range allNames {
		sb.WriteString(fmt.Sprintf("\t%q: true,\n", name))
	}
	sb.WriteString("}\n")

	outputPath := filepath.Join(projectRoot, "cmd", "bindgenCheck", "types_gen.go")
	if err := os.WriteFile(outputPath, []byte(sb.String()), 0644); err != nil {
		t.Fatalf("Failed to write types_gen.go: %v", err)
	}

	t.Logf("Generated types_gen.go:")
	t.Logf("  struct: %d", len(types["struct"]))
	t.Logf("  type: %d", len(types["type"]))
	t.Logf("  enum: %d", len(types["enum"]))
}

func TestParseConstants(t *testing.T) {
	projectRoot := filepath.Join("..", "..")
	constantsPath := filepath.Join(projectRoot, "cmd", "bindgenCheck", "constants.rs")

	content, err := os.ReadFile(constantsPath)
	if err != nil {
		t.Fatalf("Failed to read constants.rs: %v", err)
	}

	constPattern := regexp.MustCompile(`pub const ([A-Z_][A-Z0-9_]*)\s*:`)

	var constants []string
	for _, line := range strings.Split(string(content), "\n") {
		if matches := constPattern.FindStringSubmatch(line); matches != nil {
			constants = append(constants, matches[1])
		}
	}

	sort.Strings(constants)

	var sb strings.Builder
	sb.WriteString("// Auto-generated from constants.rs - DO NOT EDIT\n\n")
	sb.WriteString("package bindgenCheck\n\n")
	sb.WriteString("// NtddkConstants contains all constant names from constants.rs\n")
	sb.WriteString("var NtddkConstants = map[string]bool{\n")

	for _, name := range constants {
		sb.WriteString(fmt.Sprintf("\t%q: true,\n", name))
	}
	sb.WriteString("}\n")

	outputPath := filepath.Join(projectRoot, "cmd", "bindgenCheck", "constants_gen.go")
	if err := os.WriteFile(outputPath, []byte(sb.String()), 0644); err != nil {
		t.Fatalf("Failed to write constants_gen.go: %v", err)
	}

	t.Logf("Generated constants_gen.go: %d constants", len(constants))
}

func TestScanRustExternFunctions(t *testing.T) {
	projectRoot := filepath.Join("..", "..")
	rustDriverPath := filepath.Join(projectRoot, "rust-driver", "kd", "src")
	bindgenCheckDir := filepath.Join(projectRoot, "cmd", "bindgenCheck")

	wdkFunctions := loadWdkFunctions(t, filepath.Join(bindgenCheckDir, "functions_gen.go"))

	externPattern := regexp.MustCompile(`extern\s+"C"\s*\{`)
	funcPattern := regexp.MustCompile(`fn\s+([A-Z][a-zA-Z0-9]+)\s*\(([^)]*)\)(?:\s*->\s*([^;{]+))?`)

	allExterns := make(map[string][]ExternFunction)

	err := filepath.Walk(rustDriverPath, func(path string, info os.FileInfo, err error) error {
		if err != nil {
			return err
		}

		if info.IsDir() {
			return nil
		}

		if filepath.Ext(path) != ".rs" {
			return nil
		}

		content, err := os.ReadFile(path)
		if err != nil {
			return err
		}

		lines := strings.Split(string(content), "\n")
		inExternBlock := false

		for i, line := range lines {
			if externPattern.MatchString(line) {
				inExternBlock = true
				continue
			}

			if inExternBlock {
				if strings.Contains(line, "}") {
					inExternBlock = false
					continue
				}

				if matches := funcPattern.FindStringSubmatch(line); matches != nil {
					name := matches[1]

					isWdkPrefix := false
					for _, prefix := range []string{"Ps", "Mm", "Io", "Ex", "Ob", "Ke", "Rtl", "Nt", "Dbg"} {
						if strings.HasPrefix(name, prefix) {
							isWdkPrefix = true
							break
						}
					}

					if !isWdkPrefix {
						continue
					}

					params := strings.TrimSpace(matches[2])
					returnType := "void"
					if len(matches) > 3 && matches[3] != "" {
						returnType = strings.TrimSpace(matches[3])
					}

					relPath, _ := filepath.Rel(projectRoot, path)
					extFunc := ExternFunction{
						Name:       name,
						File:       relPath,
						Line:       i + 1,
						Params:     params,
						ReturnType: returnType,
						FoundInWdk: wdkFunctions[name],
					}

					allExterns[name] = append(allExterns[name], extFunc)
				}
			}
		}

		return nil
	})

	if err != nil {
		t.Fatalf("Failed to walk rust-driver directory: %v", err)
	}

	var sb strings.Builder
	sb.WriteString("// Auto-generated Rust extern \"C\" function analysis - DO NOT EDIT\n\n")
	sb.WriteString("=== SUMMARY ===\n\n")

	missingCount := 0
	for _, funcs := range allExterns {
		if !funcs[0].FoundInWdk {
			missingCount++
		}
	}

	sb.WriteString(fmt.Sprintf("Total extern functions: %d\n", len(allExterns)))
	sb.WriteString(fmt.Sprintf("Found in WDK bindings: %d\n", len(allExterns)-missingCount))
	sb.WriteString(fmt.Sprintf("Missing from WDK bindings: %d\n\n", missingCount))

	sb.WriteString("=== FUNCTIONS MISSING FROM WDK BINDINGS ===\n\n")
	for name, funcs := range allExterns {
		if !funcs[0].FoundInWdk {
			sb.WriteString(fmt.Sprintf("%s:\n", name))
			for _, f := range funcs {
				sb.WriteString(fmt.Sprintf("  %s:%d (%s) -> %s\n", f.File, f.Line, f.Params, f.ReturnType))
			}
			sb.WriteString("\n")
		}
	}

	sb.WriteString("=== ALL EXTERN FUNCTIONS BY FILE ===\n\n")

	fileFuncs := make(map[string][]string)
	for name, funcs := range allExterns {
		for _, f := range funcs {
			fileFuncs[f.File] = append(fileFuncs[f.File], fmt.Sprintf("%s (line %d)", name, f.Line))
		}
	}

	var files []string
	for f := range fileFuncs {
		files = append(files, f)
	}
	sort.Strings(files)

	for _, file := range files {
		sb.WriteString(fmt.Sprintf("\n%s:\n", file))
		funcs := fileFuncs[file]
		sort.Strings(funcs)
		for _, f := range funcs {
			sb.WriteString(fmt.Sprintf("  - %s\n", f))
		}
	}

	sb.WriteString("\n=== ALL EXTERN FUNCTIONS BY NAME ===\n\n")

	var names []string
	for name := range allExterns {
		names = append(names, name)
	}
	sort.Strings(names)

	for _, name := range names {
		funcs := allExterns[name]
		status := "WDK"
		if !funcs[0].FoundInWdk {
			status = "MISSING"
		}
		sb.WriteString(fmt.Sprintf("%-40s %s\n", name, status))
		for _, f := range funcs {
			sb.WriteString(fmt.Sprintf("  -> %s:%d\n", f.File, f.Line))
		}
	}

	outputPath := filepath.Join(bindgenCheckDir, "rust_extern_analysis.txt")
	if err := os.WriteFile(outputPath, []byte(sb.String()), 0644); err != nil {
		t.Fatalf("Failed to write rust_extern_analysis.txt: %v", err)
	}

	sb.Reset()
	sb.WriteString("// Auto-generated - DO NOT EDIT\n\n")
	sb.WriteString("package bindgenCheck\n\n")
	sb.WriteString("// RustExternFunctions contains all extern \"C\" function declarations found in Rust code\n")
	sb.WriteString("var RustExternFunctions = map[string][]ExternFuncLocation{\n")

	for _, name := range names {
		funcs := allExterns[name]
		sb.WriteString(fmt.Sprintf("\t%q: {\n", name))
		for _, f := range funcs {
			sb.WriteString(fmt.Sprintf("\t\t{File: %q, Line: %d, FoundInWdk: %v},\n", f.File, f.Line, f.FoundInWdk))
		}
		sb.WriteString("\t},\n")
	}
	sb.WriteString("}\n")

	goOutputPath := filepath.Join(bindgenCheckDir, "rust_externs_gen.go")
	if err := os.WriteFile(goOutputPath, []byte(sb.String()), 0644); err != nil {
		t.Fatalf("Failed to write rust_externs_gen.go: %v", err)
	}

	t.Logf("Generated files:")
	t.Logf("  - rust_extern_analysis.txt: detailed analysis")
	t.Logf("  - rust_externs_gen.go: Go map for validation")
	t.Logf("  Total: %d extern functions", len(allExterns))
	t.Logf("  Missing from WDK: %d", missingCount)

	if missingCount > 0 {
		t.Logf("\nFunctions missing from WDK bindings:")
		for name, funcs := range allExterns {
			if !funcs[0].FoundInWdk {
				t.Logf("  %s (%s)", name, funcs[0].File)
			}
		}
	}
}

func loadWdkFunctions(t *testing.T, path string) map[string]bool {
	t.Helper()

	content, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("Failed to read functions_gen.go: %v", err)
	}

	functions := make(map[string]bool)
	pattern := regexp.MustCompile(`"([A-Z][a-zA-Z0-9]+)":\s*true`)

	matches := pattern.FindAllStringSubmatch(string(content), -1)
	for _, m := range matches {
		functions[m[1]] = true
	}

	return functions
}

func TestValidateTypeSignatures(t *testing.T) {
	projectRoot := filepath.Join("..", "..")
	bindgenCheckDir := filepath.Join(projectRoot, "cmd", "bindgenCheck")

	wdkSignatures := loadWdkSignatures(t, filepath.Join(bindgenCheckDir, "ntddk.rs"))

	rustExterns := scanRustExternsWithSignatures(t, projectRoot)

	var mismatches []TypeMismatch
	var notExportedFuncs []struct {
		Name  string
		Funcs []FunctionSignature
	}

	for name, funcs := range rustExterns {
		wdkSig, exists := wdkSignatures[name]
		if !exists {
			notExportedFuncs = append(notExportedFuncs, struct {
				Name  string
				Funcs []FunctionSignature
			}{Name: name, Funcs: funcs})
			continue
		}

		for _, rustFunc := range funcs {
			mismatch := compareSignatures(name, rustFunc, wdkSig)
			if mismatch != nil {
				mismatches = append(mismatches, *mismatch)
			}
		}
	}

	sort.Slice(mismatches, func(i, j int) bool {
		if mismatches[i].RustFile != mismatches[j].RustFile {
			return mismatches[i].RustFile < mismatches[j].RustFile
		}
		return mismatches[i].RustLine < mismatches[j].RustLine
	})

	sort.Slice(notExportedFuncs, func(i, j int) bool {
		return notExportedFuncs[i].Name < notExportedFuncs[j].Name
	})

	var sb strings.Builder
	sb.WriteString("// Auto-generated type signature validation report - DO NOT EDIT\n\n")
	sb.WriteString("=== TYPE SIGNATURE VALIDATION REPORT ===\n\n")

	sb.WriteString(fmt.Sprintf("Total functions checked: %d\n", len(rustExterns)))
	sb.WriteString(fmt.Sprintf("Type mismatches found: %d\n", len(mismatches)))
	sb.WriteString(fmt.Sprintf("Functions NOT exported by WDK: %d\n\n", len(notExportedFuncs)))

	if len(notExportedFuncs) > 0 {
		sb.WriteString("=== FUNCTIONS NOT EXPORTED BY WDK (need manual declaration) ===\n\n")
		sb.WriteString("// NOTE: These functions are not exported by wdk_sys bindings.\n")
		sb.WriteString("// They require manual extern \"C\" declarations with correct signatures.\n")
		sb.WriteString("// Check ntddk.rs to verify if the function exists but is not exported.\n\n")

		for _, nf := range notExportedFuncs {
			sb.WriteString(fmt.Sprintf("### %s\n", nf.Name))
			sb.WriteString("// NOT found in WDK bindings - requires manual declaration\n")
			sb.WriteString("// Locations:\n")
			for _, f := range nf.Funcs {
				sb.WriteString(fmt.Sprintf("//   - %s:%d\n", f.File, f.Line))
			}
			sb.WriteString("\n")
		}
	}

	if len(mismatches) > 0 {
		sb.WriteString("=== TYPE MISMATCHES (POTENTIAL BSOD CAUSES) ===\n\n")

		for _, m := range mismatches {
			sb.WriteString(fmt.Sprintf("FUNCTION: %s\n", m.FunctionName))
			sb.WriteString(fmt.Sprintf("  Rust File: %s:%d\n", m.RustFile, m.RustLine))
			sb.WriteString(fmt.Sprintf("  Rust Signature: fn %s\n", m.RustSignature))
			sb.WriteString(fmt.Sprintf("  WDK Signature:   fn %s (ntddk.rs:%d)\n", m.WdkSignature, m.WdkLine))
			sb.WriteString(fmt.Sprintf("  Mismatch Type: %s\n\n", m.MismatchType))
		}

		sb.WriteString("=== MISMATCHES BY FILE ===\n\n")

		fileMismatches := make(map[string][]TypeMismatch)
		for _, m := range mismatches {
			fileMismatches[m.RustFile] = append(fileMismatches[m.RustFile], m)
		}

		var files []string
		for f := range fileMismatches {
			files = append(files, f)
		}
		sort.Strings(files)

		for _, file := range files {
			sb.WriteString(fmt.Sprintf("\n%s:\n", file))
			for _, m := range fileMismatches[file] {
				sb.WriteString(fmt.Sprintf("  Line %d: %s - %s\n", m.RustLine, m.FunctionName, m.MismatchType))
			}
		}
	} else {
		sb.WriteString("No type mismatches found. All extern declarations match WDK signatures.\n")
	}

	outputPath := filepath.Join(bindgenCheckDir, "type_validation_report.txt")
	if err := os.WriteFile(outputPath, []byte(sb.String()), 0644); err != nil {
		t.Fatalf("Failed to write type_validation_report.txt: %v", err)
	}

	t.Logf("Generated type_validation_report.txt")
	t.Logf("  Total functions checked: %d", len(rustExterns))
	t.Logf("  Type mismatches found: %d", len(mismatches))
	t.Logf("  Functions NOT exported by WDK: %d", len(notExportedFuncs))

	if len(mismatches) > 0 {
		t.Logf("\n=== TYPE MISMATCHES DETECTED ===")
		for _, m := range mismatches {
			t.Logf("  %s:%d: %s - %s", m.RustFile, m.RustLine, m.FunctionName, m.MismatchType)
		}
	}

	if len(notExportedFuncs) > 0 {
		t.Logf("\n=== FUNCTIONS NOT EXPORTED BY WDK ===")
		for _, nf := range notExportedFuncs {
			t.Logf("  %s (%s)", nf.Name, nf.Funcs[0].File)
		}
	}
}

func loadWdkSignatures(t *testing.T, path string) map[string]FunctionSignature {
	t.Helper()

	content, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("Failed to read ntddk.rs: %v", err)
	}

	signatures := make(map[string]FunctionSignature)

	funcPattern := regexp.MustCompile(`pub fn ([A-Z][a-zA-Z0-9]+)\s*\(([^)]*)\)(?:\s*->\s*([^;{]+))?`)

	lines := strings.Split(string(content), "\n")
	for i, line := range lines {
		matches := funcPattern.FindStringSubmatch(line)
		if matches == nil {
			continue
		}

		name := matches[1]

		isWdkPrefix := false
		for _, prefix := range []string{"Ps", "Mm", "Io", "Ex", "Ob", "Ke", "Rtl", "Nt", "Dbg"} {
			if strings.HasPrefix(name, prefix) {
				isWdkPrefix = true
				break
			}
		}

		if !isWdkPrefix {
			continue
		}

		params := strings.TrimSpace(matches[2])
		returnType := "void"
		if len(matches) > 3 && matches[3] != "" {
			returnType = strings.TrimSpace(matches[3])
		}

		signatures[name] = FunctionSignature{
			Name:       name,
			Params:     params,
			ReturnType: returnType,
			Line:       i + 1,
			RawLine:    strings.TrimSpace(line),
		}
	}

	return signatures
}

func scanRustExternsWithSignatures(t *testing.T, projectRoot string) map[string][]FunctionSignature {
	t.Helper()

	rustDriverPath := filepath.Join(projectRoot, "rust-driver", "kd", "src")

	externs := make(map[string][]FunctionSignature)

	externPattern := regexp.MustCompile(`extern\s+"C"\s*\{`)
	funcPattern := regexp.MustCompile(`fn\s+([A-Z][a-zA-Z0-9]+)\s*\(([^)]*)\)(?:\s*->\s*([^;{]+))?`)

	err := filepath.Walk(rustDriverPath, func(path string, info os.FileInfo, err error) error {
		if err != nil {
			return err
		}

		if info.IsDir() {
			return nil
		}

		if filepath.Ext(path) != ".rs" {
			return nil
		}

		content, err := os.ReadFile(path)
		if err != nil {
			return err
		}

		lines := strings.Split(string(content), "\n")
		inExternBlock := false

		for i, line := range lines {
			if externPattern.MatchString(line) {
				inExternBlock = true
				continue
			}

			if inExternBlock {
				if strings.Contains(line, "}") {
					inExternBlock = false
					continue
				}

				if matches := funcPattern.FindStringSubmatch(line); matches != nil {
					name := matches[1]

					isWdkPrefix := false
					for _, prefix := range []string{"Ps", "Mm", "Io", "Ex", "Ob", "Ke", "Rtl", "Nt", "Dbg"} {
						if strings.HasPrefix(name, prefix) {
							isWdkPrefix = true
							break
						}
					}

					if !isWdkPrefix {
						continue
					}

					params := strings.TrimSpace(matches[2])
					returnType := "void"
					if len(matches) > 3 && matches[3] != "" {
						returnType = strings.TrimSpace(matches[3])
					}

					relPath, _ := filepath.Rel(projectRoot, path)
					sig := FunctionSignature{
						Name:       name,
						File:       relPath,
						Params:     params,
						ReturnType: returnType,
						Line:       i + 1,
						RawLine:    strings.TrimSpace(line),
					}

					externs[name] = append(externs[name], sig)
				}
			}
		}

		return nil
	})

	if err != nil {
		t.Fatalf("Failed to walk rust-driver directory: %v", err)
	}

	return externs
}

func compareSignatures(name string, rustSig FunctionSignature, wdkSig FunctionSignature) *TypeMismatch {
	rustParams := normalizeParams(rustSig.Params)
	wdkParams := normalizeParams(wdkSig.Params)

	rustReturn := normalizeType(rustSig.ReturnType)
	wdkReturn := normalizeType(wdkSig.ReturnType)

	var mismatches []string

	if rustReturn != wdkReturn {
		mismatches = append(mismatches, fmt.Sprintf("return type: rust=%s, wdk=%s", rustReturn, wdkReturn))
	}

	rustParamTypes := extractParamTypes(rustParams)
	wdkParamTypes := extractParamTypes(wdkParams)

	if len(rustParamTypes) != len(wdkParamTypes) {
		mismatches = append(mismatches, fmt.Sprintf("param count: rust=%d, wdk=%d", len(rustParamTypes), len(wdkParamTypes)))
	} else {
		for i := 0; i < len(rustParamTypes); i++ {
			rustType := normalizeType(rustParamTypes[i])
			wdkType := normalizeType(wdkParamTypes[i])

			if !typesCompatible(rustType, wdkType) {
				mismatches = append(mismatches, fmt.Sprintf("param[%d]: rust=%s, wdk=%s", i, rustType, wdkType))
			}
		}
	}

	if len(mismatches) > 0 {
		return &TypeMismatch{
			FunctionName:  name,
			RustFile:      rustSig.File,
			RustLine:      rustSig.Line,
			RustSignature: fmt.Sprintf("(%s) -> %s", rustSig.Params, rustSig.ReturnType),
			WdkSignature:  fmt.Sprintf("(%s) -> %s", wdkSig.Params, wdkSig.ReturnType),
			WdkLine:       wdkSig.Line,
			MismatchType:  strings.Join(mismatches, "; "),
		}
	}

	return nil
}

func normalizeParams(params string) string {
	params = strings.TrimSpace(params)
	params = regexp.MustCompile(`\s+`).ReplaceAllString(params, " ")
	return params
}

func normalizeType(t string) string {
	t = strings.TrimSpace(t)

	t = strings.TrimPrefix(t, "*mut ")
	t = strings.TrimPrefix(t, "*const ")
	t = strings.TrimSuffix(t, "*")
	t = strings.TrimSpace(t)

	t = regexp.MustCompile(`\s+`).ReplaceAllString(t, " ")

	return t
}

func extractParamTypes(params string) []string {
	if params == "" {
		return nil
	}

	var types []string
	depth := 0
	current := ""

	for _, ch := range params {
		switch ch {
		case '<', '(', '[', '{':
			depth++
			current += string(ch)
		case '>', ')', ']', '}':
			depth--
			current += string(ch)
		case ',':
			if depth == 0 {
				types = append(types, extractTypeFromParam(current))
				current = ""
			} else {
				current += string(ch)
			}
		default:
			current += string(ch)
		}
	}

	if current != "" {
		types = append(types, extractTypeFromParam(current))
	}

	return types
}

func extractTypeFromParam(param string) string {
	param = strings.TrimSpace(param)

	if strings.Contains(param, ":") {
		parts := strings.SplitN(param, ":", 2)
		if len(parts) == 2 {
			return strings.TrimSpace(parts[1])
		}
	}

	return param
}

func typesCompatible(rustType, wdkType string) bool {
	rustType = strings.ToLower(strings.TrimSpace(rustType))
	wdkType = strings.ToLower(strings.TrimSpace(wdkType))

	if rustType == wdkType {
		return true
	}

	pointerTypes := map[string][]string{
		"u64":  {"pvoid", "handle", "ulong64", "usize", "isize", "i64"},
		"u32":  {"ulong", "uint32", "dword"},
		"i32":  {"ntstatus", "long", "int32"},
		"bool": {"boolean"},
	}

	for rust, wdkList := range pointerTypes {
		if rustType == rust {
			for _, wdk := range wdkList {
				if wdkType == wdk || strings.Contains(wdkType, wdk) {
					return true
				}
			}
		}
	}

	if strings.HasSuffix(rustType, "*") && strings.HasSuffix(wdkType, "*") {
		return true
	}

	if strings.HasPrefix(rustType, "*") && strings.Contains(wdkType, "p") {
		return true
	}

	return false
}

func TestGenerateFixSuggestions(t *testing.T) {
	projectRoot := filepath.Join("..", "..")
	bindgenCheckDir := filepath.Join(projectRoot, "cmd", "bindgenCheck")

	wdkFunctions := loadWdkFunctions(t, filepath.Join(bindgenCheckDir, "functions_gen.go"))

	content, err := os.ReadFile(filepath.Join(bindgenCheckDir, "rust_externs_gen.go"))
	if err != nil {
		t.Fatalf("Failed to read rust_externs_gen.go: %v", err)
	}

	rustExterns := make(map[string][]ExternFuncLocation)
	namePattern := regexp.MustCompile(`"([A-Z][a-zA-Z0-9]+)":\s*\{`)
	locPattern := regexp.MustCompile(`File:\s*"([^"]+)",\s*Line:\s*(\d+),\s*FoundInWdk:\s*(true|false)`)

	lines := strings.Split(string(content), "\n")
	currentName := ""

	for _, line := range lines {
		if matches := namePattern.FindStringSubmatch(line); matches != nil {
			currentName = matches[1]
			rustExterns[currentName] = nil
		}
		if matches := locPattern.FindStringSubmatch(line); matches != nil && currentName != "" {
			loc := ExternFuncLocation{
				File:       matches[1],
				Line:       parseInt(matches[2]),
				FoundInWdk: matches[3] == "true",
			}
			rustExterns[currentName] = append(rustExterns[currentName], loc)
		}
	}

	var sb strings.Builder
	sb.WriteString("// Auto-generated fix suggestions - DO NOT EDIT\n\n")
	sb.WriteString("=== SUGGESTED FIXES FOR RUST EXTERN DECLARATIONS ===\n\n")

	sb.WriteString("## Functions that should use wdk_sys::ntddk\n\n")

	var availableFuncs []string
	for name := range rustExterns {
		if wdkFunctions[name] {
			availableFuncs = append(availableFuncs, name)
		}
	}
	sort.Strings(availableFuncs)

	for _, name := range availableFuncs {
		locs := rustExterns[name]
		sb.WriteString(fmt.Sprintf("### %s\n", name))
		sb.WriteString(fmt.Sprintf("// Found in WDK: use `use wdk_sys::ntddk::%s;`\n", name))
		sb.WriteString("// Files to update:\n")
		for _, loc := range locs {
			sb.WriteString(fmt.Sprintf("//   - %s:%d\n", loc.File, loc.Line))
		}
		sb.WriteString("\n")
	}

	sb.WriteString("## Functions NOT in WDK bindings (need manual declaration or generator update)\n\n")

	var missingFuncs []string
	for name := range rustExterns {
		if !wdkFunctions[name] {
			missingFuncs = append(missingFuncs, name)
		}
	}
	sort.Strings(missingFuncs)

	for _, name := range missingFuncs {
		locs := rustExterns[name]
		sb.WriteString(fmt.Sprintf("### %s\n", name))
		sb.WriteString("// NOT found in WDK bindings\n")
		sb.WriteString("// Files:\n")
		for _, loc := range locs {
			sb.WriteString(fmt.Sprintf("//   - %s:%d\n", loc.File, loc.Line))
		}
		sb.WriteString("\n")
	}

	outputPath := filepath.Join(bindgenCheckDir, "fix_suggestions.txt")
	if err := os.WriteFile(outputPath, []byte(sb.String()), 0644); err != nil {
		t.Fatalf("Failed to write fix_suggestions.txt: %v", err)
	}

	t.Logf("Generated fix_suggestions.txt")
	t.Logf("  Available in WDK: %d", len(availableFuncs))
	t.Logf("  Missing from WDK: %d", len(missingFuncs))
}

func parseInt(s string) int {
	var n int
	fmt.Sscanf(s, "%d", &n)
	return n
}
