name: vs2019-ci

on:
  push:
    branches:
      - master
      - dev
    tags:
      - 'v*'
    paths-ignore:
      - '.gitignore'
      - '.gitattributes'
      - '**.cmd'
      - '**.bat'
      - '**.md'
      
  pull_request:
    paths-ignore:
      - '.gitignore'
      - '.gitattributes'
      - '**.cmd'
      - '**.bat'
      - '**.md'
env:
  # WDK for Windows 10, version 2004
  WDK_URL: https://go.microsoft.com/fwlink/?linkid=2128854
  
  # Path to the solution file relative to the root of the project.
  SOLUTION_FILE_PATH: ./hyperdbg/hyperdbg.sln

  RELEASE_ZIP_FILE_NAME: hyperdbg

  BUILD_BIN_DIR: ./hyperdbg/build/bin/

jobs:
  win-amd64-build:
    runs-on: windows-2019
    strategy:
      matrix:
        BUILD_CONFIGURATION: [release, debug]
        PLATFORM: [x64]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        submodules: recursive

    - name: Setup WDK version 2004
      run: |
        $wdkSetupPath = "$Env:TEMP\wdksetup.exe"
        (New-Object Net.WebClient).DownloadFile('${{env.WDK_URL}}', $wdkSetupPath)
        Start-Process -FilePath $wdkSetupPath -ArgumentList "/quiet" -NoNewWindow -Wait     

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2
      
    - name: Build
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: msbuild /m /p:Configuration=${{matrix.BUILD_CONFIGURATION}} /p:Platform=${{matrix.PLATFORM}} ${{env.SOLUTION_FILE_PATH}}
    
    - name: Upload build directory 
      uses: actions/upload-artifact@v2
      with:
        name: build_files_${{matrix.BUILD_CONFIGURATION}}
        path: ${{ env.BUILD_BIN_DIR }}

  deploy-release:
    name: Deploy release
    needs: win-amd64-build
    runs-on: windows-2019

    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Download build files from "build" job
        uses: actions/download-artifact@v2
        with:
          name: build_files_release
          path: ${{ env.BUILD_BIN_DIR }}
                
      - name: Archive release
        uses: thedoctor0/zip-release@master
        with:
          path: ${{ env.BUILD_BIN_DIR }}release/
          type: 'zip'
          filename: ${{env.RELEASE_ZIP_FILE_NAME}}-${{ github.ref_name }}.zip

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            ${{env.RELEASE_ZIP_FILE_NAME}}-${{ github.ref_name }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
