package core
//back\HyperDbgDev\hyperdbg\hprdbghv\header\debugger\core\Debugger.h.back

const(
DEBUGGER_DEBUG_REGISTER_FOR_STEP_OVER = 0 //col:39
DEBUGGER_DEBUG_REGISTER_FOR_THREAD_MANAGEMENT = 1 //col:44
DEBUGGER_DEBUG_REGISTER_FOR_USER_MODE_ENTRY_POINT = 1 //col:49
)

type     DEBUGGER_TRIGGERING_EVENT_STATUS_SUCCESSFUL              = 0 uint32
const(
    DEBUGGER_TRIGGERING_EVENT_STATUS_SUCCESSFUL               DEBUGGER_TRIGGERING_EVENT_STATUS_TYPE =  0  //col:245
    DEBUGGER_TRIGGERING_EVENT_STATUS_SUCCESSFUL_IGNORE_EVENT  DEBUGGER_TRIGGERING_EVENT_STATUS_TYPE =  1  //col:246
    DEBUGGER_TRIGGERING_EVENT_STATUS_DEBUGGER_NOT_ENABLED     DEBUGGER_TRIGGERING_EVENT_STATUS_TYPE =  2  //col:247
    DEBUGGER_TRIGGERING_EVENT_STATUS_INVALID_EVENT_TYPE       DEBUGGER_TRIGGERING_EVENT_STATUS_TYPE =  3  //col:248
)



type (
Debugger interface{
 * command ()(ok bool)//col:111
}
)

func NewDebugger() { return & debugger{} }

func (d *debugger) * command ()(ok bool){//col:111
/* * command (i command)
 *
typedef struct _DEBUGGEE_INSTRUMENTATION_STEP_IN_TRACE
{
    BOOLEAN WaitForInstrumentationStepInMtf;
} DEBUGGEE_INSTRUMENTATION_STEP_IN_TRACE, *PDEBUGGEE_INSTRUMENTATION_STEP_IN_TRACE;*/
return true
}



