package core


const(
DEBUGGER_DEBUG_REGISTER_FOR_STEP_OVER = 0 //col:39
DEBUGGER_DEBUG_REGISTER_FOR_THREAD_MANAGEMENT = 1 //col:44
DEBUGGER_DEBUG_REGISTER_FOR_USER_MODE_ENTRY_POINT = 1 //col:49
)

const(
    DEBUGGER_TRIGGERING_EVENT_STATUS_SUCCESSFUL               =  0  //col:245
    DEBUGGER_TRIGGERING_EVENT_STATUS_SUCCESSFUL_IGNORE_EVENT  =  1  //col:246
    DEBUGGER_TRIGGERING_EVENT_STATUS_DEBUGGER_NOT_ENABLED     =  2  //col:247
    DEBUGGER_TRIGGERING_EVENT_STATUS_INVALID_EVENT_TYPE       =  3  //col:248
)




