// Auto-generated by rustgen - DO NOT EDIT
// Source: event_exception.go

#![allow(non_snake_case)]

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[repr(u32)]
pub enum ExceptionCode {
    Debug = 1,
    Nmi = 2,
    Breakpoint = 3,
    Overflow = 4,
    Bound = 5,
    InvalidOpcode = 6,
    NoMath = 7,
    DoubleFault = 8,
    CoprocessorSegment = 9,
    InvalidTss = 10,
    SegmentNotPresent = 11,
    StackSegment = 12,
    GeneralProtection = 13,
    PageFault = 14,
    FloatingPoint = 16,
    AlignmentCheck = 17,
    MachineCheck = 18,
    SimdFloatingPoint = 19,
}

#[derive(Serialize, Deserialize, Debug, Clone, Default)]
pub struct ExceptionEvent {
    #[serde(rename = "header")]
    pub header: EventHeader,
    #[serde(rename = "exception_code")]
    pub exception_code: ExceptionCode,
    #[serde(rename = "address")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub address: Option<String>,
    #[serde(rename = "error_code")]
    pub error_code: u64,
    #[serde(rename = "registers")]
    pub registers: RegisterState,
}

