// Auto-generated by rustgen - DO NOT EDIT
// Source: event_dr_access.go

#![allow(non_snake_case)]

#[derive(Serialize, Deserialize, Debug, Clone, Default)]
pub struct DrAccessEvent {
    #[serde(rename = "header")]
    pub header: EventHeader,
    #[serde(rename = "dr_number")]
    pub dr_number: u32,
    #[serde(rename = "is_write")]
    pub is_write: bool,
    #[serde(rename = "value")]
    pub value: u64,
}

