// Auto-generated by rustgen - DO NOT EDIT
// Source: event.go

#![allow(non_snake_case)]

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[repr(u32)]
pub enum EventType {
    Breakpoint = 1,
    Exception = 2,
    MemoryAccess = 3,
    SyscallEntry = 4,
    SyscallExit = 5,
    ProcessCreate = 6,
    ProcessExit = 7,
    ThreadCreate = 8,
    ThreadExit = 9,
    ModuleLoad = 10,
    ModuleUnload = 11,
    DebugPrint = 12,
    VmxExit = 13,
    Trap = 14,
    HiddenHookExec = 15,
    HiddenHookRead = 16,
    HiddenHookWrite = 17,
    Cpuid = 18,
    Tsc = 19,
    Pmc = 20,
    Interrupt = 21,
    ExceptionBitmap = 22,
    CrAccess = 23,
    DrAccess = 24,
    IoPort = 25,
    MsrRead = 26,
    MsrWrite = 27,
    EptViolation = 28,
    Vmcalled = 29,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[repr(i32)]
pub enum DebuggerEventType {
    Breakpoint = 0,
    Exception = 1,
    MemoryAccess = 2,
    Syscall = 3,
    ProcessCreate = 4,
    ProcessExit = 5,
    ThreadCreate = 6,
    ThreadExit = 7,
    ModuleLoad = 8,
    ModuleUnload = 9,
    DebugPrint = 10,
    VmxExit = 11,
    Trap = 12,
    HiddenHook = 13,
    Cpuid = 14,
    Tsc = 15,
    CrAccess = 16,
    DrAccess = 17,
    IoPort = 18,
    Msr = 19,
    EptViolation = 20,
}

#[derive(Serialize, Deserialize, Debug, Clone, Default)]
pub struct EventHeader {
    #[serde(rename = "event_type")]
    pub event_type: EventType,
    #[serde(rename = "process_id")]
    pub process_id: ProcessId,
    #[serde(rename = "thread_id")]
    pub thread_id: ThreadId,
    #[serde(rename = "core_id")]
    pub core_id: u32,
    #[serde(rename = "timestamp")]
    pub timestamp: u64,
}

