// Auto-generated by rustgen - DO NOT EDIT
// Source: event_syscall.go

#![allow(non_snake_case)]

#[derive(Serialize, Deserialize, Debug, Clone, Default)]
pub struct SyscallEvent {
    #[serde(rename = "header")]
    pub header: EventHeader,
    #[serde(rename = "syscall_number")]
    pub syscall_number: u32,
    #[serde(rename = "arguments")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub arguments: Option<Vec<u64>>,
    #[serde(rename = "return_value")]
    pub return_value: u64,
    #[serde(rename = "is_entry")]
    pub is_entry: bool,
}

