// Auto-generated by rustgen - DO NOT EDIT
// Source: event_debug_print.go

#![allow(non_snake_case)]

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[repr(u32)]
pub enum LogLevel {
    Debug = 1,
    Info = 2,
    Warn = 3,
    Error = 4,
}

#[derive(Serialize, Deserialize, Debug, Clone, Default)]
pub struct DebugPrintEvent {
    #[serde(rename = "header")]
    pub header: EventHeader,
    #[serde(rename = "message")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub message: Option<String>,
    #[serde(rename = "level")]
    pub level: LogLevel,
}

