// Auto-generated by rustgen - DO NOT EDIT

extern crate alloc;

use alloc::string::String;
use serde::{Deserialize, Serialize};

#[derive(Serialize, Deserialize, Debug)]
pub struct Response<T: Serialize> {
    pub success: bool,
    pub message: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub data: Option<T>,
}

pub type EmptyResponse = Response<()>;
pub type Empty = ();

#[derive(Clone, Debug, Serialize, Deserialize)]
pub enum DebuggerEvent {
    Breakpoint(BreakpointEvent),
    Exception(ExceptionEvent),
    MemoryAccess(MemoryAccessEvent),
    Syscall(SyscallEvent),
    ProcessCreate(ProcessEvent),
    ProcessExit(ProcessEvent),
    ThreadCreate(ThreadEvent),
    ThreadExit(ThreadEvent),
    ModuleLoad(ModuleEvent),
    ModuleUnload(ModuleEvent),
    DebugPrint(DebugPrintEvent),
    VmxExit(VmxExitEvent),
    Trap(TrapEvent),
    HiddenHook(HiddenHookEvent),
    Cpuid(CpuidEvent),
    Tsc(TscEvent),
    CrAccess(CrAccessEvent),
    DrAccess(DrAccessEvent),
    IoPort(IoPortEvent),
    Msr(MsrEvent),
    EptViolation(EptViolationEvent),
}

pub fn debugger_event_type_from_name(name: &str) -> Option<DebuggerEventType> {
    match name {
        "Breakpoint" => Some(DebuggerEventType::Breakpoint),
        "Exception" => Some(DebuggerEventType::Exception),
        "MemoryAccess" => Some(DebuggerEventType::MemoryAccess),
        "Syscall" => Some(DebuggerEventType::Syscall),
        "ProcessCreate" => Some(DebuggerEventType::ProcessCreate),
        "ProcessExit" => Some(DebuggerEventType::ProcessExit),
        "ThreadCreate" => Some(DebuggerEventType::ThreadCreate),
        "ThreadExit" => Some(DebuggerEventType::ThreadExit),
        "ModuleLoad" => Some(DebuggerEventType::ModuleLoad),
        "ModuleUnload" => Some(DebuggerEventType::ModuleUnload),
        "DebugPrint" => Some(DebuggerEventType::DebugPrint),
        "VmxExit" => Some(DebuggerEventType::VmxExit),
        "Trap" => Some(DebuggerEventType::Trap),
        "HiddenHook" => Some(DebuggerEventType::HiddenHook),
        "Cpuid" => Some(DebuggerEventType::Cpuid),
        "Tsc" => Some(DebuggerEventType::Tsc),
        "CrAccess" => Some(DebuggerEventType::CrAccess),
        "DrAccess" => Some(DebuggerEventType::DrAccess),
        "IoPort" => Some(DebuggerEventType::IoPort),
        "Msr" => Some(DebuggerEventType::Msr),
        "EptViolation" => Some(DebuggerEventType::EptViolation),
        _ => None,
    }
}

pub fn debugger_event_type_name(t: DebuggerEventType) -> &'static str {
    match t {
        DebuggerEventType::Breakpoint => "Breakpoint",
        DebuggerEventType::Exception => "Exception",
        DebuggerEventType::MemoryAccess => "MemoryAccess",
        DebuggerEventType::Syscall => "Syscall",
        DebuggerEventType::ProcessCreate => "ProcessCreate",
        DebuggerEventType::ProcessExit => "ProcessExit",
        DebuggerEventType::ThreadCreate => "ThreadCreate",
        DebuggerEventType::ThreadExit => "ThreadExit",
        DebuggerEventType::ModuleLoad => "ModuleLoad",
        DebuggerEventType::ModuleUnload => "ModuleUnload",
        DebuggerEventType::DebugPrint => "DebugPrint",
        DebuggerEventType::VmxExit => "VmxExit",
        DebuggerEventType::Trap => "Trap",
        DebuggerEventType::HiddenHook => "HiddenHook",
        DebuggerEventType::Cpuid => "Cpuid",
        DebuggerEventType::Tsc => "Tsc",
        DebuggerEventType::CrAccess => "CrAccess",
        DebuggerEventType::DrAccess => "DrAccess",
        DebuggerEventType::IoPort => "IoPort",
        DebuggerEventType::Msr => "Msr",
        DebuggerEventType::EptViolation => "EptViolation",
    }
}
