// Code generated by gengo. DO NOT EDIT.
package libdemo

import (
	"github.com/can1357/gengo/gengort"
)

const GengoLibraryName = "libdemo"

var GengoLibrary = gengort.NewLibrary(GengoLibraryName)

type (
	_Int128T           = any
	_Uint128T          = any
	__NSConstantString = any
	SizeT              = uint64
	_BuiltinMsVaList   = *byte
	_BuiltinVaList     = *byte
)

var __imp_hello gengort.PreloadProc

// Gengo init function.
func init()  { __imp_hello = GengoLibrary.ImportNow("hello") }
func Hello() { gengort.CCall0(__imp_hello.Addr()) }
