package phnt
const(
_NTBCD_H =  //col:13
MAKE_BCD_OBJECT(ObjectType, ImageType, ApplicationType) = (((ULONG)(ObjectType) << 28) | (((ULONG)(ImageType) & 0xF) << 20) | ((ULONG)(ApplicationType) & 0xFFFFF)) //col:286
MAKE_BCD_APPLICATION_OBJECT(ImageType, ApplicationType) = MAKE_BCD_OBJECT(BCD_OBJECT_TYPE_APPLICATION, (ULONG)(ImageType), (ULONG)(ApplicationType)) //col:291
GET_BCD_OBJECT_TYPE(DataType) = ((BCD_OBJECT_TYPE)(((((ULONG)DataType)) >> 28) & 0xF)) //col:294
GET_BCD_APPLICATION_IMAGE(DataType) = ((BCD_APPLICATION_IMAGE_TYPE)(((((ULONG)DataType)) >> 20) & 0xF)) //col:296
GET_BCD_APPLICATION_OBJECT(DataType) = ((BCD_APPLICATION_OBJECT_TYPE)((((ULONG)DataType)) & 0xFFFFF)) //col:298
BCD_OBJECT_OSLOADER_TYPE = MAKE_BCD_APPLICATION_OBJECT(BCD_APPLICATION_IMAGE_BOOT_APPLICATION, BCD_APPLICATION_OBJECT_WINDOWS_BOOT_LOADER) //col:301
BCD_OBJECT_DESCRIPTION_VERSION = 0x1 //col:336
MAKE_BCDE_DATA_TYPE(Class, Format, Subtype) = (((((ULONG)Class) & 0xF) << 28) | ((((ULONG)Format) & 0xF) << 24) | (((ULONG)Subtype) & 0x00FFFFFF)) //col:495
GET_BCDE_DATA_CLASS(DataType) = ((BCD_ELEMENT_DATATYPE_CLASS)(((((ULONG)DataType)) >> 28) & 0xF)) //col:498
GET_BCDE_DATA_FORMAT(DataType) = ((BCD_ELEMENT_DATATYPE_FORMAT)(((((ULONG)DataType)) >> 24) & 0xF)) //col:500
GET_BCDE_DATA_SUBTYPE(DataType) = ((ULONG)((((ULONG)DataType)) & 0x00FFFFFF)) //col:502
BCD_ELEMENT_DESCRIPTION_VERSION = 0x1 //col:610
)
type     BCD_MESSAGE_TYPE_NONE uint32
const(
    BCD_MESSAGE_TYPE_NONE BCD_MESSAGE_TYPE = 1  //col:84
    BCD_MESSAGE_TYPE_TRACE BCD_MESSAGE_TYPE = 2  //col:85
    BCD_MESSAGE_TYPE_INFORMATION BCD_MESSAGE_TYPE = 3  //col:86
    BCD_MESSAGE_TYPE_WARNING BCD_MESSAGE_TYPE = 4  //col:87
    BCD_MESSAGE_TYPE_ERROR BCD_MESSAGE_TYPE = 5  //col:88
    BCD_MESSAGE_TYPE_MAXIMUM BCD_MESSAGE_TYPE = 6  //col:89
)
type     BCD_IMPORT_NONE uint32
const(
    BCD_IMPORT_NONE BCD_IMPORT_FLAGS = 1  //col:174
    BCD_IMPORT_DELETE_FIRMWARE_OBJECTS BCD_IMPORT_FLAGS = 2  //col:175
)
type     BCD_OPEN_NONE uint32
const(
    BCD_OPEN_NONE BCD_OPEN_FLAGS = 1  //col:203
    BCD_OPEN_OPEN_STORE_OFFLINE BCD_OPEN_FLAGS = 2  //col:204
    BCD_OPEN_SYNC_FIRMWARE_ENTRIES BCD_OPEN_FLAGS = 3  //col:205
)
type     BCD_OBJECT_TYPE_NONE uint32
const(
    BCD_OBJECT_TYPE_NONE BCD_OBJECT_TYPE = 1  //col:247
    BCD_OBJECT_TYPE_APPLICATION BCD_OBJECT_TYPE = 2  //col:248
    BCD_OBJECT_TYPE_INHERITED BCD_OBJECT_TYPE = 3  //col:249
    BCD_OBJECT_TYPE_DEVICE BCD_OBJECT_TYPE = 4  //col:250
)
type     BCD_APPLICATION_OBJECT_NONE = 0 uint32
const(
    BCD_APPLICATION_OBJECT_NONE  BCD_APPLICATION_OBJECT_TYPE =  0  //col:255
    BCD_APPLICATION_OBJECT_FIRMWARE_BOOT_MANAGER  BCD_APPLICATION_OBJECT_TYPE =  1  //col:256
    BCD_APPLICATION_OBJECT_WINDOWS_BOOT_MANAGER  BCD_APPLICATION_OBJECT_TYPE =  2  //col:257
    BCD_APPLICATION_OBJECT_WINDOWS_BOOT_LOADER  BCD_APPLICATION_OBJECT_TYPE =  3  //col:258
    BCD_APPLICATION_OBJECT_WINDOWS_RESUME_APPLICATION  BCD_APPLICATION_OBJECT_TYPE =  4  //col:259
    BCD_APPLICATION_OBJECT_MEMORY_TESTER  BCD_APPLICATION_OBJECT_TYPE =  5  //col:260
    BCD_APPLICATION_OBJECT_LEGACY_NTLDR  BCD_APPLICATION_OBJECT_TYPE =  6  //col:261
    BCD_APPLICATION_OBJECT_LEGACY_SETUPLDR  BCD_APPLICATION_OBJECT_TYPE =  7  //col:262
    BCD_APPLICATION_OBJECT_BOOT_SECTOR  BCD_APPLICATION_OBJECT_TYPE =  8  //col:263
    BCD_APPLICATION_OBJECT_STARTUP_MODULE  BCD_APPLICATION_OBJECT_TYPE =  9  //col:264
    BCD_APPLICATION_OBJECT_GENERIC_APPLICATION  BCD_APPLICATION_OBJECT_TYPE =  10  //col:265
    BCD_APPLICATION_OBJECT_RESERVED  BCD_APPLICATION_OBJECT_TYPE =  0xFFFFF  //col:266
)
type     BCD_APPLICATION_IMAGE_NONE uint32
const(
    BCD_APPLICATION_IMAGE_NONE BCD_APPLICATION_IMAGE_TYPE = 1  //col:271
    BCD_APPLICATION_IMAGE_FIRMWARE_APPLICATION BCD_APPLICATION_IMAGE_TYPE = 2  //col:272
    BCD_APPLICATION_IMAGE_BOOT_APPLICATION BCD_APPLICATION_IMAGE_TYPE = 3  //col:273
    BCD_APPLICATION_IMAGE_LEGACY_LOADER BCD_APPLICATION_IMAGE_TYPE = 4  //col:274
    BCD_APPLICATION_IMAGE_REALMODE_CODE BCD_APPLICATION_IMAGE_TYPE = 5  //col:275
)
type     BCD_INHERITED_CLASS_NONE uint32
const(
    BCD_INHERITED_CLASS_NONE BCD_INHERITED_CLASS_TYPE = 1  //col:280
    BCD_INHERITED_CLASS_LIBRARY BCD_INHERITED_CLASS_TYPE = 2  //col:281
    BCD_INHERITED_CLASS_APPLICATION BCD_INHERITED_CLASS_TYPE = 3  //col:282
    BCD_INHERITED_CLASS_DEVICE BCD_INHERITED_CLASS_TYPE = 4  //col:283
)
type     BCD_COPY_NONE = 0x0 uint32
const(
    BCD_COPY_NONE  BCD_COPY_FLAGS =  0x0  //col:396
    BCD_COPY_COPY_CREATE_NEW_OBJECT_IDENTIFIER  BCD_COPY_FLAGS =  0x1  //col:397
    BCD_COPY_COPY_DELETE_EXISTING_OBJECT  BCD_COPY_FLAGS =  0x2  //col:398
    BCD_COPY_COPY_UNKNOWN_FIRMWARE_APPLICATION  BCD_COPY_FLAGS =  0x4  //col:399
    BCD_COPY_IGNORE_SETUP_TEMPLATE_ELEMENTS  BCD_COPY_FLAGS =  0x8  //col:400
    BCD_COPY_RETAIN_ELEMENT_DATA  BCD_COPY_FLAGS =  0x10  //col:401
    BCD_COPY_MIGRATE_ELEMENT_DATA  BCD_COPY_FLAGS =  0x20  //col:402
)
type     BCD_ELEMENT_DATATYPE_FORMAT_UNKNOWN uint32
const(
    BCD_ELEMENT_DATATYPE_FORMAT_UNKNOWN BCD_ELEMENT_DATATYPE_FORMAT = 1  //col:459
    BCD_ELEMENT_DATATYPE_FORMAT_DEVICE // 0x01000000 BCD_ELEMENT_DATATYPE_FORMAT = 2  //col:460
    BCD_ELEMENT_DATATYPE_FORMAT_STRING // 0x02000000 BCD_ELEMENT_DATATYPE_FORMAT = 3  //col:461
    BCD_ELEMENT_DATATYPE_FORMAT_OBJECT // 0x03000000  BCD_ELEMENT_DATATYPE_FORMAT = 4  //col:462
    BCD_ELEMENT_DATATYPE_FORMAT_OBJECTLIST // 0x04000000  BCD_ELEMENT_DATATYPE_FORMAT = 5  //col:463
    BCD_ELEMENT_DATATYPE_FORMAT_INTEGER // 0x05000000 BCD_ELEMENT_DATATYPE_FORMAT = 6  //col:464
    BCD_ELEMENT_DATATYPE_FORMAT_BOOLEAN // 0x06000000 BCD_ELEMENT_DATATYPE_FORMAT = 7  //col:465
    BCD_ELEMENT_DATATYPE_FORMAT_INTEGERLIST // 0x07000000 BCD_ELEMENT_DATATYPE_FORMAT = 8  //col:466
    BCD_ELEMENT_DATATYPE_FORMAT_BINARY // 0x08000000 BCD_ELEMENT_DATATYPE_FORMAT = 9  //col:467
)
type     BCD_ELEMENT_DATATYPE_CLASS_NONE uint32
const(
    BCD_ELEMENT_DATATYPE_CLASS_NONE BCD_ELEMENT_DATATYPE_CLASS = 1  //col:472
    BCD_ELEMENT_DATATYPE_CLASS_LIBRARY BCD_ELEMENT_DATATYPE_CLASS = 2  //col:473
    BCD_ELEMENT_DATATYPE_CLASS_APPLICATION BCD_ELEMENT_DATATYPE_CLASS = 3  //col:474
    BCD_ELEMENT_DATATYPE_CLASS_DEVICE BCD_ELEMENT_DATATYPE_CLASS = 4  //col:475
    BCD_ELEMENT_DATATYPE_CLASS_SETUPTEMPLATE BCD_ELEMENT_DATATYPE_CLASS = 5  //col:476
    BCD_ELEMENT_DATATYPE_CLASS_OEM BCD_ELEMENT_DATATYPE_CLASS = 6  //col:477
)
type     BCD_ELEMENT_DEVICE_TYPE_NONE uint32
const(
    BCD_ELEMENT_DEVICE_TYPE_NONE BCD_ELEMENT_DEVICE_TYPE = 1  //col:482
    BCD_ELEMENT_DEVICE_TYPE_BOOT_DEVICE BCD_ELEMENT_DEVICE_TYPE = 2  //col:483
    BCD_ELEMENT_DEVICE_TYPE_PARTITION BCD_ELEMENT_DEVICE_TYPE = 3  //col:484
    BCD_ELEMENT_DEVICE_TYPE_FILE BCD_ELEMENT_DEVICE_TYPE = 4  //col:485
    BCD_ELEMENT_DEVICE_TYPE_RAMDISK BCD_ELEMENT_DEVICE_TYPE = 5  //col:486
    BCD_ELEMENT_DEVICE_TYPE_UNKNOWN BCD_ELEMENT_DEVICE_TYPE = 6  //col:487
    BCD_ELEMENT_DEVICE_TYPE_QUALIFIED_PARTITION BCD_ELEMENT_DEVICE_TYPE = 7  //col:488
    BCD_ELEMENT_DEVICE_TYPE_VMBUS BCD_ELEMENT_DEVICE_TYPE = 8  //col:489
    BCD_ELEMENT_DEVICE_TYPE_LOCATE_DEVICE BCD_ELEMENT_DEVICE_TYPE = 9  //col:490
    BCD_ELEMENT_DEVICE_TYPE_URI BCD_ELEMENT_DEVICE_TYPE = 10  //col:491
    BCD_ELEMENT_DEVICE_TYPE_COMPOSITE BCD_ELEMENT_DEVICE_TYPE = 11  //col:492
)
type     BCD_FLAG_NONE = 0x0 uint32
const(
    BCD_FLAG_NONE  BCD_FLAGS =  0x0  //col:637
    BCD_FLAG_QUALIFIED_PARTITION  BCD_FLAGS =  0x1  //col:638
    BCD_FLAG_NO_DEVICE_TRANSLATION  BCD_FLAGS =  0x2  //col:639
    BCD_FLAG_ENUMERATE_INHERITED_OBJECTS  BCD_FLAGS =  0x4  //col:640
    BCD_FLAG_ENUMERATE_DEVICE_OPTIONS  BCD_FLAGS =  0x8  //col:641
    BCD_FLAG_OBSERVE_PRECEDENCE  BCD_FLAGS =  0x10  //col:642
    BCD_FLAG_DISABLE_VHD_NT_TRANSLATION  BCD_FLAGS =  0x20  //col:643
    BCD_FLAG_DISABLE_VHD_DEVICE_DETECTION  BCD_FLAGS =  0x40  //col:644
    BCD_FLAG_DISABLE_POLICY_CHECKS  BCD_FLAGS =  0x80  //col:645
)
type     /// <summary> uint32
const(
    BcdBootMgrObjectList_DisplayOrder  BcdBootMgrElementTypes =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_APPLICATION BCD_ELEMENT_DATATYPE_FORMAT_OBJECTLIST 1)  //col:730
    BcdBootMgrObjectList_BootSequence  BcdBootMgrElementTypes =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_APPLICATION BCD_ELEMENT_DATATYPE_FORMAT_OBJECTLIST 2)  //col:737
    BcdBootMgrObject_DefaultObject  BcdBootMgrElementTypes =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_APPLICATION BCD_ELEMENT_DATATYPE_FORMAT_OBJECT 3)  //col:742
    BcdBootMgrInteger_Timeout  BcdBootMgrElementTypes =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_APPLICATION BCD_ELEMENT_DATATYPE_FORMAT_INTEGER 4)  //col:749
    BcdBootMgrBoolean_AttemptResume  BcdBootMgrElementTypes =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_APPLICATION BCD_ELEMENT_DATATYPE_FORMAT_BOOLEAN 5)  //col:754
    BcdBootMgrObject_ResumeObject  BcdBootMgrElementTypes =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_APPLICATION BCD_ELEMENT_DATATYPE_FORMAT_OBJECT 6)  //col:759
    BcdBootMgrObjectList_StartupSequence  BcdBootMgrElementTypes =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_APPLICATION BCD_ELEMENT_DATATYPE_FORMAT_OBJECTLIST 7)  //col:764
    BcdBootMgrObjectList_ToolsDisplayOrder  BcdBootMgrElementTypes =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_APPLICATION BCD_ELEMENT_DATATYPE_FORMAT_OBJECTLIST 16)  //col:769
    BcdBootMgrBoolean_DisplayBootMenu  BcdBootMgrElementTypes =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_APPLICATION BCD_ELEMENT_DATATYPE_FORMAT_BOOLEAN 32)  //col:774
    BcdBootMgrBoolean_NoErrorDisplay  BcdBootMgrElementTypes =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_APPLICATION BCD_ELEMENT_DATATYPE_FORMAT_BOOLEAN 33)  //col:780
    BcdBootMgrDevice_BcdDevice  BcdBootMgrElementTypes =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_APPLICATION BCD_ELEMENT_DATATYPE_FORMAT_DEVICE 34)  //col:785
    BcdBootMgrString_BcdFilePath  BcdBootMgrElementTypes =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_APPLICATION BCD_ELEMENT_DATATYPE_FORMAT_STRING 35)  //col:790
    BcdBootMgrBoolean_HormEnabled  BcdBootMgrElementTypes =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_APPLICATION BCD_ELEMENT_DATATYPE_FORMAT_BOOLEAN 36)  //col:795
    BcdBootMgrBoolean_HiberRoot  BcdBootMgrElementTypes =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_APPLICATION BCD_ELEMENT_DATATYPE_FORMAT_BOOLEAN 37)  //col:800
    BcdBootMgrString_PasswordOverride  BcdBootMgrElementTypes =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_APPLICATION BCD_ELEMENT_DATATYPE_FORMAT_STRING 38)  //col:805
    BcdBootMgrString_PinpassPhraseOverride  BcdBootMgrElementTypes =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_APPLICATION BCD_ELEMENT_DATATYPE_FORMAT_STRING 39)  //col:810
    BcdBootMgrBoolean_ProcessCustomActionsFirst  BcdBootMgrElementTypes =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_APPLICATION BCD_ELEMENT_DATATYPE_FORMAT_BOOLEAN 40)  //col:816
    BcdBootMgrIntegerList_CustomActionsList  BcdBootMgrElementTypes =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_APPLICATION BCD_ELEMENT_DATATYPE_FORMAT_INTEGERLIST 48)  //col:821
    BcdBootMgrBoolean_PersistBootSequence  BcdBootMgrElementTypes =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_APPLICATION BCD_ELEMENT_DATATYPE_FORMAT_BOOLEAN 49)  //col:827
    BcdBootMgrBoolean_SkipStartupSequence  BcdBootMgrElementTypes =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_APPLICATION BCD_ELEMENT_DATATYPE_FORMAT_BOOLEAN 50)  //col:832
)
type     /// <summary> uint32
const(
    FirstMegabytePolicyUseNone BcdLibrary_FirstMegabytePolicy = 4  //col:840
    FirstMegabytePolicyUseAll BcdLibrary_FirstMegabytePolicy = 8  //col:844
    FirstMegabytePolicyUsePrivate BcdLibrary_FirstMegabytePolicy = 12  //col:848
)
type     DebuggerSerial = 0 uint32
const(
    DebuggerSerial  BcdLibrary_DebuggerType =  0  //col:853
    Debugger1394  BcdLibrary_DebuggerType =  1  //col:854
    DebuggerUsb  BcdLibrary_DebuggerType =  2  //col:855
    DebuggerNet  BcdLibrary_DebuggerType =  3  //col:856
    DebuggerLocal  BcdLibrary_DebuggerType =  4  //col:857
)
type     /// <summary> uint32
const(
    DebuggerStartActive BcdLibrary_DebuggerStartPolicy = 4  //col:865
    DebuggerStartAutoEnable BcdLibrary_DebuggerStartPolicy = 9  //col:870
    DebuggerStartDisable BcdLibrary_DebuggerStartPolicy = 13  //col:874
)
type     /// <summary> uint32
const(
    ConfigAccessPolicyDefault BcdLibrary_ConfigAccessPolicy = 4  //col:882
    ConfigAccessPolicyDisallowMmConfig BcdLibrary_ConfigAccessPolicy = 10  //col:888
)
type     DisplayMessageTypeDefault = 0 uint32
const(
    DisplayMessageTypeDefault  BcdLibrary_UxDisplayMessageType =  0  //col:893
    DisplayMessageTypeResume  BcdLibrary_UxDisplayMessageType =  1  //col:894
    DisplayMessageTypeHyperV  BcdLibrary_UxDisplayMessageType =  2  //col:895
    DisplayMessageTypeRecovery  BcdLibrary_UxDisplayMessageType =  3  //col:896
    DisplayMessageTypeStartupRepair  BcdLibrary_UxDisplayMessageType =  4  //col:897
    DisplayMessageTypeSystemImageRecovery  BcdLibrary_UxDisplayMessageType =  5  //col:898
    DisplayMessageTypeCommandPrompt  BcdLibrary_UxDisplayMessageType =  6  //col:899
    DisplayMessageTypeSystemRestore  BcdLibrary_UxDisplayMessageType =  7  //col:900
    DisplayMessageTypePushButtonReset  BcdLibrary_UxDisplayMessageType =  8  //col:901
)
type     /// <summary> uint32
const(
    SafemodeMinimal  typedef enum BcdLibrary_SafeBoot =  0  //col:910
    SafemodeNetwork  typedef enum BcdLibrary_SafeBoot =  1  //col:915
    SafemodeDsRepair  typedef enum BcdLibrary_SafeBoot =  2  //col:919
)
type     /// <summary> uint32
const(
    BcdLibraryDevice_ApplicationDevice  BcdLibraryElementTypes =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_LIBRARY BCD_ELEMENT_DATATYPE_FORMAT_DEVICE 1)  //col:929
    BcdLibraryString_ApplicationPath  BcdLibraryElementTypes =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_LIBRARY BCD_ELEMENT_DATATYPE_FORMAT_STRING 2)  //col:934
    BcdLibraryString_Description  BcdLibraryElementTypes =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_LIBRARY BCD_ELEMENT_DATATYPE_FORMAT_STRING 4)  //col:939
    BcdLibraryString_PreferredLocale  BcdLibraryElementTypes =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_LIBRARY BCD_ELEMENT_DATATYPE_FORMAT_STRING 5)  //col:944
    BcdLibraryObjectList_InheritedObjects  BcdLibraryElementTypes =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_LIBRARY BCD_ELEMENT_DATATYPE_FORMAT_OBJECTLIST 6)  //col:949
    BcdLibraryInteger_TruncatePhysicalMemory  BcdLibraryElementTypes =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_LIBRARY BCD_ELEMENT_DATATYPE_FORMAT_INTEGER 7)  //col:954
    BcdLibraryObjectList_RecoverySequence  BcdLibraryElementTypes =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_LIBRARY BCD_ELEMENT_DATATYPE_FORMAT_OBJECTLIST 8)  //col:959
    BcdLibraryBoolean_AutoRecoveryEnabled  BcdLibraryElementTypes =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_LIBRARY BCD_ELEMENT_DATATYPE_FORMAT_BOOLEAN 9)  //col:964
    BcdLibraryIntegerList_BadMemoryList  BcdLibraryElementTypes =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_LIBRARY BCD_ELEMENT_DATATYPE_FORMAT_INTEGERLIST 10)  //col:969
    BcdLibraryBoolean_AllowBadMemoryAccess  BcdLibraryElementTypes =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_LIBRARY BCD_ELEMENT_DATATYPE_FORMAT_BOOLEAN 11)  //col:974
    BcdLibraryInteger_FirstMegabytePolicy  BcdLibraryElementTypes =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_LIBRARY BCD_ELEMENT_DATATYPE_FORMAT_INTEGER 12)  //col:979
    BcdLibraryInteger_RelocatePhysicalMemory  BcdLibraryElementTypes =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_LIBRARY BCD_ELEMENT_DATATYPE_FORMAT_INTEGER 13)  //col:985
    BcdLibraryInteger_AvoidLowPhysicalMemory  BcdLibraryElementTypes =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_LIBRARY BCD_ELEMENT_DATATYPE_FORMAT_INTEGER 14)  //col:990
    BcdLibraryBoolean_TraditionalKsegMappings  BcdLibraryElementTypes =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_LIBRARY BCD_ELEMENT_DATATYPE_FORMAT_BOOLEAN 15)  //col:995
    BcdLibraryBoolean_DebuggerEnabled  BcdLibraryElementTypes =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_LIBRARY BCD_ELEMENT_DATATYPE_FORMAT_BOOLEAN 16)  //col:1000
    BcdLibraryInteger_DebuggerType  BcdLibraryElementTypes =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_LIBRARY BCD_ELEMENT_DATATYPE_FORMAT_INTEGER 17)  //col:1005
    BcdLibraryInteger_SerialDebuggerPortAddress  BcdLibraryElementTypes =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_LIBRARY BCD_ELEMENT_DATATYPE_FORMAT_INTEGER 18)  //col:1010
    BcdLibraryInteger_SerialDebuggerPort  BcdLibraryElementTypes =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_LIBRARY BCD_ELEMENT_DATATYPE_FORMAT_INTEGER 19)  //col:1016
    BcdLibraryInteger_SerialDebuggerBaudRate  BcdLibraryElementTypes =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_LIBRARY BCD_ELEMENT_DATATYPE_FORMAT_INTEGER 20)  //col:1021
    BcdLibraryInteger_1394DebuggerChannel  BcdLibraryElementTypes =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_LIBRARY BCD_ELEMENT_DATATYPE_FORMAT_INTEGER 21)  //col:1026
    BcdLibraryString_UsbDebuggerTargetName  BcdLibraryElementTypes =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_LIBRARY BCD_ELEMENT_DATATYPE_FORMAT_STRING 22)  //col:1031
    BcdLibraryBoolean_DebuggerIgnoreUsermodeExceptions  BcdLibraryElementTypes =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_LIBRARY BCD_ELEMENT_DATATYPE_FORMAT_BOOLEAN 23)  //col:1036
    BcdLibraryInteger_DebuggerStartPolicy  BcdLibraryElementTypes =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_LIBRARY BCD_ELEMENT_DATATYPE_FORMAT_INTEGER 24)  //col:1041
    BcdLibraryString_DebuggerBusParameters  BcdLibraryElementTypes =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_LIBRARY BCD_ELEMENT_DATATYPE_FORMAT_STRING 25)  //col:1046
    BcdLibraryInteger_DebuggerNetHostIP  BcdLibraryElementTypes =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_LIBRARY BCD_ELEMENT_DATATYPE_FORMAT_INTEGER 26)  //col:1051
    BcdLibraryInteger_DebuggerNetPort  BcdLibraryElementTypes =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_LIBRARY BCD_ELEMENT_DATATYPE_FORMAT_INTEGER 27)  //col:1056
    BcdLibraryBoolean_DebuggerNetDhcp  BcdLibraryElementTypes =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_LIBRARY BCD_ELEMENT_DATATYPE_FORMAT_BOOLEAN 28)  //col:1062
    BcdLibraryString_DebuggerNetKey  BcdLibraryElementTypes =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_LIBRARY BCD_ELEMENT_DATATYPE_FORMAT_STRING 29)  //col:1068
    BcdLibraryBoolean_DebuggerNetVM  BcdLibraryElementTypes =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_LIBRARY BCD_ELEMENT_DATATYPE_FORMAT_BOOLEAN 30)  //col:1073
    BcdLibraryString_DebuggerNetHostIpv6  BcdLibraryElementTypes =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_LIBRARY BCD_ELEMENT_DATATYPE_FORMAT_STRING 31)  //col:1078
    BcdLibraryBoolean_EmsEnabled  BcdLibraryElementTypes =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_LIBRARY BCD_ELEMENT_DATATYPE_FORMAT_BOOLEAN 32)  //col:1083
    BcdLibraryInteger_EmsPort  BcdLibraryElementTypes =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_LIBRARY BCD_ELEMENT_DATATYPE_FORMAT_INTEGER 34)  //col:1088
    BcdLibraryInteger_EmsBaudRate  BcdLibraryElementTypes =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_LIBRARY BCD_ELEMENT_DATATYPE_FORMAT_INTEGER 35)  //col:1093
    BcdLibraryString_LoadOptionsString  BcdLibraryElementTypes =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_LIBRARY BCD_ELEMENT_DATATYPE_FORMAT_STRING 48)  //col:1099
    BcdLibraryBoolean_AttemptNonBcdStart  BcdLibraryElementTypes =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_LIBRARY BCD_ELEMENT_DATATYPE_FORMAT_BOOLEAN 49)  //col:1104
    BcdLibraryBoolean_DisplayAdvancedOptions  BcdLibraryElementTypes =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_LIBRARY BCD_ELEMENT_DATATYPE_FORMAT_BOOLEAN 64)  //col:1109
    BcdLibraryBoolean_DisplayOptionsEdit  BcdLibraryElementTypes =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_LIBRARY BCD_ELEMENT_DATATYPE_FORMAT_BOOLEAN 65)  //col:1114
    BcdLibraryInteger_FVEKeyRingAddress  BcdLibraryElementTypes =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_LIBRARY BCD_ELEMENT_DATATYPE_FORMAT_INTEGER 66)  //col:1119
    BcdLibraryDevice_BsdLogDevice  BcdLibraryElementTypes =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_LIBRARY BCD_ELEMENT_DATATYPE_FORMAT_DEVICE 67)  //col:1124
    BcdLibraryString_BsdLogPath  BcdLibraryElementTypes =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_LIBRARY BCD_ELEMENT_DATATYPE_FORMAT_STRING 68)  //col:1129
    BcdLibraryBoolean_BsdPreserveLog  BcdLibraryElementTypes =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_LIBRARY BCD_ELEMENT_DATATYPE_FORMAT_BOOLEAN 69)  //col:1134
    BcdLibraryBoolean_GraphicsModeDisabled  BcdLibraryElementTypes =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_LIBRARY BCD_ELEMENT_DATATYPE_FORMAT_BOOLEAN 70)  //col:1139
    BcdLibraryInteger_ConfigAccessPolicy  BcdLibraryElementTypes =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_LIBRARY BCD_ELEMENT_DATATYPE_FORMAT_INTEGER 71)  //col:1144
    BcdLibraryBoolean_DisableIntegrityChecks  BcdLibraryElementTypes =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_LIBRARY BCD_ELEMENT_DATATYPE_FORMAT_BOOLEAN 72)  //col:1151
    BcdLibraryBoolean_AllowPrereleaseSignatures  BcdLibraryElementTypes =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_LIBRARY BCD_ELEMENT_DATATYPE_FORMAT_BOOLEAN 73)  //col:1156
    BcdLibraryString_FontPath  BcdLibraryElementTypes =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_LIBRARY BCD_ELEMENT_DATATYPE_FORMAT_STRING 74)  //col:1161
    BcdLibraryInteger_SiPolicy  BcdLibraryElementTypes =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_LIBRARY BCD_ELEMENT_DATATYPE_FORMAT_INTEGER 75)  //col:1166
    BcdLibraryInteger_FveBandId  BcdLibraryElementTypes =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_LIBRARY BCD_ELEMENT_DATATYPE_FORMAT_INTEGER 76)  //col:1171
    BcdLibraryBoolean_ConsoleExtendedInput  BcdLibraryElementTypes =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_LIBRARY BCD_ELEMENT_DATATYPE_FORMAT_BOOLEAN 80)  //col:1176
    BcdLibraryInteger_InitialConsoleInput  BcdLibraryElementTypes =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_LIBRARY BCD_ELEMENT_DATATYPE_FORMAT_INTEGER 81)  //col:1181
    BcdLibraryInteger_GraphicsResolution  BcdLibraryElementTypes =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_LIBRARY BCD_ELEMENT_DATATYPE_FORMAT_INTEGER 82)  //col:1187
    BcdLibraryBoolean_RestartOnFailure  BcdLibraryElementTypes =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_LIBRARY BCD_ELEMENT_DATATYPE_FORMAT_BOOLEAN 83)  //col:1192
    BcdLibraryBoolean_GraphicsForceHighestMode  BcdLibraryElementTypes =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_LIBRARY BCD_ELEMENT_DATATYPE_FORMAT_BOOLEAN 84)  //col:1199
    BcdLibraryBoolean_IsolatedExecutionContext  BcdLibraryElementTypes =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_LIBRARY BCD_ELEMENT_DATATYPE_FORMAT_BOOLEAN 96)  //col:1207
    BcdLibraryInteger_BootUxDisplayMessage  BcdLibraryElementTypes =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_LIBRARY BCD_ELEMENT_DATATYPE_FORMAT_INTEGER 101)  //col:1213
    BcdLibraryInteger_BootUxDisplayMessageOverride  BcdLibraryElementTypes =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_LIBRARY BCD_ELEMENT_DATATYPE_FORMAT_INTEGER 102)  //col:1218
    BcdLibraryBoolean_BootUxLogoDisable  BcdLibraryElementTypes =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_LIBRARY BCD_ELEMENT_DATATYPE_FORMAT_BOOLEAN 103)  //col:1223
    BcdLibraryBoolean_BootUxTextDisable  BcdLibraryElementTypes =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_LIBRARY BCD_ELEMENT_DATATYPE_FORMAT_BOOLEAN 104)  //col:1228
    BcdLibraryBoolean_BootUxProgressDisable  BcdLibraryElementTypes =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_LIBRARY BCD_ELEMENT_DATATYPE_FORMAT_BOOLEAN 105)  //col:1233
    BcdLibraryBoolean_BootUxFadeDisable  BcdLibraryElementTypes =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_LIBRARY BCD_ELEMENT_DATATYPE_FORMAT_BOOLEAN 106)  //col:1238
    BcdLibraryBoolean_BootUxReservePoolDebug  BcdLibraryElementTypes =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_LIBRARY BCD_ELEMENT_DATATYPE_FORMAT_BOOLEAN 107)  //col:1243
    BcdLibraryBoolean_BootUxDisable  BcdLibraryElementTypes =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_LIBRARY BCD_ELEMENT_DATATYPE_FORMAT_BOOLEAN 108)  //col:1248
    BcdLibraryInteger_BootUxFadeFrames  BcdLibraryElementTypes =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_LIBRARY BCD_ELEMENT_DATATYPE_FORMAT_INTEGER 109)  //col:1253
    BcdLibraryBoolean_BootUxDumpStats  BcdLibraryElementTypes =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_LIBRARY BCD_ELEMENT_DATATYPE_FORMAT_BOOLEAN 110)  //col:1258
    BcdLibraryBoolean_BootUxShowStats  BcdLibraryElementTypes =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_LIBRARY BCD_ELEMENT_DATATYPE_FORMAT_BOOLEAN 111)  //col:1263
    BcdLibraryBoolean_MultiBootSystem  BcdLibraryElementTypes =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_LIBRARY BCD_ELEMENT_DATATYPE_FORMAT_BOOLEAN 113)  //col:1268
    BcdLibraryBoolean_ForceNoKeyboard  BcdLibraryElementTypes =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_LIBRARY BCD_ELEMENT_DATATYPE_FORMAT_BOOLEAN 114)  //col:1273
    BcdLibraryInteger_AliasWindowsKey  BcdLibraryElementTypes =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_LIBRARY BCD_ELEMENT_DATATYPE_FORMAT_INTEGER 115)  //col:1278
    BcdLibraryBoolean_BootShutdownDisabled  BcdLibraryElementTypes =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_LIBRARY BCD_ELEMENT_DATATYPE_FORMAT_BOOLEAN 116)  //col:1283
    BcdLibraryInteger_PerformanceFrequency  BcdLibraryElementTypes =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_LIBRARY BCD_ELEMENT_DATATYPE_FORMAT_INTEGER 117)  //col:1288
    BcdLibraryInteger_SecurebootRawPolicy  BcdLibraryElementTypes =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_LIBRARY BCD_ELEMENT_DATATYPE_FORMAT_INTEGER 118)  //col:1293
    BcdLibraryIntegerList_AllowedInMemorySettings  BcdLibraryElementTypes =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_LIBRARY BCD_ELEMENT_DATATYPE_FORMAT_INTEGER 119)  //col:1299
    BcdLibraryInteger_BootUxBitmapTransitionTime  BcdLibraryElementTypes =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_LIBRARY BCD_ELEMENT_DATATYPE_FORMAT_INTEGER 121)  //col:1304
    BcdLibraryBoolean_TwoBootImages  BcdLibraryElementTypes =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_LIBRARY BCD_ELEMENT_DATATYPE_FORMAT_BOOLEAN 122)  //col:1309
    BcdLibraryBoolean_ForceFipsCrypto  BcdLibraryElementTypes =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_LIBRARY BCD_ELEMENT_DATATYPE_FORMAT_BOOLEAN 123)  //col:1315
    BcdLibraryInteger_BootErrorUx  BcdLibraryElementTypes =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_LIBRARY BCD_ELEMENT_DATATYPE_FORMAT_INTEGER 125)  //col:1320
    BcdLibraryBoolean_AllowFlightSignatures  BcdLibraryElementTypes =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_LIBRARY BCD_ELEMENT_DATATYPE_FORMAT_BOOLEAN 126)  //col:1325
    BcdLibraryInteger_BootMeasurementLogFormat  BcdLibraryElementTypes =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_LIBRARY BCD_ELEMENT_DATATYPE_FORMAT_INTEGER 127)  //col:1330
    BcdLibraryInteger_DisplayRotation  BcdLibraryElementTypes =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_LIBRARY BCD_ELEMENT_DATATYPE_FORMAT_INTEGER 128)  //col:1335
    BcdLibraryInteger_LogControl  BcdLibraryElementTypes =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_LIBRARY BCD_ELEMENT_DATATYPE_FORMAT_INTEGER 129)  //col:1340
    BcdLibraryBoolean_NoFirmwareSync  BcdLibraryElementTypes =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_LIBRARY BCD_ELEMENT_DATATYPE_FORMAT_BOOLEAN 130)  //col:1345
    BcdLibraryDevice_WindowsSystemDevice  BcdLibraryElementTypes =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_LIBRARY BCD_ELEMENT_DATATYPE_FORMAT_DEVICE 132)  //col:1350
    BcdLibraryBoolean_NumLockOn  BcdLibraryElementTypes =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_LIBRARY BCD_ELEMENT_DATATYPE_FORMAT_BOOLEAN 135)  //col:1355
    BcdLibraryString_AdditionalCiPolicy  BcdLibraryElementTypes =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_LIBRARY BCD_ELEMENT_DATATYPE_FORMAT_STRING 136)  //col:1360
)
type     /// <summary> uint32
const(
    BcdSetupInteger_DeviceType  BcdTemplateElementTypes =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_SETUPTEMPLATE BCD_ELEMENT_DATATYPE_FORMAT_INTEGER 1)  //col:1369
    BcdSetupString_ApplicationRelativePath  BcdTemplateElementTypes =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_SETUPTEMPLATE BCD_ELEMENT_DATATYPE_FORMAT_STRING 2)  //col:1374
    BcdSetupString_RamdiskDeviceRelativePath  BcdTemplateElementTypes =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_SETUPTEMPLATE BCD_ELEMENT_DATATYPE_FORMAT_STRING 3)  //col:1379
    BcdSetupBoolean_OmitOsLoaderElements  BcdTemplateElementTypes =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_SETUPTEMPLATE BCD_ELEMENT_DATATYPE_FORMAT_BOOLEAN 4)  //col:1384
    BcdSetupIntegerList_ElementsToMigrateList  BcdTemplateElementTypes =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_SETUPTEMPLATE BCD_ELEMENT_DATATYPE_FORMAT_INTEGERLIST 6)  //col:1389
    BcdSetupBoolean_RecoveryOs  BcdTemplateElementTypes =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_SETUPTEMPLATE BCD_ELEMENT_DATATYPE_FORMAT_BOOLEAN 16)  //col:1394
)
type     /// <summary> uint32
const(
    NxPolicyOptIn  BcdOSLoader_NxPolicy =  0  //col:1405
    NxPolicyOptOut  BcdOSLoader_NxPolicy =  1  //col:1409
    NxPolicyAlwaysOff  BcdOSLoader_NxPolicy =  2  //col:1413
    NxPolicyAlwaysOn  BcdOSLoader_NxPolicy =  3  //col:1417
)
type     /// <summary> uint32
const(
    PaePolicyDefault  BcdOSLoader_PAEPolicy =  0  //col:1428
    PaePolicyForceEnable  BcdOSLoader_PAEPolicy =  1  //col:1432
    PaePolicyForceDisable  BcdOSLoader_PAEPolicy =  2  //col:1436
)
type     /// <summary> uint32
const(
    BootStatusPolicyDisplayAllFailures  BcdOSLoader_BootStatusPolicy =  0  //col:1444
    BootStatusPolicyIgnoreAllFailures  BcdOSLoader_BootStatusPolicy =  1  //col:1448
    BootStatusPolicyIgnoreShutdownFailures  BcdOSLoader_BootStatusPolicy =  2  //col:1452
    BootStatusPolicyIgnoreBootFailures  BcdOSLoader_BootStatusPolicy =  3  //col:1456
    BootStatusPolicyIgnoreCheckpointFailures  BcdOSLoader_BootStatusPolicy =  4  //col:1460
    BootStatusPolicyDisplayShutdownFailures  BcdOSLoader_BootStatusPolicy =  5  //col:1464
    BootStatusPolicyDisplayBootFailures  BcdOSLoader_BootStatusPolicy =  6  //col:1468
    BootStatusPolicyDisplayCheckpointFailures  BcdOSLoader_BootStatusPolicy =  7  //col:1472
)
type     /// <summary> uint32
const(
    BcdOSLoaderDevice_OSDevice  BcdOSLoaderElementTypes =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_APPLICATION BCD_ELEMENT_DATATYPE_FORMAT_DEVICE 1)  //col:1482
    BcdOSLoaderString_SystemRoot  BcdOSLoaderElementTypes =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_APPLICATION BCD_ELEMENT_DATATYPE_FORMAT_STRING 2)  //col:1487
    BcdOSLoaderObject_AssociatedResumeObject  BcdOSLoaderElementTypes =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_APPLICATION BCD_ELEMENT_DATATYPE_FORMAT_OBJECT 3)  //col:1492
    BcdOSLoaderBoolean_StampDisks  BcdOSLoaderElementTypes =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_APPLICATION BCD_ELEMENT_DATATYPE_FORMAT_BOOLEAN 4)  //col:1497
    BcdOSLoaderBoolean_DetectKernelAndHal  BcdOSLoaderElementTypes =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_APPLICATION BCD_ELEMENT_DATATYPE_FORMAT_BOOLEAN 16)  //col:1502
    BcdOSLoaderString_KernelPath  BcdOSLoaderElementTypes =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_APPLICATION BCD_ELEMENT_DATATYPE_FORMAT_STRING 17)  //col:1507
    BcdOSLoaderString_HalPath  BcdOSLoaderElementTypes =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_APPLICATION BCD_ELEMENT_DATATYPE_FORMAT_STRING 18)  //col:1512
    BcdOSLoaderString_DbgTransportPath  BcdOSLoaderElementTypes =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_APPLICATION BCD_ELEMENT_DATATYPE_FORMAT_STRING 19)  //col:1517
    BcdOSLoaderInteger_NxPolicy  BcdOSLoaderElementTypes =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_APPLICATION BCD_ELEMENT_DATATYPE_FORMAT_INTEGER 32)  //col:1522
    BcdOSLoaderInteger_PAEPolicy  BcdOSLoaderElementTypes =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_APPLICATION BCD_ELEMENT_DATATYPE_FORMAT_INTEGER 33)  //col:1527
    BcdOSLoaderBoolean_WinPEMode  BcdOSLoaderElementTypes =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_APPLICATION BCD_ELEMENT_DATATYPE_FORMAT_BOOLEAN 34)  //col:1532
    BcdOSLoaderBoolean_DisableCrashAutoReboot  BcdOSLoaderElementTypes =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_APPLICATION BCD_ELEMENT_DATATYPE_FORMAT_BOOLEAN 36)  //col:1537
    BcdOSLoaderBoolean_UseLastGoodSettings  BcdOSLoaderElementTypes =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_APPLICATION BCD_ELEMENT_DATATYPE_FORMAT_BOOLEAN 37)  //col:1542
    BcdOSLoaderBoolean_DisableCodeIntegrityChecks  BcdOSLoaderElementTypes =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_APPLICATION BCD_ELEMENT_DATATYPE_FORMAT_BOOLEAN 38)  //col:1547
    BcdOSLoaderBoolean_AllowPrereleaseSignatures  BcdOSLoaderElementTypes =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_APPLICATION BCD_ELEMENT_DATATYPE_FORMAT_BOOLEAN 39)  //col:1552
    BcdOSLoaderBoolean_NoLowMemory  BcdOSLoaderElementTypes =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_APPLICATION BCD_ELEMENT_DATATYPE_FORMAT_BOOLEAN 48)  //col:1558
    BcdOSLoaderInteger_RemoveMemory  BcdOSLoaderElementTypes =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_APPLICATION BCD_ELEMENT_DATATYPE_FORMAT_INTEGER 49)  //col:1563
    BcdOSLoaderInteger_IncreaseUserVa  BcdOSLoaderElementTypes =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_APPLICATION BCD_ELEMENT_DATATYPE_FORMAT_INTEGER 50)  //col:1570
    BcdOSLoaderInteger_PerformaceDataMemory  BcdOSLoaderElementTypes =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_APPLICATION BCD_ELEMENT_DATATYPE_FORMAT_INTEGER 51)  //col:1575
    BcdOSLoaderBoolean_UseVgaDriver  BcdOSLoaderElementTypes =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_APPLICATION BCD_ELEMENT_DATATYPE_FORMAT_BOOLEAN 64)  //col:1580
    BcdOSLoaderBoolean_DisableBootDisplay  BcdOSLoaderElementTypes =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_APPLICATION BCD_ELEMENT_DATATYPE_FORMAT_BOOLEAN 65)  //col:1586
    BcdOSLoaderBoolean_DisableVesaBios  BcdOSLoaderElementTypes =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_APPLICATION BCD_ELEMENT_DATATYPE_FORMAT_BOOLEAN 66)  //col:1592
    BcdOSLoaderBoolean_DisableVgaMode  BcdOSLoaderElementTypes =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_APPLICATION BCD_ELEMENT_DATATYPE_FORMAT_BOOLEAN 67)  //col:1597
    BcdOSLoaderInteger_ClusterModeAddressing  BcdOSLoaderElementTypes =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_APPLICATION BCD_ELEMENT_DATATYPE_FORMAT_INTEGER 80)  //col:1602
    BcdOSLoaderBoolean_UsePhysicalDestination  BcdOSLoaderElementTypes =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_APPLICATION BCD_ELEMENT_DATATYPE_FORMAT_BOOLEAN 81)  //col:1607
    BcdOSLoaderInteger_RestrictApicCluster  BcdOSLoaderElementTypes =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_APPLICATION BCD_ELEMENT_DATATYPE_FORMAT_INTEGER 82)  //col:1612
    BcdOSLoaderString_OSLoaderTypeEVStore  BcdOSLoaderElementTypes =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_APPLICATION BCD_ELEMENT_DATATYPE_FORMAT_STRING 83)  //col:1617
    BcdOSLoaderBoolean_UseLegacyApicMode  BcdOSLoaderElementTypes =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_APPLICATION BCD_ELEMENT_DATATYPE_FORMAT_BOOLEAN 84)  //col:1622
    BcdOSLoaderInteger_X2ApicPolicy  BcdOSLoaderElementTypes =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_APPLICATION BCD_ELEMENT_DATATYPE_FORMAT_INTEGER 85)  //col:1629
    BcdOSLoaderBoolean_UseBootProcessorOnly  BcdOSLoaderElementTypes =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_APPLICATION BCD_ELEMENT_DATATYPE_FORMAT_BOOLEAN 96)  //col:1634
    BcdOSLoaderInteger_NumberOfProcessors  BcdOSLoaderElementTypes =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_APPLICATION BCD_ELEMENT_DATATYPE_FORMAT_INTEGER 97)  //col:1639
    BcdOSLoaderBoolean_ForceMaximumProcessors  BcdOSLoaderElementTypes =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_APPLICATION BCD_ELEMENT_DATATYPE_FORMAT_BOOLEAN 98)  //col:1644
    BcdOSLoaderBoolean_ProcessorConfigurationFlags  BcdOSLoaderElementTypes =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_APPLICATION BCD_ELEMENT_DATATYPE_FORMAT_INTEGER 99)  //col:1649
    BcdOSLoaderBoolean_MaximizeGroupsCreated  BcdOSLoaderElementTypes =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_APPLICATION BCD_ELEMENT_DATATYPE_FORMAT_BOOLEAN 100)  //col:1654
    BcdOSLoaderBoolean_ForceGroupAwareness  BcdOSLoaderElementTypes =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_APPLICATION BCD_ELEMENT_DATATYPE_FORMAT_BOOLEAN 101)  //col:1659
    BcdOSLoaderInteger_GroupSize  BcdOSLoaderElementTypes =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_APPLICATION BCD_ELEMENT_DATATYPE_FORMAT_INTEGER 102)  //col:1664
    BcdOSLoaderInteger_UseFirmwarePciSettings  BcdOSLoaderElementTypes =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_APPLICATION BCD_ELEMENT_DATATYPE_FORMAT_BOOLEAN 112)  //col:1669
    BcdOSLoaderInteger_MsiPolicy  BcdOSLoaderElementTypes =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_APPLICATION BCD_ELEMENT_DATATYPE_FORMAT_INTEGER 113)  //col:1674
    BcdOSLoaderInteger_PciExpressPolicy  BcdOSLoaderElementTypes =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_APPLICATION BCD_ELEMENT_DATATYPE_FORMAT_INTEGER 114)  //col:1679
    BcdOSLoaderInteger_SafeBoot  BcdOSLoaderElementTypes =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_APPLICATION BCD_ELEMENT_DATATYPE_FORMAT_INTEGER 128)  //col:1684
    BcdOSLoaderBoolean_SafeBootAlternateShell  BcdOSLoaderElementTypes =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_APPLICATION BCD_ELEMENT_DATATYPE_FORMAT_BOOLEAN 129)  //col:1690
    BcdOSLoaderBoolean_BootLogInitialization  BcdOSLoaderElementTypes =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_APPLICATION BCD_ELEMENT_DATATYPE_FORMAT_BOOLEAN 144)  //col:1695
    BcdOSLoaderBoolean_VerboseObjectLoadMode  BcdOSLoaderElementTypes =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_APPLICATION BCD_ELEMENT_DATATYPE_FORMAT_BOOLEAN 145)  //col:1700
    BcdOSLoaderBoolean_KernelDebuggerEnabled  BcdOSLoaderElementTypes =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_APPLICATION BCD_ELEMENT_DATATYPE_FORMAT_BOOLEAN 160)  //col:1705
    BcdOSLoaderBoolean_DebuggerHalBreakpoint  BcdOSLoaderElementTypes =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_APPLICATION BCD_ELEMENT_DATATYPE_FORMAT_BOOLEAN 161)  //col:1710
    BcdOSLoaderBoolean_UsePlatformClock  BcdOSLoaderElementTypes =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_APPLICATION BCD_ELEMENT_DATATYPE_FORMAT_BOOLEAN 162)  //col:1715
    BcdOSLoaderBoolean_ForceLegacyPlatform  BcdOSLoaderElementTypes =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_APPLICATION BCD_ELEMENT_DATATYPE_FORMAT_BOOLEAN 163)  //col:1721
    BcdOSLoaderBoolean_UsePlatformTick  BcdOSLoaderElementTypes =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_APPLICATION BCD_ELEMENT_DATATYPE_FORMAT_BOOLEAN 164)  //col:1726
    BcdOSLoaderBoolean_DisableDynamicTick  BcdOSLoaderElementTypes =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_APPLICATION BCD_ELEMENT_DATATYPE_FORMAT_BOOLEAN 165)  //col:1731
    BcdOSLoaderInteger_TscSyncPolicy  BcdOSLoaderElementTypes =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_APPLICATION BCD_ELEMENT_DATATYPE_FORMAT_INTEGER 166)  //col:1737
    BcdOSLoaderBoolean_EmsEnabled  BcdOSLoaderElementTypes =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_APPLICATION BCD_ELEMENT_DATATYPE_FORMAT_BOOLEAN 176)  //col:1742
    BcdOSLoaderInteger_ForceFailure  BcdOSLoaderElementTypes =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_APPLICATION BCD_ELEMENT_DATATYPE_FORMAT_INTEGER 192)  //col:1747
    BcdOSLoaderInteger_DriverLoadFailurePolicy  BcdOSLoaderElementTypes =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_APPLICATION BCD_ELEMENT_DATATYPE_FORMAT_INTEGER 193)  //col:1753
    BcdOSLoaderInteger_BootMenuPolicy  BcdOSLoaderElementTypes =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_APPLICATION BCD_ELEMENT_DATATYPE_FORMAT_INTEGER 194)  //col:1759
    BcdOSLoaderBoolean_AdvancedOptionsOneTime  BcdOSLoaderElementTypes =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_APPLICATION BCD_ELEMENT_DATATYPE_FORMAT_BOOLEAN 195)  //col:1765
    BcdOSLoaderBoolean_OptionsEditOneTime  BcdOSLoaderElementTypes =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_APPLICATION BCD_ELEMENT_DATATYPE_FORMAT_BOOLEAN 196)  //col:1770
    BcdOSLoaderInteger_BootStatusPolicy  BcdOSLoaderElementTypes =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_APPLICATION BCD_ELEMENT_DATATYPE_FORMAT_INTEGER 224)  //col:1775
    BcdOSLoaderBoolean_DisableElamDrivers  BcdOSLoaderElementTypes =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_APPLICATION BCD_ELEMENT_DATATYPE_FORMAT_BOOLEAN 225)  //col:1781
    BcdOSLoaderInteger_HypervisorLaunchType  BcdOSLoaderElementTypes =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_APPLICATION BCD_ELEMENT_DATATYPE_FORMAT_INTEGER 240)  //col:1786
    BcdOSLoaderString_HypervisorPath  BcdOSLoaderElementTypes =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_APPLICATION BCD_ELEMENT_DATATYPE_FORMAT_INTEGER 241)  //col:1791
    BcdOSLoaderBoolean_HypervisorDebuggerEnabled  BcdOSLoaderElementTypes =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_APPLICATION BCD_ELEMENT_DATATYPE_FORMAT_BOOLEAN 242)  //col:1796
    BcdOSLoaderInteger_HypervisorDebuggerType  BcdOSLoaderElementTypes =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_APPLICATION BCD_ELEMENT_DATATYPE_FORMAT_INTEGER 243)  //col:1801
    BcdOSLoaderInteger_HypervisorDebuggerPortNumber  BcdOSLoaderElementTypes =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_APPLICATION BCD_ELEMENT_DATATYPE_FORMAT_INTEGER 244)  //col:1806
    BcdOSLoaderInteger_HypervisorDebuggerBaudrate  BcdOSLoaderElementTypes =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_APPLICATION BCD_ELEMENT_DATATYPE_FORMAT_INTEGER 245)  //col:1811
    BcdOSLoaderInteger_HypervisorDebugger1394Channel  BcdOSLoaderElementTypes =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_APPLICATION BCD_ELEMENT_DATATYPE_FORMAT_INTEGER 246)  //col:1816
    BcdOSLoaderInteger_BootUxPolicy  BcdOSLoaderElementTypes =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_APPLICATION BCD_ELEMENT_DATATYPE_FORMAT_INTEGER 247)  //col:1821
    BcdOSLoaderInteger_HypervisorSlatDisabled  BcdOSLoaderElementTypes =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_APPLICATION BCD_ELEMENT_DATATYPE_FORMAT_STRING 248)  //col:1826
    BcdOSLoaderString_HypervisorDebuggerBusParams  BcdOSLoaderElementTypes =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_APPLICATION BCD_ELEMENT_DATATYPE_FORMAT_STRING 249)  //col:1832
    BcdOSLoaderInteger_HypervisorNumProc  BcdOSLoaderElementTypes =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_APPLICATION BCD_ELEMENT_DATATYPE_FORMAT_INTEGER 250)  //col:1837
    BcdOSLoaderInteger_HypervisorRootProcPerNode  BcdOSLoaderElementTypes =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_APPLICATION BCD_ELEMENT_DATATYPE_FORMAT_INTEGER 251)  //col:1842
    BcdOSLoaderBoolean_HypervisorUseLargeVTlb  BcdOSLoaderElementTypes =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_APPLICATION BCD_ELEMENT_DATATYPE_FORMAT_BOOLEAN 252)  //col:1847
    BcdOSLoaderInteger_HypervisorDebuggerNetHostIp  BcdOSLoaderElementTypes =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_APPLICATION BCD_ELEMENT_DATATYPE_FORMAT_INTEGER 253)  //col:1852
    BcdOSLoaderInteger_HypervisorDebuggerNetHostPort  BcdOSLoaderElementTypes =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_APPLICATION BCD_ELEMENT_DATATYPE_FORMAT_INTEGER 254)  //col:1857
    BcdOSLoaderInteger_HypervisorDebuggerPages  BcdOSLoaderElementTypes =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_APPLICATION BCD_ELEMENT_DATATYPE_FORMAT_INTEGER 255)  //col:1862
    BcdOSLoaderInteger_TpmBootEntropyPolicy  BcdOSLoaderElementTypes =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_APPLICATION BCD_ELEMENT_DATATYPE_FORMAT_INTEGER 256)  //col:1867
    BcdOSLoaderString_HypervisorDebuggerNetKey  BcdOSLoaderElementTypes =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_APPLICATION BCD_ELEMENT_DATATYPE_FORMAT_STRING 272)  //col:1872
    BcdOSLoaderString_HypervisorProductSkuType  BcdOSLoaderElementTypes =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_APPLICATION BCD_ELEMENT_DATATYPE_FORMAT_STRING 274)  //col:1877
    BcdOSLoaderInteger_HypervisorRootProc  BcdOSLoaderElementTypes =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_APPLICATION BCD_ELEMENT_DATATYPE_FORMAT_STRING 275)  //col:1882
    BcdOSLoaderBoolean_HypervisorDebuggerNetDhcp  BcdOSLoaderElementTypes =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_APPLICATION BCD_ELEMENT_DATATYPE_FORMAT_BOOLEAN 276)  //col:1887
    BcdOSLoaderInteger_HypervisorIommuPolicy  BcdOSLoaderElementTypes =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_APPLICATION BCD_ELEMENT_DATATYPE_FORMAT_INTEGER 277)  //col:1892
    BcdOSLoaderBoolean_HypervisorUseVApic  BcdOSLoaderElementTypes =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_APPLICATION BCD_ELEMENT_DATATYPE_FORMAT_BOOLEAN 278)  //col:1897
    BcdOSLoaderString_HypervisorLoadOptions  BcdOSLoaderElementTypes =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_APPLICATION BCD_ELEMENT_DATATYPE_FORMAT_STRING 279)  //col:1902
    BcdOSLoaderInteger_HypervisorMsrFilterPolicy  BcdOSLoaderElementTypes =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_APPLICATION BCD_ELEMENT_DATATYPE_FORMAT_INTEGER 280)  //col:1907
    BcdOSLoaderInteger_HypervisorMmioNxPolicy  BcdOSLoaderElementTypes =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_APPLICATION BCD_ELEMENT_DATATYPE_FORMAT_INTEGER 281)  //col:1912
    BcdOSLoaderInteger_HypervisorSchedulerType  BcdOSLoaderElementTypes =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_APPLICATION BCD_ELEMENT_DATATYPE_FORMAT_INTEGER 282)  //col:1917
    BcdOSLoaderString_HypervisorRootProcNumaNodes  BcdOSLoaderElementTypes =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_APPLICATION BCD_ELEMENT_DATATYPE_FORMAT_STRING 283)  //col:1922
    BcdOSLoaderInteger_HypervisorPerfmon  BcdOSLoaderElementTypes =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_APPLICATION BCD_ELEMENT_DATATYPE_FORMAT_INTEGER 284)  //col:1927
    BcdOSLoaderInteger_HypervisorRootProcPerCore  BcdOSLoaderElementTypes =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_APPLICATION BCD_ELEMENT_DATATYPE_FORMAT_INTEGER 285)  //col:1932
    BcdOSLoaderString_HypervisorRootProcNumaNodeLps  BcdOSLoaderElementTypes =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_APPLICATION BCD_ELEMENT_DATATYPE_FORMAT_STRING 286)  //col:1937
    BcdOSLoaderInteger_XSavePolicy  BcdOSLoaderElementTypes =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_APPLICATION BCD_ELEMENT_DATATYPE_FORMAT_INTEGER 288)  //col:1942
    BcdOSLoaderInteger_XSaveAddFeature0  BcdOSLoaderElementTypes =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_APPLICATION BCD_ELEMENT_DATATYPE_FORMAT_INTEGER 289)  //col:1947
    BcdOSLoaderInteger_XSaveAddFeature1  BcdOSLoaderElementTypes =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_APPLICATION BCD_ELEMENT_DATATYPE_FORMAT_INTEGER 290)  //col:1952
    BcdOSLoaderInteger_XSaveAddFeature2  BcdOSLoaderElementTypes =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_APPLICATION BCD_ELEMENT_DATATYPE_FORMAT_INTEGER 291)  //col:1957
    BcdOSLoaderInteger_XSaveAddFeature3  BcdOSLoaderElementTypes =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_APPLICATION BCD_ELEMENT_DATATYPE_FORMAT_INTEGER 292)  //col:1962
    BcdOSLoaderInteger_XSaveAddFeature4  BcdOSLoaderElementTypes =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_APPLICATION BCD_ELEMENT_DATATYPE_FORMAT_INTEGER 293)  //col:1967
    BcdOSLoaderInteger_XSaveAddFeature5  BcdOSLoaderElementTypes =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_APPLICATION BCD_ELEMENT_DATATYPE_FORMAT_INTEGER 294)  //col:1972
    BcdOSLoaderInteger_XSaveAddFeature6  BcdOSLoaderElementTypes =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_APPLICATION BCD_ELEMENT_DATATYPE_FORMAT_INTEGER 295)  //col:1977
    BcdOSLoaderInteger_XSaveAddFeature7  BcdOSLoaderElementTypes =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_APPLICATION BCD_ELEMENT_DATATYPE_FORMAT_INTEGER 296)  //col:1982
    BcdOSLoaderInteger_XSaveRemoveFeature  BcdOSLoaderElementTypes =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_APPLICATION BCD_ELEMENT_DATATYPE_FORMAT_INTEGER 297)  //col:1987
    BcdOSLoaderInteger_XSaveProcessorsMask  BcdOSLoaderElementTypes =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_APPLICATION BCD_ELEMENT_DATATYPE_FORMAT_INTEGER 298)  //col:1992
    BcdOSLoaderInteger_XSaveDisable  BcdOSLoaderElementTypes =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_APPLICATION BCD_ELEMENT_DATATYPE_FORMAT_INTEGER 299)  //col:1997
    BcdOSLoaderInteger_KernelDebuggerType  BcdOSLoaderElementTypes =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_APPLICATION BCD_ELEMENT_DATATYPE_FORMAT_INTEGER 300)  //col:2002
    BcdOSLoaderString_KernelDebuggerBusParameters  BcdOSLoaderElementTypes =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_APPLICATION BCD_ELEMENT_DATATYPE_FORMAT_STRING 301)  //col:2007
    BcdOSLoaderInteger_KernelDebuggerPortAddress  BcdOSLoaderElementTypes =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_APPLICATION BCD_ELEMENT_DATATYPE_FORMAT_INTEGER 302)  //col:2012
    BcdOSLoaderInteger_KernelDebuggerPortNumber  BcdOSLoaderElementTypes =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_APPLICATION BCD_ELEMENT_DATATYPE_FORMAT_INTEGER 303)  //col:2017
    BcdOSLoaderInteger_ClaimedTpmCounter  BcdOSLoaderElementTypes =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_APPLICATION BCD_ELEMENT_DATATYPE_FORMAT_INTEGER 304)  //col:2022
    BcdOSLoaderInteger_KernelDebugger1394Channel  BcdOSLoaderElementTypes =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_APPLICATION BCD_ELEMENT_DATATYPE_FORMAT_INTEGER 305)  //col:2027
    BcdOSLoaderString_KernelDebuggerUsbTargetname  BcdOSLoaderElementTypes =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_APPLICATION BCD_ELEMENT_DATATYPE_FORMAT_STRING 306)  //col:2032
    BcdOSLoaderInteger_KernelDebuggerNetHostIp  BcdOSLoaderElementTypes =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_APPLICATION BCD_ELEMENT_DATATYPE_FORMAT_INTEGER 307)  //col:2037
    BcdOSLoaderInteger_KernelDebuggerNetHostPort  BcdOSLoaderElementTypes =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_APPLICATION BCD_ELEMENT_DATATYPE_FORMAT_INTEGER 308)  //col:2042
    BcdOSLoaderBoolean_KernelDebuggerNetDhcp  BcdOSLoaderElementTypes =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_APPLICATION BCD_ELEMENT_DATATYPE_FORMAT_BOOLEAN 309)  //col:2047
    BcdOSLoaderString_KernelDebuggerNetKey  BcdOSLoaderElementTypes =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_APPLICATION BCD_ELEMENT_DATATYPE_FORMAT_STRING 310)  //col:2052
    BcdOSLoaderString_IMCHiveName  BcdOSLoaderElementTypes =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_APPLICATION BCD_ELEMENT_DATATYPE_FORMAT_STRING 311)  //col:2057
    BcdOSLoaderDevice_IMCDevice  BcdOSLoaderElementTypes =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_APPLICATION BCD_ELEMENT_DATATYPE_FORMAT_DEVICE 312)  //col:2062
    BcdOSLoaderInteger_KernelDebuggerBaudrate  BcdOSLoaderElementTypes =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_APPLICATION BCD_ELEMENT_DATATYPE_FORMAT_INTEGER 313)  //col:2067
    BcdOSLoaderString_ManufacturingMode  BcdOSLoaderElementTypes =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_APPLICATION BCD_ELEMENT_DATATYPE_FORMAT_STRING 320)  //col:2072
    BcdOSLoaderBoolean_EventLoggingEnabled  BcdOSLoaderElementTypes =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_APPLICATION BCD_ELEMENT_DATATYPE_FORMAT_BOOLEAN 321)  //col:2077
    BcdOSLoaderInteger_VsmLaunchType  BcdOSLoaderElementTypes =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_APPLICATION BCD_ELEMENT_DATATYPE_FORMAT_INTEGER 322)  //col:2082
    BcdOSLoaderInteger_HypervisorEnforcedCodeIntegrity  BcdOSLoaderElementTypes =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_APPLICATION BCD_ELEMENT_DATATYPE_FORMAT_INTEGER 324)  //col:2087
    BcdOSLoaderBoolean_DtraceEnabled  BcdOSLoaderElementTypes =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_APPLICATION BCD_ELEMENT_DATATYPE_FORMAT_BOOLEAN 325)  //col:2092
    BcdOSLoaderDevice_SystemDataDevice  BcdOSLoaderElementTypes =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_APPLICATION BCD_ELEMENT_DATATYPE_FORMAT_DEVICE 336)  //col:2097
    BcdOSLoaderDevice_OsArcDevice  BcdOSLoaderElementTypes =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_APPLICATION BCD_ELEMENT_DATATYPE_FORMAT_DEVICE 337)  //col:2102
    BcdOSLoaderDevice_OsDataDevice  BcdOSLoaderElementTypes =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_APPLICATION BCD_ELEMENT_DATATYPE_FORMAT_DEVICE 339)  //col:2107
    BcdOSLoaderDevice_BspDevice  BcdOSLoaderElementTypes =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_APPLICATION BCD_ELEMENT_DATATYPE_FORMAT_DEVICE 340)  //col:2112
    BcdOSLoaderDevice_BspFilepath  BcdOSLoaderElementTypes =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_APPLICATION BCD_ELEMENT_DATATYPE_FORMAT_DEVICE 341)  //col:2117
    BcdOSLoaderString_KernelDebuggerNetHostIpv6  BcdOSLoaderElementTypes =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_APPLICATION BCD_ELEMENT_DATATYPE_FORMAT_STRING 342)  //col:2122
    BcdOSLoaderString_HypervisorDebuggerNetHostIpv6  BcdOSLoaderElementTypes =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_APPLICATION BCD_ELEMENT_DATATYPE_FORMAT_STRING 353)  //col:2127
)
type (
Ntbcd interface{
 * Attribution 4.0 International ()(ok bool)//col:90
typedef VOID ()(ok bool)//col:176
BcdImportStoreWithFlags()(ok bool)//col:206
BcdOpenStore()(ok bool)//col:251
#define MAKE_BCD_OBJECT()(ok bool)//col:334
BcdEnumerateObjects()(ok bool)//col:403
BcdCopyObject()(ok bool)//col:468
#define MAKE_BCDE_DATA_TYPE()(ok bool)//col:514
BcdEnumerateElementTypes()(ok bool)//col:543
BcdEnumerateElements()(ok bool)//col:646
BcdEnumerateElementsWithFlags()(ok bool)//col:833
    BcdLibraryDevice_ApplicationDevice = MAKE_BCDE_DATA_TYPE()(ok bool)//col:1361
    BcdSetupInteger_DeviceType = MAKE_BCDE_DATA_TYPE()(ok bool)//col:1395
    BcdOSLoaderDevice_OSDevice = MAKE_BCDE_DATA_TYPE()(ok bool)//col:2128
}

)
func NewNtbcd() { return & ntbcd{} }
func (n *ntbcd) * Attribution 4.0 International ()(ok bool){//col:90
return true
}

func (n *ntbcd)typedef VOID ()(ok bool){//col:176
return true
}

func (n *ntbcd)BcdImportStoreWithFlags()(ok bool){//col:206
return true
}

func (n *ntbcd)BcdOpenStore()(ok bool){//col:251
return true
}

func (n *ntbcd)#define MAKE_BCD_OBJECT()(ok bool){//col:334
return true
}

func (n *ntbcd)BcdEnumerateObjects()(ok bool){//col:403
return true
}

func (n *ntbcd)BcdCopyObject()(ok bool){//col:468
return true
}

func (n *ntbcd)#define MAKE_BCDE_DATA_TYPE()(ok bool){//col:514
return true
}

func (n *ntbcd)BcdEnumerateElementTypes()(ok bool){//col:543
return true
}

func (n *ntbcd)BcdEnumerateElements()(ok bool){//col:646
return true
}

func (n *ntbcd)BcdEnumerateElementsWithFlags()(ok bool){//col:833
return true
}

func (n *ntbcd)    BcdLibraryDevice_ApplicationDevice = MAKE_BCDE_DATA_TYPE()(ok bool){//col:1361
return true
}

func (n *ntbcd)    BcdSetupInteger_DeviceType = MAKE_BCDE_DATA_TYPE()(ok bool){//col:1395
return true
}

func (n *ntbcd)    BcdOSLoaderDevice_OSDevice = MAKE_BCDE_DATA_TYPE()(ok bool){//col:2128
return true
}

