package phnt


const(
_NTBCD_H =  //col:13
MAKE_BCD_OBJECT(ObjectType, ImageType, ApplicationType) = (((ULONG)(ObjectType) << 28) | (((ULONG)(ImageType) & 0xF) << 20) | ((ULONG)(ApplicationType) & 0xFFFFF)) //col:286
MAKE_BCD_APPLICATION_OBJECT(ImageType, ApplicationType) = MAKE_BCD_OBJECT(BCD_OBJECT_TYPE_APPLICATION, (ULONG)(ImageType), (ULONG)(ApplicationType)) //col:291
GET_BCD_OBJECT_TYPE(DataType) = ((BCD_OBJECT_TYPE)(((((ULONG)DataType)) >> 28) & 0xF)) //col:294
GET_BCD_APPLICATION_IMAGE(DataType) = ((BCD_APPLICATION_IMAGE_TYPE)(((((ULONG)DataType)) >> 20) & 0xF)) //col:296
GET_BCD_APPLICATION_OBJECT(DataType) = ((BCD_APPLICATION_OBJECT_TYPE)((((ULONG)DataType)) & 0xFFFFF)) //col:298
BCD_OBJECT_OSLOADER_TYPE = MAKE_BCD_APPLICATION_OBJECT(BCD_APPLICATION_IMAGE_BOOT_APPLICATION, BCD_APPLICATION_OBJECT_WINDOWS_BOOT_LOADER) //col:301
BCD_OBJECT_DESCRIPTION_VERSION = 0x1 //col:336
MAKE_BCDE_DATA_TYPE(Class, Format, Subtype) = (((((ULONG)Class) & 0xF) << 28) | ((((ULONG)Format) & 0xF) << 24) | (((ULONG)Subtype) & 0x00FFFFFF)) //col:495
GET_BCDE_DATA_CLASS(DataType) = ((BCD_ELEMENT_DATATYPE_CLASS)(((((ULONG)DataType)) >> 28) & 0xF)) //col:498
GET_BCDE_DATA_FORMAT(DataType) = ((BCD_ELEMENT_DATATYPE_FORMAT)(((((ULONG)DataType)) >> 24) & 0xF)) //col:500
GET_BCDE_DATA_SUBTYPE(DataType) = ((ULONG)((((ULONG)DataType)) & 0x00FFFFFF)) //col:502
BCD_ELEMENT_DESCRIPTION_VERSION = 0x1 //col:610
)

const(
    BCD_MESSAGE_TYPE_NONE = 1  //col:84
    BCD_MESSAGE_TYPE_TRACE = 2  //col:85
    BCD_MESSAGE_TYPE_INFORMATION = 3  //col:86
    BCD_MESSAGE_TYPE_WARNING = 4  //col:87
    BCD_MESSAGE_TYPE_ERROR = 5  //col:88
    BCD_MESSAGE_TYPE_MAXIMUM = 6  //col:89
)


const(
    BCD_IMPORT_NONE = 1  //col:174
    BCD_IMPORT_DELETE_FIRMWARE_OBJECTS = 2  //col:175
)


const(
    BCD_OPEN_NONE = 1  //col:203
    BCD_OPEN_OPEN_STORE_OFFLINE = 2  //col:204
    BCD_OPEN_SYNC_FIRMWARE_ENTRIES = 3  //col:205
)


const(
    BCD_OBJECT_TYPE_NONE = 1  //col:247
    BCD_OBJECT_TYPE_APPLICATION = 2  //col:248
    BCD_OBJECT_TYPE_INHERITED = 3  //col:249
    BCD_OBJECT_TYPE_DEVICE = 4  //col:250
)


const(
    BCD_APPLICATION_OBJECT_NONE  =  0  //col:255
    BCD_APPLICATION_OBJECT_FIRMWARE_BOOT_MANAGER  =  1  //col:256
    BCD_APPLICATION_OBJECT_WINDOWS_BOOT_MANAGER  =  2  //col:257
    BCD_APPLICATION_OBJECT_WINDOWS_BOOT_LOADER  =  3  //col:258
    BCD_APPLICATION_OBJECT_WINDOWS_RESUME_APPLICATION  =  4  //col:259
    BCD_APPLICATION_OBJECT_MEMORY_TESTER  =  5  //col:260
    BCD_APPLICATION_OBJECT_LEGACY_NTLDR  =  6  //col:261
    BCD_APPLICATION_OBJECT_LEGACY_SETUPLDR  =  7  //col:262
    BCD_APPLICATION_OBJECT_BOOT_SECTOR  =  8  //col:263
    BCD_APPLICATION_OBJECT_STARTUP_MODULE  =  9  //col:264
    BCD_APPLICATION_OBJECT_GENERIC_APPLICATION  =  10  //col:265
    BCD_APPLICATION_OBJECT_RESERVED  =  0xFFFFF  //col:266
)


const(
    BCD_APPLICATION_IMAGE_NONE = 1  //col:271
    BCD_APPLICATION_IMAGE_FIRMWARE_APPLICATION = 2  //col:272
    BCD_APPLICATION_IMAGE_BOOT_APPLICATION = 3  //col:273
    BCD_APPLICATION_IMAGE_LEGACY_LOADER = 4  //col:274
    BCD_APPLICATION_IMAGE_REALMODE_CODE = 5  //col:275
)


const(
    BCD_INHERITED_CLASS_NONE = 1  //col:280
    BCD_INHERITED_CLASS_LIBRARY = 2  //col:281
    BCD_INHERITED_CLASS_APPLICATION = 3  //col:282
    BCD_INHERITED_CLASS_DEVICE = 4  //col:283
)


const(
    BCD_COPY_NONE  =  0x0  //col:396
    BCD_COPY_COPY_CREATE_NEW_OBJECT_IDENTIFIER  =  0x1  //col:397
    BCD_COPY_COPY_DELETE_EXISTING_OBJECT  =  0x2  //col:398
    BCD_COPY_COPY_UNKNOWN_FIRMWARE_APPLICATION  =  0x4  //col:399
    BCD_COPY_IGNORE_SETUP_TEMPLATE_ELEMENTS  =  0x8  //col:400
    BCD_COPY_RETAIN_ELEMENT_DATA  =  0x10  //col:401
    BCD_COPY_MIGRATE_ELEMENT_DATA  =  0x20  //col:402
)


const(
    BCD_ELEMENT_DATATYPE_FORMAT_UNKNOWN = 1  //col:459
    BCD_ELEMENT_DATATYPE_FORMAT_DEVICE // 0x01000000 = 2  //col:460
    BCD_ELEMENT_DATATYPE_FORMAT_STRING // 0x02000000 = 3  //col:461
    BCD_ELEMENT_DATATYPE_FORMAT_OBJECT // 0x03000000  = 4  //col:462
    BCD_ELEMENT_DATATYPE_FORMAT_OBJECTLIST // 0x04000000  = 5  //col:463
    BCD_ELEMENT_DATATYPE_FORMAT_INTEGER // 0x05000000 = 6  //col:464
    BCD_ELEMENT_DATATYPE_FORMAT_BOOLEAN // 0x06000000 = 7  //col:465
    BCD_ELEMENT_DATATYPE_FORMAT_INTEGERLIST // 0x07000000 = 8  //col:466
    BCD_ELEMENT_DATATYPE_FORMAT_BINARY // 0x08000000 = 9  //col:467
)


const(
    BCD_ELEMENT_DATATYPE_CLASS_NONE = 1  //col:472
    BCD_ELEMENT_DATATYPE_CLASS_LIBRARY = 2  //col:473
    BCD_ELEMENT_DATATYPE_CLASS_APPLICATION = 3  //col:474
    BCD_ELEMENT_DATATYPE_CLASS_DEVICE = 4  //col:475
    BCD_ELEMENT_DATATYPE_CLASS_SETUPTEMPLATE = 5  //col:476
    BCD_ELEMENT_DATATYPE_CLASS_OEM = 6  //col:477
)


const(
    BCD_ELEMENT_DEVICE_TYPE_NONE = 1  //col:482
    BCD_ELEMENT_DEVICE_TYPE_BOOT_DEVICE = 2  //col:483
    BCD_ELEMENT_DEVICE_TYPE_PARTITION = 3  //col:484
    BCD_ELEMENT_DEVICE_TYPE_FILE = 4  //col:485
    BCD_ELEMENT_DEVICE_TYPE_RAMDISK = 5  //col:486
    BCD_ELEMENT_DEVICE_TYPE_UNKNOWN = 6  //col:487
    BCD_ELEMENT_DEVICE_TYPE_QUALIFIED_PARTITION = 7  //col:488
    BCD_ELEMENT_DEVICE_TYPE_VMBUS = 8  //col:489
    BCD_ELEMENT_DEVICE_TYPE_LOCATE_DEVICE = 9  //col:490
    BCD_ELEMENT_DEVICE_TYPE_URI = 10  //col:491
    BCD_ELEMENT_DEVICE_TYPE_COMPOSITE = 11  //col:492
)


const(
    BCD_FLAG_NONE  =  0x0  //col:637
    BCD_FLAG_QUALIFIED_PARTITION  =  0x1  //col:638
    BCD_FLAG_NO_DEVICE_TRANSLATION  =  0x2  //col:639
    BCD_FLAG_ENUMERATE_INHERITED_OBJECTS  =  0x4  //col:640
    BCD_FLAG_ENUMERATE_DEVICE_OPTIONS  =  0x8  //col:641
    BCD_FLAG_OBSERVE_PRECEDENCE  =  0x10  //col:642
    BCD_FLAG_DISABLE_VHD_NT_TRANSLATION  =  0x20  //col:643
    BCD_FLAG_DISABLE_VHD_DEVICE_DETECTION  =  0x40  //col:644
    BCD_FLAG_DISABLE_POLICY_CHECKS  =  0x80  //col:645
)


const(
    BcdBootMgrObjectList_DisplayOrder  =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_APPLICATION BCD_ELEMENT_DATATYPE_FORMAT_OBJECTLIST 1)  //col:730
    BcdBootMgrObjectList_BootSequence  =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_APPLICATION BCD_ELEMENT_DATATYPE_FORMAT_OBJECTLIST 2)  //col:737
    BcdBootMgrObject_DefaultObject  =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_APPLICATION BCD_ELEMENT_DATATYPE_FORMAT_OBJECT 3)  //col:742
    BcdBootMgrInteger_Timeout  =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_APPLICATION BCD_ELEMENT_DATATYPE_FORMAT_INTEGER 4)  //col:749
    BcdBootMgrBoolean_AttemptResume  =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_APPLICATION BCD_ELEMENT_DATATYPE_FORMAT_BOOLEAN 5)  //col:754
    BcdBootMgrObject_ResumeObject  =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_APPLICATION BCD_ELEMENT_DATATYPE_FORMAT_OBJECT 6)  //col:759
    BcdBootMgrObjectList_StartupSequence  =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_APPLICATION BCD_ELEMENT_DATATYPE_FORMAT_OBJECTLIST 7)  //col:764
    BcdBootMgrObjectList_ToolsDisplayOrder  =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_APPLICATION BCD_ELEMENT_DATATYPE_FORMAT_OBJECTLIST 16)  //col:769
    BcdBootMgrBoolean_DisplayBootMenu  =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_APPLICATION BCD_ELEMENT_DATATYPE_FORMAT_BOOLEAN 32)  //col:774
    BcdBootMgrBoolean_NoErrorDisplay  =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_APPLICATION BCD_ELEMENT_DATATYPE_FORMAT_BOOLEAN 33)  //col:780
    BcdBootMgrDevice_BcdDevice  =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_APPLICATION BCD_ELEMENT_DATATYPE_FORMAT_DEVICE 34)  //col:785
    BcdBootMgrString_BcdFilePath  =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_APPLICATION BCD_ELEMENT_DATATYPE_FORMAT_STRING 35)  //col:790
    BcdBootMgrBoolean_HormEnabled  =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_APPLICATION BCD_ELEMENT_DATATYPE_FORMAT_BOOLEAN 36)  //col:795
    BcdBootMgrBoolean_HiberRoot  =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_APPLICATION BCD_ELEMENT_DATATYPE_FORMAT_BOOLEAN 37)  //col:800
    BcdBootMgrString_PasswordOverride  =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_APPLICATION BCD_ELEMENT_DATATYPE_FORMAT_STRING 38)  //col:805
    BcdBootMgrString_PinpassPhraseOverride  =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_APPLICATION BCD_ELEMENT_DATATYPE_FORMAT_STRING 39)  //col:810
    BcdBootMgrBoolean_ProcessCustomActionsFirst  =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_APPLICATION BCD_ELEMENT_DATATYPE_FORMAT_BOOLEAN 40)  //col:816
    BcdBootMgrIntegerList_CustomActionsList  =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_APPLICATION BCD_ELEMENT_DATATYPE_FORMAT_INTEGERLIST 48)  //col:821
    BcdBootMgrBoolean_PersistBootSequence  =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_APPLICATION BCD_ELEMENT_DATATYPE_FORMAT_BOOLEAN 49)  //col:827
    BcdBootMgrBoolean_SkipStartupSequence  =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_APPLICATION BCD_ELEMENT_DATATYPE_FORMAT_BOOLEAN 50)  //col:832
)


const(
    FirstMegabytePolicyUseNone = 1  //col:840
    FirstMegabytePolicyUseAll = 2  //col:844
    FirstMegabytePolicyUsePrivate = 3  //col:848
)


const(
    DebuggerSerial  =  0  //col:853
    Debugger1394  =  1  //col:854
    DebuggerUsb  =  2  //col:855
    DebuggerNet  =  3  //col:856
    DebuggerLocal  =  4  //col:857
)


const(
    DebuggerStartActive = 1  //col:865
    DebuggerStartAutoEnable = 2  //col:870
    DebuggerStartDisable = 3  //col:874
)


const(
    ConfigAccessPolicyDefault = 1  //col:882
    ConfigAccessPolicyDisallowMmConfig = 2  //col:888
)


const(
    DisplayMessageTypeDefault  =  0  //col:893
    DisplayMessageTypeResume  =  1  //col:894
    DisplayMessageTypeHyperV  =  2  //col:895
    DisplayMessageTypeRecovery  =  3  //col:896
    DisplayMessageTypeStartupRepair  =  4  //col:897
    DisplayMessageTypeSystemImageRecovery  =  5  //col:898
    DisplayMessageTypeCommandPrompt  =  6  //col:899
    DisplayMessageTypeSystemRestore  =  7  //col:900
    DisplayMessageTypePushButtonReset  =  8  //col:901
)


const(
    SafemodeMinimal  =  0  //col:910
    SafemodeNetwork  =  1  //col:915
    SafemodeDsRepair  =  2  //col:919
)


const(
    BcdLibraryDevice_ApplicationDevice  =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_LIBRARY BCD_ELEMENT_DATATYPE_FORMAT_DEVICE 1)  //col:929
    BcdLibraryString_ApplicationPath  =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_LIBRARY BCD_ELEMENT_DATATYPE_FORMAT_STRING 2)  //col:934
    BcdLibraryString_Description  =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_LIBRARY BCD_ELEMENT_DATATYPE_FORMAT_STRING 4)  //col:939
    BcdLibraryString_PreferredLocale  =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_LIBRARY BCD_ELEMENT_DATATYPE_FORMAT_STRING 5)  //col:944
    BcdLibraryObjectList_InheritedObjects  =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_LIBRARY BCD_ELEMENT_DATATYPE_FORMAT_OBJECTLIST 6)  //col:949
    BcdLibraryInteger_TruncatePhysicalMemory  =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_LIBRARY BCD_ELEMENT_DATATYPE_FORMAT_INTEGER 7)  //col:954
    BcdLibraryObjectList_RecoverySequence  =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_LIBRARY BCD_ELEMENT_DATATYPE_FORMAT_OBJECTLIST 8)  //col:959
    BcdLibraryBoolean_AutoRecoveryEnabled  =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_LIBRARY BCD_ELEMENT_DATATYPE_FORMAT_BOOLEAN 9)  //col:964
    BcdLibraryIntegerList_BadMemoryList  =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_LIBRARY BCD_ELEMENT_DATATYPE_FORMAT_INTEGERLIST 10)  //col:969
    BcdLibraryBoolean_AllowBadMemoryAccess  =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_LIBRARY BCD_ELEMENT_DATATYPE_FORMAT_BOOLEAN 11)  //col:974
    BcdLibraryInteger_FirstMegabytePolicy  =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_LIBRARY BCD_ELEMENT_DATATYPE_FORMAT_INTEGER 12)  //col:979
    BcdLibraryInteger_RelocatePhysicalMemory  =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_LIBRARY BCD_ELEMENT_DATATYPE_FORMAT_INTEGER 13)  //col:985
    BcdLibraryInteger_AvoidLowPhysicalMemory  =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_LIBRARY BCD_ELEMENT_DATATYPE_FORMAT_INTEGER 14)  //col:990
    BcdLibraryBoolean_TraditionalKsegMappings  =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_LIBRARY BCD_ELEMENT_DATATYPE_FORMAT_BOOLEAN 15)  //col:995
    BcdLibraryBoolean_DebuggerEnabled  =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_LIBRARY BCD_ELEMENT_DATATYPE_FORMAT_BOOLEAN 16)  //col:1000
    BcdLibraryInteger_DebuggerType  =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_LIBRARY BCD_ELEMENT_DATATYPE_FORMAT_INTEGER 17)  //col:1005
    BcdLibraryInteger_SerialDebuggerPortAddress  =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_LIBRARY BCD_ELEMENT_DATATYPE_FORMAT_INTEGER 18)  //col:1010
    BcdLibraryInteger_SerialDebuggerPort  =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_LIBRARY BCD_ELEMENT_DATATYPE_FORMAT_INTEGER 19)  //col:1016
    BcdLibraryInteger_SerialDebuggerBaudRate  =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_LIBRARY BCD_ELEMENT_DATATYPE_FORMAT_INTEGER 20)  //col:1021
    BcdLibraryInteger_1394DebuggerChannel  =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_LIBRARY BCD_ELEMENT_DATATYPE_FORMAT_INTEGER 21)  //col:1026
    BcdLibraryString_UsbDebuggerTargetName  =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_LIBRARY BCD_ELEMENT_DATATYPE_FORMAT_STRING 22)  //col:1031
    BcdLibraryBoolean_DebuggerIgnoreUsermodeExceptions  =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_LIBRARY BCD_ELEMENT_DATATYPE_FORMAT_BOOLEAN 23)  //col:1036
    BcdLibraryInteger_DebuggerStartPolicy  =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_LIBRARY BCD_ELEMENT_DATATYPE_FORMAT_INTEGER 24)  //col:1041
    BcdLibraryString_DebuggerBusParameters  =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_LIBRARY BCD_ELEMENT_DATATYPE_FORMAT_STRING 25)  //col:1046
    BcdLibraryInteger_DebuggerNetHostIP  =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_LIBRARY BCD_ELEMENT_DATATYPE_FORMAT_INTEGER 26)  //col:1051
    BcdLibraryInteger_DebuggerNetPort  =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_LIBRARY BCD_ELEMENT_DATATYPE_FORMAT_INTEGER 27)  //col:1056
    BcdLibraryBoolean_DebuggerNetDhcp  =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_LIBRARY BCD_ELEMENT_DATATYPE_FORMAT_BOOLEAN 28)  //col:1062
    BcdLibraryString_DebuggerNetKey  =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_LIBRARY BCD_ELEMENT_DATATYPE_FORMAT_STRING 29)  //col:1068
    BcdLibraryBoolean_DebuggerNetVM  =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_LIBRARY BCD_ELEMENT_DATATYPE_FORMAT_BOOLEAN 30)  //col:1073
    BcdLibraryString_DebuggerNetHostIpv6  =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_LIBRARY BCD_ELEMENT_DATATYPE_FORMAT_STRING 31)  //col:1078
    BcdLibraryBoolean_EmsEnabled  =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_LIBRARY BCD_ELEMENT_DATATYPE_FORMAT_BOOLEAN 32)  //col:1083
    BcdLibraryInteger_EmsPort  =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_LIBRARY BCD_ELEMENT_DATATYPE_FORMAT_INTEGER 34)  //col:1088
    BcdLibraryInteger_EmsBaudRate  =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_LIBRARY BCD_ELEMENT_DATATYPE_FORMAT_INTEGER 35)  //col:1093
    BcdLibraryString_LoadOptionsString  =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_LIBRARY BCD_ELEMENT_DATATYPE_FORMAT_STRING 48)  //col:1099
    BcdLibraryBoolean_AttemptNonBcdStart  =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_LIBRARY BCD_ELEMENT_DATATYPE_FORMAT_BOOLEAN 49)  //col:1104
    BcdLibraryBoolean_DisplayAdvancedOptions  =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_LIBRARY BCD_ELEMENT_DATATYPE_FORMAT_BOOLEAN 64)  //col:1109
    BcdLibraryBoolean_DisplayOptionsEdit  =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_LIBRARY BCD_ELEMENT_DATATYPE_FORMAT_BOOLEAN 65)  //col:1114
    BcdLibraryInteger_FVEKeyRingAddress  =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_LIBRARY BCD_ELEMENT_DATATYPE_FORMAT_INTEGER 66)  //col:1119
    BcdLibraryDevice_BsdLogDevice  =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_LIBRARY BCD_ELEMENT_DATATYPE_FORMAT_DEVICE 67)  //col:1124
    BcdLibraryString_BsdLogPath  =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_LIBRARY BCD_ELEMENT_DATATYPE_FORMAT_STRING 68)  //col:1129
    BcdLibraryBoolean_BsdPreserveLog  =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_LIBRARY BCD_ELEMENT_DATATYPE_FORMAT_BOOLEAN 69)  //col:1134
    BcdLibraryBoolean_GraphicsModeDisabled  =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_LIBRARY BCD_ELEMENT_DATATYPE_FORMAT_BOOLEAN 70)  //col:1139
    BcdLibraryInteger_ConfigAccessPolicy  =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_LIBRARY BCD_ELEMENT_DATATYPE_FORMAT_INTEGER 71)  //col:1144
    BcdLibraryBoolean_DisableIntegrityChecks  =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_LIBRARY BCD_ELEMENT_DATATYPE_FORMAT_BOOLEAN 72)  //col:1151
    BcdLibraryBoolean_AllowPrereleaseSignatures  =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_LIBRARY BCD_ELEMENT_DATATYPE_FORMAT_BOOLEAN 73)  //col:1156
    BcdLibraryString_FontPath  =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_LIBRARY BCD_ELEMENT_DATATYPE_FORMAT_STRING 74)  //col:1161
    BcdLibraryInteger_SiPolicy  =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_LIBRARY BCD_ELEMENT_DATATYPE_FORMAT_INTEGER 75)  //col:1166
    BcdLibraryInteger_FveBandId  =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_LIBRARY BCD_ELEMENT_DATATYPE_FORMAT_INTEGER 76)  //col:1171
    BcdLibraryBoolean_ConsoleExtendedInput  =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_LIBRARY BCD_ELEMENT_DATATYPE_FORMAT_BOOLEAN 80)  //col:1176
    BcdLibraryInteger_InitialConsoleInput  =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_LIBRARY BCD_ELEMENT_DATATYPE_FORMAT_INTEGER 81)  //col:1181
    BcdLibraryInteger_GraphicsResolution  =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_LIBRARY BCD_ELEMENT_DATATYPE_FORMAT_INTEGER 82)  //col:1187
    BcdLibraryBoolean_RestartOnFailure  =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_LIBRARY BCD_ELEMENT_DATATYPE_FORMAT_BOOLEAN 83)  //col:1192
    BcdLibraryBoolean_GraphicsForceHighestMode  =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_LIBRARY BCD_ELEMENT_DATATYPE_FORMAT_BOOLEAN 84)  //col:1199
    BcdLibraryBoolean_IsolatedExecutionContext  =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_LIBRARY BCD_ELEMENT_DATATYPE_FORMAT_BOOLEAN 96)  //col:1207
    BcdLibraryInteger_BootUxDisplayMessage  =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_LIBRARY BCD_ELEMENT_DATATYPE_FORMAT_INTEGER 101)  //col:1213
    BcdLibraryInteger_BootUxDisplayMessageOverride  =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_LIBRARY BCD_ELEMENT_DATATYPE_FORMAT_INTEGER 102)  //col:1218
    BcdLibraryBoolean_BootUxLogoDisable  =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_LIBRARY BCD_ELEMENT_DATATYPE_FORMAT_BOOLEAN 103)  //col:1223
    BcdLibraryBoolean_BootUxTextDisable  =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_LIBRARY BCD_ELEMENT_DATATYPE_FORMAT_BOOLEAN 104)  //col:1228
    BcdLibraryBoolean_BootUxProgressDisable  =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_LIBRARY BCD_ELEMENT_DATATYPE_FORMAT_BOOLEAN 105)  //col:1233
    BcdLibraryBoolean_BootUxFadeDisable  =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_LIBRARY BCD_ELEMENT_DATATYPE_FORMAT_BOOLEAN 106)  //col:1238
    BcdLibraryBoolean_BootUxReservePoolDebug  =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_LIBRARY BCD_ELEMENT_DATATYPE_FORMAT_BOOLEAN 107)  //col:1243
    BcdLibraryBoolean_BootUxDisable  =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_LIBRARY BCD_ELEMENT_DATATYPE_FORMAT_BOOLEAN 108)  //col:1248
    BcdLibraryInteger_BootUxFadeFrames  =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_LIBRARY BCD_ELEMENT_DATATYPE_FORMAT_INTEGER 109)  //col:1253
    BcdLibraryBoolean_BootUxDumpStats  =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_LIBRARY BCD_ELEMENT_DATATYPE_FORMAT_BOOLEAN 110)  //col:1258
    BcdLibraryBoolean_BootUxShowStats  =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_LIBRARY BCD_ELEMENT_DATATYPE_FORMAT_BOOLEAN 111)  //col:1263
    BcdLibraryBoolean_MultiBootSystem  =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_LIBRARY BCD_ELEMENT_DATATYPE_FORMAT_BOOLEAN 113)  //col:1268
    BcdLibraryBoolean_ForceNoKeyboard  =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_LIBRARY BCD_ELEMENT_DATATYPE_FORMAT_BOOLEAN 114)  //col:1273
    BcdLibraryInteger_AliasWindowsKey  =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_LIBRARY BCD_ELEMENT_DATATYPE_FORMAT_INTEGER 115)  //col:1278
    BcdLibraryBoolean_BootShutdownDisabled  =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_LIBRARY BCD_ELEMENT_DATATYPE_FORMAT_BOOLEAN 116)  //col:1283
    BcdLibraryInteger_PerformanceFrequency  =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_LIBRARY BCD_ELEMENT_DATATYPE_FORMAT_INTEGER 117)  //col:1288
    BcdLibraryInteger_SecurebootRawPolicy  =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_LIBRARY BCD_ELEMENT_DATATYPE_FORMAT_INTEGER 118)  //col:1293
    BcdLibraryIntegerList_AllowedInMemorySettings  =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_LIBRARY BCD_ELEMENT_DATATYPE_FORMAT_INTEGER 119)  //col:1299
    BcdLibraryInteger_BootUxBitmapTransitionTime  =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_LIBRARY BCD_ELEMENT_DATATYPE_FORMAT_INTEGER 121)  //col:1304
    BcdLibraryBoolean_TwoBootImages  =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_LIBRARY BCD_ELEMENT_DATATYPE_FORMAT_BOOLEAN 122)  //col:1309
    BcdLibraryBoolean_ForceFipsCrypto  =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_LIBRARY BCD_ELEMENT_DATATYPE_FORMAT_BOOLEAN 123)  //col:1315
    BcdLibraryInteger_BootErrorUx  =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_LIBRARY BCD_ELEMENT_DATATYPE_FORMAT_INTEGER 125)  //col:1320
    BcdLibraryBoolean_AllowFlightSignatures  =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_LIBRARY BCD_ELEMENT_DATATYPE_FORMAT_BOOLEAN 126)  //col:1325
    BcdLibraryInteger_BootMeasurementLogFormat  =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_LIBRARY BCD_ELEMENT_DATATYPE_FORMAT_INTEGER 127)  //col:1330
    BcdLibraryInteger_DisplayRotation  =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_LIBRARY BCD_ELEMENT_DATATYPE_FORMAT_INTEGER 128)  //col:1335
    BcdLibraryInteger_LogControl  =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_LIBRARY BCD_ELEMENT_DATATYPE_FORMAT_INTEGER 129)  //col:1340
    BcdLibraryBoolean_NoFirmwareSync  =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_LIBRARY BCD_ELEMENT_DATATYPE_FORMAT_BOOLEAN 130)  //col:1345
    BcdLibraryDevice_WindowsSystemDevice  =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_LIBRARY BCD_ELEMENT_DATATYPE_FORMAT_DEVICE 132)  //col:1350
    BcdLibraryBoolean_NumLockOn  =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_LIBRARY BCD_ELEMENT_DATATYPE_FORMAT_BOOLEAN 135)  //col:1355
    BcdLibraryString_AdditionalCiPolicy  =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_LIBRARY BCD_ELEMENT_DATATYPE_FORMAT_STRING 136)  //col:1360
)


const(
    BcdSetupInteger_DeviceType  =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_SETUPTEMPLATE BCD_ELEMENT_DATATYPE_FORMAT_INTEGER 1)  //col:1369
    BcdSetupString_ApplicationRelativePath  =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_SETUPTEMPLATE BCD_ELEMENT_DATATYPE_FORMAT_STRING 2)  //col:1374
    BcdSetupString_RamdiskDeviceRelativePath  =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_SETUPTEMPLATE BCD_ELEMENT_DATATYPE_FORMAT_STRING 3)  //col:1379
    BcdSetupBoolean_OmitOsLoaderElements  =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_SETUPTEMPLATE BCD_ELEMENT_DATATYPE_FORMAT_BOOLEAN 4)  //col:1384
    BcdSetupIntegerList_ElementsToMigrateList  =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_SETUPTEMPLATE BCD_ELEMENT_DATATYPE_FORMAT_INTEGERLIST 6)  //col:1389
    BcdSetupBoolean_RecoveryOs  =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_SETUPTEMPLATE BCD_ELEMENT_DATATYPE_FORMAT_BOOLEAN 16)  //col:1394
)


const(
    NxPolicyOptIn  =  0  //col:1405
    NxPolicyOptOut  =  1  //col:1409
    NxPolicyAlwaysOff  =  2  //col:1413
    NxPolicyAlwaysOn  =  3  //col:1417
)


const(
    PaePolicyDefault  =  0  //col:1428
    PaePolicyForceEnable  =  1  //col:1432
    PaePolicyForceDisable  =  2  //col:1436
)


const(
    BootStatusPolicyDisplayAllFailures  =  0  //col:1444
    BootStatusPolicyIgnoreAllFailures  =  1  //col:1448
    BootStatusPolicyIgnoreShutdownFailures  =  2  //col:1452
    BootStatusPolicyIgnoreBootFailures  =  3  //col:1456
    BootStatusPolicyIgnoreCheckpointFailures  =  4  //col:1460
    BootStatusPolicyDisplayShutdownFailures  =  5  //col:1464
    BootStatusPolicyDisplayBootFailures  =  6  //col:1468
    BootStatusPolicyDisplayCheckpointFailures  =  7  //col:1472
)


const(
    BcdOSLoaderDevice_OSDevice  =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_APPLICATION BCD_ELEMENT_DATATYPE_FORMAT_DEVICE 1)  //col:1482
    BcdOSLoaderString_SystemRoot  =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_APPLICATION BCD_ELEMENT_DATATYPE_FORMAT_STRING 2)  //col:1487
    BcdOSLoaderObject_AssociatedResumeObject  =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_APPLICATION BCD_ELEMENT_DATATYPE_FORMAT_OBJECT 3)  //col:1492
    BcdOSLoaderBoolean_StampDisks  =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_APPLICATION BCD_ELEMENT_DATATYPE_FORMAT_BOOLEAN 4)  //col:1497
    BcdOSLoaderBoolean_DetectKernelAndHal  =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_APPLICATION BCD_ELEMENT_DATATYPE_FORMAT_BOOLEAN 16)  //col:1502
    BcdOSLoaderString_KernelPath  =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_APPLICATION BCD_ELEMENT_DATATYPE_FORMAT_STRING 17)  //col:1507
    BcdOSLoaderString_HalPath  =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_APPLICATION BCD_ELEMENT_DATATYPE_FORMAT_STRING 18)  //col:1512
    BcdOSLoaderString_DbgTransportPath  =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_APPLICATION BCD_ELEMENT_DATATYPE_FORMAT_STRING 19)  //col:1517
    BcdOSLoaderInteger_NxPolicy  =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_APPLICATION BCD_ELEMENT_DATATYPE_FORMAT_INTEGER 32)  //col:1522
    BcdOSLoaderInteger_PAEPolicy  =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_APPLICATION BCD_ELEMENT_DATATYPE_FORMAT_INTEGER 33)  //col:1527
    BcdOSLoaderBoolean_WinPEMode  =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_APPLICATION BCD_ELEMENT_DATATYPE_FORMAT_BOOLEAN 34)  //col:1532
    BcdOSLoaderBoolean_DisableCrashAutoReboot  =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_APPLICATION BCD_ELEMENT_DATATYPE_FORMAT_BOOLEAN 36)  //col:1537
    BcdOSLoaderBoolean_UseLastGoodSettings  =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_APPLICATION BCD_ELEMENT_DATATYPE_FORMAT_BOOLEAN 37)  //col:1542
    BcdOSLoaderBoolean_DisableCodeIntegrityChecks  =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_APPLICATION BCD_ELEMENT_DATATYPE_FORMAT_BOOLEAN 38)  //col:1547
    BcdOSLoaderBoolean_AllowPrereleaseSignatures  =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_APPLICATION BCD_ELEMENT_DATATYPE_FORMAT_BOOLEAN 39)  //col:1552
    BcdOSLoaderBoolean_NoLowMemory  =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_APPLICATION BCD_ELEMENT_DATATYPE_FORMAT_BOOLEAN 48)  //col:1558
    BcdOSLoaderInteger_RemoveMemory  =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_APPLICATION BCD_ELEMENT_DATATYPE_FORMAT_INTEGER 49)  //col:1563
    BcdOSLoaderInteger_IncreaseUserVa  =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_APPLICATION BCD_ELEMENT_DATATYPE_FORMAT_INTEGER 50)  //col:1570
    BcdOSLoaderInteger_PerformaceDataMemory  =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_APPLICATION BCD_ELEMENT_DATATYPE_FORMAT_INTEGER 51)  //col:1575
    BcdOSLoaderBoolean_UseVgaDriver  =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_APPLICATION BCD_ELEMENT_DATATYPE_FORMAT_BOOLEAN 64)  //col:1580
    BcdOSLoaderBoolean_DisableBootDisplay  =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_APPLICATION BCD_ELEMENT_DATATYPE_FORMAT_BOOLEAN 65)  //col:1586
    BcdOSLoaderBoolean_DisableVesaBios  =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_APPLICATION BCD_ELEMENT_DATATYPE_FORMAT_BOOLEAN 66)  //col:1592
    BcdOSLoaderBoolean_DisableVgaMode  =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_APPLICATION BCD_ELEMENT_DATATYPE_FORMAT_BOOLEAN 67)  //col:1597
    BcdOSLoaderInteger_ClusterModeAddressing  =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_APPLICATION BCD_ELEMENT_DATATYPE_FORMAT_INTEGER 80)  //col:1602
    BcdOSLoaderBoolean_UsePhysicalDestination  =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_APPLICATION BCD_ELEMENT_DATATYPE_FORMAT_BOOLEAN 81)  //col:1607
    BcdOSLoaderInteger_RestrictApicCluster  =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_APPLICATION BCD_ELEMENT_DATATYPE_FORMAT_INTEGER 82)  //col:1612
    BcdOSLoaderString_OSLoaderTypeEVStore  =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_APPLICATION BCD_ELEMENT_DATATYPE_FORMAT_STRING 83)  //col:1617
    BcdOSLoaderBoolean_UseLegacyApicMode  =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_APPLICATION BCD_ELEMENT_DATATYPE_FORMAT_BOOLEAN 84)  //col:1622
    BcdOSLoaderInteger_X2ApicPolicy  =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_APPLICATION BCD_ELEMENT_DATATYPE_FORMAT_INTEGER 85)  //col:1629
    BcdOSLoaderBoolean_UseBootProcessorOnly  =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_APPLICATION BCD_ELEMENT_DATATYPE_FORMAT_BOOLEAN 96)  //col:1634
    BcdOSLoaderInteger_NumberOfProcessors  =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_APPLICATION BCD_ELEMENT_DATATYPE_FORMAT_INTEGER 97)  //col:1639
    BcdOSLoaderBoolean_ForceMaximumProcessors  =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_APPLICATION BCD_ELEMENT_DATATYPE_FORMAT_BOOLEAN 98)  //col:1644
    BcdOSLoaderBoolean_ProcessorConfigurationFlags  =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_APPLICATION BCD_ELEMENT_DATATYPE_FORMAT_INTEGER 99)  //col:1649
    BcdOSLoaderBoolean_MaximizeGroupsCreated  =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_APPLICATION BCD_ELEMENT_DATATYPE_FORMAT_BOOLEAN 100)  //col:1654
    BcdOSLoaderBoolean_ForceGroupAwareness  =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_APPLICATION BCD_ELEMENT_DATATYPE_FORMAT_BOOLEAN 101)  //col:1659
    BcdOSLoaderInteger_GroupSize  =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_APPLICATION BCD_ELEMENT_DATATYPE_FORMAT_INTEGER 102)  //col:1664
    BcdOSLoaderInteger_UseFirmwarePciSettings  =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_APPLICATION BCD_ELEMENT_DATATYPE_FORMAT_BOOLEAN 112)  //col:1669
    BcdOSLoaderInteger_MsiPolicy  =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_APPLICATION BCD_ELEMENT_DATATYPE_FORMAT_INTEGER 113)  //col:1674
    BcdOSLoaderInteger_PciExpressPolicy  =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_APPLICATION BCD_ELEMENT_DATATYPE_FORMAT_INTEGER 114)  //col:1679
    BcdOSLoaderInteger_SafeBoot  =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_APPLICATION BCD_ELEMENT_DATATYPE_FORMAT_INTEGER 128)  //col:1684
    BcdOSLoaderBoolean_SafeBootAlternateShell  =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_APPLICATION BCD_ELEMENT_DATATYPE_FORMAT_BOOLEAN 129)  //col:1690
    BcdOSLoaderBoolean_BootLogInitialization  =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_APPLICATION BCD_ELEMENT_DATATYPE_FORMAT_BOOLEAN 144)  //col:1695
    BcdOSLoaderBoolean_VerboseObjectLoadMode  =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_APPLICATION BCD_ELEMENT_DATATYPE_FORMAT_BOOLEAN 145)  //col:1700
    BcdOSLoaderBoolean_KernelDebuggerEnabled  =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_APPLICATION BCD_ELEMENT_DATATYPE_FORMAT_BOOLEAN 160)  //col:1705
    BcdOSLoaderBoolean_DebuggerHalBreakpoint  =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_APPLICATION BCD_ELEMENT_DATATYPE_FORMAT_BOOLEAN 161)  //col:1710
    BcdOSLoaderBoolean_UsePlatformClock  =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_APPLICATION BCD_ELEMENT_DATATYPE_FORMAT_BOOLEAN 162)  //col:1715
    BcdOSLoaderBoolean_ForceLegacyPlatform  =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_APPLICATION BCD_ELEMENT_DATATYPE_FORMAT_BOOLEAN 163)  //col:1721
    BcdOSLoaderBoolean_UsePlatformTick  =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_APPLICATION BCD_ELEMENT_DATATYPE_FORMAT_BOOLEAN 164)  //col:1726
    BcdOSLoaderBoolean_DisableDynamicTick  =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_APPLICATION BCD_ELEMENT_DATATYPE_FORMAT_BOOLEAN 165)  //col:1731
    BcdOSLoaderInteger_TscSyncPolicy  =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_APPLICATION BCD_ELEMENT_DATATYPE_FORMAT_INTEGER 166)  //col:1737
    BcdOSLoaderBoolean_EmsEnabled  =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_APPLICATION BCD_ELEMENT_DATATYPE_FORMAT_BOOLEAN 176)  //col:1742
    BcdOSLoaderInteger_ForceFailure  =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_APPLICATION BCD_ELEMENT_DATATYPE_FORMAT_INTEGER 192)  //col:1747
    BcdOSLoaderInteger_DriverLoadFailurePolicy  =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_APPLICATION BCD_ELEMENT_DATATYPE_FORMAT_INTEGER 193)  //col:1753
    BcdOSLoaderInteger_BootMenuPolicy  =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_APPLICATION BCD_ELEMENT_DATATYPE_FORMAT_INTEGER 194)  //col:1759
    BcdOSLoaderBoolean_AdvancedOptionsOneTime  =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_APPLICATION BCD_ELEMENT_DATATYPE_FORMAT_BOOLEAN 195)  //col:1765
    BcdOSLoaderBoolean_OptionsEditOneTime  =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_APPLICATION BCD_ELEMENT_DATATYPE_FORMAT_BOOLEAN 196)  //col:1770
    BcdOSLoaderInteger_BootStatusPolicy  =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_APPLICATION BCD_ELEMENT_DATATYPE_FORMAT_INTEGER 224)  //col:1775
    BcdOSLoaderBoolean_DisableElamDrivers  =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_APPLICATION BCD_ELEMENT_DATATYPE_FORMAT_BOOLEAN 225)  //col:1781
    BcdOSLoaderInteger_HypervisorLaunchType  =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_APPLICATION BCD_ELEMENT_DATATYPE_FORMAT_INTEGER 240)  //col:1786
    BcdOSLoaderString_HypervisorPath  =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_APPLICATION BCD_ELEMENT_DATATYPE_FORMAT_INTEGER 241)  //col:1791
    BcdOSLoaderBoolean_HypervisorDebuggerEnabled  =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_APPLICATION BCD_ELEMENT_DATATYPE_FORMAT_BOOLEAN 242)  //col:1796
    BcdOSLoaderInteger_HypervisorDebuggerType  =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_APPLICATION BCD_ELEMENT_DATATYPE_FORMAT_INTEGER 243)  //col:1801
    BcdOSLoaderInteger_HypervisorDebuggerPortNumber  =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_APPLICATION BCD_ELEMENT_DATATYPE_FORMAT_INTEGER 244)  //col:1806
    BcdOSLoaderInteger_HypervisorDebuggerBaudrate  =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_APPLICATION BCD_ELEMENT_DATATYPE_FORMAT_INTEGER 245)  //col:1811
    BcdOSLoaderInteger_HypervisorDebugger1394Channel  =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_APPLICATION BCD_ELEMENT_DATATYPE_FORMAT_INTEGER 246)  //col:1816
    BcdOSLoaderInteger_BootUxPolicy  =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_APPLICATION BCD_ELEMENT_DATATYPE_FORMAT_INTEGER 247)  //col:1821
    BcdOSLoaderInteger_HypervisorSlatDisabled  =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_APPLICATION BCD_ELEMENT_DATATYPE_FORMAT_STRING 248)  //col:1826
    BcdOSLoaderString_HypervisorDebuggerBusParams  =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_APPLICATION BCD_ELEMENT_DATATYPE_FORMAT_STRING 249)  //col:1832
    BcdOSLoaderInteger_HypervisorNumProc  =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_APPLICATION BCD_ELEMENT_DATATYPE_FORMAT_INTEGER 250)  //col:1837
    BcdOSLoaderInteger_HypervisorRootProcPerNode  =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_APPLICATION BCD_ELEMENT_DATATYPE_FORMAT_INTEGER 251)  //col:1842
    BcdOSLoaderBoolean_HypervisorUseLargeVTlb  =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_APPLICATION BCD_ELEMENT_DATATYPE_FORMAT_BOOLEAN 252)  //col:1847
    BcdOSLoaderInteger_HypervisorDebuggerNetHostIp  =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_APPLICATION BCD_ELEMENT_DATATYPE_FORMAT_INTEGER 253)  //col:1852
    BcdOSLoaderInteger_HypervisorDebuggerNetHostPort  =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_APPLICATION BCD_ELEMENT_DATATYPE_FORMAT_INTEGER 254)  //col:1857
    BcdOSLoaderInteger_HypervisorDebuggerPages  =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_APPLICATION BCD_ELEMENT_DATATYPE_FORMAT_INTEGER 255)  //col:1862
    BcdOSLoaderInteger_TpmBootEntropyPolicy  =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_APPLICATION BCD_ELEMENT_DATATYPE_FORMAT_INTEGER 256)  //col:1867
    BcdOSLoaderString_HypervisorDebuggerNetKey  =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_APPLICATION BCD_ELEMENT_DATATYPE_FORMAT_STRING 272)  //col:1872
    BcdOSLoaderString_HypervisorProductSkuType  =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_APPLICATION BCD_ELEMENT_DATATYPE_FORMAT_STRING 274)  //col:1877
    BcdOSLoaderInteger_HypervisorRootProc  =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_APPLICATION BCD_ELEMENT_DATATYPE_FORMAT_STRING 275)  //col:1882
    BcdOSLoaderBoolean_HypervisorDebuggerNetDhcp  =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_APPLICATION BCD_ELEMENT_DATATYPE_FORMAT_BOOLEAN 276)  //col:1887
    BcdOSLoaderInteger_HypervisorIommuPolicy  =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_APPLICATION BCD_ELEMENT_DATATYPE_FORMAT_INTEGER 277)  //col:1892
    BcdOSLoaderBoolean_HypervisorUseVApic  =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_APPLICATION BCD_ELEMENT_DATATYPE_FORMAT_BOOLEAN 278)  //col:1897
    BcdOSLoaderString_HypervisorLoadOptions  =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_APPLICATION BCD_ELEMENT_DATATYPE_FORMAT_STRING 279)  //col:1902
    BcdOSLoaderInteger_HypervisorMsrFilterPolicy  =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_APPLICATION BCD_ELEMENT_DATATYPE_FORMAT_INTEGER 280)  //col:1907
    BcdOSLoaderInteger_HypervisorMmioNxPolicy  =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_APPLICATION BCD_ELEMENT_DATATYPE_FORMAT_INTEGER 281)  //col:1912
    BcdOSLoaderInteger_HypervisorSchedulerType  =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_APPLICATION BCD_ELEMENT_DATATYPE_FORMAT_INTEGER 282)  //col:1917
    BcdOSLoaderString_HypervisorRootProcNumaNodes  =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_APPLICATION BCD_ELEMENT_DATATYPE_FORMAT_STRING 283)  //col:1922
    BcdOSLoaderInteger_HypervisorPerfmon  =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_APPLICATION BCD_ELEMENT_DATATYPE_FORMAT_INTEGER 284)  //col:1927
    BcdOSLoaderInteger_HypervisorRootProcPerCore  =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_APPLICATION BCD_ELEMENT_DATATYPE_FORMAT_INTEGER 285)  //col:1932
    BcdOSLoaderString_HypervisorRootProcNumaNodeLps  =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_APPLICATION BCD_ELEMENT_DATATYPE_FORMAT_STRING 286)  //col:1937
    BcdOSLoaderInteger_XSavePolicy  =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_APPLICATION BCD_ELEMENT_DATATYPE_FORMAT_INTEGER 288)  //col:1942
    BcdOSLoaderInteger_XSaveAddFeature0  =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_APPLICATION BCD_ELEMENT_DATATYPE_FORMAT_INTEGER 289)  //col:1947
    BcdOSLoaderInteger_XSaveAddFeature1  =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_APPLICATION BCD_ELEMENT_DATATYPE_FORMAT_INTEGER 290)  //col:1952
    BcdOSLoaderInteger_XSaveAddFeature2  =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_APPLICATION BCD_ELEMENT_DATATYPE_FORMAT_INTEGER 291)  //col:1957
    BcdOSLoaderInteger_XSaveAddFeature3  =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_APPLICATION BCD_ELEMENT_DATATYPE_FORMAT_INTEGER 292)  //col:1962
    BcdOSLoaderInteger_XSaveAddFeature4  =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_APPLICATION BCD_ELEMENT_DATATYPE_FORMAT_INTEGER 293)  //col:1967
    BcdOSLoaderInteger_XSaveAddFeature5  =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_APPLICATION BCD_ELEMENT_DATATYPE_FORMAT_INTEGER 294)  //col:1972
    BcdOSLoaderInteger_XSaveAddFeature6  =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_APPLICATION BCD_ELEMENT_DATATYPE_FORMAT_INTEGER 295)  //col:1977
    BcdOSLoaderInteger_XSaveAddFeature7  =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_APPLICATION BCD_ELEMENT_DATATYPE_FORMAT_INTEGER 296)  //col:1982
    BcdOSLoaderInteger_XSaveRemoveFeature  =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_APPLICATION BCD_ELEMENT_DATATYPE_FORMAT_INTEGER 297)  //col:1987
    BcdOSLoaderInteger_XSaveProcessorsMask  =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_APPLICATION BCD_ELEMENT_DATATYPE_FORMAT_INTEGER 298)  //col:1992
    BcdOSLoaderInteger_XSaveDisable  =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_APPLICATION BCD_ELEMENT_DATATYPE_FORMAT_INTEGER 299)  //col:1997
    BcdOSLoaderInteger_KernelDebuggerType  =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_APPLICATION BCD_ELEMENT_DATATYPE_FORMAT_INTEGER 300)  //col:2002
    BcdOSLoaderString_KernelDebuggerBusParameters  =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_APPLICATION BCD_ELEMENT_DATATYPE_FORMAT_STRING 301)  //col:2007
    BcdOSLoaderInteger_KernelDebuggerPortAddress  =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_APPLICATION BCD_ELEMENT_DATATYPE_FORMAT_INTEGER 302)  //col:2012
    BcdOSLoaderInteger_KernelDebuggerPortNumber  =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_APPLICATION BCD_ELEMENT_DATATYPE_FORMAT_INTEGER 303)  //col:2017
    BcdOSLoaderInteger_ClaimedTpmCounter  =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_APPLICATION BCD_ELEMENT_DATATYPE_FORMAT_INTEGER 304)  //col:2022
    BcdOSLoaderInteger_KernelDebugger1394Channel  =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_APPLICATION BCD_ELEMENT_DATATYPE_FORMAT_INTEGER 305)  //col:2027
    BcdOSLoaderString_KernelDebuggerUsbTargetname  =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_APPLICATION BCD_ELEMENT_DATATYPE_FORMAT_STRING 306)  //col:2032
    BcdOSLoaderInteger_KernelDebuggerNetHostIp  =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_APPLICATION BCD_ELEMENT_DATATYPE_FORMAT_INTEGER 307)  //col:2037
    BcdOSLoaderInteger_KernelDebuggerNetHostPort  =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_APPLICATION BCD_ELEMENT_DATATYPE_FORMAT_INTEGER 308)  //col:2042
    BcdOSLoaderBoolean_KernelDebuggerNetDhcp  =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_APPLICATION BCD_ELEMENT_DATATYPE_FORMAT_BOOLEAN 309)  //col:2047
    BcdOSLoaderString_KernelDebuggerNetKey  =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_APPLICATION BCD_ELEMENT_DATATYPE_FORMAT_STRING 310)  //col:2052
    BcdOSLoaderString_IMCHiveName  =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_APPLICATION BCD_ELEMENT_DATATYPE_FORMAT_STRING 311)  //col:2057
    BcdOSLoaderDevice_IMCDevice  =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_APPLICATION BCD_ELEMENT_DATATYPE_FORMAT_DEVICE 312)  //col:2062
    BcdOSLoaderInteger_KernelDebuggerBaudrate  =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_APPLICATION BCD_ELEMENT_DATATYPE_FORMAT_INTEGER 313)  //col:2067
    BcdOSLoaderString_ManufacturingMode  =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_APPLICATION BCD_ELEMENT_DATATYPE_FORMAT_STRING 320)  //col:2072
    BcdOSLoaderBoolean_EventLoggingEnabled  =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_APPLICATION BCD_ELEMENT_DATATYPE_FORMAT_BOOLEAN 321)  //col:2077
    BcdOSLoaderInteger_VsmLaunchType  =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_APPLICATION BCD_ELEMENT_DATATYPE_FORMAT_INTEGER 322)  //col:2082
    BcdOSLoaderInteger_HypervisorEnforcedCodeIntegrity  =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_APPLICATION BCD_ELEMENT_DATATYPE_FORMAT_INTEGER 324)  //col:2087
    BcdOSLoaderBoolean_DtraceEnabled  =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_APPLICATION BCD_ELEMENT_DATATYPE_FORMAT_BOOLEAN 325)  //col:2092
    BcdOSLoaderDevice_SystemDataDevice  =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_APPLICATION BCD_ELEMENT_DATATYPE_FORMAT_DEVICE 336)  //col:2097
    BcdOSLoaderDevice_OsArcDevice  =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_APPLICATION BCD_ELEMENT_DATATYPE_FORMAT_DEVICE 337)  //col:2102
    BcdOSLoaderDevice_OsDataDevice  =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_APPLICATION BCD_ELEMENT_DATATYPE_FORMAT_DEVICE 339)  //col:2107
    BcdOSLoaderDevice_BspDevice  =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_APPLICATION BCD_ELEMENT_DATATYPE_FORMAT_DEVICE 340)  //col:2112
    BcdOSLoaderDevice_BspFilepath  =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_APPLICATION BCD_ELEMENT_DATATYPE_FORMAT_DEVICE 341)  //col:2117
    BcdOSLoaderString_KernelDebuggerNetHostIpv6  =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_APPLICATION BCD_ELEMENT_DATATYPE_FORMAT_STRING 342)  //col:2122
    BcdOSLoaderString_HypervisorDebuggerNetHostIpv6  =  MAKE_BCDE_DATA_TYPE(BCD_ELEMENT_DATATYPE_CLASS_APPLICATION BCD_ELEMENT_DATATYPE_FORMAT_STRING 353)  //col:2127
)



type (
Ntbcd interface{
typedef VOID ()(ok bool)//col:176
BcdImportStoreWithFlags()(ok bool)//col:206
BcdOpenStore()(ok bool)//col:251
    ()(ok bool)//col:334
BcdEnumerateObjects()(ok bool)//col:403
BcdCopyObject()(ok bool)//col:468
    ()(ok bool)//col:514
BcdEnumerateElementTypes()(ok bool)//col:543
BcdEnumerateElements()(ok bool)//col:646
BcdEnumerateElementsWithFlags()(ok bool)//col:833
    BcdLibraryDevice_ApplicationDevice = MAKE_BCDE_DATA_TYPE()(ok bool)//col:1361
    BcdSetupInteger_DeviceType = MAKE_BCDE_DATA_TYPE()(ok bool)//col:1395
    BcdOSLoaderDevice_OSDevice = MAKE_BCDE_DATA_TYPE()(ok bool)//col:2128
}

















)

func NewNtbcd() { return & ntbcd{} }

func (n *ntbcd)typedef VOID ()(ok bool){//col:176









































































return true
}


















func (n *ntbcd)BcdImportStoreWithFlags()(ok bool){//col:206























return true
}


















func (n *ntbcd)BcdOpenStore()(ok bool){//col:251




































return true
}


















func (n *ntbcd)    ()(ok bool){//col:334












































return true
}


















func (n *ntbcd)BcdEnumerateObjects()(ok bool){//col:403













































return true
}


















func (n *ntbcd)BcdCopyObject()(ok bool){//col:468















































return true
}


















func (n *ntbcd)    ()(ok bool){//col:514

















return true
}


















func (n *ntbcd)BcdEnumerateElementTypes()(ok bool){//col:543























return true
}


















func (n *ntbcd)BcdEnumerateElements()(ok bool){//col:646

















return true
}


















func (n *ntbcd)BcdEnumerateElementsWithFlags()(ok bool){//col:833















































































return true
}


















func (n *ntbcd)    BcdLibraryDevice_ApplicationDevice = MAKE_BCDE_DATA_TYPE()(ok bool){//col:1361





















































































return true
}


















func (n *ntbcd)    BcdSetupInteger_DeviceType = MAKE_BCDE_DATA_TYPE()(ok bool){//col:1395







return true
}


















func (n *ntbcd)    BcdOSLoaderDevice_OSDevice = MAKE_BCDE_DATA_TYPE()(ok bool){//col:2128
































































































































return true
}




















