package phnt
//back\HyperDbgDev\hyperdbg\dependencies\phnt\phnt_windows.h.back

const(
_PHNT_WINDOWS_H =  //col:13
CINTERFACE =  //col:19
COBJMACROS =  //col:23
INITGUID =  //col:28
WIN32_LEAN_AND_MEAN =  //col:32
WIN32_NO_STATUS =  //col:36
MICROSOFT_WINDOWS_WINBASE_H_DEFINE_INTERLOCKED_CPLUSPLUS_OVERLOADS = 0 //col:42
DESKTOP_ALL_ACCESS = (DESKTOP_CREATEMENU | DESKTOP_CREATEWINDOW | DESKTOP_ENUMERATE | DESKTOP_HOOKCONTROL | DESKTOP_JOURNALPLAYBACK | DESKTOP_JOURNALRECORD | DESKTOP_READOBJECTS | DESKTOP_SWITCHDESKTOP | DESKTOP_WRITEOBJECTS | STANDARD_RIGHTS_REQUIRED) //col:56
DESKTOP_GENERIC_READ = (DESKTOP_ENUMERATE | DESKTOP_READOBJECTS | STANDARD_RIGHTS_READ) //col:61
DESKTOP_GENERIC_WRITE = (DESKTOP_CREATEMENU | DESKTOP_CREATEWINDOW | DESKTOP_HOOKCONTROL | DESKTOP_JOURNALPLAYBACK | DESKTOP_JOURNALRECORD | DESKTOP_WRITEOBJECTS | STANDARD_RIGHTS_WRITE) //col:63
DESKTOP_GENERIC_EXECUTE = (DESKTOP_SWITCHDESKTOP | STANDARD_RIGHTS_EXECUTE) //col:67
WINSTA_GENERIC_READ = (WINSTA_ENUMDESKTOPS | WINSTA_ENUMERATE | WINSTA_READATTRIBUTES | WINSTA_READSCREEN | STANDARD_RIGHTS_READ) //col:71
WINSTA_GENERIC_WRITE = (WINSTA_ACCESSCLIPBOARD | WINSTA_CREATEDESKTOP | WINSTA_WRITEATTRIBUTES | STANDARD_RIGHTS_WRITE) //col:74
WINSTA_GENERIC_EXECUTE = (WINSTA_ACCESSGLOBALATOMS | WINSTA_EXITWINDOWS | STANDARD_RIGHTS_EXECUTE) //col:77
WMIGUID_GENERIC_READ = (WMIGUID_QUERY | WMIGUID_NOTIFICATION | WMIGUID_READ_DESCRIPTION | STANDARD_RIGHTS_READ) //col:81
WMIGUID_GENERIC_WRITE = (WMIGUID_SET | TRACELOG_CREATE_REALTIME | TRACELOG_CREATE_ONDISK | STANDARD_RIGHTS_WRITE) //col:84
WMIGUID_GENERIC_EXECUTE = (WMIGUID_EXECUTE | TRACELOG_GUID_ENABLE | TRACELOG_LOG_EVENT | TRACELOG_ACCESS_REALTIME | TRACELOG_REGISTER_GUIDS | STANDARD_RIGHTS_EXECUTE) //col:87
)


