version: 0.{build}
branches:
  only:
  - master
skip_tags: true
image: Visual Studio 2019
configuration: Release
platform: x86
build:
  project: pdbex.sln
  parallel: true
  verbosity: minimal
artifacts:
- path: Bin\x86\$(Configuration)\*.exe
  name: pdbex
deploy:
- provider: GitHub
  tag: v$(appveyor_build_version)
  auth_token:
    secure: bBXezT+UC8HSipR8wUFj1RrOPgsFjRvJxoBERczc7dJuFH08RhqfPuuJcvpQQsCR
