// Auto-generated by rustgen - DO NOT EDIT
// Source: event_trap.go

#![allow(non_snake_case)]

extern crate alloc;

use alloc::string::String;
use serde::{Serialize, Deserialize};

use super::*;

#[derive(Serialize, Deserialize, Debug, Clone, Default)]
pub struct TrapEvent {
    #[serde(rename = "header")]
    pub header: EventHeader,
    #[serde(rename = "trap_number")]
    pub trap_number: u32,
    #[serde(rename = "error_code")]
    pub error_code: u64,
    #[serde(rename = "address")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub address: Option<String>,
}

