// Auto-generated by rustgen - DO NOT EDIT
// Source: event_msr.go

#![allow(non_snake_case)]
#![allow(unused_imports)]

extern crate alloc;

use alloc::string::String;
use alloc::vec::Vec;
use serde::{Serialize, Deserialize};

use super::*;

#[derive(Serialize, Deserialize, Debug, Clone, Default)]
pub struct MsrEvent {
    #[serde(rename = "header")]
    pub header: EventHeader,
    #[serde(rename = "msr")]
    pub msr: u32,
    #[serde(rename = "is_write")]
    pub is_write: bool,
    #[serde(rename = "value")]
    pub value: u64,
}

