// Auto-generated by rustgen - DO NOT EDIT
// Source: event_breakpoint.go

#![allow(non_snake_case)]

extern crate alloc;

use alloc::string::String;
use alloc::vec::Vec;
use serde::{Serialize, Deserialize};

use super::*;

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[repr(u32)]
pub enum BreakpointType {
    Software = 0,
    Hardware = 1,
    Hidden = 2,
    Ept = 3,
}

impl Default for BreakpointType {
    fn default() -> Self {
        BreakpointType::Software
    }
}

#[derive(Serialize, Deserialize, Debug, Clone, Default)]
pub struct BreakpointEvent {
    #[serde(rename = "header")]
    pub header: EventHeader,
    #[serde(rename = "address")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub address: Option<String>,
    #[serde(rename = "breakpoint_id")]
    pub breakpoint_id: u64,
    #[serde(rename = "registers")]
    pub registers: RegisterState,
}

