// Auto-generated by rustgen - DO NOT EDIT
// Source: event_thread.go

#![allow(non_snake_case)]
#![allow(unused_imports)]

extern crate alloc;

use alloc::string::String;
use alloc::vec::Vec;
use serde::{Serialize, Deserialize};

use super::*;

#[derive(Serialize, Deserialize, Debug, Clone, Default)]
pub struct ThreadEvent {
    #[serde(rename = "header")]
    pub header: EventHeader,
    #[serde(rename = "thread_info")]
    pub thread_info: ThreadInfo,
    #[serde(rename = "is_create")]
    pub is_create: bool,
}

