// Auto-generated by rustgen - DO NOT EDIT
// Source: hook_db_gen.go

#![allow(non_snake_case)]
#![allow(unused_imports)]

extern crate alloc;

use alloc::string::String;
use alloc::vec::Vec;
use serde::{Serialize, Deserialize};

use super::*;

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[repr(i32)]
pub enum HookType {
    EPT = 0,
    Inline = 1,
}

impl Default for HookType {
    fn default() -> Self {
        HookType::EPT
    }
}

#[derive(Serialize, Deserialize, Debug, Clone, Default)]
pub struct HookInfo {
    #[serde(rename = "name")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "params")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub params: Option<Vec<HookParam>>,
    #[serde(rename = "return_type")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub return_type: Option<String>,
    #[serde(rename = "go_type")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub go_type: Option<String>,
}

#[derive(Serialize, Deserialize, Debug, Clone, Default)]
pub struct HookParam {
    #[serde(rename = "name")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "type")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub bp_type: Option<String>,
    #[serde(rename = "go_type")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub go_type: Option<String>,
}

