package Headers

//#define SIZEOF_DEBUGGER_READ_PAGE_TABLE_ENTRIES_DETAILS \
//sizeof(DEBUGGER_READ_PAGE_TABLE_ENTRIES_DETAILS)

type (
	DEBUGGER_READ_PAGE_TABLE_ENTRIES_DETAILS struct {
		VirtualAddress uint64
		ProcessId      uint32

		Pml4eVirtualAddress uint64
		Pml4eValue          uint64

		PdpteVirtualAddress uint64
		PdpteValue          uint64

		PdeVirtualAddress uint64
		PdeValue          uint64

		PteVirtualAddress uint64
		PteValue          uint64

		KernelStatus uint32
	}

	PDEBUGGER_READ_PAGE_TABLE_ENTRIES_DETAILS *DEBUGGER_READ_PAGE_TABLE_ENTRIES_DETAILS
)

//#define SIZEOF_DEBUGGER_VA2PA_AND_PA2VA_COMMANDS \
//sizeof(DEBUGGER_VA2PA_AND_PA2VA_COMMANDS)

type (
	DEBUGGER_VA2PA_AND_PA2VA_COMMANDS struct {
		VirtualAddress     uint64
		PhysicalAddress    uint64
		ProcessId          uint32
		IsVirtual2Physical bool
		KernelStatus       uint32
	}
	PDEBUGGER_VA2PA_AND_PA2VA_COMMANDS *DEBUGGER_VA2PA_AND_PA2VA_COMMANDS
)

// #define SIZEOF_DEBUGGER_DT_COMMAND_OPTIONS \
// sizeof(DEBUGGER_DT_COMMAND_OPTIONS)
type (
	DEBUGGER_DT_COMMAND_OPTIONS struct {
		TypeName             *byte
		SizeOfTypeName       uint64
		Address              uint64
		IsStruct             bool
		BufferAddress        PVOID
		TargetPid            uint32
		AdditionalParameters *byte
	}
	PDEBUGGER_DT_COMMAND_OPTIONS *DEBUGGER_DT_COMMAND_OPTIONS
)

type DEBUGGER_PREALLOC_COMMAND_TYPE byte

const (
	DEBUGGER_PREALLOC_COMMAND_TYPE_MONITOR DEBUGGER_PREALLOC_COMMAND_TYPE = iota
	DEBUGGER_PREALLOC_COMMAND_TYPE_THREAD_INTERCEPTION
)

//#define SIZEOF_DEBUGGER_PREALLOC_COMMAND \
//sizeof(DEBUGGER_PREALLOC_COMMAND)

type (
	DEBUGGER_PREALLOC_COMMAND struct {
		Type         DEBUGGER_PREALLOC_COMMAND_TYPE
		Count        uint64
		KernelStatus uint32
	}
	PDEBUGGER_PREALLOC_COMMAND *DEBUGGER_PREALLOC_COMMAND
)

// #define SIZEOF_DEBUGGER_READ_MEMORY sizeof(DEBUGGER_READ_MEMORY)
type DEBUGGER_READ_READING_TYPE byte

const (
	READ_FROM_KERNEL DEBUGGER_READ_READING_TYPE = iota
	READ_FROM_VMX_ROOT
)

type DEBUGGER_READ_MEMORY_TYPE byte

const (
	DEBUGGER_READ_PHYSICAL_ADDRESS DEBUGGER_READ_MEMORY_TYPE = iota
	DEBUGGER_READ_VIRTUAL_ADDRESS
)

type DEBUGGER_SHOW_MEMORY_STYLE byte

const (
	DEBUGGER_SHOW_MEMORY_STYLE_bad DEBUGGER_SHOW_MEMORY_STYLE = iota
	DEBUGGER_SHOW_COMMAND_DT                                  = 1
	DEBUGGER_SHOW_COMMAND_DISASSEMBLE64
	DEBUGGER_SHOW_COMMAND_DISASSEMBLE32
	DEBUGGER_SHOW_COMMAND_DB
	DEBUGGER_SHOW_COMMAND_DC
	DEBUGGER_SHOW_COMMAND_DQ
	DEBUGGER_SHOW_COMMAND_DD
)
