package phnt
//binding\codespace\gui\sdk\HyperDbgDev\hyperdbg\dependencies\phnt\ntgdi.h.back

const(
_NTGDI_H =  //col:1
GDI_MAX_HANDLE_COUNT = 0xFFFF //col:2
GDI_HANDLE_INDEX_SHIFT = 0 //col:3
GDI_HANDLE_INDEX_BITS = 16 //col:4
GDI_HANDLE_INDEX_MASK = 0xffff //col:5
GDI_HANDLE_TYPE_SHIFT = 16 //col:6
GDI_HANDLE_TYPE_BITS = 5 //col:7
GDI_HANDLE_TYPE_MASK = 0x1f //col:8
GDI_HANDLE_ALTTYPE_SHIFT = 21 //col:9
GDI_HANDLE_ALTTYPE_BITS = 2 //col:10
GDI_HANDLE_ALTTYPE_MASK = 0x3 //col:11
GDI_HANDLE_STOCK_SHIFT = 23 //col:12
GDI_HANDLE_STOCK_BITS = 1 //col:13
GDI_HANDLE_STOCK_MASK = 0x1 //col:14
GDI_HANDLE_UNIQUE_SHIFT = 24 //col:15
GDI_HANDLE_UNIQUE_BITS = 8 //col:16
GDI_HANDLE_UNIQUE_MASK = 0xff //col:17
GDI_HANDLE_INDEX(Handle) = ((ULONG)(Handle) & GDI_HANDLE_INDEX_MASK) //col:18
GDI_HANDLE_TYPE(Handle) = (((ULONG)(Handle) >> GDI_HANDLE_TYPE_SHIFT) & GDI_HANDLE_TYPE_MASK) //col:19
GDI_HANDLE_ALTTYPE(Handle) = (((ULONG)(Handle) >> GDI_HANDLE_ALTTYPE_SHIFT) & GDI_HANDLE_ALTTYPE_MASK) //col:20
GDI_HANDLE_STOCK(Handle) = (((ULONG)(Handle) >> GDI_HANDLE_STOCK_SHIFT)) & GDI_HANDLE_STOCK_MASK) //col:21
GDI_MAKE_HANDLE(Index, = Unique) ((ULONG)(((ULONG)(Unique) << GDI_HANDLE_INDEX_BITS) | (ULONG)(Index))) //col:22
GDI_DEF_TYPE = 0 //col:23
GDI_DC_TYPE = 1 //col:24
GDI_DD_DIRECTDRAW_TYPE = 2 //col:25
GDI_DD_SURFACE_TYPE = 3 //col:26
GDI_RGN_TYPE = 4 //col:27
GDI_SURF_TYPE = 5 //col:28
GDI_CLIENTOBJ_TYPE = 6 //col:29
GDI_PATH_TYPE = 7 //col:30
GDI_PAL_TYPE = 8 //col:31
GDI_ICMLCS_TYPE = 9 //col:32
GDI_LFONT_TYPE = 10 //col:33
GDI_RFONT_TYPE = 11 //col:34
GDI_PFE_TYPE = 12 //col:35
GDI_PFT_TYPE = 13 //col:36
GDI_ICMCXF_TYPE = 14 //col:37
GDI_ICMDLL_TYPE = 15 //col:38
GDI_BRUSH_TYPE = 16 //col:39
GDI_PFF_TYPE = 17 //col:40
GDI_CACHE_TYPE = 18 //col:41
GDI_SPACE_TYPE = 19 //col:42
GDI_DBRUSH_TYPE = 20 //col:43
GDI_META_TYPE = 21 //col:44
GDI_EFSTATE_TYPE = 22 //col:45
GDI_BMFD_TYPE = 23 //col:46
GDI_VTFD_TYPE = 24 //col:47
GDI_TTFD_TYPE = 25 //col:48
GDI_RC_TYPE = 26 //col:49
GDI_TEMP_TYPE = 27 //col:50
GDI_DRVOBJ_TYPE = 28 //col:51
GDI_DCIOBJ_TYPE = 29 //col:52
GDI_SPOOL_TYPE = 30 //col:53
GDI_CLIENT_TYPE_FROM_HANDLE(Handle) ((ULONG)(Handle) & ((GDI_HANDLE_ALTTYPE_MASK << GDI_HANDLE_ALTTYPE_SHIFT) | = (GDI_HANDLE_TYPE_MASK << GDI_HANDLE_TYPE_SHIFT))) //col:54
GDI_CLIENT_TYPE_FROM_UNIQUE(Unique) = GDI_CLIENT_TYPE_FROM_HANDLE((ULONG)(Unique) << 16) //col:56
GDI_ALTTYPE_1 = (1 << GDI_HANDLE_ALTTYPE_SHIFT) //col:57
GDI_ALTTYPE_2 = (2 << GDI_HANDLE_ALTTYPE_SHIFT) //col:58
GDI_ALTTYPE_3 = (3 << GDI_HANDLE_ALTTYPE_SHIFT) //col:59
GDI_CLIENT_BITMAP_TYPE = (GDI_SURF_TYPE << GDI_HANDLE_TYPE_SHIFT) //col:60
GDI_CLIENT_BRUSH_TYPE = (GDI_BRUSH_TYPE << GDI_HANDLE_TYPE_SHIFT) //col:61
GDI_CLIENT_CLIENTOBJ_TYPE = (GDI_CLIENTOBJ_TYPE << GDI_HANDLE_TYPE_SHIFT) //col:62
GDI_CLIENT_DC_TYPE = (GDI_DC_TYPE << GDI_HANDLE_TYPE_SHIFT) //col:63
GDI_CLIENT_FONT_TYPE = (GDI_LFONT_TYPE << GDI_HANDLE_TYPE_SHIFT) //col:64
GDI_CLIENT_PALETTE_TYPE = (GDI_PAL_TYPE << GDI_HANDLE_TYPE_SHIFT) //col:65
GDI_CLIENT_REGION_TYPE = (GDI_RGN_TYPE << GDI_HANDLE_TYPE_SHIFT) //col:66
GDI_CLIENT_ALTDC_TYPE = (GDI_CLIENT_DC_TYPE | GDI_ALTTYPE_1) //col:67
GDI_CLIENT_DIBSECTION_TYPE = (GDI_CLIENT_BITMAP_TYPE | GDI_ALTTYPE_1) //col:68
GDI_CLIENT_EXTPEN_TYPE = (GDI_CLIENT_BRUSH_TYPE | GDI_ALTTYPE_2) //col:69
GDI_CLIENT_METADC16_TYPE = (GDI_CLIENT_CLIENTOBJ_TYPE | GDI_ALTTYPE_3) //col:70
GDI_CLIENT_METAFILE_TYPE = (GDI_CLIENT_CLIENTOBJ_TYPE | GDI_ALTTYPE_2) //col:71
GDI_CLIENT_METAFILE16_TYPE = (GDI_CLIENT_CLIENTOBJ_TYPE | GDI_ALTTYPE_1) //col:72
GDI_CLIENT_PEN_TYPE = (GDI_CLIENT_BRUSH_TYPE | GDI_ALTTYPE_1) //col:73
)

type GDI_HANDLE_ENTRY struct{
Union union
Object PVOID
NextFree PVOID
}


type GDI_SHARED_MEMORY struct{
Handles[GDI_MAX_HANDLE_COUNT] GDI_HANDLE_ENTRY
}




