package phnt
//binding\codespace\gui\sdk\HyperDbgDev\hyperdbg\dependencies\phnt\phnt_windows.h.back

const(
_PHNT_WINDOWS_H =  //col:1
CINTERFACE =  //col:2
COBJMACROS =  //col:3
INITGUID =  //col:4
WIN32_LEAN_AND_MEAN =  //col:5
WIN32_NO_STATUS =  //col:6
MICROSOFT_WINDOWS_WINBASE_H_DEFINE_INTERLOCKED_CPLUSPLUS_OVERLOADS = 0 //col:7
DESKTOP_ALL_ACCESS = (DESKTOP_CREATEMENU | DESKTOP_CREATEWINDOW | DESKTOP_ENUMERATE | DESKTOP_HOOKCONTROL | DESKTOP_JOURNALPLAYBACK | DESKTOP_JOURNALRECORD | DESKTOP_READOBJECTS | DESKTOP_SWITCHDESKTOP | DESKTOP_WRITEOBJECTS | STANDARD_RIGHTS_REQUIRED) //col:8
DESKTOP_GENERIC_READ = (DESKTOP_ENUMERATE | DESKTOP_READOBJECTS | STANDARD_RIGHTS_READ) //col:13
DESKTOP_GENERIC_WRITE = (DESKTOP_CREATEMENU | DESKTOP_CREATEWINDOW | DESKTOP_HOOKCONTROL | DESKTOP_JOURNALPLAYBACK | DESKTOP_JOURNALRECORD | DESKTOP_WRITEOBJECTS | STANDARD_RIGHTS_WRITE) //col:15
DESKTOP_GENERIC_EXECUTE = (DESKTOP_SWITCHDESKTOP | STANDARD_RIGHTS_EXECUTE) //col:19
WINSTA_GENERIC_READ = (WINSTA_ENUMDESKTOPS | WINSTA_ENUMERATE | WINSTA_READATTRIBUTES | WINSTA_READSCREEN | STANDARD_RIGHTS_READ) //col:21
WINSTA_GENERIC_WRITE = (WINSTA_ACCESSCLIPBOARD | WINSTA_CREATEDESKTOP | WINSTA_WRITEATTRIBUTES | STANDARD_RIGHTS_WRITE) //col:24
WINSTA_GENERIC_EXECUTE = (WINSTA_ACCESSGLOBALATOMS | WINSTA_EXITWINDOWS | STANDARD_RIGHTS_EXECUTE) //col:27
WMIGUID_GENERIC_READ = (WMIGUID_QUERY | WMIGUID_NOTIFICATION | WMIGUID_READ_DESCRIPTION | STANDARD_RIGHTS_READ) //col:29
WMIGUID_GENERIC_WRITE = (WMIGUID_SET | TRACELOG_CREATE_REALTIME | TRACELOG_CREATE_ONDISK | STANDARD_RIGHTS_WRITE) //col:32
WMIGUID_GENERIC_EXECUTE = (WMIGUID_EXECUTE | TRACELOG_GUID_ENABLE | TRACELOG_LOG_EVENT | TRACELOG_ACCESS_REALTIME | TRACELOG_REGISTER_GUIDS | STANDARD_RIGHTS_EXECUTE) //col:35
)


