// Code generated by gengo. DO NOT EDIT.
package bug

import (
	"unsafe"
	"github.com/can1357/gengo/gengort"
)

const GengoLibraryName = "bug"

var GengoLibrary = gengort.NewLibrary(GengoLibraryName)

type _Int128T = any
type _Uint128T = any
type __NSConstantString = any
type SizeT = uint64
type _BuiltinMsVaList = *byte
type _BuiltinVaList = *byte
type Qword = uint64
type Uint64 = uint64
type Puint64 = *uint64
type Dword = uint64
type Bool = int32
type Byte = uint8
type Word = uint16
type Int = int32
type Uint = uint32
type Puint = *uint32
type Ulong64 = uint64
type Pulong64 = *uint64
type Dword64 = uint64
type Pdword64 = *uint64
type Char = byte
type Wchar = any
type Uchar = uint8
type Ushort = uint16
type Ulong = uint64
type Boolean = Uchar
type Pboolean = *Boolean
type Int8 = int8
type Pint8 = *int8
type Int16 = int16
type Pint16 = *int16
type Int32 = int32
type Pint32 = *int32
type Int64 = int64
type Pint64 = *int64
type Uint8 = uint8
type Puint8 = *uint8
type Uint16 = uint16
type Puint16 = *uint16
type Uint32 = uint32
type Puint32 = *uint32
type Uint64 = uint64
type Puint64 = *uint64
type Cr3Type = any
type Pcr3Type = unsafe.Pointer

//  Gengo init function.
func init() {}
