// Code generated by gengo. DO NOT EDIT.
package bug

import (
	"unsafe"

	"github.com/can1357/gengo/gengort"
)

const GengoLibraryName = "bug"

var GengoLibrary = gengort.NewLibrary(GengoLibraryName)

type (
	_Int128T                   = any
	_Uint128T                  = any
	__NSConstantString         = any
	SizeT                      = uint64
	_BuiltinMsVaList           = *byte
	_BuiltinVaList             = *byte
	Qword                      = uint64
	Uint64                     = uint64
	Puint64                    = *uint64
	Dword                      = uint64
	Bool                       = int32
	Byte                       = uint8
	Word                       = uint16
	Int                        = int32
	Uint                       = uint32
	Puint                      = *uint32
	Ulong64                    = uint64
	Pulong64                   = *uint64
	Dword64                    = uint64
	Pdword64                   = *uint64
	Char                       = byte
	Wchar                      = any
	Uchar                      = uint8
	Ushort                     = uint16
	Ulong                      = uint64
	Boolean                    = Uchar
	Pboolean                   = *Boolean
	Int8                       = int8
	Pint8                      = *int8
	Int16                      = int16
	Pint16                     = *int16
	Int32                      = int32
	Pint32                     = *int32
	Int64                      = int64
	Pint64                     = *int64
	Uint8                      = uint8
	Puint8                     = *uint8
	Uint16                     = uint16
	Puint16                    = *uint16
	Uint32                     = uint32
	Puint32                    = *uint32
	Uint64                     = uint64
	Puint64                    = *uint64
	Cr3Type                    = any
	Pcr3Type                   = unsafe.Pointer
	XedImmdisT                 = any
	VmxSegmentAccessRightsType = any
)

// Gengo init function.
func init() {}
