package header
//back\HyperDbgDev\hyperdbg\script-engine\header\parse-table.h.back

const(
PARSE_TABLE_H =  //col:3
RULES_COUNT = 134 //col:4
TERMINAL_COUNT = 73 //col:5
NONETERMINAL_COUNT = 34 //col:6
START_VARIABLE = "S" //col:7
MAX_RHS_LEN = 15 //col:8
KEYWORD_LIST_LENGTH = 58 //col:9
OPERATORS_ONE_OPERAND_LIST_LENGTH = 4 //col:10
OPERATORS_TWO_OPERAND_LIST_LENGTH = 16 //col:11
REGISTER_MAP_LIST_LENGTH = 120 //col:12
PSEUDO_REGISTER_MAP_LIST_LENGTH = 13 //col:13
SEMANTIC_RULES_MAP_LIST_LENGTH = 97 //col:14
THREEOPFUNC1_LENGTH = 1 //col:15
TWOOPFUNC1_LENGTH = 5 //col:16
TWOOPFUNC2_LENGTH = 1 //col:17
ONEOPFUNC1_LENGTH = 17 //col:18
ONEOPFUNC2_LENGTH = 7 //col:19
ZEROOPFUNC1_LENGTH = 3 //col:20
VARARGFUNC1_LENGTH = 1 //col:21
LALR_RULES_COUNT = 69 //col:43
LALR_TERMINAL_COUNT = 54 //col:44
LALR_NONTERMINAL_COUNT = 15 //col:45
LALR_MAX_RHS_LEN = 9 //col:46
LALR_STATE_COUNT = 180 //col:47
)


