// Code generated by gengo. DO NOT EDIT.
package ARImpRec

import (
	"github.com/can1357/gengo/gengort"
)

const GengoLibraryName = "ARImpRec"

var GengoLibrary = gengort.NewLibrary(GengoLibraryName)

type (
	_Int128T           = any
	_Uint128T          = any
	__NSConstantString = any
	SizeT              = uint64
	_BuiltinMsVaList   = *byte
	_BuiltinVaList     = *byte
)

var __imp_UnpackPdataSection gengort.PreloadProc

// Gengo init function.
func init() {
	__imp_UnpackPdataSection = GengoLibrary.ImportNow("UnpackPdataSection")
	__imp_GetNameFileOptimized = GengoLibrary.ImportNow("GetNameFileOptimized")
	__imp_RebuildSectionsFromArmadillo = GengoLibrary.ImportNow("RebuildSectionsFromArmadillo")
	__imp_TryGetImportedFunction = GengoLibrary.ImportNow("TryGetImportedFunction")
	__imp_SearchAndRebuildImportsNoNewSection = GengoLibrary.ImportNow("SearchAndRebuildImportsNoNewSection")
	__imp_SearchAndRebuildImportsIATOptimized = GengoLibrary.ImportNow("SearchAndRebuildImportsIATOptimized")
	__imp_SearchAndRebuildImports = GengoLibrary.ImportNow("SearchAndRebuildImports")
	__imp_GetProcNameAndOrdinal = GengoLibrary.ImportNow("GetProcNameAndOrdinal")
	__imp_GetProcOrdinal = GengoLibrary.ImportNow("GetProcOrdinal")
	__imp_GetProcName = GengoLibrary.ImportNow("GetProcName")
	__imp_GetAllVAddressesOfImports = GengoLibrary.ImportNow("GetAllVAddressesOfImports")
}
func UnpackPdataSection() { gengort.CCall0(__imp_UnpackPdataSection.Addr()) }

var __imp_GetNameFileOptimized gengort.PreloadProc

func GetNameFileOptimized() { gengort.CCall0(__imp_GetNameFileOptimized.Addr()) }

var __imp_RebuildSectionsFromArmadillo gengort.PreloadProc

func RebuildSectionsFromArmadillo() { gengort.CCall0(__imp_RebuildSectionsFromArmadillo.Addr()) }

var __imp_TryGetImportedFunction gengort.PreloadProc

func TryGetImportedFunction() { gengort.CCall0(__imp_TryGetImportedFunction.Addr()) }

var __imp_SearchAndRebuildImportsNoNewSection gengort.PreloadProc

func SearchAndRebuildImportsNoNewSection() {
	gengort.CCall0(__imp_SearchAndRebuildImportsNoNewSection.Addr())
}

var __imp_SearchAndRebuildImportsIATOptimized gengort.PreloadProc

func SearchAndRebuildImportsIATOptimized() {
	gengort.CCall0(__imp_SearchAndRebuildImportsIATOptimized.Addr())
}

var __imp_SearchAndRebuildImports gengort.PreloadProc

func SearchAndRebuildImports() { gengort.CCall0(__imp_SearchAndRebuildImports.Addr()) }

var __imp_GetProcNameAndOrdinal gengort.PreloadProc

func GetProcNameAndOrdinal() { gengort.CCall0(__imp_GetProcNameAndOrdinal.Addr()) }

var __imp_GetProcOrdinal gengort.PreloadProc

func GetProcOrdinal() { gengort.CCall0(__imp_GetProcOrdinal.Addr()) }

var __imp_GetProcName gengort.PreloadProc

func GetProcName() { gengort.CCall0(__imp_GetProcName.Addr()) }

var __imp_GetAllVAddressesOfImports gengort.PreloadProc

func GetAllVAddressesOfImports() { gengort.CCall0(__imp_GetAllVAddressesOfImports.Addr()) }
