package vmx


const(
RESERVED_MSR_RANGE_LOW = 0x40000000 //col:18
RESERVED_MSR_RANGE_HI =  0x4000109F //col:19
)

const(
    EXCEPTION_VECTOR_DIVIDE_ERROR = 1  //col:31
    EXCEPTION_VECTOR_DEBUG_BREAKPOINT = 2  //col:32
    EXCEPTION_VECTOR_NMI = 3  //col:33
    EXCEPTION_VECTOR_BREAKPOINT = 4  //col:34
    EXCEPTION_VECTOR_OVERFLOW = 5  //col:35
    EXCEPTION_VECTOR_BOUND_RANGE_EXCEEDED = 6  //col:36
    EXCEPTION_VECTOR_UNDEFINED_OPCODE = 7  //col:37
    EXCEPTION_VECTOR_NO_MATH_COPROCESSOR = 8  //col:38
    EXCEPTION_VECTOR_DOUBLE_FAULT = 9  //col:39
    EXCEPTION_VECTOR_RESERVED0 = 10  //col:40
    EXCEPTION_VECTOR_INVALID_TASK_SEGMENT_SELECTOR = 11  //col:41
    EXCEPTION_VECTOR_SEGMENT_NOT_PRESENT = 12  //col:42
    EXCEPTION_VECTOR_STACK_SEGMENT_FAULT = 13  //col:43
    EXCEPTION_VECTOR_GENERAL_PROTECTION_FAULT = 14  //col:44
    EXCEPTION_VECTOR_PAGE_FAULT = 15  //col:45
    EXCEPTION_VECTOR_RESERVED1 = 16  //col:46
    EXCEPTION_VECTOR_MATH_FAULT = 17  //col:47
    EXCEPTION_VECTOR_ALIGNMENT_CHECK = 18  //col:48
    EXCEPTION_VECTOR_MACHINE_CHECK = 19  //col:49
    EXCEPTION_VECTOR_SIMD_FLOATING_POINT_NUMERIC_ERROR = 20  //col:50
    EXCEPTION_VECTOR_VIRTUAL_EXCEPTION = 21  //col:51
    EXCEPTION_VECTOR_RESERVED2 = 22  //col:52
    EXCEPTION_VECTOR_RESERVED3 = 23  //col:53
    EXCEPTION_VECTOR_RESERVED4 = 24  //col:54
    EXCEPTION_VECTOR_RESERVED5 = 25  //col:55
    EXCEPTION_VECTOR_RESERVED6 = 26  //col:56
    EXCEPTION_VECTOR_RESERVED7 = 27  //col:57
    EXCEPTION_VECTOR_RESERVED8 = 28  //col:58
    EXCEPTION_VECTOR_RESERVED9 = 29  //col:59
    EXCEPTION_VECTOR_RESERVED10 = 30  //col:60
    EXCEPTION_VECTOR_RESERVED11 = 31  //col:61
    EXCEPTION_VECTOR_RESERVED12 = 32  //col:62
    APC_INTERRUPT    =  31  //col:67
    DPC_INTERRUPT    =  47  //col:68
    CLOCK_INTERRUPT  =  209  //col:69
    IPI_INTERRUPT    =  225  //col:70
    PMI_INTERRUPT    =  254  //col:71
)


const(
    INTERRUPT_TYPE_EXTERNAL_INTERRUPT             =  0  //col:81
    INTERRUPT_TYPE_RESERVED                       =  1  //col:82
    INTERRUPT_TYPE_NMI                            =  2  //col:83
    INTERRUPT_TYPE_HARDWARE_EXCEPTION             =  3  //col:84
    INTERRUPT_TYPE_SOFTWARE_INTERRUPT             =  4  //col:85
    INTERRUPT_TYPE_PRIVILEGED_SOFTWARE_INTERRUPT  =  5  //col:86
    INTERRUPT_TYPE_SOFTWARE_EXCEPTION             =  6  //col:87
    INTERRUPT_TYPE_OTHER_EVENT                    =  7  //col:88
)




