package vmx

//back\HyperDbgDev\hyperdbg\hprdbghv\header\vmm\vmx\ProtectedHv.h.back

type // uint32
const (
	// PROTECTED_HV_RESOURCES_PASSING_OVERS = 1  //col:27
	// for exception bitmap PROTECTED_HV_RESOURCES_PASSING_OVERS = 2  //col:28
	// PROTECTED_HV_RESOURCES_PASSING_OVERS = 3  //col:29
	PASSING_OVER_NONE                                  PROTECTED_HV_RESOURCES_PASSING_OVERS = 0 //col:30
	PASSING_OVER_UD_EXCEPTIONS_FOR_SYSCALL_SYSRET_HOOK PROTECTED_HV_RESOURCES_PASSING_OVERS = 1 //col:31
	PASSING_OVER_EXCEPTION_EVENTS                      PROTECTED_HV_RESOURCES_PASSING_OVERS = 6 //col:32
	// PROTECTED_HV_RESOURCES_PASSING_OVERS = 7  //col:34
	// for external interupts-exitings PROTECTED_HV_RESOURCES_PASSING_OVERS = 8  //col:35
	// PROTECTED_HV_RESOURCES_PASSING_OVERS = 9  //col:36
	PASSING_OVER_INTERRUPT_EVENTS PROTECTED_HV_RESOURCES_PASSING_OVERS = 10 //col:37
	// PROTECTED_HV_RESOURCES_PASSING_OVERS = 11  //col:39
	// for external rdtsc/p exitings PROTECTED_HV_RESOURCES_PASSING_OVERS = 12  //col:40
	// PROTECTED_HV_RESOURCES_PASSING_OVERS = 13  //col:41
	PASSING_OVER_TSC_EVENTS PROTECTED_HV_RESOURCES_PASSING_OVERS = 14 //col:42
	// PROTECTED_HV_RESOURCES_PASSING_OVERS = 15  //col:44
	// for external mov to hardware debug registers exitings PROTECTED_HV_RESOURCES_PASSING_OVERS = 16  //col:45
	// PROTECTED_HV_RESOURCES_PASSING_OVERS = 17  //col:46
	PASSING_OVER_MOV_TO_HW_DEBUG_REGS_EVENTS PROTECTED_HV_RESOURCES_PASSING_OVERS = 18 //col:47
	// PROTECTED_HV_RESOURCES_PASSING_OVERS = 19  //col:49
	// for external mov to control registers exitings PROTECTED_HV_RESOURCES_PASSING_OVERS = 20  //col:50
	// PROTECTED_HV_RESOURCES_PASSING_OVERS = 21  //col:51
	PASSING_OVER_MOV_TO_CONTROL_REGS_EVENTS PROTECTED_HV_RESOURCES_PASSING_OVERS = 22 //col:52
)
