// Code generated by "stringer -type=ExceptionClass -linecomment"; DO NOT EDIT.

package zydis

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ExceptionClassNone-0]
	_ = x[ExceptionClassSSE1-1]
	_ = x[ExceptionClassSSE2-2]
	_ = x[ExceptionClassSSE3-3]
	_ = x[ExceptionClassSSE4-4]
	_ = x[ExceptionClassSSE5-5]
	_ = x[ExceptionClassSSE7-6]
	_ = x[ExceptionClassAVX1-7]
	_ = x[ExceptionClassAVX2-8]
	_ = x[ExceptionClassAVX3-9]
	_ = x[ExceptionClassAVX4-10]
	_ = x[ExceptionClassAVX5-11]
	_ = x[ExceptionClassAVX6-12]
	_ = x[ExceptionClassAVX7-13]
	_ = x[ExceptionClassAVX8-14]
	_ = x[ExceptionClassAVX11-15]
	_ = x[ExceptionClassAVX12-16]
	_ = x[ExceptionClassE1-17]
	_ = x[ExceptionClassE1NF-18]
	_ = x[ExceptionClassE2-19]
	_ = x[ExceptionClassE2NF-20]
	_ = x[ExceptionClassE3-21]
	_ = x[ExceptionClassE3NF-22]
	_ = x[ExceptionClassE4-23]
	_ = x[ExceptionClassE4NF-24]
	_ = x[ExceptionClassE5-25]
	_ = x[ExceptionClassE5NF-26]
	_ = x[ExceptionClassE6-27]
	_ = x[ExceptionClassE6NF-28]
	_ = x[ExceptionClassE7NM-29]
	_ = x[ExceptionClassE7NM128-30]
	_ = x[ExceptionClassE9NF-31]
	_ = x[ExceptionClassE10-32]
	_ = x[ExceptionClassE10NF-33]
	_ = x[ExceptionClassE11-34]
	_ = x[ExceptionClassE11NF-35]
	_ = x[ExceptionClassE12-36]
	_ = x[ExceptionClassE12NP-37]
	_ = x[ExceptionClassK20-38]
	_ = x[ExceptionClassK21-39]
	_ = x[ExceptionClassAMXE1-40]
	_ = x[ExceptionClassAMXE2-41]
	_ = x[ExceptionClassAMXE3-42]
	_ = x[ExceptionClassAMXE4-43]
	_ = x[ExceptionClassAMXE5-44]
	_ = x[ExceptionClassAMXE6-45]
}

const _ExceptionClass_name = "ExceptionClassNoneSSE1SSE2SSE3SSE4SSE5SSE7AVX1AVX2AVX3AVX4AVX5AVX6AVX7AVX8AVX11AVX12E1E1NFE2E2NFE3E3NFE4E4NFE5E5NFE6E6NFE7NME7NM128E9NFE10E10NFE11E11NFE12E12NPK20K21AMXE1AMXE2AMXE3AMXE4AMXE5AMXE6"

var _ExceptionClass_index = [...]uint8{0, 18, 22, 26, 30, 34, 38, 42, 46, 50, 54, 58, 62, 66, 70, 74, 79, 84, 86, 90, 92, 96, 98, 102, 104, 108, 110, 114, 116, 120, 124, 131, 135, 138, 143, 146, 151, 154, 159, 162, 165, 170, 175, 180, 185, 190, 195}

func (i ExceptionClass) String() string {
	if i < 0 || i >= ExceptionClass(len(_ExceptionClass_index)-1) {
		return "ExceptionClass(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ExceptionClass_name[_ExceptionClass_index[i]:_ExceptionClass_index[i+1]]
}
