// Copyright 2019 John Papandriopoulos.  All rights reserved.
// Use of this source code is governed by a MIT-style
// license that can be found in the LICENSE file.

package zydis

// Mnemonic is an enum of instruction mnemonics.
type Mnemonic int

//go:generate stringer -type=Mnemonic -linecomment

// Mnemonic values
const (
	MnemonicINVALID            Mnemonic = iota // invalid
	MnemonicAAA                                // aaa
	MnemonicAAD                                // aad
	MnemonicAAM                                // aam
	MnemonicAAS                                // aas
	MnemonicADC                                // adc
	MnemonicADCX                               // adcx
	MnemonicADD                                // add
	MnemonicADDPD                              // addpd
	MnemonicADDPS                              // addps
	MnemonicADDSD                              // addsd
	MnemonicADDSS                              // addss
	MnemonicADDSUBPD                           // addsubpd
	MnemonicADDSUBPS                           // addsubps
	MnemonicADOX                               // adox
	MnemonicAESDEC                             // aesdec
	MnemonicAESDECLAST                         // aesdeclast
	MnemonicAESENC                             // aesenc
	MnemonicAESENCLAST                         // aesenclast
	MnemonicAESIMC                             // aesimc
	MnemonicAESKEYGENASSIST                    // aeskeygenassist
	MnemonicAND                                // and
	MnemonicANDN                               // andn
	MnemonicANDNPD                             // andnpd
	MnemonicANDNPS                             // andnps
	MnemonicANDPD                              // andpd
	MnemonicANDPS                              // andps
	MnemonicARPL                               // arpl
	MnemonicBEXTR                              // bextr
	MnemonicBLCFILL                            // blcfill
	MnemonicBLCI                               // blci
	MnemonicBLCIC                              // blcic
	MnemonicBLCMSK                             // blcmsk
	MnemonicBLCS                               // blcs
	MnemonicBLENDPD                            // blendpd
	MnemonicBLENDPS                            // blendps
	MnemonicBLENDVPD                           // blendvpd
	MnemonicBLENDVPS                           // blendvps
	MnemonicBLSFILL                            // blsfill
	MnemonicBLSI                               // blsi
	MnemonicBLSIC                              // blsic
	MnemonicBLSMSK                             // blsmsk
	MnemonicBLSR                               // blsr
	MnemonicBNDCL                              // bndcl
	MnemonicBNDCN                              // bndcn
	MnemonicBNDCU                              // bndcu
	MnemonicBNDLDX                             // bndldx
	MnemonicBNDMK                              // bndmk
	MnemonicBNDMOV                             // bndmov
	MnemonicBNDSTX                             // bndstx
	MnemonicBOUND                              // bound
	MnemonicBSF                                // bsf
	MnemonicBSR                                // bsr
	MnemonicBSWAP                              // bswap
	MnemonicBT                                 // bt
	MnemonicBTC                                // btc
	MnemonicBTR                                // btr
	MnemonicBTS                                // bts
	MnemonicBZHI                               // bzhi
	MnemonicCALL                               // call
	MnemonicCBW                                // cbw
	MnemonicCDQ                                // cdq
	MnemonicCDQE                               // cdqe
	MnemonicCLAC                               // clac
	MnemonicCLC                                // clc
	MnemonicCLD                                // cld
	MnemonicCLDEMOTE                           // cldemote
	MnemonicCLEVICT0                           // clevict0
	MnemonicCLEVICT1                           // clevict1
	MnemonicCLFLUSH                            // clflush
	MnemonicCLFLUSHOPT                         // clflushopt
	MnemonicCLGI                               // clgi
	MnemonicCLI                                // cli
	MnemonicCLRSSBSY                           // clrssbsy
	MnemonicCLTS                               // clts
	MnemonicCLWB                               // clwb
	MnemonicCLZERO                             // clzero
	MnemonicCMC                                // cmc
	MnemonicCMOVB                              // cmovb
	MnemonicCMOVBE                             // cmovbe
	MnemonicCMOVL                              // cmovl
	MnemonicCMOVLE                             // cmovle
	MnemonicCMOVNB                             // cmovnb
	MnemonicCMOVNBE                            // cmovnbe
	MnemonicCMOVNL                             // cmovnl
	MnemonicCMOVNLE                            // cmovnle
	MnemonicCMOVNO                             // cmovno
	MnemonicCMOVNP                             // cmovnp
	MnemonicCMOVNS                             // cmovns
	MnemonicCMOVNZ                             // cmovnz
	MnemonicCMOVO                              // cmovo
	MnemonicCMOVP                              // cmovp
	MnemonicCMOVS                              // cmovs
	MnemonicCMOVZ                              // cmovz
	MnemonicCMP                                // cmp
	MnemonicCMPPD                              // cmppd
	MnemonicCMPPS                              // cmpps
	MnemonicCMPSB                              // cmpsb
	MnemonicCMPSD                              // cmpsd
	MnemonicCMPSQ                              // cmpsq
	MnemonicCMPSS                              // cmpss
	MnemonicCMPSW                              // cmpsw
	MnemonicCMPXCHG                            // cmpxchg
	MnemonicCMPXCHG16B                         // cmpxchg16b
	MnemonicCMPXCHG8B                          // cmpxchg8b
	MnemonicCOMISD                             // comisd
	MnemonicCOMISS                             // comiss
	MnemonicCPUID                              // cpuid
	MnemonicCQO                                // cqo
	MnemonicCRC32                              // crc32
	MnemonicCVTDQ2PD                           // cvtdq2pd
	MnemonicCVTDQ2PS                           // cvtdq2ps
	MnemonicCVTPD2DQ                           // cvtpd2dq
	MnemonicCVTPD2PI                           // cvtpd2pi
	MnemonicCVTPD2PS                           // cvtpd2ps
	MnemonicCVTPI2PD                           // cvtpi2pd
	MnemonicCVTPI2PS                           // cvtpi2ps
	MnemonicCVTPS2DQ                           // cvtps2dq
	MnemonicCVTPS2PD                           // cvtps2pd
	MnemonicCVTPS2PI                           // cvtps2pi
	MnemonicCVTSD2SI                           // cvtsd2si
	MnemonicCVTSD2SS                           // cvtsd2ss
	MnemonicCVTSI2SD                           // cvtsi2sd
	MnemonicCVTSI2SS                           // cvtsi2ss
	MnemonicCVTSS2SD                           // cvtss2sd
	MnemonicCVTSS2SI                           // cvtss2si
	MnemonicCVTTPD2DQ                          // cvttpd2dq
	MnemonicCVTTPD2PI                          // cvttpd2pi
	MnemonicCVTTPS2DQ                          // cvttps2dq
	MnemonicCVTTPS2PI                          // cvttps2pi
	MnemonicCVTTSD2SI                          // cvttsd2si
	MnemonicCVTTSS2SI                          // cvttss2si
	MnemonicCWD                                // cwd
	MnemonicCWDE                               // cwde
	MnemonicDAA                                // daa
	MnemonicDAS                                // das
	MnemonicDEC                                // dec
	MnemonicDELAY                              // delay
	MnemonicDIV                                // div
	MnemonicDIVPD                              // divpd
	MnemonicDIVPS                              // divps
	MnemonicDIVSD                              // divsd
	MnemonicDIVSS                              // divss
	MnemonicDPPD                               // dppd
	MnemonicDPPS                               // dpps
	MnemonicEMMS                               // emms
	MnemonicENCLS                              // encls
	MnemonicENCLU                              // enclu
	MnemonicENCLV                              // enclv
	MnemonicENDBR32                            // endbr32
	MnemonicENDBR64                            // endbr64
	MnemonicENQCMD                             // enqcmd
	MnemonicENQCMDS                            // enqcmds
	MnemonicENTER                              // enter
	MnemonicEXTRACTPS                          // extractps
	MnemonicEXTRQ                              // extrq
	MnemonicF2XM1                              // f2xm1
	MnemonicFABS                               // fabs
	MnemonicFADD                               // fadd
	MnemonicFADDP                              // faddp
	MnemonicFBLD                               // fbld
	MnemonicFBSTP                              // fbstp
	MnemonicFCHS                               // fchs
	MnemonicFCMOVB                             // fcmovb
	MnemonicFCMOVBE                            // fcmovbe
	MnemonicFCMOVE                             // fcmove
	MnemonicFCMOVNB                            // fcmovnb
	MnemonicFCMOVNBE                           // fcmovnbe
	MnemonicFCMOVNE                            // fcmovne
	MnemonicFCMOVNU                            // fcmovnu
	MnemonicFCMOVU                             // fcmovu
	MnemonicFCOM                               // fcom
	MnemonicFCOMI                              // fcomi
	MnemonicFCOMIP                             // fcomip
	MnemonicFCOMP                              // fcomp
	MnemonicFCOMPP                             // fcompp
	MnemonicFCOS                               // fcos
	MnemonicFDECSTP                            // fdecstp
	MnemonicFDISI8087NOP                       // fdisi8087nop
	MnemonicFDIV                               // fdiv
	MnemonicFDIVP                              // fdivp
	MnemonicFDIVR                              // fdivr
	MnemonicFDIVRP                             // fdivrp
	MnemonicFEMMS                              // femms
	MnemonicFENI8087NOP                        // feni8087nop
	MnemonicFFREE                              // ffree
	MnemonicFFREEP                             // ffreep
	MnemonicFIADD                              // fiadd
	MnemonicFICOM                              // ficom
	MnemonicFICOMP                             // ficomp
	MnemonicFIDIV                              // fidiv
	MnemonicFIDIVR                             // fidivr
	MnemonicFILD                               // fild
	MnemonicFIMUL                              // fimul
	MnemonicFINCSTP                            // fincstp
	MnemonicFIST                               // fist
	MnemonicFISTP                              // fistp
	MnemonicFISTTP                             // fisttp
	MnemonicFISUB                              // fisub
	MnemonicFISUBR                             // fisubr
	MnemonicFLD                                // fld
	MnemonicFLD1                               // fld1
	MnemonicFLDCW                              // fldcw
	MnemonicFLDENV                             // fldenv
	MnemonicFLDL2E                             // fldl2e
	MnemonicFLDL2T                             // fldl2t
	MnemonicFLDLG2                             // fldlg2
	MnemonicFLDLN2                             // fldln2
	MnemonicFLDPI                              // fldpi
	MnemonicFLDZ                               // fldz
	MnemonicFMUL                               // fmul
	MnemonicFMULP                              // fmulp
	MnemonicFNCLEX                             // fnclex
	MnemonicFNINIT                             // fninit
	MnemonicFNOP                               // fnop
	MnemonicFNSAVE                             // fnsave
	MnemonicFNSTCW                             // fnstcw
	MnemonicFNSTENV                            // fnstenv
	MnemonicFNSTSW                             // fnstsw
	MnemonicFPATAN                             // fpatan
	MnemonicFPREM                              // fprem
	MnemonicFPREM1                             // fprem1
	MnemonicFPTAN                              // fptan
	MnemonicFRNDINT                            // frndint
	MnemonicFRSTOR                             // frstor
	MnemonicFSCALE                             // fscale
	MnemonicFSETPM287NOP                       // fsetpm287nop
	MnemonicFSIN                               // fsin
	MnemonicFSINCOS                            // fsincos
	MnemonicFSQRT                              // fsqrt
	MnemonicFST                                // fst
	MnemonicFSTP                               // fstp
	MnemonicFSTPNCE                            // fstpnce
	MnemonicFSUB                               // fsub
	MnemonicFSUBP                              // fsubp
	MnemonicFSUBR                              // fsubr
	MnemonicFSUBRP                             // fsubrp
	MnemonicFTST                               // ftst
	MnemonicFUCOM                              // fucom
	MnemonicFUCOMI                             // fucomi
	MnemonicFUCOMIP                            // fucomip
	MnemonicFUCOMP                             // fucomp
	MnemonicFUCOMPP                            // fucompp
	MnemonicFWAIT                              // fwait
	MnemonicFXAM                               // fxam
	MnemonicFXCH                               // fxch
	MnemonicFXRSTOR                            // fxrstor
	MnemonicFXRSTOR64                          // fxrstor64
	MnemonicFXSAVE                             // fxsave
	MnemonicFXSAVE64                           // fxsave64
	MnemonicFXTRACT                            // fxtract
	MnemonicFYL2X                              // fyl2x
	MnemonicFYL2XP1                            // fyl2xp1
	MnemonicGETSEC                             // getsec
	MnemonicGF2P8AFFINEINVQB                   // gf2p8affineinvqb
	MnemonicGF2P8AFFINEQB                      // gf2p8affineqb
	MnemonicGF2P8MULB                          // gf2p8mulb
	MnemonicHADDPD                             // haddpd
	MnemonicHADDPS                             // haddps
	MnemonicHLT                                // hlt
	MnemonicHSUBPD                             // hsubpd
	MnemonicHSUBPS                             // hsubps
	MnemonicIDIV                               // idiv
	MnemonicIMUL                               // imul
	MnemonicIN                                 // in
	MnemonicINC                                // inc
	MnemonicINCSSPD                            // incsspd
	MnemonicINCSSPQ                            // incsspq
	MnemonicINSB                               // insb
	MnemonicINSD                               // insd
	MnemonicINSERTPS                           // insertps
	MnemonicINSERTQ                            // insertq
	MnemonicINSW                               // insw
	MnemonicINT                                // int
	MnemonicINT1                               // int1
	MnemonicINT3                               // int3
	MnemonicINTO                               // into
	MnemonicINVD                               // invd
	MnemonicINVEPT                             // invept
	MnemonicINVLPG                             // invlpg
	MnemonicINVLPGA                            // invlpga
	MnemonicINVLPGB                            // invlpgb
	MnemonicINVPCID                            // invpcid
	MnemonicINVVPID                            // invvpid
	MnemonicIRET                               // iret
	MnemonicIRETD                              // iretd
	MnemonicIRETQ                              // iretq
	MnemonicJB                                 // jb
	MnemonicJBE                                // jbe
	MnemonicJCXZ                               // jcxz
	MnemonicJECXZ                              // jecxz
	MnemonicJKNZD                              // jknzd
	MnemonicJKZD                               // jkzd
	MnemonicJL                                 // jl
	MnemonicJLE                                // jle
	MnemonicJMP                                // jmp
	MnemonicJNB                                // jnb
	MnemonicJNBE                               // jnbe
	MnemonicJNL                                // jnl
	MnemonicJNLE                               // jnle
	MnemonicJNO                                // jno
	MnemonicJNP                                // jnp
	MnemonicJNS                                // jns
	MnemonicJNZ                                // jnz
	MnemonicJO                                 // jo
	MnemonicJP                                 // jp
	MnemonicJRCXZ                              // jrcxz
	MnemonicJS                                 // js
	MnemonicJZ                                 // jz
	MnemonicKADDB                              // kaddb
	MnemonicKADDD                              // kaddd
	MnemonicKADDQ                              // kaddq
	MnemonicKADDW                              // kaddw
	MnemonicKAND                               // kand
	MnemonicKANDB                              // kandb
	MnemonicKANDD                              // kandd
	MnemonicKANDN                              // kandn
	MnemonicKANDNB                             // kandnb
	MnemonicKANDND                             // kandnd
	MnemonicKANDNQ                             // kandnq
	MnemonicKANDNR                             // kandnr
	MnemonicKANDNW                             // kandnw
	MnemonicKANDQ                              // kandq
	MnemonicKANDW                              // kandw
	MnemonicKCONCATH                           // kconcath
	MnemonicKCONCATL                           // kconcatl
	MnemonicKEXTRACT                           // kextract
	MnemonicKMERGE2L1H                         // kmerge2l1h
	MnemonicKMERGE2L1L                         // kmerge2l1l
	MnemonicKMOV                               // kmov
	MnemonicKMOVB                              // kmovb
	MnemonicKMOVD                              // kmovd
	MnemonicKMOVQ                              // kmovq
	MnemonicKMOVW                              // kmovw
	MnemonicKNOT                               // knot
	MnemonicKNOTB                              // knotb
	MnemonicKNOTD                              // knotd
	MnemonicKNOTQ                              // knotq
	MnemonicKNOTW                              // knotw
	MnemonicKOR                                // kor
	MnemonicKORB                               // korb
	MnemonicKORD                               // kord
	MnemonicKORQ                               // korq
	MnemonicKORTEST                            // kortest
	MnemonicKORTESTB                           // kortestb
	MnemonicKORTESTD                           // kortestd
	MnemonicKORTESTQ                           // kortestq
	MnemonicKORTESTW                           // kortestw
	MnemonicKORW                               // korw
	MnemonicKSHIFTLB                           // kshiftlb
	MnemonicKSHIFTLD                           // kshiftld
	MnemonicKSHIFTLQ                           // kshiftlq
	MnemonicKSHIFTLW                           // kshiftlw
	MnemonicKSHIFTRB                           // kshiftrb
	MnemonicKSHIFTRD                           // kshiftrd
	MnemonicKSHIFTRQ                           // kshiftrq
	MnemonicKSHIFTRW                           // kshiftrw
	MnemonicKTESTB                             // ktestb
	MnemonicKTESTD                             // ktestd
	MnemonicKTESTQ                             // ktestq
	MnemonicKTESTW                             // ktestw
	MnemonicKUNPCKBW                           // kunpckbw
	MnemonicKUNPCKDQ                           // kunpckdq
	MnemonicKUNPCKWD                           // kunpckwd
	MnemonicKXNOR                              // kxnor
	MnemonicKXNORB                             // kxnorb
	MnemonicKXNORD                             // kxnord
	MnemonicKXNORQ                             // kxnorq
	MnemonicKXNORW                             // kxnorw
	MnemonicKXOR                               // kxor
	MnemonicKXORB                              // kxorb
	MnemonicKXORD                              // kxord
	MnemonicKXORQ                              // kxorq
	MnemonicKXORW                              // kxorw
	MnemonicLAHF                               // lahf
	MnemonicLAR                                // lar
	MnemonicLDDQU                              // lddqu
	MnemonicLDMXCSR                            // ldmxcsr
	MnemonicLDS                                // lds
	MnemonicLDTILECFG                          // ldtilecfg
	MnemonicLEA                                // lea
	MnemonicLEAVE                              // leave
	MnemonicLES                                // les
	MnemonicLFENCE                             // lfence
	MnemonicLFS                                // lfs
	MnemonicLGDT                               // lgdt
	MnemonicLGS                                // lgs
	MnemonicLIDT                               // lidt
	MnemonicLLDT                               // lldt
	MnemonicLLWPCB                             // llwpcb
	MnemonicLMSW                               // lmsw
	MnemonicLODSB                              // lodsb
	MnemonicLODSD                              // lodsd
	MnemonicLODSQ                              // lodsq
	MnemonicLODSW                              // lodsw
	MnemonicLOOP                               // loop
	MnemonicLOOPE                              // loope
	MnemonicLOOPNE                             // loopne
	MnemonicLSL                                // lsl
	MnemonicLSS                                // lss
	MnemonicLTR                                // ltr
	MnemonicLWPINS                             // lwpins
	MnemonicLWPVAL                             // lwpval
	MnemonicLZCNT                              // lzcnt
	MnemonicMASKMOVDQU                         // maskmovdqu
	MnemonicMASKMOVQ                           // maskmovq
	MnemonicMAXPD                              // maxpd
	MnemonicMAXPS                              // maxps
	MnemonicMAXSD                              // maxsd
	MnemonicMAXSS                              // maxss
	MnemonicMCOMMIT                            // mcommit
	MnemonicMFENCE                             // mfence
	MnemonicMINPD                              // minpd
	MnemonicMINPS                              // minps
	MnemonicMINSD                              // minsd
	MnemonicMINSS                              // minss
	MnemonicMONITOR                            // monitor
	MnemonicMONITORX                           // monitorx
	MnemonicMONTMUL                            // montmul
	MnemonicMOV                                // mov
	MnemonicMOVAPD                             // movapd
	MnemonicMOVAPS                             // movaps
	MnemonicMOVBE                              // movbe
	MnemonicMOVD                               // movd
	MnemonicMOVDDUP                            // movddup
	MnemonicMOVDIR64B                          // movdir64b
	MnemonicMOVDIRI                            // movdiri
	MnemonicMOVDQ2Q                            // movdq2q
	MnemonicMOVDQA                             // movdqa
	MnemonicMOVDQU                             // movdqu
	MnemonicMOVHLPS                            // movhlps
	MnemonicMOVHPD                             // movhpd
	MnemonicMOVHPS                             // movhps
	MnemonicMOVLHPS                            // movlhps
	MnemonicMOVLPD                             // movlpd
	MnemonicMOVLPS                             // movlps
	MnemonicMOVMSKPD                           // movmskpd
	MnemonicMOVMSKPS                           // movmskps
	MnemonicMOVNTDQ                            // movntdq
	MnemonicMOVNTDQA                           // movntdqa
	MnemonicMOVNTI                             // movnti
	MnemonicMOVNTPD                            // movntpd
	MnemonicMOVNTPS                            // movntps
	MnemonicMOVNTQ                             // movntq
	MnemonicMOVNTSD                            // movntsd
	MnemonicMOVNTSS                            // movntss
	MnemonicMOVQ                               // movq
	MnemonicMOVQ2DQ                            // movq2dq
	MnemonicMOVSB                              // movsb
	MnemonicMOVSD                              // movsd
	MnemonicMOVSHDUP                           // movshdup
	MnemonicMOVSLDUP                           // movsldup
	MnemonicMOVSQ                              // movsq
	MnemonicMOVSS                              // movss
	MnemonicMOVSW                              // movsw
	MnemonicMOVSX                              // movsx
	MnemonicMOVSXD                             // movsxd
	MnemonicMOVUPD                             // movupd
	MnemonicMOVUPS                             // movups
	MnemonicMOVZX                              // movzx
	MnemonicMPSADBW                            // mpsadbw
	MnemonicMUL                                // mul
	MnemonicMULPD                              // mulpd
	MnemonicMULPS                              // mulps
	MnemonicMULSD                              // mulsd
	MnemonicMULSS                              // mulss
	MnemonicMULX                               // mulx
	MnemonicMWAIT                              // mwait
	MnemonicMWAITX                             // mwaitx
	MnemonicNEG                                // neg
	MnemonicNOP                                // nop
	MnemonicNOT                                // not
	MnemonicOR                                 // or
	MnemonicORPD                               // orpd
	MnemonicORPS                               // orps
	MnemonicOUT                                // out
	MnemonicOUTSB                              // outsb
	MnemonicOUTSD                              // outsd
	MnemonicOUTSW                              // outsw
	MnemonicPABSB                              // pabsb
	MnemonicPABSD                              // pabsd
	MnemonicPABSW                              // pabsw
	MnemonicPACKSSDW                           // packssdw
	MnemonicPACKSSWB                           // packsswb
	MnemonicPACKUSDW                           // packusdw
	MnemonicPACKUSWB                           // packuswb
	MnemonicPADDB                              // paddb
	MnemonicPADDD                              // paddd
	MnemonicPADDQ                              // paddq
	MnemonicPADDSB                             // paddsb
	MnemonicPADDSW                             // paddsw
	MnemonicPADDUSB                            // paddusb
	MnemonicPADDUSW                            // paddusw
	MnemonicPADDW                              // paddw
	MnemonicPALIGNR                            // palignr
	MnemonicPAND                               // pand
	MnemonicPANDN                              // pandn
	MnemonicPAUSE                              // pause
	MnemonicPAVGB                              // pavgb
	MnemonicPAVGUSB                            // pavgusb
	MnemonicPAVGW                              // pavgw
	MnemonicPBLENDVB                           // pblendvb
	MnemonicPBLENDW                            // pblendw
	MnemonicPCLMULQDQ                          // pclmulqdq
	MnemonicPCMPEQB                            // pcmpeqb
	MnemonicPCMPEQD                            // pcmpeqd
	MnemonicPCMPEQQ                            // pcmpeqq
	MnemonicPCMPEQW                            // pcmpeqw
	MnemonicPCMPESTRI                          // pcmpestri
	MnemonicPCMPESTRM                          // pcmpestrm
	MnemonicPCMPGTB                            // pcmpgtb
	MnemonicPCMPGTD                            // pcmpgtd
	MnemonicPCMPGTQ                            // pcmpgtq
	MnemonicPCMPGTW                            // pcmpgtw
	MnemonicPCMPISTRI                          // pcmpistri
	MnemonicPCMPISTRM                          // pcmpistrm
	MnemonicPCONFIG                            // pconfig
	MnemonicPDEP                               // pdep
	MnemonicPEXT                               // pext
	MnemonicPEXTRB                             // pextrb
	MnemonicPEXTRD                             // pextrd
	MnemonicPEXTRQ                             // pextrq
	MnemonicPEXTRW                             // pextrw
	MnemonicPF2ID                              // pf2id
	MnemonicPF2IW                              // pf2iw
	MnemonicPFACC                              // pfacc
	MnemonicPFADD                              // pfadd
	MnemonicPFCMPEQ                            // pfcmpeq
	MnemonicPFCMPGE                            // pfcmpge
	MnemonicPFCMPGT                            // pfcmpgt
	MnemonicPFCPIT1                            // pfcpit1
	MnemonicPFMAX                              // pfmax
	MnemonicPFMIN                              // pfmin
	MnemonicPFMUL                              // pfmul
	MnemonicPFNACC                             // pfnacc
	MnemonicPFPNACC                            // pfpnacc
	MnemonicPFRCP                              // pfrcp
	MnemonicPFRCPIT2                           // pfrcpit2
	MnemonicPFRSQIT1                           // pfrsqit1
	MnemonicPFSQRT                             // pfsqrt
	MnemonicPFSUB                              // pfsub
	MnemonicPFSUBR                             // pfsubr
	MnemonicPHADDD                             // phaddd
	MnemonicPHADDSW                            // phaddsw
	MnemonicPHADDW                             // phaddw
	MnemonicPHMINPOSUW                         // phminposuw
	MnemonicPHSUBD                             // phsubd
	MnemonicPHSUBSW                            // phsubsw
	MnemonicPHSUBW                             // phsubw
	MnemonicPI2FD                              // pi2fd
	MnemonicPI2FW                              // pi2fw
	MnemonicPINSRB                             // pinsrb
	MnemonicPINSRD                             // pinsrd
	MnemonicPINSRQ                             // pinsrq
	MnemonicPINSRW                             // pinsrw
	MnemonicPMADDUBSW                          // pmaddubsw
	MnemonicPMADDWD                            // pmaddwd
	MnemonicPMAXSB                             // pmaxsb
	MnemonicPMAXSD                             // pmaxsd
	MnemonicPMAXSW                             // pmaxsw
	MnemonicPMAXUB                             // pmaxub
	MnemonicPMAXUD                             // pmaxud
	MnemonicPMAXUW                             // pmaxuw
	MnemonicPMINSB                             // pminsb
	MnemonicPMINSD                             // pminsd
	MnemonicPMINSW                             // pminsw
	MnemonicPMINUB                             // pminub
	MnemonicPMINUD                             // pminud
	MnemonicPMINUW                             // pminuw
	MnemonicPMOVMSKB                           // pmovmskb
	MnemonicPMOVSXBD                           // pmovsxbd
	MnemonicPMOVSXBQ                           // pmovsxbq
	MnemonicPMOVSXBW                           // pmovsxbw
	MnemonicPMOVSXDQ                           // pmovsxdq
	MnemonicPMOVSXWD                           // pmovsxwd
	MnemonicPMOVSXWQ                           // pmovsxwq
	MnemonicPMOVZXBD                           // pmovzxbd
	MnemonicPMOVZXBQ                           // pmovzxbq
	MnemonicPMOVZXBW                           // pmovzxbw
	MnemonicPMOVZXDQ                           // pmovzxdq
	MnemonicPMOVZXWD                           // pmovzxwd
	MnemonicPMOVZXWQ                           // pmovzxwq
	MnemonicPMULDQ                             // pmuldq
	MnemonicPMULHRSW                           // pmulhrsw
	MnemonicPMULHRW                            // pmulhrw
	MnemonicPMULHUW                            // pmulhuw
	MnemonicPMULHW                             // pmulhw
	MnemonicPMULLD                             // pmulld
	MnemonicPMULLW                             // pmullw
	MnemonicPMULUDQ                            // pmuludq
	MnemonicPOP                                // pop
	MnemonicPOPA                               // popa
	MnemonicPOPAD                              // popad
	MnemonicPOPCNT                             // popcnt
	MnemonicPOPF                               // popf
	MnemonicPOPFD                              // popfd
	MnemonicPOPFQ                              // popfq
	MnemonicPOR                                // por
	MnemonicPREFETCH                           // prefetch
	MnemonicPREFETCHNTA                        // prefetchnta
	MnemonicPREFETCHT0                         // prefetcht0
	MnemonicPREFETCHT1                         // prefetcht1
	MnemonicPREFETCHT2                         // prefetcht2
	MnemonicPREFETCHW                          // prefetchw
	MnemonicPREFETCHWT1                        // prefetchwt1
	MnemonicPSADBW                             // psadbw
	MnemonicPSHUFB                             // pshufb
	MnemonicPSHUFD                             // pshufd
	MnemonicPSHUFHW                            // pshufhw
	MnemonicPSHUFLW                            // pshuflw
	MnemonicPSHUFW                             // pshufw
	MnemonicPSIGNB                             // psignb
	MnemonicPSIGND                             // psignd
	MnemonicPSIGNW                             // psignw
	MnemonicPSLLD                              // pslld
	MnemonicPSLLDQ                             // pslldq
	MnemonicPSLLQ                              // psllq
	MnemonicPSLLW                              // psllw
	MnemonicPSMASH                             // psmash
	MnemonicPSRAD                              // psrad
	MnemonicPSRAW                              // psraw
	MnemonicPSRLD                              // psrld
	MnemonicPSRLDQ                             // psrldq
	MnemonicPSRLQ                              // psrlq
	MnemonicPSRLW                              // psrlw
	MnemonicPSUBB                              // psubb
	MnemonicPSUBD                              // psubd
	MnemonicPSUBQ                              // psubq
	MnemonicPSUBSB                             // psubsb
	MnemonicPSUBSW                             // psubsw
	MnemonicPSUBUSB                            // psubusb
	MnemonicPSUBUSW                            // psubusw
	MnemonicPSUBW                              // psubw
	MnemonicPSWAPD                             // pswapd
	MnemonicPTEST                              // ptest
	MnemonicPTWRITE                            // ptwrite
	MnemonicPUNPCKHBW                          // punpckhbw
	MnemonicPUNPCKHDQ                          // punpckhdq
	MnemonicPUNPCKHQDQ                         // punpckhqdq
	MnemonicPUNPCKHWD                          // punpckhwd
	MnemonicPUNPCKLBW                          // punpcklbw
	MnemonicPUNPCKLDQ                          // punpckldq
	MnemonicPUNPCKLQDQ                         // punpcklqdq
	MnemonicPUNPCKLWD                          // punpcklwd
	MnemonicPUSH                               // push
	MnemonicPUSHA                              // pusha
	MnemonicPUSHAD                             // pushad
	MnemonicPUSHF                              // pushf
	MnemonicPUSHFD                             // pushfd
	MnemonicPUSHFQ                             // pushfq
	MnemonicPVALIDATE                          // pvalidate
	MnemonicPXOR                               // pxor
	MnemonicRCL                                // rcl
	MnemonicRCPPS                              // rcpps
	MnemonicRCPSS                              // rcpss
	MnemonicRCR                                // rcr
	MnemonicRDFSBASE                           // rdfsbase
	MnemonicRDGSBASE                           // rdgsbase
	MnemonicRDMSR                              // rdmsr
	MnemonicRDPID                              // rdpid
	MnemonicRDPKRU                             // rdpkru
	MnemonicRDPMC                              // rdpmc
	MnemonicRDPRU                              // rdpru
	MnemonicRDRAND                             // rdrand
	MnemonicRDSEED                             // rdseed
	MnemonicRDSSPD                             // rdsspd
	MnemonicRDSSPQ                             // rdsspq
	MnemonicRDTSC                              // rdtsc
	MnemonicRDTSCP                             // rdtscp
	MnemonicRET                                // ret
	MnemonicRMPADJUST                          // rmpadjust
	MnemonicRMPUPDATE                          // rmpupdate
	MnemonicROL                                // rol
	MnemonicROR                                // ror
	MnemonicRORX                               // rorx
	MnemonicROUNDPD                            // roundpd
	MnemonicROUNDPS                            // roundps
	MnemonicROUNDSD                            // roundsd
	MnemonicROUNDSS                            // roundss
	MnemonicRSM                                // rsm
	MnemonicRSQRTPS                            // rsqrtps
	MnemonicRSQRTSS                            // rsqrtss
	MnemonicRSTORSSP                           // rstorssp
	MnemonicSAHF                               // sahf
	MnemonicSALC                               // salc
	MnemonicSAR                                // sar
	MnemonicSARX                               // sarx
	MnemonicSAVEPREVSSP                        // saveprevssp
	MnemonicSBB                                // sbb
	MnemonicSCASB                              // scasb
	MnemonicSCASD                              // scasd
	MnemonicSCASQ                              // scasq
	MnemonicSCASW                              // scasw
	MnemonicSERIALIZE                          // serialize
	MnemonicSETB                               // setb
	MnemonicSETBE                              // setbe
	MnemonicSETL                               // setl
	MnemonicSETLE                              // setle
	MnemonicSETNB                              // setnb
	MnemonicSETNBE                             // setnbe
	MnemonicSETNL                              // setnl
	MnemonicSETNLE                             // setnle
	MnemonicSETNO                              // setno
	MnemonicSETNP                              // setnp
	MnemonicSETNS                              // setns
	MnemonicSETNZ                              // setnz
	MnemonicSETO                               // seto
	MnemonicSETP                               // setp
	MnemonicSETS                               // sets
	MnemonicSETSSBSY                           // setssbsy
	MnemonicSETZ                               // setz
	MnemonicSFENCE                             // sfence
	MnemonicSGDT                               // sgdt
	MnemonicSHA1MSG1                           // sha1msg1
	MnemonicSHA1MSG2                           // sha1msg2
	MnemonicSHA1NEXTE                          // sha1nexte
	MnemonicSHA1RNDS4                          // sha1rnds4
	MnemonicSHA256MSG1                         // sha256msg1
	MnemonicSHA256MSG2                         // sha256msg2
	MnemonicSHA256RNDS2                        // sha256rnds2
	MnemonicSHL                                // shl
	MnemonicSHLD                               // shld
	MnemonicSHLX                               // shlx
	MnemonicSHR                                // shr
	MnemonicSHRD                               // shrd
	MnemonicSHRX                               // shrx
	MnemonicSHUFPD                             // shufpd
	MnemonicSHUFPS                             // shufps
	MnemonicSIDT                               // sidt
	MnemonicSKINIT                             // skinit
	MnemonicSLDT                               // sldt
	MnemonicSLWPCB                             // slwpcb
	MnemonicSMSW                               // smsw
	MnemonicSPFLT                              // spflt
	MnemonicSQRTPD                             // sqrtpd
	MnemonicSQRTPS                             // sqrtps
	MnemonicSQRTSD                             // sqrtsd
	MnemonicSQRTSS                             // sqrtss
	MnemonicSTAC                               // stac
	MnemonicSTC                                // stc
	MnemonicSTD                                // std
	MnemonicSTGI                               // stgi
	MnemonicSTI                                // sti
	MnemonicSTMXCSR                            // stmxcsr
	MnemonicSTOSB                              // stosb
	MnemonicSTOSD                              // stosd
	MnemonicSTOSQ                              // stosq
	MnemonicSTOSW                              // stosw
	MnemonicSTR                                // str
	MnemonicSTTILECFG                          // sttilecfg
	MnemonicSUB                                // sub
	MnemonicSUBPD                              // subpd
	MnemonicSUBPS                              // subps
	MnemonicSUBSD                              // subsd
	MnemonicSUBSS                              // subss
	MnemonicSWAPGS                             // swapgs
	MnemonicSYSCALL                            // syscall
	MnemonicSYSENTER                           // sysenter
	MnemonicSYSEXIT                            // sysexit
	MnemonicSYSRET                             // sysret
	MnemonicT1MSKC                             // t1mskc
	MnemonicTDPBF16PS                          // tdpbf16ps
	MnemonicTDPBSSD                            // tdpbssd
	MnemonicTDPBSUD                            // tdpbsud
	MnemonicTDPBUSD                            // tdpbusd
	MnemonicTDPBUUD                            // tdpbuud
	MnemonicTEST                               // test
	MnemonicTILELOADD                          // tileloadd
	MnemonicTILELOADDT1                        // tileloaddt1
	MnemonicTILERELEASE                        // tilerelease
	MnemonicTILESTORED                         // tilestored
	MnemonicTILEZERO                           // tilezero
	MnemonicTLBSYNC                            // tlbsync
	MnemonicTPAUSE                             // tpause
	MnemonicTZCNT                              // tzcnt
	MnemonicTZCNTI                             // tzcnti
	MnemonicTZMSK                              // tzmsk
	MnemonicUCOMISD                            // ucomisd
	MnemonicUCOMISS                            // ucomiss
	MnemonicUD0                                // ud0
	MnemonicUD1                                // ud1
	MnemonicUD2                                // ud2
	MnemonicUMONITOR                           // umonitor
	MnemonicUMWAIT                             // umwait
	MnemonicUNPCKHPD                           // unpckhpd
	MnemonicUNPCKHPS                           // unpckhps
	MnemonicUNPCKLPD                           // unpcklpd
	MnemonicUNPCKLPS                           // unpcklps
	MnemonicV4FMADDPS                          // v4fmaddps
	MnemonicV4FMADDSS                          // v4fmaddss
	MnemonicV4FNMADDPS                         // v4fnmaddps
	MnemonicV4FNMADDSS                         // v4fnmaddss
	MnemonicVADDNPD                            // vaddnpd
	MnemonicVADDNPS                            // vaddnps
	MnemonicVADDPD                             // vaddpd
	MnemonicVADDPS                             // vaddps
	MnemonicVADDSD                             // vaddsd
	MnemonicVADDSETSPS                         // vaddsetsps
	MnemonicVADDSS                             // vaddss
	MnemonicVADDSUBPD                          // vaddsubpd
	MnemonicVADDSUBPS                          // vaddsubps
	MnemonicVAESDEC                            // vaesdec
	MnemonicVAESDECLAST                        // vaesdeclast
	MnemonicVAESENC                            // vaesenc
	MnemonicVAESENCLAST                        // vaesenclast
	MnemonicVAESIMC                            // vaesimc
	MnemonicVAESKEYGENASSIST                   // vaeskeygenassist
	MnemonicVALIGND                            // valignd
	MnemonicVALIGNQ                            // valignq
	MnemonicVANDNPD                            // vandnpd
	MnemonicVANDNPS                            // vandnps
	MnemonicVANDPD                             // vandpd
	MnemonicVANDPS                             // vandps
	MnemonicVBLENDMPD                          // vblendmpd
	MnemonicVBLENDMPS                          // vblendmps
	MnemonicVBLENDPD                           // vblendpd
	MnemonicVBLENDPS                           // vblendps
	MnemonicVBLENDVPD                          // vblendvpd
	MnemonicVBLENDVPS                          // vblendvps
	MnemonicVBROADCASTF128                     // vbroadcastf128
	MnemonicVBROADCASTF32X2                    // vbroadcastf32x2
	MnemonicVBROADCASTF32X4                    // vbroadcastf32x4
	MnemonicVBROADCASTF32X8                    // vbroadcastf32x8
	MnemonicVBROADCASTF64X2                    // vbroadcastf64x2
	MnemonicVBROADCASTF64X4                    // vbroadcastf64x4
	MnemonicVBROADCASTI128                     // vbroadcasti128
	MnemonicVBROADCASTI32X2                    // vbroadcasti32x2
	MnemonicVBROADCASTI32X4                    // vbroadcasti32x4
	MnemonicVBROADCASTI32X8                    // vbroadcasti32x8
	MnemonicVBROADCASTI64X2                    // vbroadcasti64x2
	MnemonicVBROADCASTI64X4                    // vbroadcasti64x4
	MnemonicVBROADCASTSD                       // vbroadcastsd
	MnemonicVBROADCASTSS                       // vbroadcastss
	MnemonicVCMPPD                             // vcmppd
	MnemonicVCMPPS                             // vcmpps
	MnemonicVCMPSD                             // vcmpsd
	MnemonicVCMPSS                             // vcmpss
	MnemonicVCOMISD                            // vcomisd
	MnemonicVCOMISS                            // vcomiss
	MnemonicVCOMPRESSPD                        // vcompresspd
	MnemonicVCOMPRESSPS                        // vcompressps
	MnemonicVCVTDQ2PD                          // vcvtdq2pd
	MnemonicVCVTDQ2PS                          // vcvtdq2ps
	MnemonicVCVTFXPNTDQ2PS                     // vcvtfxpntdq2ps
	MnemonicVCVTFXPNTPD2DQ                     // vcvtfxpntpd2dq
	MnemonicVCVTFXPNTPD2UDQ                    // vcvtfxpntpd2udq
	MnemonicVCVTFXPNTPS2DQ                     // vcvtfxpntps2dq
	MnemonicVCVTFXPNTPS2UDQ                    // vcvtfxpntps2udq
	MnemonicVCVTFXPNTUDQ2PS                    // vcvtfxpntudq2ps
	MnemonicVCVTNE2PS2BF16                     // vcvtne2ps2bf16
	MnemonicVCVTNEPS2BF16                      // vcvtneps2bf16
	MnemonicVCVTPD2DQ                          // vcvtpd2dq
	MnemonicVCVTPD2PS                          // vcvtpd2ps
	MnemonicVCVTPD2QQ                          // vcvtpd2qq
	MnemonicVCVTPD2UDQ                         // vcvtpd2udq
	MnemonicVCVTPD2UQQ                         // vcvtpd2uqq
	MnemonicVCVTPH2PS                          // vcvtph2ps
	MnemonicVCVTPS2DQ                          // vcvtps2dq
	MnemonicVCVTPS2PD                          // vcvtps2pd
	MnemonicVCVTPS2PH                          // vcvtps2ph
	MnemonicVCVTPS2QQ                          // vcvtps2qq
	MnemonicVCVTPS2UDQ                         // vcvtps2udq
	MnemonicVCVTPS2UQQ                         // vcvtps2uqq
	MnemonicVCVTQQ2PD                          // vcvtqq2pd
	MnemonicVCVTQQ2PS                          // vcvtqq2ps
	MnemonicVCVTSD2SI                          // vcvtsd2si
	MnemonicVCVTSD2SS                          // vcvtsd2ss
	MnemonicVCVTSD2USI                         // vcvtsd2usi
	MnemonicVCVTSI2SD                          // vcvtsi2sd
	MnemonicVCVTSI2SS                          // vcvtsi2ss
	MnemonicVCVTSS2SD                          // vcvtss2sd
	MnemonicVCVTSS2SI                          // vcvtss2si
	MnemonicVCVTSS2USI                         // vcvtss2usi
	MnemonicVCVTTPD2DQ                         // vcvttpd2dq
	MnemonicVCVTTPD2QQ                         // vcvttpd2qq
	MnemonicVCVTTPD2UDQ                        // vcvttpd2udq
	MnemonicVCVTTPD2UQQ                        // vcvttpd2uqq
	MnemonicVCVTTPS2DQ                         // vcvttps2dq
	MnemonicVCVTTPS2QQ                         // vcvttps2qq
	MnemonicVCVTTPS2UDQ                        // vcvttps2udq
	MnemonicVCVTTPS2UQQ                        // vcvttps2uqq
	MnemonicVCVTTSD2SI                         // vcvttsd2si
	MnemonicVCVTTSD2USI                        // vcvttsd2usi
	MnemonicVCVTTSS2SI                         // vcvttss2si
	MnemonicVCVTTSS2USI                        // vcvttss2usi
	MnemonicVCVTUDQ2PD                         // vcvtudq2pd
	MnemonicVCVTUDQ2PS                         // vcvtudq2ps
	MnemonicVCVTUQQ2PD                         // vcvtuqq2pd
	MnemonicVCVTUQQ2PS                         // vcvtuqq2ps
	MnemonicVCVTUSI2SD                         // vcvtusi2sd
	MnemonicVCVTUSI2SS                         // vcvtusi2ss
	MnemonicVDBPSADBW                          // vdbpsadbw
	MnemonicVDIVPD                             // vdivpd
	MnemonicVDIVPS                             // vdivps
	MnemonicVDIVSD                             // vdivsd
	MnemonicVDIVSS                             // vdivss
	MnemonicVDPBF16PS                          // vdpbf16ps
	MnemonicVDPPD                              // vdppd
	MnemonicVDPPS                              // vdpps
	MnemonicVERR                               // verr
	MnemonicVERW                               // verw
	MnemonicVEXP223PS                          // vexp223ps
	MnemonicVEXP2PD                            // vexp2pd
	MnemonicVEXP2PS                            // vexp2ps
	MnemonicVEXPANDPD                          // vexpandpd
	MnemonicVEXPANDPS                          // vexpandps
	MnemonicVEXTRACTF128                       // vextractf128
	MnemonicVEXTRACTF32X4                      // vextractf32x4
	MnemonicVEXTRACTF32X8                      // vextractf32x8
	MnemonicVEXTRACTF64X2                      // vextractf64x2
	MnemonicVEXTRACTF64X4                      // vextractf64x4
	MnemonicVEXTRACTI128                       // vextracti128
	MnemonicVEXTRACTI32X4                      // vextracti32x4
	MnemonicVEXTRACTI32X8                      // vextracti32x8
	MnemonicVEXTRACTI64X2                      // vextracti64x2
	MnemonicVEXTRACTI64X4                      // vextracti64x4
	MnemonicVEXTRACTPS                         // vextractps
	MnemonicVFIXUPIMMPD                        // vfixupimmpd
	MnemonicVFIXUPIMMPS                        // vfixupimmps
	MnemonicVFIXUPIMMSD                        // vfixupimmsd
	MnemonicVFIXUPIMMSS                        // vfixupimmss
	MnemonicVFIXUPNANPD                        // vfixupnanpd
	MnemonicVFIXUPNANPS                        // vfixupnanps
	MnemonicVFMADD132PD                        // vfmadd132pd
	MnemonicVFMADD132PS                        // vfmadd132ps
	MnemonicVFMADD132SD                        // vfmadd132sd
	MnemonicVFMADD132SS                        // vfmadd132ss
	MnemonicVFMADD213PD                        // vfmadd213pd
	MnemonicVFMADD213PS                        // vfmadd213ps
	MnemonicVFMADD213SD                        // vfmadd213sd
	MnemonicVFMADD213SS                        // vfmadd213ss
	MnemonicVFMADD231PD                        // vfmadd231pd
	MnemonicVFMADD231PS                        // vfmadd231ps
	MnemonicVFMADD231SD                        // vfmadd231sd
	MnemonicVFMADD231SS                        // vfmadd231ss
	MnemonicVFMADD233PS                        // vfmadd233ps
	MnemonicVFMADDPD                           // vfmaddpd
	MnemonicVFMADDPS                           // vfmaddps
	MnemonicVFMADDSD                           // vfmaddsd
	MnemonicVFMADDSS                           // vfmaddss
	MnemonicVFMADDSUB132PD                     // vfmaddsub132pd
	MnemonicVFMADDSUB132PS                     // vfmaddsub132ps
	MnemonicVFMADDSUB213PD                     // vfmaddsub213pd
	MnemonicVFMADDSUB213PS                     // vfmaddsub213ps
	MnemonicVFMADDSUB231PD                     // vfmaddsub231pd
	MnemonicVFMADDSUB231PS                     // vfmaddsub231ps
	MnemonicVFMADDSUBPD                        // vfmaddsubpd
	MnemonicVFMADDSUBPS                        // vfmaddsubps
	MnemonicVFMSUB132PD                        // vfmsub132pd
	MnemonicVFMSUB132PS                        // vfmsub132ps
	MnemonicVFMSUB132SD                        // vfmsub132sd
	MnemonicVFMSUB132SS                        // vfmsub132ss
	MnemonicVFMSUB213PD                        // vfmsub213pd
	MnemonicVFMSUB213PS                        // vfmsub213ps
	MnemonicVFMSUB213SD                        // vfmsub213sd
	MnemonicVFMSUB213SS                        // vfmsub213ss
	MnemonicVFMSUB231PD                        // vfmsub231pd
	MnemonicVFMSUB231PS                        // vfmsub231ps
	MnemonicVFMSUB231SD                        // vfmsub231sd
	MnemonicVFMSUB231SS                        // vfmsub231ss
	MnemonicVFMSUBADD132PD                     // vfmsubadd132pd
	MnemonicVFMSUBADD132PS                     // vfmsubadd132ps
	MnemonicVFMSUBADD213PD                     // vfmsubadd213pd
	MnemonicVFMSUBADD213PS                     // vfmsubadd213ps
	MnemonicVFMSUBADD231PD                     // vfmsubadd231pd
	MnemonicVFMSUBADD231PS                     // vfmsubadd231ps
	MnemonicVFMSUBADDPD                        // vfmsubaddpd
	MnemonicVFMSUBADDPS                        // vfmsubaddps
	MnemonicVFMSUBPD                           // vfmsubpd
	MnemonicVFMSUBPS                           // vfmsubps
	MnemonicVFMSUBSD                           // vfmsubsd
	MnemonicVFMSUBSS                           // vfmsubss
	MnemonicVFNMADD132PD                       // vfnmadd132pd
	MnemonicVFNMADD132PS                       // vfnmadd132ps
	MnemonicVFNMADD132SD                       // vfnmadd132sd
	MnemonicVFNMADD132SS                       // vfnmadd132ss
	MnemonicVFNMADD213PD                       // vfnmadd213pd
	MnemonicVFNMADD213PS                       // vfnmadd213ps
	MnemonicVFNMADD213SD                       // vfnmadd213sd
	MnemonicVFNMADD213SS                       // vfnmadd213ss
	MnemonicVFNMADD231PD                       // vfnmadd231pd
	MnemonicVFNMADD231PS                       // vfnmadd231ps
	MnemonicVFNMADD231SD                       // vfnmadd231sd
	MnemonicVFNMADD231SS                       // vfnmadd231ss
	MnemonicVFNMADDPD                          // vfnmaddpd
	MnemonicVFNMADDPS                          // vfnmaddps
	MnemonicVFNMADDSD                          // vfnmaddsd
	MnemonicVFNMADDSS                          // vfnmaddss
	MnemonicVFNMSUB132PD                       // vfnmsub132pd
	MnemonicVFNMSUB132PS                       // vfnmsub132ps
	MnemonicVFNMSUB132SD                       // vfnmsub132sd
	MnemonicVFNMSUB132SS                       // vfnmsub132ss
	MnemonicVFNMSUB213PD                       // vfnmsub213pd
	MnemonicVFNMSUB213PS                       // vfnmsub213ps
	MnemonicVFNMSUB213SD                       // vfnmsub213sd
	MnemonicVFNMSUB213SS                       // vfnmsub213ss
	MnemonicVFNMSUB231PD                       // vfnmsub231pd
	MnemonicVFNMSUB231PS                       // vfnmsub231ps
	MnemonicVFNMSUB231SD                       // vfnmsub231sd
	MnemonicVFNMSUB231SS                       // vfnmsub231ss
	MnemonicVFNMSUBPD                          // vfnmsubpd
	MnemonicVFNMSUBPS                          // vfnmsubps
	MnemonicVFNMSUBSD                          // vfnmsubsd
	MnemonicVFNMSUBSS                          // vfnmsubss
	MnemonicVFPCLASSPD                         // vfpclasspd
	MnemonicVFPCLASSPS                         // vfpclassps
	MnemonicVFPCLASSSD                         // vfpclasssd
	MnemonicVFPCLASSSS                         // vfpclassss
	MnemonicVFRCZPD                            // vfrczpd
	MnemonicVFRCZPS                            // vfrczps
	MnemonicVFRCZSD                            // vfrczsd
	MnemonicVFRCZSS                            // vfrczss
	MnemonicVGATHERDPD                         // vgatherdpd
	MnemonicVGATHERDPS                         // vgatherdps
	MnemonicVGATHERPF0DPD                      // vgatherpf0dpd
	MnemonicVGATHERPF0DPS                      // vgatherpf0dps
	MnemonicVGATHERPF0HINTDPD                  // vgatherpf0hintdpd
	MnemonicVGATHERPF0HINTDPS                  // vgatherpf0hintdps
	MnemonicVGATHERPF0QPD                      // vgatherpf0qpd
	MnemonicVGATHERPF0QPS                      // vgatherpf0qps
	MnemonicVGATHERPF1DPD                      // vgatherpf1dpd
	MnemonicVGATHERPF1DPS                      // vgatherpf1dps
	MnemonicVGATHERPF1QPD                      // vgatherpf1qpd
	MnemonicVGATHERPF1QPS                      // vgatherpf1qps
	MnemonicVGATHERQPD                         // vgatherqpd
	MnemonicVGATHERQPS                         // vgatherqps
	MnemonicVGETEXPPD                          // vgetexppd
	MnemonicVGETEXPPS                          // vgetexpps
	MnemonicVGETEXPSD                          // vgetexpsd
	MnemonicVGETEXPSS                          // vgetexpss
	MnemonicVGETMANTPD                         // vgetmantpd
	MnemonicVGETMANTPS                         // vgetmantps
	MnemonicVGETMANTSD                         // vgetmantsd
	MnemonicVGETMANTSS                         // vgetmantss
	MnemonicVGF2P8AFFINEINVQB                  // vgf2p8affineinvqb
	MnemonicVGF2P8AFFINEQB                     // vgf2p8affineqb
	MnemonicVGF2P8MULB                         // vgf2p8mulb
	MnemonicVGMAXABSPS                         // vgmaxabsps
	MnemonicVGMAXPD                            // vgmaxpd
	MnemonicVGMAXPS                            // vgmaxps
	MnemonicVGMINPD                            // vgminpd
	MnemonicVGMINPS                            // vgminps
	MnemonicVHADDPD                            // vhaddpd
	MnemonicVHADDPS                            // vhaddps
	MnemonicVHSUBPD                            // vhsubpd
	MnemonicVHSUBPS                            // vhsubps
	MnemonicVINSERTF128                        // vinsertf128
	MnemonicVINSERTF32X4                       // vinsertf32x4
	MnemonicVINSERTF32X8                       // vinsertf32x8
	MnemonicVINSERTF64X2                       // vinsertf64x2
	MnemonicVINSERTF64X4                       // vinsertf64x4
	MnemonicVINSERTI128                        // vinserti128
	MnemonicVINSERTI32X4                       // vinserti32x4
	MnemonicVINSERTI32X8                       // vinserti32x8
	MnemonicVINSERTI64X2                       // vinserti64x2
	MnemonicVINSERTI64X4                       // vinserti64x4
	MnemonicVINSERTPS                          // vinsertps
	MnemonicVLDDQU                             // vlddqu
	MnemonicVLDMXCSR                           // vldmxcsr
	MnemonicVLOADUNPACKHD                      // vloadunpackhd
	MnemonicVLOADUNPACKHPD                     // vloadunpackhpd
	MnemonicVLOADUNPACKHPS                     // vloadunpackhps
	MnemonicVLOADUNPACKHQ                      // vloadunpackhq
	MnemonicVLOADUNPACKLD                      // vloadunpackld
	MnemonicVLOADUNPACKLPD                     // vloadunpacklpd
	MnemonicVLOADUNPACKLPS                     // vloadunpacklps
	MnemonicVLOADUNPACKLQ                      // vloadunpacklq
	MnemonicVLOG2PS                            // vlog2ps
	MnemonicVMASKMOVDQU                        // vmaskmovdqu
	MnemonicVMASKMOVPD                         // vmaskmovpd
	MnemonicVMASKMOVPS                         // vmaskmovps
	MnemonicVMAXPD                             // vmaxpd
	MnemonicVMAXPS                             // vmaxps
	MnemonicVMAXSD                             // vmaxsd
	MnemonicVMAXSS                             // vmaxss
	MnemonicVMCALL                             // vmcall
	MnemonicVMCLEAR                            // vmclear
	MnemonicVMFUNC                             // vmfunc
	MnemonicVMINPD                             // vminpd
	MnemonicVMINPS                             // vminps
	MnemonicVMINSD                             // vminsd
	MnemonicVMINSS                             // vminss
	MnemonicVMLAUNCH                           // vmlaunch
	MnemonicVMLOAD                             // vmload
	MnemonicVMMCALL                            // vmmcall
	MnemonicVMOVAPD                            // vmovapd
	MnemonicVMOVAPS                            // vmovaps
	MnemonicVMOVD                              // vmovd
	MnemonicVMOVDDUP                           // vmovddup
	MnemonicVMOVDQA                            // vmovdqa
	MnemonicVMOVDQA32                          // vmovdqa32
	MnemonicVMOVDQA64                          // vmovdqa64
	MnemonicVMOVDQU                            // vmovdqu
	MnemonicVMOVDQU16                          // vmovdqu16
	MnemonicVMOVDQU32                          // vmovdqu32
	MnemonicVMOVDQU64                          // vmovdqu64
	MnemonicVMOVDQU8                           // vmovdqu8
	MnemonicVMOVHLPS                           // vmovhlps
	MnemonicVMOVHPD                            // vmovhpd
	MnemonicVMOVHPS                            // vmovhps
	MnemonicVMOVLHPS                           // vmovlhps
	MnemonicVMOVLPD                            // vmovlpd
	MnemonicVMOVLPS                            // vmovlps
	MnemonicVMOVMSKPD                          // vmovmskpd
	MnemonicVMOVMSKPS                          // vmovmskps
	MnemonicVMOVNRAPD                          // vmovnrapd
	MnemonicVMOVNRAPS                          // vmovnraps
	MnemonicVMOVNRNGOAPD                       // vmovnrngoapd
	MnemonicVMOVNRNGOAPS                       // vmovnrngoaps
	MnemonicVMOVNTDQ                           // vmovntdq
	MnemonicVMOVNTDQA                          // vmovntdqa
	MnemonicVMOVNTPD                           // vmovntpd
	MnemonicVMOVNTPS                           // vmovntps
	MnemonicVMOVQ                              // vmovq
	MnemonicVMOVSD                             // vmovsd
	MnemonicVMOVSHDUP                          // vmovshdup
	MnemonicVMOVSLDUP                          // vmovsldup
	MnemonicVMOVSS                             // vmovss
	MnemonicVMOVUPD                            // vmovupd
	MnemonicVMOVUPS                            // vmovups
	MnemonicVMPSADBW                           // vmpsadbw
	MnemonicVMPTRLD                            // vmptrld
	MnemonicVMPTRST                            // vmptrst
	MnemonicVMREAD                             // vmread
	MnemonicVMRESUME                           // vmresume
	MnemonicVMRUN                              // vmrun
	MnemonicVMSAVE                             // vmsave
	MnemonicVMULPD                             // vmulpd
	MnemonicVMULPS                             // vmulps
	MnemonicVMULSD                             // vmulsd
	MnemonicVMULSS                             // vmulss
	MnemonicVMWRITE                            // vmwrite
	MnemonicVMXOFF                             // vmxoff
	MnemonicVMXON                              // vmxon
	MnemonicVORPD                              // vorpd
	MnemonicVORPS                              // vorps
	MnemonicVP2INTERSECTD                      // vp2intersectd
	MnemonicVP2INTERSECTQ                      // vp2intersectq
	MnemonicVP4DPWSSD                          // vp4dpwssd
	MnemonicVP4DPWSSDS                         // vp4dpwssds
	MnemonicVPABSB                             // vpabsb
	MnemonicVPABSD                             // vpabsd
	MnemonicVPABSQ                             // vpabsq
	MnemonicVPABSW                             // vpabsw
	MnemonicVPACKSSDW                          // vpackssdw
	MnemonicVPACKSSWB                          // vpacksswb
	MnemonicVPACKSTOREHD                       // vpackstorehd
	MnemonicVPACKSTOREHPD                      // vpackstorehpd
	MnemonicVPACKSTOREHPS                      // vpackstorehps
	MnemonicVPACKSTOREHQ                       // vpackstorehq
	MnemonicVPACKSTORELD                       // vpackstoreld
	MnemonicVPACKSTORELPD                      // vpackstorelpd
	MnemonicVPACKSTORELPS                      // vpackstorelps
	MnemonicVPACKSTORELQ                       // vpackstorelq
	MnemonicVPACKUSDW                          // vpackusdw
	MnemonicVPACKUSWB                          // vpackuswb
	MnemonicVPADCD                             // vpadcd
	MnemonicVPADDB                             // vpaddb
	MnemonicVPADDD                             // vpaddd
	MnemonicVPADDQ                             // vpaddq
	MnemonicVPADDSB                            // vpaddsb
	MnemonicVPADDSETCD                         // vpaddsetcd
	MnemonicVPADDSETSD                         // vpaddsetsd
	MnemonicVPADDSW                            // vpaddsw
	MnemonicVPADDUSB                           // vpaddusb
	MnemonicVPADDUSW                           // vpaddusw
	MnemonicVPADDW                             // vpaddw
	MnemonicVPALIGNR                           // vpalignr
	MnemonicVPAND                              // vpand
	MnemonicVPANDD                             // vpandd
	MnemonicVPANDN                             // vpandn
	MnemonicVPANDND                            // vpandnd
	MnemonicVPANDNQ                            // vpandnq
	MnemonicVPANDQ                             // vpandq
	MnemonicVPAVGB                             // vpavgb
	MnemonicVPAVGW                             // vpavgw
	MnemonicVPBLENDD                           // vpblendd
	MnemonicVPBLENDMB                          // vpblendmb
	MnemonicVPBLENDMD                          // vpblendmd
	MnemonicVPBLENDMQ                          // vpblendmq
	MnemonicVPBLENDMW                          // vpblendmw
	MnemonicVPBLENDVB                          // vpblendvb
	MnemonicVPBLENDW                           // vpblendw
	MnemonicVPBROADCASTB                       // vpbroadcastb
	MnemonicVPBROADCASTD                       // vpbroadcastd
	MnemonicVPBROADCASTMB2Q                    // vpbroadcastmb2q
	MnemonicVPBROADCASTMW2D                    // vpbroadcastmw2d
	MnemonicVPBROADCASTQ                       // vpbroadcastq
	MnemonicVPBROADCASTW                       // vpbroadcastw
	MnemonicVPCLMULQDQ                         // vpclmulqdq
	MnemonicVPCMOV                             // vpcmov
	MnemonicVPCMPB                             // vpcmpb
	MnemonicVPCMPD                             // vpcmpd
	MnemonicVPCMPEQB                           // vpcmpeqb
	MnemonicVPCMPEQD                           // vpcmpeqd
	MnemonicVPCMPEQQ                           // vpcmpeqq
	MnemonicVPCMPEQW                           // vpcmpeqw
	MnemonicVPCMPESTRI                         // vpcmpestri
	MnemonicVPCMPESTRM                         // vpcmpestrm
	MnemonicVPCMPGTB                           // vpcmpgtb
	MnemonicVPCMPGTD                           // vpcmpgtd
	MnemonicVPCMPGTQ                           // vpcmpgtq
	MnemonicVPCMPGTW                           // vpcmpgtw
	MnemonicVPCMPISTRI                         // vpcmpistri
	MnemonicVPCMPISTRM                         // vpcmpistrm
	MnemonicVPCMPLTD                           // vpcmpltd
	MnemonicVPCMPQ                             // vpcmpq
	MnemonicVPCMPUB                            // vpcmpub
	MnemonicVPCMPUD                            // vpcmpud
	MnemonicVPCMPUQ                            // vpcmpuq
	MnemonicVPCMPUW                            // vpcmpuw
	MnemonicVPCMPW                             // vpcmpw
	MnemonicVPCOMB                             // vpcomb
	MnemonicVPCOMD                             // vpcomd
	MnemonicVPCOMPRESSB                        // vpcompressb
	MnemonicVPCOMPRESSD                        // vpcompressd
	MnemonicVPCOMPRESSQ                        // vpcompressq
	MnemonicVPCOMPRESSW                        // vpcompressw
	MnemonicVPCOMQ                             // vpcomq
	MnemonicVPCOMUB                            // vpcomub
	MnemonicVPCOMUD                            // vpcomud
	MnemonicVPCOMUQ                            // vpcomuq
	MnemonicVPCOMUW                            // vpcomuw
	MnemonicVPCOMW                             // vpcomw
	MnemonicVPCONFLICTD                        // vpconflictd
	MnemonicVPCONFLICTQ                        // vpconflictq
	MnemonicVPDPBUSD                           // vpdpbusd
	MnemonicVPDPBUSDS                          // vpdpbusds
	MnemonicVPDPWSSD                           // vpdpwssd
	MnemonicVPDPWSSDS                          // vpdpwssds
	MnemonicVPERM2F128                         // vperm2f128
	MnemonicVPERM2I128                         // vperm2i128
	MnemonicVPERMB                             // vpermb
	MnemonicVPERMD                             // vpermd
	MnemonicVPERMF32X4                         // vpermf32x4
	MnemonicVPERMI2B                           // vpermi2b
	MnemonicVPERMI2D                           // vpermi2d
	MnemonicVPERMI2PD                          // vpermi2pd
	MnemonicVPERMI2PS                          // vpermi2ps
	MnemonicVPERMI2Q                           // vpermi2q
	MnemonicVPERMI2W                           // vpermi2w
	MnemonicVPERMIL2PD                         // vpermil2pd
	MnemonicVPERMIL2PS                         // vpermil2ps
	MnemonicVPERMILPD                          // vpermilpd
	MnemonicVPERMILPS                          // vpermilps
	MnemonicVPERMPD                            // vpermpd
	MnemonicVPERMPS                            // vpermps
	MnemonicVPERMQ                             // vpermq
	MnemonicVPERMT2B                           // vpermt2b
	MnemonicVPERMT2D                           // vpermt2d
	MnemonicVPERMT2PD                          // vpermt2pd
	MnemonicVPERMT2PS                          // vpermt2ps
	MnemonicVPERMT2Q                           // vpermt2q
	MnemonicVPERMT2W                           // vpermt2w
	MnemonicVPERMW                             // vpermw
	MnemonicVPEXPANDB                          // vpexpandb
	MnemonicVPEXPANDD                          // vpexpandd
	MnemonicVPEXPANDQ                          // vpexpandq
	MnemonicVPEXPANDW                          // vpexpandw
	MnemonicVPEXTRB                            // vpextrb
	MnemonicVPEXTRD                            // vpextrd
	MnemonicVPEXTRQ                            // vpextrq
	MnemonicVPEXTRW                            // vpextrw
	MnemonicVPGATHERDD                         // vpgatherdd
	MnemonicVPGATHERDQ                         // vpgatherdq
	MnemonicVPGATHERQD                         // vpgatherqd
	MnemonicVPGATHERQQ                         // vpgatherqq
	MnemonicVPHADDBD                           // vphaddbd
	MnemonicVPHADDBQ                           // vphaddbq
	MnemonicVPHADDBW                           // vphaddbw
	MnemonicVPHADDD                            // vphaddd
	MnemonicVPHADDDQ                           // vphadddq
	MnemonicVPHADDSW                           // vphaddsw
	MnemonicVPHADDUBD                          // vphaddubd
	MnemonicVPHADDUBQ                          // vphaddubq
	MnemonicVPHADDUBW                          // vphaddubw
	MnemonicVPHADDUDQ                          // vphaddudq
	MnemonicVPHADDUWD                          // vphadduwd
	MnemonicVPHADDUWQ                          // vphadduwq
	MnemonicVPHADDW                            // vphaddw
	MnemonicVPHADDWD                           // vphaddwd
	MnemonicVPHADDWQ                           // vphaddwq
	MnemonicVPHMINPOSUW                        // vphminposuw
	MnemonicVPHSUBBW                           // vphsubbw
	MnemonicVPHSUBD                            // vphsubd
	MnemonicVPHSUBDQ                           // vphsubdq
	MnemonicVPHSUBSW                           // vphsubsw
	MnemonicVPHSUBW                            // vphsubw
	MnemonicVPHSUBWD                           // vphsubwd
	MnemonicVPINSRB                            // vpinsrb
	MnemonicVPINSRD                            // vpinsrd
	MnemonicVPINSRQ                            // vpinsrq
	MnemonicVPINSRW                            // vpinsrw
	MnemonicVPLZCNTD                           // vplzcntd
	MnemonicVPLZCNTQ                           // vplzcntq
	MnemonicVPMACSDD                           // vpmacsdd
	MnemonicVPMACSDQH                          // vpmacsdqh
	MnemonicVPMACSDQL                          // vpmacsdql
	MnemonicVPMACSSDD                          // vpmacssdd
	MnemonicVPMACSSDQH                         // vpmacssdqh
	MnemonicVPMACSSDQL                         // vpmacssdql
	MnemonicVPMACSSWD                          // vpmacsswd
	MnemonicVPMACSSWW                          // vpmacssww
	MnemonicVPMACSWD                           // vpmacswd
	MnemonicVPMACSWW                           // vpmacsww
	MnemonicVPMADCSSWD                         // vpmadcsswd
	MnemonicVPMADCSWD                          // vpmadcswd
	MnemonicVPMADD231D                         // vpmadd231d
	MnemonicVPMADD233D                         // vpmadd233d
	MnemonicVPMADD52HUQ                        // vpmadd52huq
	MnemonicVPMADD52LUQ                        // vpmadd52luq
	MnemonicVPMADDUBSW                         // vpmaddubsw
	MnemonicVPMADDWD                           // vpmaddwd
	MnemonicVPMASKMOVD                         // vpmaskmovd
	MnemonicVPMASKMOVQ                         // vpmaskmovq
	MnemonicVPMAXSB                            // vpmaxsb
	MnemonicVPMAXSD                            // vpmaxsd
	MnemonicVPMAXSQ                            // vpmaxsq
	MnemonicVPMAXSW                            // vpmaxsw
	MnemonicVPMAXUB                            // vpmaxub
	MnemonicVPMAXUD                            // vpmaxud
	MnemonicVPMAXUQ                            // vpmaxuq
	MnemonicVPMAXUW                            // vpmaxuw
	MnemonicVPMINSB                            // vpminsb
	MnemonicVPMINSD                            // vpminsd
	MnemonicVPMINSQ                            // vpminsq
	MnemonicVPMINSW                            // vpminsw
	MnemonicVPMINUB                            // vpminub
	MnemonicVPMINUD                            // vpminud
	MnemonicVPMINUQ                            // vpminuq
	MnemonicVPMINUW                            // vpminuw
	MnemonicVPMOVB2M                           // vpmovb2m
	MnemonicVPMOVD2M                           // vpmovd2m
	MnemonicVPMOVDB                            // vpmovdb
	MnemonicVPMOVDW                            // vpmovdw
	MnemonicVPMOVM2B                           // vpmovm2b
	MnemonicVPMOVM2D                           // vpmovm2d
	MnemonicVPMOVM2Q                           // vpmovm2q
	MnemonicVPMOVM2W                           // vpmovm2w
	MnemonicVPMOVMSKB                          // vpmovmskb
	MnemonicVPMOVQ2M                           // vpmovq2m
	MnemonicVPMOVQB                            // vpmovqb
	MnemonicVPMOVQD                            // vpmovqd
	MnemonicVPMOVQW                            // vpmovqw
	MnemonicVPMOVSDB                           // vpmovsdb
	MnemonicVPMOVSDW                           // vpmovsdw
	MnemonicVPMOVSQB                           // vpmovsqb
	MnemonicVPMOVSQD                           // vpmovsqd
	MnemonicVPMOVSQW                           // vpmovsqw
	MnemonicVPMOVSWB                           // vpmovswb
	MnemonicVPMOVSXBD                          // vpmovsxbd
	MnemonicVPMOVSXBQ                          // vpmovsxbq
	MnemonicVPMOVSXBW                          // vpmovsxbw
	MnemonicVPMOVSXDQ                          // vpmovsxdq
	MnemonicVPMOVSXWD                          // vpmovsxwd
	MnemonicVPMOVSXWQ                          // vpmovsxwq
	MnemonicVPMOVUSDB                          // vpmovusdb
	MnemonicVPMOVUSDW                          // vpmovusdw
	MnemonicVPMOVUSQB                          // vpmovusqb
	MnemonicVPMOVUSQD                          // vpmovusqd
	MnemonicVPMOVUSQW                          // vpmovusqw
	MnemonicVPMOVUSWB                          // vpmovuswb
	MnemonicVPMOVW2M                           // vpmovw2m
	MnemonicVPMOVWB                            // vpmovwb
	MnemonicVPMOVZXBD                          // vpmovzxbd
	MnemonicVPMOVZXBQ                          // vpmovzxbq
	MnemonicVPMOVZXBW                          // vpmovzxbw
	MnemonicVPMOVZXDQ                          // vpmovzxdq
	MnemonicVPMOVZXWD                          // vpmovzxwd
	MnemonicVPMOVZXWQ                          // vpmovzxwq
	MnemonicVPMULDQ                            // vpmuldq
	MnemonicVPMULHD                            // vpmulhd
	MnemonicVPMULHRSW                          // vpmulhrsw
	MnemonicVPMULHUD                           // vpmulhud
	MnemonicVPMULHUW                           // vpmulhuw
	MnemonicVPMULHW                            // vpmulhw
	MnemonicVPMULLD                            // vpmulld
	MnemonicVPMULLQ                            // vpmullq
	MnemonicVPMULLW                            // vpmullw
	MnemonicVPMULTISHIFTQB                     // vpmultishiftqb
	MnemonicVPMULUDQ                           // vpmuludq
	MnemonicVPOPCNTB                           // vpopcntb
	MnemonicVPOPCNTD                           // vpopcntd
	MnemonicVPOPCNTQ                           // vpopcntq
	MnemonicVPOPCNTW                           // vpopcntw
	MnemonicVPOR                               // vpor
	MnemonicVPORD                              // vpord
	MnemonicVPORQ                              // vporq
	MnemonicVPPERM                             // vpperm
	MnemonicVPREFETCH0                         // vprefetch0
	MnemonicVPREFETCH1                         // vprefetch1
	MnemonicVPREFETCH2                         // vprefetch2
	MnemonicVPREFETCHE0                        // vprefetche0
	MnemonicVPREFETCHE1                        // vprefetche1
	MnemonicVPREFETCHE2                        // vprefetche2
	MnemonicVPREFETCHENTA                      // vprefetchenta
	MnemonicVPREFETCHNTA                       // vprefetchnta
	MnemonicVPROLD                             // vprold
	MnemonicVPROLQ                             // vprolq
	MnemonicVPROLVD                            // vprolvd
	MnemonicVPROLVQ                            // vprolvq
	MnemonicVPRORD                             // vprord
	MnemonicVPRORQ                             // vprorq
	MnemonicVPRORVD                            // vprorvd
	MnemonicVPRORVQ                            // vprorvq
	MnemonicVPROTB                             // vprotb
	MnemonicVPROTD                             // vprotd
	MnemonicVPROTQ                             // vprotq
	MnemonicVPROTW                             // vprotw
	MnemonicVPSADBW                            // vpsadbw
	MnemonicVPSBBD                             // vpsbbd
	MnemonicVPSBBRD                            // vpsbbrd
	MnemonicVPSCATTERDD                        // vpscatterdd
	MnemonicVPSCATTERDQ                        // vpscatterdq
	MnemonicVPSCATTERQD                        // vpscatterqd
	MnemonicVPSCATTERQQ                        // vpscatterqq
	MnemonicVPSHAB                             // vpshab
	MnemonicVPSHAD                             // vpshad
	MnemonicVPSHAQ                             // vpshaq
	MnemonicVPSHAW                             // vpshaw
	MnemonicVPSHLB                             // vpshlb
	MnemonicVPSHLD                             // vpshld
	MnemonicVPSHLDD                            // vpshldd
	MnemonicVPSHLDQ                            // vpshldq
	MnemonicVPSHLDVD                           // vpshldvd
	MnemonicVPSHLDVQ                           // vpshldvq
	MnemonicVPSHLDVW                           // vpshldvw
	MnemonicVPSHLDW                            // vpshldw
	MnemonicVPSHLQ                             // vpshlq
	MnemonicVPSHLW                             // vpshlw
	MnemonicVPSHRDD                            // vpshrdd
	MnemonicVPSHRDQ                            // vpshrdq
	MnemonicVPSHRDVD                           // vpshrdvd
	MnemonicVPSHRDVQ                           // vpshrdvq
	MnemonicVPSHRDVW                           // vpshrdvw
	MnemonicVPSHRDW                            // vpshrdw
	MnemonicVPSHUFB                            // vpshufb
	MnemonicVPSHUFBITQMB                       // vpshufbitqmb
	MnemonicVPSHUFD                            // vpshufd
	MnemonicVPSHUFHW                           // vpshufhw
	MnemonicVPSHUFLW                           // vpshuflw
	MnemonicVPSIGNB                            // vpsignb
	MnemonicVPSIGND                            // vpsignd
	MnemonicVPSIGNW                            // vpsignw
	MnemonicVPSLLD                             // vpslld
	MnemonicVPSLLDQ                            // vpslldq
	MnemonicVPSLLQ                             // vpsllq
	MnemonicVPSLLVD                            // vpsllvd
	MnemonicVPSLLVQ                            // vpsllvq
	MnemonicVPSLLVW                            // vpsllvw
	MnemonicVPSLLW                             // vpsllw
	MnemonicVPSRAD                             // vpsrad
	MnemonicVPSRAQ                             // vpsraq
	MnemonicVPSRAVD                            // vpsravd
	MnemonicVPSRAVQ                            // vpsravq
	MnemonicVPSRAVW                            // vpsravw
	MnemonicVPSRAW                             // vpsraw
	MnemonicVPSRLD                             // vpsrld
	MnemonicVPSRLDQ                            // vpsrldq
	MnemonicVPSRLQ                             // vpsrlq
	MnemonicVPSRLVD                            // vpsrlvd
	MnemonicVPSRLVQ                            // vpsrlvq
	MnemonicVPSRLVW                            // vpsrlvw
	MnemonicVPSRLW                             // vpsrlw
	MnemonicVPSUBB                             // vpsubb
	MnemonicVPSUBD                             // vpsubd
	MnemonicVPSUBQ                             // vpsubq
	MnemonicVPSUBRD                            // vpsubrd
	MnemonicVPSUBRSETBD                        // vpsubrsetbd
	MnemonicVPSUBSB                            // vpsubsb
	MnemonicVPSUBSETBD                         // vpsubsetbd
	MnemonicVPSUBSW                            // vpsubsw
	MnemonicVPSUBUSB                           // vpsubusb
	MnemonicVPSUBUSW                           // vpsubusw
	MnemonicVPSUBW                             // vpsubw
	MnemonicVPTERNLOGD                         // vpternlogd
	MnemonicVPTERNLOGQ                         // vpternlogq
	MnemonicVPTEST                             // vptest
	MnemonicVPTESTMB                           // vptestmb
	MnemonicVPTESTMD                           // vptestmd
	MnemonicVPTESTMQ                           // vptestmq
	MnemonicVPTESTMW                           // vptestmw
	MnemonicVPTESTNMB                          // vptestnmb
	MnemonicVPTESTNMD                          // vptestnmd
	MnemonicVPTESTNMQ                          // vptestnmq
	MnemonicVPTESTNMW                          // vptestnmw
	MnemonicVPUNPCKHBW                         // vpunpckhbw
	MnemonicVPUNPCKHDQ                         // vpunpckhdq
	MnemonicVPUNPCKHQDQ                        // vpunpckhqdq
	MnemonicVPUNPCKHWD                         // vpunpckhwd
	MnemonicVPUNPCKLBW                         // vpunpcklbw
	MnemonicVPUNPCKLDQ                         // vpunpckldq
	MnemonicVPUNPCKLQDQ                        // vpunpcklqdq
	MnemonicVPUNPCKLWD                         // vpunpcklwd
	MnemonicVPXOR                              // vpxor
	MnemonicVPXORD                             // vpxord
	MnemonicVPXORQ                             // vpxorq
	MnemonicVRANGEPD                           // vrangepd
	MnemonicVRANGEPS                           // vrangeps
	MnemonicVRANGESD                           // vrangesd
	MnemonicVRANGESS                           // vrangess
	MnemonicVRCP14PD                           // vrcp14pd
	MnemonicVRCP14PS                           // vrcp14ps
	MnemonicVRCP14SD                           // vrcp14sd
	MnemonicVRCP14SS                           // vrcp14ss
	MnemonicVRCP23PS                           // vrcp23ps
	MnemonicVRCP28PD                           // vrcp28pd
	MnemonicVRCP28PS                           // vrcp28ps
	MnemonicVRCP28SD                           // vrcp28sd
	MnemonicVRCP28SS                           // vrcp28ss
	MnemonicVRCPPS                             // vrcpps
	MnemonicVRCPSS                             // vrcpss
	MnemonicVREDUCEPD                          // vreducepd
	MnemonicVREDUCEPS                          // vreduceps
	MnemonicVREDUCESD                          // vreducesd
	MnemonicVREDUCESS                          // vreducess
	MnemonicVRNDFXPNTPD                        // vrndfxpntpd
	MnemonicVRNDFXPNTPS                        // vrndfxpntps
	MnemonicVRNDSCALEPD                        // vrndscalepd
	MnemonicVRNDSCALEPS                        // vrndscaleps
	MnemonicVRNDSCALESD                        // vrndscalesd
	MnemonicVRNDSCALESS                        // vrndscaless
	MnemonicVROUNDPD                           // vroundpd
	MnemonicVROUNDPS                           // vroundps
	MnemonicVROUNDSD                           // vroundsd
	MnemonicVROUNDSS                           // vroundss
	MnemonicVRSQRT14PD                         // vrsqrt14pd
	MnemonicVRSQRT14PS                         // vrsqrt14ps
	MnemonicVRSQRT14SD                         // vrsqrt14sd
	MnemonicVRSQRT14SS                         // vrsqrt14ss
	MnemonicVRSQRT23PS                         // vrsqrt23ps
	MnemonicVRSQRT28PD                         // vrsqrt28pd
	MnemonicVRSQRT28PS                         // vrsqrt28ps
	MnemonicVRSQRT28SD                         // vrsqrt28sd
	MnemonicVRSQRT28SS                         // vrsqrt28ss
	MnemonicVRSQRTPS                           // vrsqrtps
	MnemonicVRSQRTSS                           // vrsqrtss
	MnemonicVSCALEFPD                          // vscalefpd
	MnemonicVSCALEFPS                          // vscalefps
	MnemonicVSCALEFSD                          // vscalefsd
	MnemonicVSCALEFSS                          // vscalefss
	MnemonicVSCALEPS                           // vscaleps
	MnemonicVSCATTERDPD                        // vscatterdpd
	MnemonicVSCATTERDPS                        // vscatterdps
	MnemonicVSCATTERPF0DPD                     // vscatterpf0dpd
	MnemonicVSCATTERPF0DPS                     // vscatterpf0dps
	MnemonicVSCATTERPF0HINTDPD                 // vscatterpf0hintdpd
	MnemonicVSCATTERPF0HINTDPS                 // vscatterpf0hintdps
	MnemonicVSCATTERPF0QPD                     // vscatterpf0qpd
	MnemonicVSCATTERPF0QPS                     // vscatterpf0qps
	MnemonicVSCATTERPF1DPD                     // vscatterpf1dpd
	MnemonicVSCATTERPF1DPS                     // vscatterpf1dps
	MnemonicVSCATTERPF1QPD                     // vscatterpf1qpd
	MnemonicVSCATTERPF1QPS                     // vscatterpf1qps
	MnemonicVSCATTERQPD                        // vscatterqpd
	MnemonicVSCATTERQPS                        // vscatterqps
	MnemonicVSHUFF32X4                         // vshuff32x4
	MnemonicVSHUFF64X2                         // vshuff64x2
	MnemonicVSHUFI32X4                         // vshufi32x4
	MnemonicVSHUFI64X2                         // vshufi64x2
	MnemonicVSHUFPD                            // vshufpd
	MnemonicVSHUFPS                            // vshufps
	MnemonicVSQRTPD                            // vsqrtpd
	MnemonicVSQRTPS                            // vsqrtps
	MnemonicVSQRTSD                            // vsqrtsd
	MnemonicVSQRTSS                            // vsqrtss
	MnemonicVSTMXCSR                           // vstmxcsr
	MnemonicVSUBPD                             // vsubpd
	MnemonicVSUBPS                             // vsubps
	MnemonicVSUBRPD                            // vsubrpd
	MnemonicVSUBRPS                            // vsubrps
	MnemonicVSUBSD                             // vsubsd
	MnemonicVSUBSS                             // vsubss
	MnemonicVTESTPD                            // vtestpd
	MnemonicVTESTPS                            // vtestps
	MnemonicVUCOMISD                           // vucomisd
	MnemonicVUCOMISS                           // vucomiss
	MnemonicVUNPCKHPD                          // vunpckhpd
	MnemonicVUNPCKHPS                          // vunpckhps
	MnemonicVUNPCKLPD                          // vunpcklpd
	MnemonicVUNPCKLPS                          // vunpcklps
	MnemonicVXORPD                             // vxorpd
	MnemonicVXORPS                             // vxorps
	MnemonicVZEROALL                           // vzeroall
	MnemonicVZEROUPPER                         // vzeroupper
	MnemonicWBINVD                             // wbinvd
	MnemonicWRFSBASE                           // wrfsbase
	MnemonicWRGSBASE                           // wrgsbase
	MnemonicWRMSR                              // wrmsr
	MnemonicWRPKRU                             // wrpkru
	MnemonicWRSSD                              // wrssd
	MnemonicWRSSQ                              // wrssq
	MnemonicWRUSSD                             // wrussd
	MnemonicWRUSSQ                             // wrussq
	MnemonicXABORT                             // xabort
	MnemonicXADD                               // xadd
	MnemonicXBEGIN                             // xbegin
	MnemonicXCHG                               // xchg
	MnemonicXCRYPTCBC                          // xcrypt_cbc
	MnemonicXCRYPTCFB                          // xcrypt_cfb
	MnemonicXCRYPTCTR                          // xcrypt_ctr
	MnemonicXCRYPTECB                          // xcrypt_ecb
	MnemonicXCRYPTOFB                          // xcrypt_ofb
	MnemonicXEND                               // xend
	MnemonicXGETBV                             // xgetbv
	MnemonicXLAT                               // xlat
	MnemonicXOR                                // xor
	MnemonicXORPD                              // xorpd
	MnemonicXORPS                              // xorps
	MnemonicXRESLDTRK                          // xresldtrk
	MnemonicXRSTOR                             // xrstor
	MnemonicXRSTOR64                           // xrstor64
	MnemonicXRSTORS                            // xrstors
	MnemonicXRSTORS64                          // xrstors64
	MnemonicXSAVE                              // xsave
	MnemonicXSAVE64                            // xsave64
	MnemonicXSAVEC                             // xsavec
	MnemonicXSAVEC64                           // xsavec64
	MnemonicXSAVEOPT                           // xsaveopt
	MnemonicXSAVEOPT64                         // xsaveopt64
	MnemonicXSAVES                             // xsaves
	MnemonicXSAVES64                           // xsaves64
	MnemonicXSETBV                             // xsetbv
	MnemonicXSHA1                              // xsha1
	MnemonicXSHA256                            // xsha256
	MnemonicXSTORE                             // xstore
	MnemonicXSUSLDTRK                          // xsusldtrk
	MnemonicXTEST                              // xtest
)
