// Copyright 2019 John Papandriopoulos.  All rights reserved.
// Use of this source code is governed by a MIT-style
// license that can be found in the LICENSE file.

package zydis

// Register is an enum of processor registers.
type Register int

//go:generate stringer -type=Register -linecomment

// Register enum values.
const (
	RegisterNone Register = iota // None
	// General purpose registers  8-bit
	RegisterAL   // AL
	RegisterCL   // CL
	RegisterDL   // DL
	RegisterBL   // BL
	RegisterAH   // AH
	RegisterCH   // CH
	RegisterDH   // DH
	RegisterBH   // BH
	RegisterSPL  // SPL
	RegisterBPL  // BPL
	RegisterSIL  // SIL
	RegisterDIL  // DIL
	RegisterR8B  // R8B
	RegisterR9B  // R9B
	RegisterR10B // R10B
	RegisterR11B // R11B
	RegisterR12B // R12B
	RegisterR13B // R13B
	RegisterR14B // R14B
	RegisterR15B // R15B
	// General purpose registers 16-bit
	RegisterAX   // AX
	RegisterCX   // CX
	RegisterDX   // DX
	RegisterBX   // BX
	RegisterSP   // SP
	RegisterBP   // BP
	RegisterSI   // SI
	RegisterDI   // DI
	RegisterR8W  // R8W
	RegisterR9W  // R9W
	RegisterR10W // R10W
	RegisterR11W // R11W
	RegisterR12W // R12W
	RegisterR13W // R13W
	RegisterR14W // R14W
	RegisterR15W // R15W
	// General purpose registers 32-bit
	RegisterEAX  // EAX
	RegisterECX  // ECX
	RegisterEDX  // EDX
	RegisterEBX  // EBX
	RegisterESP  // ESP
	RegisterEBP  // EBP
	RegisterESI  // ESI
	RegisterEDI  // EDI
	RegisterR8D  // R8D
	RegisterR9D  // R9D
	RegisterR10D // R10D
	RegisterR11D // R11D
	RegisterR12D // R12D
	RegisterR13D // R13D
	RegisterR14D // R14D
	RegisterR15D // R15D
	// General purpose registers 64-bit
	RegisterRAX // RAX
	RegisterRCX // RCX
	RegisterRDX // RDX
	RegisterRBX // RBX
	RegisterRSP // RSP
	RegisterRBP // RBP
	RegisterRSI // RSI
	RegisterRDI // RDI
	RegisterR8  // R8
	RegisterR9  // R9
	RegisterR10 // R10
	RegisterR11 // R11
	RegisterR12 // R12
	RegisterR13 // R13
	RegisterR14 // R14
	RegisterR15 // R15
	// Floating point legacy registers
	RegisterST0        // ST0
	RegisterST1        // ST1
	RegisterST2        // ST2
	RegisterST3        // ST3
	RegisterST4        // ST4
	RegisterST5        // ST5
	RegisterST6        // ST6
	RegisterST7        // ST7
	RegisterX87Control // X87Control
	RegisterX87Status  // X87Status
	RegisterX87Tag     // X87Tag
	// Floating point multimedia registers
	RegisterMM0 // MM0
	RegisterMM1 // MM1
	RegisterMM2 // MM2
	RegisterMM3 // MM3
	RegisterMM4 // MM4
	RegisterMM5 // MM5
	RegisterMM6 // MM6
	RegisterMM7 // MM7
	// Floating point vector registers 128-bit
	RegisterXMM0  // XMM0
	RegisterXMM1  // XMM1
	RegisterXMM2  // XMM2
	RegisterXMM3  // XMM3
	RegisterXMM4  // XMM4
	RegisterXMM5  // XMM5
	RegisterXMM6  // XMM6
	RegisterXMM7  // XMM7
	RegisterXMM8  // XMM8
	RegisterXMM9  // XMM9
	RegisterXMM10 // XMM10
	RegisterXMM11 // XMM11
	RegisterXMM12 // XMM12
	RegisterXMM13 // XMM13
	RegisterXMM14 // XMM14
	RegisterXMM15 // XMM15
	RegisterXMM16 // XMM16
	RegisterXMM17 // XMM17
	RegisterXMM18 // XMM18
	RegisterXMM19 // XMM19
	RegisterXMM20 // XMM20
	RegisterXMM21 // XMM21
	RegisterXMM22 // XMM22
	RegisterXMM23 // XMM23
	RegisterXMM24 // XMM24
	RegisterXMM25 // XMM25
	RegisterXMM26 // XMM26
	RegisterXMM27 // XMM27
	RegisterXMM28 // XMM28
	RegisterXMM29 // XMM29
	RegisterXMM30 // XMM30
	RegisterXMM31 // XMM31
	// Floating point vector registers 256-bit
	RegisterYMM0  // YMM0
	RegisterYMM1  // YMM1
	RegisterYMM2  // YMM2
	RegisterYMM3  // YMM3
	RegisterYMM4  // YMM4
	RegisterYMM5  // YMM5
	RegisterYMM6  // YMM6
	RegisterYMM7  // YMM7
	RegisterYMM8  // YMM8
	RegisterYMM9  // YMM9
	RegisterYMM10 // YMM10
	RegisterYMM11 // YMM11
	RegisterYMM12 // YMM12
	RegisterYMM13 // YMM13
	RegisterYMM14 // YMM14
	RegisterYMM15 // YMM15
	RegisterYMM16 // YMM16
	RegisterYMM17 // YMM17
	RegisterYMM18 // YMM18
	RegisterYMM19 // YMM19
	RegisterYMM20 // YMM20
	RegisterYMM21 // YMM21
	RegisterYMM22 // YMM22
	RegisterYMM23 // YMM23
	RegisterYMM24 // YMM24
	RegisterYMM25 // YMM25
	RegisterYMM26 // YMM26
	RegisterYMM27 // YMM27
	RegisterYMM28 // YMM28
	RegisterYMM29 // YMM29
	RegisterYMM30 // YMM30
	RegisterYMM31 // YMM31
	// Floating point vector registers 512-bit
	RegisterZMM0  // ZMM0
	RegisterZMM1  // ZMM1
	RegisterZMM2  // ZMM2
	RegisterZMM3  // ZMM3
	RegisterZMM4  // ZMM4
	RegisterZMM5  // ZMM5
	RegisterZMM6  // ZMM6
	RegisterZMM7  // ZMM7
	RegisterZMM8  // ZMM8
	RegisterZMM9  // ZMM9
	RegisterZMM10 // ZMM10
	RegisterZMM11 // ZMM11
	RegisterZMM12 // ZMM12
	RegisterZMM13 // ZMM13
	RegisterZMM14 // ZMM14
	RegisterZMM15 // ZMM15
	RegisterZMM16 // ZMM16
	RegisterZMM17 // ZMM17
	RegisterZMM18 // ZMM18
	RegisterZMM19 // ZMM19
	RegisterZMM20 // ZMM20
	RegisterZMM21 // ZMM21
	RegisterZMM22 // ZMM22
	RegisterZMM23 // ZMM23
	RegisterZMM24 // ZMM24
	RegisterZMM25 // ZMM25
	RegisterZMM26 // ZMM26
	RegisterZMM27 // ZMM27
	RegisterZMM28 // ZMM28
	RegisterZMM29 // ZMM29
	RegisterZMM30 // ZMM30
	RegisterZMM31 // ZMM31
	// Matrix registers
	RegisterTMM0 // TMM0
	RegisterTMM1 // TMM1
	RegisterTMM2 // TMM2
	RegisterTMM3 // TMM3
	RegisterTMM4 // TMM4
	RegisterTMM5 // TMM5
	RegisterTMM6 // TMM6
	RegisterTMM7 // TMM7
	// Flags registers
	RegisterFlags  // Flags
	RegisterEFlags // EFlags
	RegisterRFlags // RFlags
	// Instruction-pointer registers
	RegisterIP  // IP
	RegisterEIP // EIP
	RegisterRIP // RIP
	// Segment registers
	RegisterES // ES
	RegisterCS // CS
	RegisterSS // SS
	RegisterDS // DS
	RegisterFS // FS
	RegisterGS // GS
	// Table registers
	RegisterGDTR // GDTR
	RegisterLDTR // LDTR
	RegisterIDTR // IDTR
	RegisterTR   // TR
	// Test registers
	RegisterTR0 // TR0
	RegisterTR1 // TR1
	RegisterTR2 // TR2
	RegisterTR3 // TR3
	RegisterTR4 // TR4
	RegisterTR5 // TR5
	RegisterTR6 // TR6
	RegisterTR7 // TR7
	// Control registers
	RegisterCR0  // CR0
	RegisterCR1  // CR1
	RegisterCR2  // CR2
	RegisterCR3  // CR3
	RegisterCR4  // CR4
	RegisterCR5  // CR5
	RegisterCR6  // CR6
	RegisterCR7  // CR7
	RegisterCR8  // CR8
	RegisterCR9  // CR9
	RegisterCR10 // CR10
	RegisterCR11 // CR11
	RegisterCR12 // CR12
	RegisterCR13 // CR13
	RegisterCR14 // CR14
	RegisterCR15 // CR15
	// Debug registers
	RegisterDR0  // DR0
	RegisterDR1  // DR1
	RegisterDR2  // DR2
	RegisterDR3  // DR3
	RegisterDR4  // DR4
	RegisterDR5  // DR5
	RegisterDR6  // DR6
	RegisterDR7  // DR7
	RegisterDR8  // DR8
	RegisterDR9  // DR9
	RegisterDR10 // DR10
	RegisterDR11 // DR11
	RegisterDR12 // DR12
	RegisterDR13 // DR13
	RegisterDR14 // DR14
	RegisterDR15 // DR15
	// Mask registers
	RegisterK0 // K0
	RegisterK1 // K1
	RegisterK2 // K2
	RegisterK3 // K3
	RegisterK4 // K4
	RegisterK5 // K5
	RegisterK6 // K6
	RegisterK7 // K7
	// Bound registers
	RegisterBND0      // BND0
	RegisterBND1      // BND1
	RegisterBND2      // BND2
	RegisterBND3      // BND3
	RegisterBNDCfg    // BNDCfg
	RegisterBNDStatus // BNDStatus
	// Uncategorized
	RegisterMXCSR // MXCSR
	RegisterPKRU  // PKRU
	RegisterXCR0  // XCR0
)
