package header
//back\HyperDbgDev\hyperdbg\hprdbgctrl\header\commands.h.back

const(
DEBUGGER_COMMAND_ATTRIBUTE_EVENT = 0x1 | DEBUGGER_COMMAND_ATTRIBUTE_LOCAL_COMMAND_IN_DEBUGGER_MODE | DEBUGGER_COMMAND_ATTRIBUTE_LOCAL_CASE_SENSITIVE //col:155
DEBUGGER_COMMAND_ATTRIBUTE_LOCAL_COMMAND_IN_DEBUGGER_MODE =     0x2 //col:157
DEBUGGER_COMMAND_ATTRIBUTE_LOCAL_COMMAND_IN_REMOTE_CONNECTION = 0x4 //col:158
DEBUGGER_COMMAND_ATTRIBUTE_LOCAL_CASE_SENSITIVE =               0x8 //col:159
DEBUGGER_COMMAND_ATTRIBUTE_REPEAT_ON_ENTER =                    0x10 //col:160
DEBUGGER_COMMAND_ATTRIBUTE_WONT_STOP_DEBUGGER_AGAIN =           0x20 //col:161
DEBUGGER_COMMAND_ATTRIBUTE_ABSOLUTE_LOCAL = DEBUGGER_COMMAND_ATTRIBUTE_LOCAL_COMMAND_IN_DEBUGGER_MODE | DEBUGGER_COMMAND_ATTRIBUTE_LOCAL_COMMAND_IN_REMOTE_CONNECTION //col:167
DEBUGGER_COMMAND_CLEAR_ATTRIBUTES = DEBUGGER_COMMAND_ATTRIBUTE_ABSOLUTE_LOCAL //col:175
DEBUGGER_COMMAND_HELP_ATTRIBUTES = DEBUGGER_COMMAND_ATTRIBUTE_ABSOLUTE_LOCAL //col:178
DEBUGGER_COMMAND_CONNECT_ATTRIBUTES = DEBUGGER_COMMAND_ATTRIBUTE_ABSOLUTE_LOCAL //col:181
DEBUGGER_COMMAND_LISTEN_ATTRIBUTES = DEBUGGER_COMMAND_ATTRIBUTE_ABSOLUTE_LOCAL //col:184
DEBUGGER_COMMAND_G_ATTRIBUTES = DEBUGGER_COMMAND_ATTRIBUTE_ABSOLUTE_LOCAL | DEBUGGER_COMMAND_ATTRIBUTE_REPEAT_ON_ENTER //col:187
DEBUGGER_COMMAND_ATTACH_ATTRIBUTES = DEBUGGER_COMMAND_ATTRIBUTE_LOCAL_COMMAND_IN_DEBUGGER_MODE //col:189
DEBUGGER_COMMAND_DETACH_ATTRIBUTES = DEBUGGER_COMMAND_ATTRIBUTE_LOCAL_COMMAND_IN_DEBUGGER_MODE //col:191
DEBUGGER_COMMAND_SWITCH_ATTRIBUTES = DEBUGGER_COMMAND_ATTRIBUTE_LOCAL_COMMAND_IN_DEBUGGER_MODE //col:193
DEBUGGER_COMMAND_START_ATTRIBUTES = DEBUGGER_COMMAND_ATTRIBUTE_WONT_STOP_DEBUGGER_AGAIN //col:195
DEBUGGER_COMMAND_RESTART_ATTRIBUTES = DEBUGGER_COMMAND_ATTRIBUTE_WONT_STOP_DEBUGGER_AGAIN //col:197
DEBUGGER_COMMAND_KILL_ATTRIBUTES = DEBUGGER_COMMAND_ATTRIBUTE_WONT_STOP_DEBUGGER_AGAIN //col:199
DEBUGGER_COMMAND_PROCESS_ATTRIBUTES = DEBUGGER_COMMAND_ATTRIBUTE_LOCAL_COMMAND_IN_DEBUGGER_MODE //col:201
DEBUGGER_COMMAND_THREAD_ATTRIBUTES = DEBUGGER_COMMAND_ATTRIBUTE_LOCAL_COMMAND_IN_DEBUGGER_MODE //col:204
DEBUGGER_COMMAND_SLEEP_ATTRIBUTES = DEBUGGER_COMMAND_ATTRIBUTE_ABSOLUTE_LOCAL //col:207
DEBUGGER_COMMAND_EVENTS_ATTRIBUTES = DEBUGGER_COMMAND_ATTRIBUTE_LOCAL_COMMAND_IN_DEBUGGER_MODE //col:210
DEBUGGER_COMMAND_SETTINGS_ATTRIBUTES = DEBUGGER_COMMAND_ATTRIBUTE_LOCAL_COMMAND_IN_DEBUGGER_MODE //col:213
DEBUGGER_COMMAND_DISCONNECT_ATTRIBUTES = DEBUGGER_COMMAND_ATTRIBUTE_ABSOLUTE_LOCAL //col:216
DEBUGGER_COMMAND_DEBUG_ATTRIBUTES = DEBUGGER_COMMAND_ATTRIBUTE_ABSOLUTE_LOCAL | DEBUGGER_COMMAND_ATTRIBUTE_LOCAL_CASE_SENSITIVE //col:219
DEBUGGER_COMMAND_DOT_STATUS_ATTRIBUTES = DEBUGGER_COMMAND_ATTRIBUTE_ABSOLUTE_LOCAL //col:222
DEBUGGER_COMMAND_STATUS_ATTRIBUTES = NULL //col:225
DEBUGGER_COMMAND_LOAD_ATTRIBUTES = NULL //col:227
DEBUGGER_COMMAND_EXIT_ATTRIBUTES = DEBUGGER_COMMAND_ATTRIBUTE_ABSOLUTE_LOCAL //col:229
DEBUGGER_COMMAND_FLUSH_ATTRIBUTES = DEBUGGER_COMMAND_ATTRIBUTE_LOCAL_COMMAND_IN_DEBUGGER_MODE //col:232
DEBUGGER_COMMAND_PAUSE_ATTRIBUTES = DEBUGGER_COMMAND_ATTRIBUTE_ABSOLUTE_LOCAL //col:235
DEBUGGER_COMMAND_UNLOAD_ATTRIBUTES = NULL //col:238
DEBUGGER_COMMAND_SCRIPT_ATTRIBUTES = DEBUGGER_COMMAND_ATTRIBUTE_ABSOLUTE_LOCAL | DEBUGGER_COMMAND_ATTRIBUTE_LOCAL_CASE_SENSITIVE //col:240
DEBUGGER_COMMAND_OUTPUT_ATTRIBUTES = DEBUGGER_COMMAND_ATTRIBUTE_LOCAL_COMMAND_IN_DEBUGGER_MODE | DEBUGGER_COMMAND_ATTRIBUTE_LOCAL_CASE_SENSITIVE //col:243
DEBUGGER_COMMAND_PRINT_ATTRIBUTES = DEBUGGER_COMMAND_ATTRIBUTE_LOCAL_COMMAND_IN_DEBUGGER_MODE | DEBUGGER_COMMAND_ATTRIBUTE_LOCAL_CASE_SENSITIVE | DEBUGGER_COMMAND_ATTRIBUTE_REPEAT_ON_ENTER //col:246
DEBUGGER_COMMAND_EVAL_ATTRIBUTES = DEBUGGER_COMMAND_ATTRIBUTE_LOCAL_COMMAND_IN_DEBUGGER_MODE | DEBUGGER_COMMAND_ATTRIBUTE_LOCAL_CASE_SENSITIVE | DEBUGGER_COMMAND_ATTRIBUTE_REPEAT_ON_ENTER //col:249
DEBUGGER_COMMAND_LOGOPEN_ATTRIBUTES = DEBUGGER_COMMAND_ATTRIBUTE_ABSOLUTE_LOCAL | DEBUGGER_COMMAND_ATTRIBUTE_LOCAL_CASE_SENSITIVE //col:252
DEBUGGER_COMMAND_LOGCLOSE_ATTRIBUTES = DEBUGGER_COMMAND_ATTRIBUTE_ABSOLUTE_LOCAL //col:255
DEBUGGER_COMMAND_TEST_ATTRIBUTES = DEBUGGER_COMMAND_ATTRIBUTE_LOCAL_COMMAND_IN_DEBUGGER_MODE //col:258
DEBUGGER_COMMAND_CPU_ATTRIBUTES = NULL //col:260
DEBUGGER_COMMAND_WRMSR_ATTRIBUTES = NULL //col:262
DEBUGGER_COMMAND_RDMSR_ATTRIBUTES = NULL //col:264
DEBUGGER_COMMAND_VA2PA_ATTRIBUTES = DEBUGGER_COMMAND_ATTRIBUTE_LOCAL_CASE_SENSITIVE | DEBUGGER_COMMAND_ATTRIBUTE_LOCAL_COMMAND_IN_DEBUGGER_MODE //col:266
DEBUGGER_COMMAND_PA2VA_ATTRIBUTES = DEBUGGER_COMMAND_ATTRIBUTE_LOCAL_CASE_SENSITIVE | DEBUGGER_COMMAND_ATTRIBUTE_LOCAL_COMMAND_IN_DEBUGGER_MODE //col:268
DEBUGGER_COMMAND_FORMATS_ATTRIBUTES = DEBUGGER_COMMAND_ATTRIBUTE_LOCAL_COMMAND_IN_DEBUGGER_MODE | DEBUGGER_COMMAND_ATTRIBUTE_LOCAL_CASE_SENSITIVE | DEBUGGER_COMMAND_ATTRIBUTE_REPEAT_ON_ENTER //col:270
DEBUGGER_COMMAND_PTE_ATTRIBUTES = DEBUGGER_COMMAND_ATTRIBUTE_LOCAL_CASE_SENSITIVE | DEBUGGER_COMMAND_ATTRIBUTE_LOCAL_COMMAND_IN_DEBUGGER_MODE //col:273
DEBUGGER_COMMAND_CORE_ATTRIBUTES = DEBUGGER_COMMAND_ATTRIBUTE_LOCAL_COMMAND_IN_DEBUGGER_MODE //col:275
DEBUGGER_COMMAND_MONITOR_ATTRIBUTES = DEBUGGER_COMMAND_ATTRIBUTE_EVENT //col:278
DEBUGGER_COMMAND_VMCALL_ATTRIBUTES = DEBUGGER_COMMAND_ATTRIBUTE_EVENT //col:280
DEBUGGER_COMMAND_EPTHOOK_ATTRIBUTES = DEBUGGER_COMMAND_ATTRIBUTE_EVENT //col:282
DEBUGGER_COMMAND_EPTHOOK2_ATTRIBUTES = DEBUGGER_COMMAND_ATTRIBUTE_EVENT //col:284
DEBUGGER_COMMAND_CPUID_ATTRIBUTES = DEBUGGER_COMMAND_ATTRIBUTE_EVENT //col:286
DEBUGGER_COMMAND_MSRREAD_ATTRIBUTES = DEBUGGER_COMMAND_ATTRIBUTE_EVENT //col:288
DEBUGGER_COMMAND_MSRWRITE_ATTRIBUTES = DEBUGGER_COMMAND_ATTRIBUTE_EVENT //col:290
DEBUGGER_COMMAND_TSC_ATTRIBUTES = DEBUGGER_COMMAND_ATTRIBUTE_EVENT //col:292
DEBUGGER_COMMAND_PMC_ATTRIBUTES = DEBUGGER_COMMAND_ATTRIBUTE_EVENT //col:294
DEBUGGER_COMMAND_CRWRITE_ATTRIBUTES = DEBUGGER_COMMAND_ATTRIBUTE_EVENT //col:296
DEBUGGER_COMMAND_DR_ATTRIBUTES = DEBUGGER_COMMAND_ATTRIBUTE_EVENT //col:298
DEBUGGER_COMMAND_IOIN_ATTRIBUTES = DEBUGGER_COMMAND_ATTRIBUTE_EVENT //col:300
DEBUGGER_COMMAND_IOOUT_ATTRIBUTES = DEBUGGER_COMMAND_ATTRIBUTE_EVENT //col:302
DEBUGGER_COMMAND_EXCEPTION_ATTRIBUTES = DEBUGGER_COMMAND_ATTRIBUTE_EVENT //col:304
DEBUGGER_COMMAND_INTERRUPT_ATTRIBUTES = DEBUGGER_COMMAND_ATTRIBUTE_EVENT //col:306
DEBUGGER_COMMAND_SYSCALL_ATTRIBUTES = DEBUGGER_COMMAND_ATTRIBUTE_EVENT //col:308
DEBUGGER_COMMAND_SYSRET_ATTRIBUTES = DEBUGGER_COMMAND_ATTRIBUTE_EVENT //col:310
DEBUGGER_COMMAND_HIDE_ATTRIBUTES = DEBUGGER_COMMAND_ATTRIBUTE_LOCAL_CASE_SENSITIVE //col:312
DEBUGGER_COMMAND_UNHIDE_ATTRIBUTES = NULL //col:314
DEBUGGER_COMMAND_MEASURE_ATTRIBUTES = NULL //col:316
DEBUGGER_COMMAND_LM_ATTRIBUTES = NULL //col:318
DEBUGGER_COMMAND_P_ATTRIBUTES = DEBUGGER_COMMAND_ATTRIBUTE_LOCAL_COMMAND_IN_DEBUGGER_MODE | DEBUGGER_COMMAND_ATTRIBUTE_REPEAT_ON_ENTER //col:320
DEBUGGER_COMMAND_T_ATTRIBUTES = DEBUGGER_COMMAND_ATTRIBUTE_LOCAL_COMMAND_IN_DEBUGGER_MODE | DEBUGGER_COMMAND_ATTRIBUTE_REPEAT_ON_ENTER //col:323
DEBUGGER_COMMAND_I_ATTRIBUTES = DEBUGGER_COMMAND_ATTRIBUTE_LOCAL_COMMAND_IN_DEBUGGER_MODE | DEBUGGER_COMMAND_ATTRIBUTE_REPEAT_ON_ENTER //col:326
DEBUGGER_COMMAND_D_AND_U_ATTRIBUTES = DEBUGGER_COMMAND_ATTRIBUTE_LOCAL_COMMAND_IN_DEBUGGER_MODE | DEBUGGER_COMMAND_ATTRIBUTE_LOCAL_CASE_SENSITIVE | DEBUGGER_COMMAND_ATTRIBUTE_REPEAT_ON_ENTER //col:329
DEBUGGER_COMMAND_E_ATTRIBUTES = DEBUGGER_COMMAND_ATTRIBUTE_LOCAL_COMMAND_IN_DEBUGGER_MODE | DEBUGGER_COMMAND_ATTRIBUTE_LOCAL_CASE_SENSITIVE //col:332
DEBUGGER_COMMAND_S_ATTRIBUTES = DEBUGGER_COMMAND_ATTRIBUTE_LOCAL_COMMAND_IN_DEBUGGER_MODE | DEBUGGER_COMMAND_ATTRIBUTE_LOCAL_CASE_SENSITIVE //col:335
DEBUGGER_COMMAND_R_ATTRIBUTES = DEBUGGER_COMMAND_ATTRIBUTE_LOCAL_COMMAND_IN_DEBUGGER_MODE | DEBUGGER_COMMAND_ATTRIBUTE_LOCAL_CASE_SENSITIVE | DEBUGGER_COMMAND_ATTRIBUTE_REPEAT_ON_ENTER //col:338
DEBUGGER_COMMAND_BP_ATTRIBUTES = DEBUGGER_COMMAND_ATTRIBUTE_LOCAL_COMMAND_IN_DEBUGGER_MODE | DEBUGGER_COMMAND_ATTRIBUTE_LOCAL_CASE_SENSITIVE //col:341
DEBUGGER_COMMAND_BE_ATTRIBUTES = DEBUGGER_COMMAND_ATTRIBUTE_LOCAL_COMMAND_IN_DEBUGGER_MODE //col:344
DEBUGGER_COMMAND_BD_ATTRIBUTES = DEBUGGER_COMMAND_ATTRIBUTE_LOCAL_COMMAND_IN_DEBUGGER_MODE //col:347
DEBUGGER_COMMAND_BC_ATTRIBUTES = DEBUGGER_COMMAND_ATTRIBUTE_LOCAL_COMMAND_IN_DEBUGGER_MODE //col:350
DEBUGGER_COMMAND_BL_ATTRIBUTES = DEBUGGER_COMMAND_ATTRIBUTE_LOCAL_COMMAND_IN_DEBUGGER_MODE //col:353
DEBUGGER_COMMAND_SYMPATH_ATTRIBUTES = DEBUGGER_COMMAND_ATTRIBUTE_LOCAL_COMMAND_IN_DEBUGGER_MODE | DEBUGGER_COMMAND_ATTRIBUTE_LOCAL_CASE_SENSITIVE //col:356
DEBUGGER_COMMAND_SYM_ATTRIBUTES = DEBUGGER_COMMAND_ATTRIBUTE_LOCAL_COMMAND_IN_DEBUGGER_MODE | DEBUGGER_COMMAND_ATTRIBUTE_LOCAL_CASE_SENSITIVE //col:359
DEBUGGER_COMMAND_X_ATTRIBUTES = DEBUGGER_COMMAND_ATTRIBUTE_LOCAL_COMMAND_IN_DEBUGGER_MODE | DEBUGGER_COMMAND_ATTRIBUTE_LOCAL_CASE_SENSITIVE //col:362
DEBUGGER_COMMAND_PREALLOC_ATTRIBUTES = NULL //col:365
DEBUGGER_COMMAND_K_ATTRIBUTES = DEBUGGER_COMMAND_ATTRIBUTE_LOCAL_COMMAND_IN_DEBUGGER_MODE //col:367
DEBUGGER_COMMAND_DT_ATTRIBUTES = DEBUGGER_COMMAND_ATTRIBUTE_LOCAL_COMMAND_IN_DEBUGGER_MODE | DEBUGGER_COMMAND_ATTRIBUTE_LOCAL_CASE_SENSITIVE | DEBUGGER_COMMAND_ATTRIBUTE_REPEAT_ON_ENTER //col:370
DEBUGGER_COMMAND_STRUCT_ATTRIBUTES = DEBUGGER_COMMAND_ATTRIBUTE_LOCAL_COMMAND_IN_DEBUGGER_MODE | DEBUGGER_COMMAND_ATTRIBUTE_LOCAL_CASE_SENSITIVE //col:373
DEBUGGER_COMMAND_PE_ATTRIBUTES = NULL //col:376
)

type (
Commands interface{
CommandSettingsLoadDefaultValuesFromConfigFile()(ok bool)//col:143
}
)

func NewCommands() { return & commands{} }

func (c *commands)CommandSettingsLoadDefaultValuesFromConfigFile()(ok bool){//col:143
/*CommandSettingsLoadDefaultValuesFromConfigFile();
VOID
CommandSettingsSetValueFromConfigFile(std::string OptionName, std::string OptionValue);
BOOLEAN
CommandSettingsGetValueFromConfigFile(std::string OptionName, std::string & OptionValue);
int
ReadCpuDetails();
string
ReadVendorString();
VOID
ShowMessages(const char * Fmt, ...);
string
SeparateTo64BitValue(UINT64 Value);
void
ShowMemoryCommandDB(unsigned char * OutputBuffer, UINT Size, UINT64 Address, DEBUGGER_READ_MEMORY_TYPE MemoryType, UINT64 Length);
void
ShowMemoryCommandDD(unsigned char * OutputBuffer, UINT Size, UINT64 Address, DEBUGGER_READ_MEMORY_TYPE MemoryType, UINT64 Length);
void
ShowMemoryCommandDC(unsigned char * OutputBuffer, UINT Size, UINT64 Address, DEBUGGER_READ_MEMORY_TYPE MemoryType, UINT64 Length);
void
ShowMemoryCommandDQ(unsigned char * OutputBuffer, UINT Size, UINT64 Address, DEBUGGER_READ_MEMORY_TYPE MemoryType, UINT64 Length);
VOID
CommandPteShowResults(UINT64 TargetVa, PDEBUGGER_READ_PAGE_TABLE_ENTRIES_DETAILS PteRead);
DEBUGGER_CONDITIONAL_JUMP_STATUS
HyperDbgIsConditionalJumpTaken(unsigned char * BufferToDisassemble,
                               UINT64          BuffLength,
                               RFLAGS          Rflags,
                               BOOLEAN         Isx86_64);
int
HyperDbgDisassembler64(unsigned char * BufferToDisassemble,
                       UINT64          BaseAddress,
                       UINT64          Size,
                       UINT32          MaximumInstrDecoded,
                       BOOLEAN         ShowBranchIsTakenOrNot,
                       PRFLAGS         Rflags);
int
HyperDbgDisassembler32(unsigned char * BufferToDisassemble,
                       UINT64          BaseAddress,
                       UINT64          Size,
                       UINT32          MaximumInstrDecoded,
                       BOOLEAN         ShowBranchIsTakenOrNot,
                       PRFLAGS         Rflags);
UINT32
HyperDbgLengthDisassemblerEngine(
    unsigned char * BufferToDisassemble,
    UINT64          BuffLength,
    BOOLEAN         Isx86_64);
BOOLEAN
HyperDbgCheckWhetherTheCurrentInstructionIsCall(
    unsigned char * BufferToDisassemble,
    UINT64          BuffLength,
    BOOLEAN         Isx86_64,
    PUINT32         CallLength);
VOID
HyperDbgReadMemoryAndDisassemble(DEBUGGER_SHOW_MEMORY_STYLE   Style,
                                 UINT64                       Address,
                                 DEBUGGER_READ_MEMORY_TYPE    MemoryType,
                                 DEBUGGER_READ_READING_TYPE   ReadingType,
                                 UINT32                       Pid,
                                 UINT32                       Size,
                                 PDEBUGGER_DT_COMMAND_OPTIONS DtDetails);
VOID
InitializeCommandsDictionary();
VOID
InitializeDebugger();
 *
typedef VOID (*CommandFuncType)(vector<string> SplittedCommand, string Command);
 *
typedef VOID (*CommandHelpFuncType)();
 *
typedef struct _COMMAND_DETAIL
{
    CommandFuncType     CommandFunction;
    CommandHelpFuncType CommandHelpFunction;
    UINT64              CommandAttrib;
} COMMAND_DETAIL, *PCOMMAND_DETAIL;*/
return true
}



