package header
//back\HyperDbgDev\hyperdbg\hprdbgctrl\header\debugger.h.back

const(
DefaultSpeedOfReadingKernelMessages = 30 //col:24
DEBUGGER_MAXIMUM_SYNCRONIZATION_KERNEL_DEBUGGER_OBJECTS = 0x40 //col:33
DEBUGGER_SYNCRONIZATION_OBJECT_KERNEL_DEBUGGER_IS_DEBUGGER_RUNNING =                 0x0 //col:44
DEBUGGER_SYNCRONIZATION_OBJECT_KERNEL_DEBUGGER_STARTED_PACKET_RECEIVED =             0x1 //col:45
DEBUGGER_SYNCRONIZATION_OBJECT_KERNEL_DEBUGGER_PAUSED_DEBUGGEE_DETAILS =             0x2 //col:46
DEBUGGER_SYNCRONIZATION_OBJECT_KERNEL_DEBUGGER_CORE_SWITCHING_RESULT =               0x3 //col:47
DEBUGGER_SYNCRONIZATION_OBJECT_KERNEL_DEBUGGER_PROCESS_SWITCHING_RESULT =            0x4 //col:48
DEBUGGER_SYNCRONIZATION_OBJECT_KERNEL_DEBUGGER_THREAD_SWITCHING_RESULT =             0x5 //col:49
DEBUGGER_SYNCRONIZATION_OBJECT_KERNEL_DEBUGGER_SCRIPT_RUNNING_RESULT =               0x6 //col:50
DEBUGGER_SYNCRONIZATION_OBJECT_KERNEL_DEBUGGER_SCRIPT_FORMATS_RESULT =               0x7 //col:51
DEBUGGER_SYNCRONIZATION_OBJECT_KERNEL_DEBUGGER_DEBUGGEE_FINISHED_COMMAND_EXECUTION = 0x8 //col:52
DEBUGGER_SYNCRONIZATION_OBJECT_KERNEL_DEBUGGER_FLUSH_RESULT =                        0x9 //col:53
DEBUGGER_SYNCRONIZATION_OBJECT_KERNEL_DEBUGGER_REGISTER_EVENT =                      0xa //col:54
DEBUGGER_SYNCRONIZATION_OBJECT_KERNEL_DEBUGGER_ADD_ACTION_TO_EVENT =                 0xb //col:55
DEBUGGER_SYNCRONIZATION_OBJECT_KERNEL_DEBUGGER_MODIFY_AND_QUERY_EVENT =              0xc //col:56
DEBUGGER_SYNCRONIZATION_OBJECT_KERNEL_DEBUGGER_READ_REGISTERS =                      0xd //col:57
DEBUGGER_SYNCRONIZATION_OBJECT_KERNEL_DEBUGGER_BP =                                  0xe //col:58
DEBUGGER_SYNCRONIZATION_OBJECT_KERNEL_DEBUGGER_LIST_OR_MODIFY_BREAKPOINTS =          0xf //col:59
DEBUGGER_SYNCRONIZATION_OBJECT_KERNEL_DEBUGGER_READ_MEMORY =                         0x10 //col:60
DEBUGGER_SYNCRONIZATION_OBJECT_KERNEL_DEBUGGER_EDIT_MEMORY =                         0x11 //col:61
DEBUGGER_SYNCRONIZATION_OBJECT_KERNEL_DEBUGGER_SYMBOL_RELOAD =                       0x12 //col:62
DEBUGGER_SYNCRONIZATION_OBJECT_KERNEL_DEBUGGER_TEST_QUERY =                          0x13 //col:63
DEBUGGER_SYNCRONIZATION_OBJECT_KERNEL_DEBUGGER_CALLSTACK_RESULT =                    0x14 //col:64
DEBUGGER_SYNCRONIZATION_OBJECT_KERNEL_DEBUGGER_SEARCH_QUERY_RESULT =                 0x15 //col:65
DEBUGGER_SYNCRONIZATION_OBJECT_KERNEL_DEBUGGER_VA2PA_AND_PA2VA_RESULT =              0x16 //col:66
DEBUGGER_SYNCRONIZATION_OBJECT_KERNEL_DEBUGGER_PTE_RESULT =                          0x17 //col:67
DEBUGGER_MAXIMUM_SYNCRONIZATION_USER_DEBUGGER_OBJECTS = 0x40 //col:96
DEBUGGER_SYNCRONIZATION_OBJECT_USER_DEBUGGER_IS_DEBUGGER_RUNNING = 0x30 //col:107
)

type     DEBUGGER_EVENT_PARSING_ERROR_CAUSE_SUCCESSFUL_NO_ERROR                          = 0 uint32
const(
    DEBUGGER_EVENT_PARSING_ERROR_CAUSE_SUCCESSFUL_NO_ERROR                           DEBUGGER_EVENT_PARSING_ERROR_CAUSE =  0  //col:79
    DEBUGGER_EVENT_PARSING_ERROR_CAUSE_SCRIPT_SYNTAX_ERROR                           DEBUGGER_EVENT_PARSING_ERROR_CAUSE =  1  //col:80
    DEBUGGER_EVENT_PARSING_ERROR_CAUSE_NO_INPUT                                      DEBUGGER_EVENT_PARSING_ERROR_CAUSE =  2  //col:81
    DEBUGGER_EVENT_PARSING_ERROR_CAUSE_MAXIMUM_INPUT_REACHED                         DEBUGGER_EVENT_PARSING_ERROR_CAUSE =  3  //col:82
    DEBUGGER_EVENT_PARSING_ERROR_CAUSE_OUTPUT_NAME_NOT_FOUND                         DEBUGGER_EVENT_PARSING_ERROR_CAUSE =  4  //col:83
    DEBUGGER_EVENT_PARSING_ERROR_CAUSE_OUTPUT_SOURCE_ALREADY_CLOSED                  DEBUGGER_EVENT_PARSING_ERROR_CAUSE =  5  //col:84
    DEBUGGER_EVENT_PARSING_ERROR_CAUSE_ALLOCATION_ERROR                              DEBUGGER_EVENT_PARSING_ERROR_CAUSE =  6  //col:85
    DEBUGGER_EVENT_PARSING_ERROR_CAUSE_FORMAT_ERROR                                  DEBUGGER_EVENT_PARSING_ERROR_CAUSE =  7  //col:86
    DEBUGGER_EVENT_PARSING_ERROR_CAUSE_ATTEMPT_TO_BREAK_ON_VMI_MODE                  DEBUGGER_EVENT_PARSING_ERROR_CAUSE =  8  //col:87
    DEBUGGER_EVENT_PARSING_ERROR_CAUSE_IMMEDIATE_MESSAGING_IN_EVENT_FORWARDING_MODE  DEBUGGER_EVENT_PARSING_ERROR_CAUSE =  9  //col:88
)




