package header
const(
MAXIMUM_CHARACTERS_FOR_EVENT_FORWARDING_NAME = 50 //col:22
)
type     EVENT_FORWARDING_NAMEDPIPE uint32
const(
    EVENT_FORWARDING_NAMEDPIPE DEBUGGER_EVENT_FORWARDING_TYPE = 1  //col:30
    EVENT_FORWARDING_FILE DEBUGGER_EVENT_FORWARDING_TYPE = 2  //col:31
    EVENT_FORWARDING_TCP DEBUGGER_EVENT_FORWARDING_TYPE = 3  //col:32
)
type     EVENT_FORWARDING_STATE_NOT_OPENED uint32
const(
    EVENT_FORWARDING_STATE_NOT_OPENED DEBUGGER_EVENT_FORWARDING_STATE = 1  //col:41
    EVENT_FORWARDING_STATE_OPENED DEBUGGER_EVENT_FORWARDING_STATE = 2  //col:42
    EVENT_FORWARDING_CLOSED DEBUGGER_EVENT_FORWARDING_STATE = 3  //col:43
)
type     DEBUGGER_OUTPUT_SOURCE_STATUS_SUCCESSFULLY_OPENED uint32
const(
    DEBUGGER_OUTPUT_SOURCE_STATUS_SUCCESSFULLY_OPENED DEBUGGER_OUTPUT_SOURCE_STATUS = 1  //col:54
    DEBUGGER_OUTPUT_SOURCE_STATUS_SUCCESSFULLY_CLOSED DEBUGGER_OUTPUT_SOURCE_STATUS = 2  //col:55
    DEBUGGER_OUTPUT_SOURCE_STATUS_ALREADY_OPENED DEBUGGER_OUTPUT_SOURCE_STATUS = 3  //col:56
    DEBUGGER_OUTPUT_SOURCE_STATUS_ALREADY_CLOSED DEBUGGER_OUTPUT_SOURCE_STATUS = 4  //col:57
    DEBUGGER_OUTPUT_SOURCE_STATUS_UNKNOWN_ERROR DEBUGGER_OUTPUT_SOURCE_STATUS = 5  //col:58
)
