package header


const(
MAXIMUM_CHARACTERS_FOR_EVENT_FORWARDING_NAME = 50 //col:22
)

const(
    EVENT_FORWARDING_NAMEDPIPE = 1  //col:30
    EVENT_FORWARDING_FILE = 2  //col:31
    EVENT_FORWARDING_TCP = 3  //col:32
)


const(
    EVENT_FORWARDING_STATE_NOT_OPENED = 1  //col:41
    EVENT_FORWARDING_STATE_OPENED = 2  //col:42
    EVENT_FORWARDING_CLOSED = 3  //col:43
)


const(
    DEBUGGER_OUTPUT_SOURCE_STATUS_SUCCESSFULLY_OPENED = 1  //col:54
    DEBUGGER_OUTPUT_SOURCE_STATUS_SUCCESSFULLY_CLOSED = 2  //col:55
    DEBUGGER_OUTPUT_SOURCE_STATUS_ALREADY_OPENED = 3  //col:56
    DEBUGGER_OUTPUT_SOURCE_STATUS_ALREADY_CLOSED = 4  //col:57
    DEBUGGER_OUTPUT_SOURCE_STATUS_UNKNOWN_ERROR = 5  //col:58
)




