// Code generated by bindgen. DO NOT EDIT.
package bug

import (
	"unsafe"

	"github.com/ddkwork/HyperDbg/sdk/dll/bindlib"
)

const GengoLibraryName = "bug"

var GengoLibrary = bindlib.NewLibrary(GengoLibraryName)

type _Int128T = any
type _Uint128T = any
type __NSConstantString = any
type SizeT = uint64
type _BuiltinMsVaList = *byte
type _BuiltinVaList = *byte
type Uint8T = uint8
type Uint16T = uint16
type Uint32T = uint32
type Uint64T = uint64
type Int8T = int8
type Int16T = int16
type Int32T = int32
type Int64T = int64
type Bool = int32
type IntptrT = *int32

// type Uint8T = uint8
// type Uint16T = uint16
// type Uint32T = uint32
// type Uint64T = uint64
// type Int8T = int8
// type Int16T = int16
// type Int32T = int32
// type Int64T = int64
// type Bool = int32
// type IntptrT = *int32
// type Uint8T = uint8
// type Uint16T = uint16
// type Uint32T = uint32
// type Uint64T = uint64
// type Int8T = int8
// type Int16T = int16
// type Int32T = int32
// type Int64T = int64
// type Bool = int32
// type IntptrT = *int32
// type Uint8T = uint8
// type Uint16T = uint16
// type Uint32T = uint32
// type Uint64T = uint64
// type Int8T = int8
// type Int16T = int16
// type Int32T = int32
// type Int64T = int64
// type Bool = int32
// type IntptrT = *int32
// type Uint8T = uint8
// type Uint16T = uint16
// type Uint32T = uint32
// type Uint64T = uint64
// type Int8T = int8
// type Int16T = int16
// type Int32T = int32
// type Int64T = int64
// type Bool = int32
// type IntptrT = *int32
// type Uint8T = uint8
// type Uint16T = uint16
// type Uint32T = uint32
// type Uint64T = uint64
// type Int8T = int8
// type Int16T = int16
// type Int32T = int32
// type Int64T = int64
// type Bool = int32
// type IntptrT = *int32
// type Uint8T = uint8
// type Uint16T = uint16
// type Uint32T = uint32
// type Uint64T = uint64
// type Int8T = int8
// type Int16T = int16
// type Int32T = int32
// type Int64T = int64
// type Bool = int32
// type IntptrT = *int32
// type Uint8T = uint8
// type Uint16T = uint16
// type Uint32T = uint32
// type Uint64T = uint64
// type Int8T = int8
// type Int16T = int16
// type Int32T = int32
// type Int64T = int64
// type Bool = int32
// type IntptrT = *int32
// type Uint8T = uint8
// type Uint16T = uint16
// type Uint32T = uint32
// type Uint64T = uint64
// type Int8T = int8
// type Int16T = int16
// type Int32T = int32
// type Int64T = int64
// type Bool = int32
// type IntptrT = *int32
type CheckVmxOperation = unsafe.Pointer

// Gengo init function.
func init() {}
