// Auto-generated by rustgen - DO NOT EDIT
// Source: event_process.go

#![allow(non_snake_case)]

extern crate alloc;

use alloc::string::String;
use alloc::vec::Vec;
use serde::{Serialize, Deserialize};

use super::*;

#[derive(Serialize, Deserialize, Debug, Clone, Default)]
pub struct ProcessEvent {
    #[serde(rename = "header")]
    pub header: EventHeader,
    #[serde(rename = "process_info")]
    pub process_info: ProcessInfo,
    #[serde(rename = "parent_process_id")]
    pub parent_process_id: ProcessId,
    #[serde(rename = "is_create")]
    pub is_create: bool,
}

