// Auto-generated by rustgen - DO NOT EDIT
// Source: types.go

#![allow(non_snake_case)]

extern crate alloc;

use alloc::string::String;
use alloc::vec::Vec;
use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[repr(u32)]
pub enum MessageType {
    BreakpointEvent = 1,
    ExceptionEvent = 2,
    MemoryAccessEvent = 3,
    SyscallEvent = 4,
    ProcessEvent = 5,
    ThreadEvent = 6,
    ModuleEvent = 7,
    DebugPrintEvent = 8,
    VmxExitEvent = 9,
    LogEvent = 10,
    Initialize = 100,
    Terminate = 101,
    Connect = 102,
    Disconnect = 103,
    AttachProcess = 104,
    DetachProcess = 105,
    StartProcess = 106,
    KillProcess = 107,
    SetBreakpoint = 108,
    RemoveBreakpoint = 109,
    EnableBreakpoint = 110,
    DisableBreakpoint = 111,
    ListBreakpoints = 112,
    Continue = 113,
    Pause = 114,
    StepInto = 115,
    StepOver = 116,
    StepOut = 117,
    ReadRegisters = 118,
    WriteRegisters = 119,
    ReadMemory = 120,
    WriteMemory = 121,
    GetProcessList = 122,
    GetThreadList = 123,
    GetModuleList = 124,
    GetCallStack = 125,
    Response = 200,
    Error = 201,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[repr(u32)]
pub enum BreakpointType {
    Software = 0,
    Hardware = 1,
    Hidden = 2,
    Ept = 3,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[repr(u32)]
pub enum DebugState {
    Running = 0,
    Paused = 1,
    Stepping = 2,
    Terminated = 3,
}

#[derive(Serialize, Deserialize, Debug, Clone, Default)]
pub struct RegisterState {
    #[serde(rename = "RAX")]
    pub rax: u64,
    #[serde(rename = "RBX")]
    pub rbx: u64,
    #[serde(rename = "RCX")]
    pub rcx: u64,
    #[serde(rename = "RDX")]
    pub rdx: u64,
    #[serde(rename = "RSI")]
    pub rsi: u64,
    #[serde(rename = "RDI")]
    pub rdi: u64,
    #[serde(rename = "RBP")]
    pub rbp: u64,
    #[serde(rename = "RSP")]
    pub rsp: u64,
    #[serde(rename = "R8")]
    pub r8: u64,
    #[serde(rename = "R9")]
    pub r9: u64,
    #[serde(rename = "R10")]
    pub r10: u64,
    #[serde(rename = "R11")]
    pub r11: u64,
    #[serde(rename = "R12")]
    pub r12: u64,
    #[serde(rename = "R13")]
    pub r13: u64,
    #[serde(rename = "R14")]
    pub r14: u64,
    #[serde(rename = "R15")]
    pub r15: u64,
    #[serde(rename = "RIP")]
    pub rip: u64,
    #[serde(rename = "RFLAGS")]
    pub rflags: u64,
    #[serde(rename = "CR0")]
    pub cr0: u64,
    #[serde(rename = "CR2")]
    pub cr2: u64,
    #[serde(rename = "CR3")]
    pub cr3: u64,
    #[serde(rename = "CR4")]
    pub cr4: u64,
    #[serde(rename = "DR0")]
    pub dr0: u64,
    #[serde(rename = "DR1")]
    pub dr1: u64,
    #[serde(rename = "DR2")]
    pub dr2: u64,
    #[serde(rename = "DR3")]
    pub dr3: u64,
    #[serde(rename = "DR6")]
    pub dr6: u64,
    #[serde(rename = "DR7")]
    pub dr7: u64,
    #[serde(rename = "GDTR")]
    pub gdtr: u64,
    #[serde(rename = "GSBase")]
    pub gsbase: u64,
    #[serde(rename = "FSBase")]
    pub fsbase: u64,
}

#[derive(Serialize, Deserialize, Debug, Clone, Default)]
pub struct ProcessInfo {
    #[serde(rename = "process_id")]
    pub process_id: u32,
    #[serde(rename = "image_name")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub image_name: Option<String>,
    #[serde(rename = "base_address")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub base_address: Option<String>,
    #[serde(rename = "size")]
    pub size: u64,
    #[serde(rename = "cr3")]
    pub cr3: u64,
}

#[derive(Serialize, Deserialize, Debug, Clone, Default)]
pub struct ThreadInfo {
    #[serde(rename = "thread_id")]
    pub thread_id: u32,
    #[serde(rename = "process_id")]
    pub process_id: u32,
    #[serde(rename = "start_address")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub start_address: Option<String>,
    #[serde(rename = "teb")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub teb: Option<String>,
    #[serde(rename = "state")]
    pub state: u32,
}

#[derive(Serialize, Deserialize, Debug, Clone, Default)]
pub struct ModuleInfo {
    #[serde(rename = "base_address")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub base_address: Option<String>,
    #[serde(rename = "size")]
    pub size: u64,
    #[serde(rename = "name")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "path")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub path: Option<String>,
}

#[derive(Serialize, Deserialize, Debug, Clone, Default)]
pub struct BreakpointInfo {
    #[serde(rename = "id")]
    pub id: u64,
    #[serde(rename = "address")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub address: Option<String>,
    #[serde(rename = "type")]
    pub bp_type: i32,
    #[serde(rename = "process_id")]
    pub process_id: u32,
    #[serde(rename = "enabled")]
    pub enabled: bool,
    #[serde(rename = "hit_count")]
    pub hit_count: u64,
}

#[derive(Serialize, Deserialize, Debug, Clone, Default)]
pub struct BreakpointEvent {
    #[serde(rename = "process_id")]
    pub process_id: u32,
    #[serde(rename = "thread_id")]
    pub thread_id: u32,
    #[serde(rename = "core_id")]
    pub core_id: u32,
    #[serde(rename = "address")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub address: Option<String>,
    #[serde(rename = "breakpoint_id")]
    pub breakpoint_id: u64,
    #[serde(rename = "registers")]
    pub registers: RegisterState,
}

#[derive(Serialize, Deserialize, Debug, Clone, Default)]
pub struct ExceptionEvent {
    #[serde(rename = "process_id")]
    pub process_id: u32,
    #[serde(rename = "thread_id")]
    pub thread_id: u32,
    #[serde(rename = "core_id")]
    pub core_id: u32,
    #[serde(rename = "exception_code")]
    pub exception_code: u32,
    #[serde(rename = "address")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub address: Option<String>,
    #[serde(rename = "error_code")]
    pub error_code: u64,
    #[serde(rename = "registers")]
    pub registers: RegisterState,
}

#[derive(Serialize, Deserialize, Debug, Clone, Default)]
pub struct DebugPrintEvent {
    #[serde(rename = "process_id")]
    pub process_id: u32,
    #[serde(rename = "thread_id")]
    pub thread_id: u32,
    #[serde(rename = "core_id")]
    pub core_id: u32,
    #[serde(rename = "message")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub message: Option<String>,
    #[serde(rename = "level")]
    pub level: u32,
}

#[derive(Serialize, Deserialize, Debug, Clone, Default)]
pub struct SyscallEvent {
    #[serde(rename = "process_id")]
    pub process_id: u32,
    #[serde(rename = "thread_id")]
    pub thread_id: u32,
    #[serde(rename = "core_id")]
    pub core_id: u32,
    #[serde(rename = "syscall_number")]
    pub syscall_number: u64,
    #[serde(rename = "rax")]
    pub rax: u64,
    #[serde(rename = "rcx")]
    pub rcx: u64,
    #[serde(rename = "rdx")]
    pub rdx: u64,
    #[serde(rename = "r8")]
    pub r8: u64,
    #[serde(rename = "r9")]
    pub r9: u64,
    #[serde(rename = "r10")]
    pub r10: u64,
    #[serde(rename = "rsp")]
    pub rsp: u64,
}

#[derive(Serialize, Deserialize, Debug)]
pub struct Response<T: Serialize> {
    pub success: bool,
    pub message: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub data: Option<T>,
}

pub type EmptyResponse = Response<()>;
