package Zydis


const(
ZYDIS_FORMATTER_H =  //col:33
ZYDIS_RUNTIME_ADDRESS_NONE = (ZyanU64)(-1) //col:53
)

const(
    ZYDIS_FORMATTER_STYLE_ATT = 1  //col:71
    ZYDIS_FORMATTER_STYLE_INTEL = 2  //col:75
    ZYDIS_FORMATTER_STYLE_INTEL_MASM = 3  //col:82
    ZYDIS_FORMATTER_STYLE_MAX_VALUE  =  ZYDIS_FORMATTER_STYLE_INTEL_MASM  //col:87
    ZYDIS_FORMATTER_STYLE_REQUIRED_BITS  =  ZYAN_BITS_TO_REPRESENT(ZYDIS_FORMATTER_STYLE_MAX_VALUE)  //col:91
)


const(
    ZYDIS_FORMATTER_PROP_FORCE_SIZE = 1  //col:114
    ZYDIS_FORMATTER_PROP_FORCE_SEGMENT = 2  //col:121
    ZYDIS_FORMATTER_PROP_FORCE_RELATIVE_BRANCHES = 3  //col:129
    ZYDIS_FORMATTER_PROP_FORCE_RELATIVE_RIPREL = 4  //col:137
    ZYDIS_FORMATTER_PROP_PRINT_BRANCH_SIZE = 5  //col:146
    ZYDIS_FORMATTER_PROP_DETAILED_PREFIXES = 6  //col:154
    ZYDIS_FORMATTER_PROP_ADDR_BASE = 7  //col:163
    ZYDIS_FORMATTER_PROP_ADDR_SIGNEDNESS = 8  //col:168
    ZYDIS_FORMATTER_PROP_ADDR_PADDING_ABSOLUTE = 9  //col:176
    ZYDIS_FORMATTER_PROP_ADDR_PADDING_RELATIVE = 10  //col:184
    ZYDIS_FORMATTER_PROP_DISP_BASE = 11  //col:191
    ZYDIS_FORMATTER_PROP_DISP_SIGNEDNESS = 12  //col:195
    ZYDIS_FORMATTER_PROP_DISP_PADDING = 13  //col:202
    ZYDIS_FORMATTER_PROP_IMM_BASE = 14  //col:209
    ZYDIS_FORMATTER_PROP_IMM_SIGNEDNESS = 15  //col:216
    ZYDIS_FORMATTER_PROP_IMM_PADDING = 16  //col:224
    ZYDIS_FORMATTER_PROP_UPPERCASE_PREFIXES = 17  //col:235
    ZYDIS_FORMATTER_PROP_UPPERCASE_MNEMONIC = 18  //col:241
    ZYDIS_FORMATTER_PROP_UPPERCASE_REGISTERS = 19  //col:247
    ZYDIS_FORMATTER_PROP_UPPERCASE_TYPECASTS = 20  //col:253
    ZYDIS_FORMATTER_PROP_UPPERCASE_DECORATORS = 21  //col:259
    ZYDIS_FORMATTER_PROP_DEC_PREFIX = 22  //col:273
    ZYDIS_FORMATTER_PROP_DEC_SUFFIX = 23  //col:282
    ZYDIS_FORMATTER_PROP_HEX_UPPERCASE = 24  //col:293
    ZYDIS_FORMATTER_PROP_HEX_PREFIX = 25  //col:302
    ZYDIS_FORMATTER_PROP_HEX_SUFFIX = 26  //col:311
    ZYDIS_FORMATTER_PROP_MAX_VALUE  =  ZYDIS_FORMATTER_PROP_HEX_SUFFIX  //col:318
    ZYDIS_FORMATTER_PROP_REQUIRED_BITS  =  ZYAN_BITS_TO_REPRESENT(ZYDIS_FORMATTER_PROP_MAX_VALUE)  //col:322
)


const(
    ZYDIS_NUMERIC_BASE_DEC = 1  //col:335
    ZYDIS_NUMERIC_BASE_HEX = 2  //col:339
    ZYDIS_NUMERIC_BASE_MAX_VALUE  =  ZYDIS_NUMERIC_BASE_HEX  //col:344
    ZYDIS_NUMERIC_BASE_REQUIRED_BITS  =  ZYAN_BITS_TO_REPRESENT(ZYDIS_NUMERIC_BASE_MAX_VALUE)  //col:348
)


const(
    ZYDIS_SIGNEDNESS_AUTO = 1  //col:362
    ZYDIS_SIGNEDNESS_SIGNED = 2  //col:366
    ZYDIS_SIGNEDNESS_UNSIGNED = 3  //col:370
    ZYDIS_SIGNEDNESS_MAX_VALUE  =  ZYDIS_SIGNEDNESS_UNSIGNED  //col:375
    ZYDIS_SIGNEDNESS_REQUIRED_BITS  =  ZYAN_BITS_TO_REPRESENT(ZYDIS_SIGNEDNESS_MAX_VALUE)  //col:379
)


const(
    ZYDIS_PADDING_DISABLED  =  0  //col:392
    ZYDIS_PADDING_AUTO      =  (-1)  //col:397
    ZYDIS_PADDING_MAX_VALUE  =  ZYDIS_PADDING_AUTO  //col:402
    ZYDIS_PADDING_REQUIRED_BITS  =  ZYAN_BITS_TO_REPRESENT(ZYDIS_PADDING_MAX_VALUE)  //col:406
)


const(
    ZYDIS_FORMATTER_FUNC_PRE_INSTRUCTION = 1  //col:428
    ZYDIS_FORMATTER_FUNC_POST_INSTRUCTION = 2  //col:432
    ZYDIS_FORMATTER_FUNC_FORMAT_INSTRUCTION = 3  //col:443
    ZYDIS_FORMATTER_FUNC_PRE_OPERAND = 4  //col:452
    ZYDIS_FORMATTER_FUNC_POST_OPERAND = 5  //col:456
    ZYDIS_FORMATTER_FUNC_FORMAT_OPERAND_REG = 6  //col:463
    ZYDIS_FORMATTER_FUNC_FORMAT_OPERAND_MEM = 7  //col:471
    ZYDIS_FORMATTER_FUNC_FORMAT_OPERAND_PTR = 8  //col:475
    ZYDIS_FORMATTER_FUNC_FORMAT_OPERAND_IMM = 9  //col:483
    ZYDIS_FORMATTER_FUNC_PRINT_MNEMONIC = 10  //col:492
    ZYDIS_FORMATTER_FUNC_PRINT_REGISTER = 11  //col:499
    ZYDIS_FORMATTER_FUNC_PRINT_ADDRESS_ABS = 12  //col:511
    ZYDIS_FORMATTER_FUNC_PRINT_ADDRESS_REL = 13  //col:518
    ZYDIS_FORMATTER_FUNC_PRINT_DISP = 14  //col:526
    ZYDIS_FORMATTER_FUNC_PRINT_IMM = 15  //col:537
    ZYDIS_FORMATTER_FUNC_PRINT_TYPECAST = 16  //col:546
    ZYDIS_FORMATTER_FUNC_PRINT_SEGMENT = 17  //col:550
    ZYDIS_FORMATTER_FUNC_PRINT_PREFIXES = 18  //col:554
    ZYDIS_FORMATTER_FUNC_PRINT_DECORATOR = 19  //col:559
    ZYDIS_FORMATTER_FUNC_MAX_VALUE  =  ZYDIS_FORMATTER_FUNC_PRINT_DECORATOR  //col:566
    ZYDIS_FORMATTER_FUNC_REQUIRED_BITS  =  ZYAN_BITS_TO_REPRESENT(ZYDIS_FORMATTER_FUNC_MAX_VALUE)  //col:570
)


const(
    ZYDIS_DECORATOR_INVALID = 1  //col:582
    ZYDIS_DECORATOR_MASK = 2  //col:586
    ZYDIS_DECORATOR_BC = 3  //col:590
    ZYDIS_DECORATOR_RC = 4  //col:594
    ZYDIS_DECORATOR_SAE = 5  //col:598
    ZYDIS_DECORATOR_SWIZZLE = 6  //col:602
    ZYDIS_DECORATOR_CONVERSION = 7  //col:606
    ZYDIS_DECORATOR_EH = 8  //col:610
    ZYDIS_DECORATOR_MAX_VALUE  =  ZYDIS_DECORATOR_EH  //col:615
    ZYDIS_DECORATOR_REQUIRED_BITS  =  ZYAN_BITS_TO_REPRESENT(ZYDIS_DECORATOR_MAX_VALUE)  //col:619
)



type (
Formatter interface{
    ZYDIS_FORMATTER_STYLE_REQUIRED_BITS = ZYAN_BITS_TO_REPRESENT()(ok bool)//col:92
    ZYDIS_FORMATTER_PROP_REQUIRED_BITS = ZYAN_BITS_TO_REPRESENT()(ok bool)//col:323
    ZYDIS_NUMERIC_BASE_REQUIRED_BITS = ZYAN_BITS_TO_REPRESENT()(ok bool)//col:349
    ZYDIS_SIGNEDNESS_REQUIRED_BITS = ZYAN_BITS_TO_REPRESENT()(ok bool)//col:380
    ZYDIS_PADDING_AUTO     = ()(ok bool)//col:407
    ZYDIS_FORMATTER_FUNC_REQUIRED_BITS = ZYAN_BITS_TO_REPRESENT()(ok bool)//col:571
    ZYDIS_DECORATOR_REQUIRED_BITS = ZYAN_BITS_TO_REPRESENT()(ok bool)//col:620
typedef ZyanStatus ()(ok bool)//col:936
ZYDIS_EXPORT ZyanStatus ZydisFormatterInit()(ok bool)//col:1176
}

)

func NewFormatter() { return & formatter{} }

func (f *formatter)    ZYDIS_FORMATTER_STYLE_REQUIRED_BITS = ZYAN_BITS_TO_REPRESENT()(ok bool){//col:92


return true
}


func (f *formatter)    ZYDIS_FORMATTER_PROP_REQUIRED_BITS = ZYAN_BITS_TO_REPRESENT()(ok bool){//col:323


return true
}


func (f *formatter)    ZYDIS_NUMERIC_BASE_REQUIRED_BITS = ZYAN_BITS_TO_REPRESENT()(ok bool){//col:349


return true
}


func (f *formatter)    ZYDIS_SIGNEDNESS_REQUIRED_BITS = ZYAN_BITS_TO_REPRESENT()(ok bool){//col:380


return true
}


func (f *formatter)    ZYDIS_PADDING_AUTO     = ()(ok bool){//col:407




return true
}


func (f *formatter)    ZYDIS_FORMATTER_FUNC_REQUIRED_BITS = ZYAN_BITS_TO_REPRESENT()(ok bool){//col:571


return true
}


func (f *formatter)    ZYDIS_DECORATOR_REQUIRED_BITS = ZYAN_BITS_TO_REPRESENT()(ok bool){//col:620


return true
}


func (f *formatter)typedef ZyanStatus ()(ok bool){//col:936

























































return true
}


func (f *formatter)ZYDIS_EXPORT ZyanStatus ZydisFormatterInit()(ok bool){//col:1176































return true
}




