package Zydis
//back\HyperDbgDev\hyperdbg\dependencies\zydis\include\Zydis\Status.h.back

const(
ZYDIS_STATUS_H =  //col:1
ZYAN_MODULE_ZYDIS =   0x002 //col:2
ZYDIS_STATUS_NO_MORE_DATA = ZYAN_MAKE_STATUS(1, ZYAN_MODULE_ZYDIS, 0x00) //col:3
ZYDIS_STATUS_DECODING_ERROR = ZYAN_MAKE_STATUS(1, ZYAN_MODULE_ZYDIS, 0x01) //col:5
ZYDIS_STATUS_INSTRUCTION_TOO_LONG = ZYAN_MAKE_STATUS(1, ZYAN_MODULE_ZYDIS, 0x02) //col:7
ZYDIS_STATUS_BAD_REGISTER = ZYAN_MAKE_STATUS(1, ZYAN_MODULE_ZYDIS, 0x03) //col:9
ZYDIS_STATUS_ILLEGAL_LOCK = ZYAN_MAKE_STATUS(1, ZYAN_MODULE_ZYDIS, 0x04) //col:11
ZYDIS_STATUS_ILLEGAL_LEGACY_PFX = ZYAN_MAKE_STATUS(1, ZYAN_MODULE_ZYDIS, 0x05) //col:13
ZYDIS_STATUS_ILLEGAL_REX = ZYAN_MAKE_STATUS(1, ZYAN_MODULE_ZYDIS, 0x06) //col:15
ZYDIS_STATUS_INVALID_MAP = ZYAN_MAKE_STATUS(1, ZYAN_MODULE_ZYDIS, 0x07) //col:17
ZYDIS_STATUS_MALFORMED_EVEX = ZYAN_MAKE_STATUS(1, ZYAN_MODULE_ZYDIS, 0x08) //col:19
ZYDIS_STATUS_MALFORMED_MVEX = ZYAN_MAKE_STATUS(1, ZYAN_MODULE_ZYDIS, 0x09) //col:21
ZYDIS_STATUS_INVALID_MASK = ZYAN_MAKE_STATUS(1, ZYAN_MODULE_ZYDIS, 0x0A) //col:23
ZYDIS_STATUS_SKIP_TOKEN = ZYAN_MAKE_STATUS(0, ZYAN_MODULE_ZYDIS, 0x0B) //col:25
)


