package Zycore

//binding\codespace\gui\sdk\HyperDbgDev\hyperdbg\dependencies\zydis\dependencies\zycore\include\Zycore\Status.h.back

const (
	ZYCORE_STATUS_H = //col:1
	ZYAN_MAKE_STATUS(error, module, code) = (
ZyanStatus
)((((error) & 0x01) << 31) | (((module) & 0x7FF) << 20) | ((code) & 0xFFFFF)) //col:2
ZYAN_SUCCESS(status) = (!((status) & 0x80000000)) //col:4
ZYAN_FAILED(status) = ((status) & 0x80000000) //col:6
ZYAN_CHECK(status) = do { const ZyanStatus status_047620348 = (status); if (!ZYAN_SUCCESS(status_047620348)) { return status_047620348; } } while (0) //col:8
ZYAN_STATUS_MODULE(status) = (((status) >> 20) & 0x7FF) //col:17
ZYAN_STATUS_CODE(status) = ((status) & 0xFFFFF) //col:19
ZYAN_MODULE_ZYCORE = 0x001                      //col:21
ZYAN_MODULE_ARGPARSE = 0x003 //col:22
ZYAN_MODULE_USER = 0x3FF     //col:23
ZYAN_STATUS_SUCCESS = ZYAN_MAKE_STATUS(0, ZYAN_MODULE_ZYCORE, 0x00) //col:24
ZYAN_STATUS_FAILED = ZYAN_MAKE_STATUS(1, ZYAN_MODULE_ZYCORE, 0x01) //col:26
ZYAN_STATUS_TRUE = ZYAN_MAKE_STATUS(0, ZYAN_MODULE_ZYCORE, 0x02) //col:28
ZYAN_STATUS_FALSE = ZYAN_MAKE_STATUS(0, ZYAN_MODULE_ZYCORE, 0x03) //col:30
ZYAN_STATUS_INVALID_ARGUMENT = ZYAN_MAKE_STATUS(1, ZYAN_MODULE_ZYCORE, 0x04) //col:32
ZYAN_STATUS_INVALID_OPERATION = ZYAN_MAKE_STATUS(1, ZYAN_MODULE_ZYCORE, 0x05) //col:34
ZYAN_STATUS_ACCESS_DENIED = ZYAN_MAKE_STATUS(1, ZYAN_MODULE_ZYCORE, 0x06) //col:36
ZYAN_STATUS_NOT_FOUND = ZYAN_MAKE_STATUS(1, ZYAN_MODULE_ZYCORE, 0x07) //col:38
ZYAN_STATUS_OUT_OF_RANGE = ZYAN_MAKE_STATUS(1, ZYAN_MODULE_ZYCORE, 0x08) //col:40
ZYAN_STATUS_INSUFFICIENT_BUFFER_SIZE = ZYAN_MAKE_STATUS(1, ZYAN_MODULE_ZYCORE, 0x09) //col:42
ZYAN_STATUS_NOT_ENOUGH_MEMORY = ZYAN_MAKE_STATUS(1, ZYAN_MODULE_ZYCORE, 0x0A) //col:44
ZYAN_STATUS_BAD_SYSTEMCALL = ZYAN_MAKE_STATUS(1, ZYAN_MODULE_ZYCORE, 0x0B) //col:46
ZYAN_STATUS_OUT_OF_RESOURCES = ZYAN_MAKE_STATUS(1, ZYAN_MODULE_ZYCORE, 0x0C) //col:48
ZYAN_STATUS_MISSING_DEPENDENCY = ZYAN_MAKE_STATUS(1, ZYAN_MODULE_ZYCORE, 0x0D) //col:50
ZYAN_STATUS_ARG_NOT_UNDERSTOOD = ZYAN_MAKE_STATUS(1, ZYAN_MODULE_ARGPARSE, 0x00) //col:52
ZYAN_STATUS_TOO_FEW_ARGS = ZYAN_MAKE_STATUS(1, ZYAN_MODULE_ARGPARSE, 0x01) //col:54
ZYAN_STATUS_TOO_MANY_ARGS = ZYAN_MAKE_STATUS(1, ZYAN_MODULE_ARGPARSE, 0x02) //col:56
ZYAN_STATUS_ARG_MISSES_VALUE = ZYAN_MAKE_STATUS(1, ZYAN_MODULE_ARGPARSE, 0x03) //col:58
ZYAN_STATUS_REQUIRED_ARG_MISSING = ZYAN_MAKE_STATUS(1, ZYAN_MODULE_ARGPARSE, 0x04) //col:60
)
