package sdk

import (
	"strings"

	"golang.org/x/exp/constraints"
)

// Code generated by GeneratedFile enum - DO NOT EDIT.

type HwdbgCommandsKind byte

const (
	HwClkKind HwdbgCommandsKind = iota
	InvalidHwdbgCommandsKind
)

func ConvertInteger2HwdbgCommandsKind[T constraints.Integer](v T) HwdbgCommandsKind {
	return HwdbgCommandsKind(v)
}

func (k HwdbgCommandsKind) AssertKind(kinds string) HwdbgCommandsKind {
	for _, kind := range k.Kinds() {
		if strings.ToLower(kinds) == strings.ToLower(kind.String()) {
			return kind
		}
	}
	return InvalidHwdbgCommandsKind
}

func (k HwdbgCommandsKind) String() string {
	switch k {
	case HwClkKind:
		return "HwClk"
	default:
		return "InvalidHwdbgCommandsKind"
	}
}

func (k HwdbgCommandsKind) Keys() []string {
	return []string{
		"HwClk",
	}
}

func (k HwdbgCommandsKind) Kinds() []HwdbgCommandsKind {
	return []HwdbgCommandsKind{
		HwClkKind,
	}
}

func (k HwdbgCommandsKind) SvgFileName() string {
	switch k {
	case HwClkKind:
		return "HwClk"
	default:
		return "InvalidHwdbgCommandsKind"
	}
}
