// Code generated by bindgen. DO NOT EDIT.
package sdk

import (
	"crypto/sha256"
	"encoding/base64"
	"fmt"
	"github.com/richardwilkes/toolbox/fatal"
	"github.com/richardwilkes/toolbox/xio/fs"
	"golang.org/x/sys/windows"
	"os"
	"path/filepath"
	"unsafe"

	"github.com/ddkwork/app/bindgen/bindlib"
)
func init() {
	dir, err := os.UserCacheDir()
	fatal.IfErr(err)
	dir = filepath.Join(dir, "unison", "dll_cache")
	fatal.IfErr(os.MkdirAll(dir, 0755))
	fatal.IfErr(windows.SetDllDirectory(dir))
	sha := sha256.Sum256(dllData)
	dllName := fmt.Sprintf("skia-%s.dll", base64.RawURLEncoding.EncodeToString(sha[:]))
	filePath := filepath.Join(dir, dllName)
	if !fs.FileExists(filePath) {
		fatal.IfErr(os.WriteFile(filePath, dllData, 0644))
	}
}

func init() {
	//windows.SetDllDirectory("../sdk.gen/SDK/Libraries")//seems need abs?
	//SetDllDirectory("D:\\workspace\\workspace\\branch\\gui\\sdk.gen\\SDK\\Libraries") // seems need abs?
}

const GengoLibraryName = "libhyperdbg" // todo

var GengoLibrary = bindlib.NewLibrary(GengoLibraryName)

// @brief enum for reasons why debuggee is paused
type DebuggeePausingReason int32

const (
	DEBUGGEE_PAUSING_REASON_NOT_PAUSED                            DebuggeePausingReason = 0
	DEBUGGEE_PAUSING_REASON_PAUSE                                 DebuggeePausingReason = 1
	DEBUGGEE_PAUSING_REASON_REQUEST_FROM_DEBUGGER                 DebuggeePausingReason = 2
	DEBUGGEE_PAUSING_REASON_DEBUGGEE_STEPPED                      DebuggeePausingReason = 3
	DEBUGGEE_PAUSING_REASON_DEBUGGEE_TRACKING_STEPPED             DebuggeePausingReason = 4
	DEBUGGEE_PAUSING_REASON_DEBUGGEE_SOFTWARE_BREAKPOINT_HIT      DebuggeePausingReason = 5
	DEBUGGEE_PAUSING_REASON_DEBUGGEE_HARDWARE_DEBUG_REGISTER_HIT  DebuggeePausingReason = 6
	DEBUGGEE_PAUSING_REASON_DEBUGGEE_CORE_SWITCHED                DebuggeePausingReason = 7
	DEBUGGEE_PAUSING_REASON_DEBUGGEE_PROCESS_SWITCHED             DebuggeePausingReason = 8
	DEBUGGEE_PAUSING_REASON_DEBUGGEE_THREAD_SWITCHED              DebuggeePausingReason = 9
	DEBUGGEE_PAUSING_REASON_DEBUGGEE_COMMAND_EXECUTION_FINISHED   DebuggeePausingReason = 10
	DEBUGGEE_PAUSING_REASON_DEBUGGEE_EVENT_TRIGGERED              DebuggeePausingReason = 11
	DEBUGGEE_PAUSING_REASON_DEBUGGEE_STARTING_MODULE_LOADED       DebuggeePausingReason = 12
	DEBUGGEE_PAUSING_REASON_DEBUGGEE_GENERAL_DEBUG_BREAK          DebuggeePausingReason = 13
	DEBUGGEE_PAUSING_REASON_DEBUGGEE_GENERAL_THREAD_INTERCEPTED   DebuggeePausingReason = 14
	DEBUGGEE_PAUSING_REASON_HARDWARE_BASED_DEBUGGEE_GENERAL_BREAK DebuggeePausingReason = 15
)

// @brief enum for requested action for HyperDbg packet
type DebuggerRemotePacketRequestedAction int32

const (
	DEBUGGER_REMOTE_PACKET_REQUESTED_ACTION_ON_USER_MODE_PAUSE                            DebuggerRemotePacketRequestedAction = 1
	DEBUGGER_REMOTE_PACKET_REQUESTED_ACTION_ON_USER_MODE_DO_NOT_READ_ANY_PACKET           DebuggerRemotePacketRequestedAction = 2
	DEBUGGER_REMOTE_PACKET_REQUESTED_ACTION_ON_USER_MODE_DEBUGGER_VERSION                 DebuggerRemotePacketRequestedAction = 3
	DEBUGGER_REMOTE_PACKET_PING_AND_SEND_SUPPORTED_VERSION                                DebuggerRemotePacketRequestedAction = 4
	DEBUGGER_REMOTE_PACKET_REQUESTED_ACTION_ON_VMX_ROOT_MODE_STEP                         DebuggerRemotePacketRequestedAction = 5
	DEBUGGER_REMOTE_PACKET_REQUESTED_ACTION_ON_VMX_ROOT_MODE_CONTINUE                     DebuggerRemotePacketRequestedAction = 6
	DEBUGGER_REMOTE_PACKET_REQUESTED_ACTION_ON_VMX_ROOT_MODE_CLOSE_AND_UNLOAD_DEBUGGEE    DebuggerRemotePacketRequestedAction = 7
	DEBUGGER_REMOTE_PACKET_REQUESTED_ACTION_ON_VMX_ROOT_MODE_CHANGE_CORE                  DebuggerRemotePacketRequestedAction = 8
	DEBUGGER_REMOTE_PACKET_REQUESTED_ACTION_ON_VMX_ROOT_MODE_FLUSH_BUFFERS                DebuggerRemotePacketRequestedAction = 9
	DEBUGGER_REMOTE_PACKET_REQUESTED_ACTION_ON_VMX_ROOT_MODE_CALLSTACK                    DebuggerRemotePacketRequestedAction = 10
	DEBUGGER_REMOTE_PACKET_REQUESTED_ACTION_ON_VMX_ROOT_MODE_TEST_QUERY                   DebuggerRemotePacketRequestedAction = 11
	DEBUGGER_REMOTE_PACKET_REQUESTED_ACTION_ON_VMX_ROOT_MODE_CHANGE_PROCESS               DebuggerRemotePacketRequestedAction = 12
	DEBUGGER_REMOTE_PACKET_REQUESTED_ACTION_ON_VMX_ROOT_MODE_CHANGE_THREAD                DebuggerRemotePacketRequestedAction = 13
	DEBUGGER_REMOTE_PACKET_REQUESTED_ACTION_ON_VMX_ROOT_RUN_SCRIPT                        DebuggerRemotePacketRequestedAction = 14
	DEBUGGER_REMOTE_PACKET_REQUESTED_ACTION_ON_VMX_ROOT_USER_INPUT_BUFFER                 DebuggerRemotePacketRequestedAction = 15
	DEBUGGER_REMOTE_PACKET_REQUESTED_ACTION_ON_VMX_ROOT_SEARCH_QUERY                      DebuggerRemotePacketRequestedAction = 16
	DEBUGGER_REMOTE_PACKET_REQUESTED_ACTION_ON_VMX_ROOT_REGISTER_EVENT                    DebuggerRemotePacketRequestedAction = 17
	DEBUGGER_REMOTE_PACKET_REQUESTED_ACTION_ON_VMX_ROOT_ADD_ACTION_TO_EVENT               DebuggerRemotePacketRequestedAction = 18
	DEBUGGER_REMOTE_PACKET_REQUESTED_ACTION_ON_VMX_ROOT_QUERY_AND_MODIFY_EVENT            DebuggerRemotePacketRequestedAction = 19
	DEBUGGER_REMOTE_PACKET_REQUESTED_ACTION_ON_VMX_ROOT_READ_REGISTERS                    DebuggerRemotePacketRequestedAction = 20
	DEBUGGER_REMOTE_PACKET_REQUESTED_ACTION_ON_VMX_ROOT_READ_MEMORY                       DebuggerRemotePacketRequestedAction = 21
	DEBUGGER_REMOTE_PACKET_REQUESTED_ACTION_ON_VMX_ROOT_EDIT_MEMORY                       DebuggerRemotePacketRequestedAction = 22
	DEBUGGER_REMOTE_PACKET_REQUESTED_ACTION_ON_VMX_ROOT_BP                                DebuggerRemotePacketRequestedAction = 23
	DEBUGGER_REMOTE_PACKET_REQUESTED_ACTION_ON_VMX_ROOT_LIST_OR_MODIFY_BREAKPOINTS        DebuggerRemotePacketRequestedAction = 24
	DEBUGGER_REMOTE_PACKET_REQUESTED_ACTION_ON_VMX_ROOT_SYMBOL_RELOAD                     DebuggerRemotePacketRequestedAction = 25
	DEBUGGER_REMOTE_PACKET_REQUESTED_ACTION_ON_VMX_ROOT_QUERY_PA2VA_AND_VA2PA             DebuggerRemotePacketRequestedAction = 26
	DEBUGGER_REMOTE_PACKET_REQUESTED_ACTION_ON_VMX_ROOT_SYMBOL_QUERY_PTE                  DebuggerRemotePacketRequestedAction = 27
	DEBUGGER_REMOTE_PACKET_REQUESTED_ACTION_ON_VMX_ROOT_SET_SHORT_CIRCUITING_STATE        DebuggerRemotePacketRequestedAction = 28
	DEBUGGER_REMOTE_PACKET_REQUESTED_ACTION_ON_VMX_ROOT_INJECT_PAGE_FAULT                 DebuggerRemotePacketRequestedAction = 29
	DEBUGGER_REMOTE_PACKET_REQUESTED_ACTION_NO_ACTION                                     DebuggerRemotePacketRequestedAction = 30
	DEBUGGER_REMOTE_PACKET_REQUESTED_ACTION_DEBUGGEE_STARTED                              DebuggerRemotePacketRequestedAction = 31
	DEBUGGER_REMOTE_PACKET_REQUESTED_ACTION_DEBUGGEE_LOGGING_MECHANISM                    DebuggerRemotePacketRequestedAction = 32
	DEBUGGER_REMOTE_PACKET_REQUESTED_ACTION_DEBUGGEE_PAUSED_AND_CURRENT_INSTRUCTION       DebuggerRemotePacketRequestedAction = 33
	DEBUGGER_REMOTE_PACKET_REQUESTED_ACTION_DEBUGGEE_RESULT_OF_CHANGING_CORE              DebuggerRemotePacketRequestedAction = 34
	DEBUGGER_REMOTE_PACKET_REQUESTED_ACTION_DEBUGGEE_RESULT_OF_CHANGING_PROCESS           DebuggerRemotePacketRequestedAction = 35
	DEBUGGER_REMOTE_PACKET_REQUESTED_ACTION_DEBUGGEE_RESULT_OF_CHANGING_THREAD            DebuggerRemotePacketRequestedAction = 36
	DEBUGGER_REMOTE_PACKET_REQUESTED_ACTION_DEBUGGEE_RESULT_OF_RUNNING_SCRIPT             DebuggerRemotePacketRequestedAction = 37
	DEBUGGER_REMOTE_PACKET_REQUESTED_ACTION_DEBUGGEE_RESULT_OF_FORMATS                    DebuggerRemotePacketRequestedAction = 38
	DEBUGGER_REMOTE_PACKET_REQUESTED_ACTION_DEBUGGEE_RESULT_OF_FLUSH                      DebuggerRemotePacketRequestedAction = 39
	DEBUGGER_REMOTE_PACKET_REQUESTED_ACTION_DEBUGGEE_RESULT_OF_CALLSTACK                  DebuggerRemotePacketRequestedAction = 40
	DEBUGGER_REMOTE_PACKET_REQUESTED_ACTION_DEBUGGEE_RESULT_TEST_QUERY                    DebuggerRemotePacketRequestedAction = 41
	DEBUGGER_REMOTE_PACKET_REQUESTED_ACTION_DEBUGGEE_RESULT_OF_REGISTERING_EVENT          DebuggerRemotePacketRequestedAction = 42
	DEBUGGER_REMOTE_PACKET_REQUESTED_ACTION_DEBUGGEE_RESULT_OF_ADDING_ACTION_TO_EVENT     DebuggerRemotePacketRequestedAction = 43
	DEBUGGER_REMOTE_PACKET_REQUESTED_ACTION_DEBUGGEE_RESULT_OF_QUERY_AND_MODIFY_EVENT     DebuggerRemotePacketRequestedAction = 44
	DEBUGGER_REMOTE_PACKET_REQUESTED_ACTION_DEBUGGEE_RESULT_OF_SHORT_CIRCUITING_EVENT     DebuggerRemotePacketRequestedAction = 45
	DEBUGGER_REMOTE_PACKET_REQUESTED_ACTION_DEBUGGEE_RESULT_OF_READING_REGISTERS          DebuggerRemotePacketRequestedAction = 46
	DEBUGGER_REMOTE_PACKET_REQUESTED_ACTION_DEBUGGEE_RESULT_OF_READING_MEMORY             DebuggerRemotePacketRequestedAction = 47
	DEBUGGER_REMOTE_PACKET_REQUESTED_ACTION_DEBUGGEE_RESULT_OF_EDITING_MEMORY             DebuggerRemotePacketRequestedAction = 48
	DEBUGGER_REMOTE_PACKET_REQUESTED_ACTION_DEBUGGEE_RESULT_OF_BP                         DebuggerRemotePacketRequestedAction = 49
	DEBUGGER_REMOTE_PACKET_REQUESTED_ACTION_DEBUGGEE_RESULT_OF_SHORT_CIRCUITING_STATE     DebuggerRemotePacketRequestedAction = 50
	DEBUGGER_REMOTE_PACKET_REQUESTED_ACTION_DEBUGGEE_RESULT_OF_LIST_OR_MODIFY_BREAKPOINTS DebuggerRemotePacketRequestedAction = 51
	DEBUGGER_REMOTE_PACKET_REQUESTED_ACTION_DEBUGGEE_UPDATE_SYMBOL_INFO                   DebuggerRemotePacketRequestedAction = 52
	DEBUGGER_REMOTE_PACKET_REQUESTED_ACTION_DEBUGGEE_RELOAD_SYMBOL_FINISHED               DebuggerRemotePacketRequestedAction = 53
	DEBUGGER_REMOTE_PACKET_REQUESTED_ACTION_DEBUGGEE_RELOAD_SEARCH_QUERY                  DebuggerRemotePacketRequestedAction = 54
	DEBUGGER_REMOTE_PACKET_REQUESTED_ACTION_DEBUGGEE_RESULT_OF_PTE                        DebuggerRemotePacketRequestedAction = 55
	DEBUGGER_REMOTE_PACKET_REQUESTED_ACTION_DEBUGGEE_RESULT_OF_VA2PA_AND_PA2VA            DebuggerRemotePacketRequestedAction = 56
	DEBUGGER_REMOTE_PACKET_REQUESTED_ACTION_DEBUGGEE_RESULT_OF_BRINGING_PAGES_IN          DebuggerRemotePacketRequestedAction = 57
)

// @brief enum for different packet types in HyperDbg packets
//
// @warning used in hwdbg
type DebuggerRemotePacketType int32

const (
	DEBUGGER_REMOTE_PACKET_TYPE_DEBUGGER_TO_DEBUGGEE_EXECUTE_ON_VMX_ROOT  DebuggerRemotePacketType = 1
	DEBUGGER_REMOTE_PACKET_TYPE_DEBUGGER_TO_DEBUGGEE_EXECUTE_ON_USER_MODE DebuggerRemotePacketType = 2
	DEBUGGER_REMOTE_PACKET_TYPE_DEBUGGEE_TO_DEBUGGER                      DebuggerRemotePacketType = 3
	DEBUGGER_REMOTE_PACKET_TYPE_DEBUGGER_TO_DEBUGGEE_HARDWARE_LEVEL       DebuggerRemotePacketType = 4
	DEBUGGER_REMOTE_PACKET_TYPE_DEBUGGEE_TO_DEBUGGER_HARDWARE_LEVEL       DebuggerRemotePacketType = 5
)

// @brief Different levels of paging
type PagingLevel int32

const (
	PAGING_LEVEL_PAGE_TABLE                   PagingLevel = 0
	PAGING_LEVEL_PAGE_DIRECTORY               PagingLevel = 1
	PAGING_LEVEL_PAGE_DIRECTORY_POINTER_TABLE PagingLevel = 2
	PAGING_LEVEL_PAGE_MAP_LEVEL4              PagingLevel = 3
)

// @brief Inum of intentions for buffers (buffer tag)
type PoolAllocationIntention int32

const (
	TRACKING_HOOKED_PAGES                  PoolAllocationIntention = 0
	EXEC_TRAMPOLINE                        PoolAllocationIntention = 1
	SPLIT_2MB_PAGING_TO_4KB_PAGE           PoolAllocationIntention = 2
	DETOUR_HOOK_DETAILS                    PoolAllocationIntention = 3
	BREAKPOINT_DEFINITION_STRUCTURE        PoolAllocationIntention = 4
	PROCESS_THREAD_HOLDER                  PoolAllocationIntention = 5
	INSTANT_REGULAR_EVENT_BUFFER           PoolAllocationIntention = 6
	INSTANT_BIG_EVENT_BUFFER               PoolAllocationIntention = 7
	INSTANT_REGULAR_EVENT_ACTION_BUFFER    PoolAllocationIntention = 8
	INSTANT_BIG_EVENT_ACTION_BUFFER        PoolAllocationIntention = 9
	INSTANT_REGULAR_SAFE_BUFFER_FOR_EVENTS PoolAllocationIntention = 10
	INSTANT_BIG_SAFE_BUFFER_FOR_EVENTS     PoolAllocationIntention = 11
)

// ///////////////////////////////////////////////
type DebugRegisterType int32

const (
	BREAK_ON_INSTRUCTION_FETCH              DebugRegisterType = 0
	BREAK_ON_WRITE_ONLY                     DebugRegisterType = 1
	BREAK_ON_IO_READ_OR_WRITE_NOT_SUPPORTED DebugRegisterType = 2
	BREAK_ON_READ_AND_WRITE_BUT_NOT_FETCH   DebugRegisterType = 3
)

// ///////////////////////////////////////////////
type VmxExecutionMode int32

const (
	VMX_EXECUTION_MODE_NON_ROOT VmxExecutionMode = 0
	VMX_EXECUTION_MODE_ROOT     VmxExecutionMode = 1
)

// @brief Type of calling the event
type VmmCallbackEventCallingStageType int32

const (
	VMM_CALLBACK_CALLING_STAGE_INVALID_EVENT_EMULATION VmmCallbackEventCallingStageType = 0
	VMM_CALLBACK_CALLING_STAGE_PRE_EVENT_EMULATION     VmmCallbackEventCallingStageType = 1
	VMM_CALLBACK_CALLING_STAGE_POST_EVENT_EMULATION    VmmCallbackEventCallingStageType = 2
	VMM_CALLBACK_CALLING_STAGE_ALL_EVENT_EMULATION     VmmCallbackEventCallingStageType = 3
)

// @brief enum to query different process and thread interception mechanisms
type DebuggerThreadProcessTracing int32

const (
	DEBUGGER_THREAD_PROCESS_TRACING_INTERCEPT_CLOCK_INTERRUPTS_FOR_THREAD_CHANGE  DebuggerThreadProcessTracing = 0
	DEBUGGER_THREAD_PROCESS_TRACING_INTERCEPT_CLOCK_INTERRUPTS_FOR_PROCESS_CHANGE DebuggerThreadProcessTracing = 1
	DEBUGGER_THREAD_PROCESS_TRACING_INTERCEPT_CLOCK_DEBUG_REGISTER_INTERCEPTION   DebuggerThreadProcessTracing = 2
	DEBUGGER_THREAD_PROCESS_TRACING_INTERCEPT_CLOCK_WAITING_FOR_MOV_CR3_VM_EXITS  DebuggerThreadProcessTracing = 3
)

// @brief Type of transferring buffer between user-to-kernel
type NotifyType int32

const (
	IRP_BASED   NotifyType = 0
	EVENT_BASED NotifyType = 1
)

// @brief different type of memory addresses
type DebuggerHookMemoryType int32

const (
	DEBUGGER_MEMORY_HOOK_VIRTUAL_ADDRESS  DebuggerHookMemoryType = 0
	DEBUGGER_MEMORY_HOOK_PHYSICAL_ADDRESS DebuggerHookMemoryType = 1
)

// @brief Exceptions enum
type ExceptionVectors int32

const (
	EXCEPTION_VECTOR_DIVIDE_ERROR                      ExceptionVectors = 0
	EXCEPTION_VECTOR_DEBUG_BREAKPOINT                  ExceptionVectors = 1
	EXCEPTION_VECTOR_NMI                               ExceptionVectors = 2
	EXCEPTION_VECTOR_BREAKPOINT                        ExceptionVectors = 3
	EXCEPTION_VECTOR_OVERFLOW                          ExceptionVectors = 4
	EXCEPTION_VECTOR_BOUND_RANGE_EXCEEDED              ExceptionVectors = 5
	EXCEPTION_VECTOR_UNDEFINED_OPCODE                  ExceptionVectors = 6
	EXCEPTION_VECTOR_NO_MATH_COPROCESSOR               ExceptionVectors = 7
	EXCEPTION_VECTOR_DOUBLE_FAULT                      ExceptionVectors = 8
	EXCEPTION_VECTOR_RESERVED0                         ExceptionVectors = 9
	EXCEPTION_VECTOR_INVALID_TASK_SEGMENT_SELECTOR     ExceptionVectors = 10
	EXCEPTION_VECTOR_SEGMENT_NOT_PRESENT               ExceptionVectors = 11
	EXCEPTION_VECTOR_STACK_SEGMENT_FAULT               ExceptionVectors = 12
	EXCEPTION_VECTOR_GENERAL_PROTECTION_FAULT          ExceptionVectors = 13
	EXCEPTION_VECTOR_PAGE_FAULT                        ExceptionVectors = 14
	EXCEPTION_VECTOR_RESERVED1                         ExceptionVectors = 15
	EXCEPTION_VECTOR_MATH_FAULT                        ExceptionVectors = 16
	EXCEPTION_VECTOR_ALIGNMENT_CHECK                   ExceptionVectors = 17
	EXCEPTION_VECTOR_MACHINE_CHECK                     ExceptionVectors = 18
	EXCEPTION_VECTOR_SIMD_FLOATING_POINT_NUMERIC_ERROR ExceptionVectors = 19
	EXCEPTION_VECTOR_VIRTUAL_EXCEPTION                 ExceptionVectors = 20
	EXCEPTION_VECTOR_RESERVED2                         ExceptionVectors = 21
	EXCEPTION_VECTOR_RESERVED3                         ExceptionVectors = 22
	EXCEPTION_VECTOR_RESERVED4                         ExceptionVectors = 23
	EXCEPTION_VECTOR_RESERVED5                         ExceptionVectors = 24
	EXCEPTION_VECTOR_RESERVED6                         ExceptionVectors = 25
	EXCEPTION_VECTOR_RESERVED7                         ExceptionVectors = 26
	EXCEPTION_VECTOR_RESERVED8                         ExceptionVectors = 27
	EXCEPTION_VECTOR_RESERVED9                         ExceptionVectors = 28
	EXCEPTION_VECTOR_RESERVED10                        ExceptionVectors = 29
	EXCEPTION_VECTOR_RESERVED11                        ExceptionVectors = 30
	EXCEPTION_VECTOR_RESERVED12                        ExceptionVectors = 31
	APC_INTERRUPT                                      ExceptionVectors = 31
	DPC_INTERRUPT                                      ExceptionVectors = 47
	CLOCK_INTERRUPT                                    ExceptionVectors = 209
	IPI_INTERRUPT                                      ExceptionVectors = 225
	PMI_INTERRUPT                                      ExceptionVectors = 254
)

// @brief The status of triggering events
type VmmCallbackTriggeringEventStatusType int32

const (
	VMM_CALLBACK_TRIGGERING_EVENT_STATUS_SUCCESSFUL_NO_INITIALIZED VmmCallbackTriggeringEventStatusType = 0
	VMM_CALLBACK_TRIGGERING_EVENT_STATUS_SUCCESSFUL                VmmCallbackTriggeringEventStatusType = 0
	VMM_CALLBACK_TRIGGERING_EVENT_STATUS_SUCCESSFUL_IGNORE_EVENT   VmmCallbackTriggeringEventStatusType = 1
	VMM_CALLBACK_TRIGGERING_EVENT_STATUS_DEBUGGER_NOT_ENABLED      VmmCallbackTriggeringEventStatusType = 2
	VMM_CALLBACK_TRIGGERING_EVENT_STATUS_INVALID_EVENT_TYPE        VmmCallbackTriggeringEventStatusType = 3
)

// @brief enum to show type of all HyperDbg events
type VmmEventTypeEnum int32

const (
	HIDDEN_HOOK_READ_AND_WRITE_AND_EXECUTE VmmEventTypeEnum = 0
	HIDDEN_HOOK_READ_AND_WRITE             VmmEventTypeEnum = 1
	HIDDEN_HOOK_READ_AND_EXECUTE           VmmEventTypeEnum = 2
	HIDDEN_HOOK_WRITE_AND_EXECUTE          VmmEventTypeEnum = 3
	HIDDEN_HOOK_READ                       VmmEventTypeEnum = 4
	HIDDEN_HOOK_WRITE                      VmmEventTypeEnum = 5
	HIDDEN_HOOK_EXECUTE                    VmmEventTypeEnum = 6
	HIDDEN_HOOK_EXEC_DETOURS               VmmEventTypeEnum = 7
	HIDDEN_HOOK_EXEC_CC                    VmmEventTypeEnum = 8
	SYSCALL_HOOK_EFER_SYSCALL              VmmEventTypeEnum = 9
	SYSCALL_HOOK_EFER_SYSRET               VmmEventTypeEnum = 10
	CPUID_INSTRUCTION_EXECUTION            VmmEventTypeEnum = 11
	RDMSR_INSTRUCTION_EXECUTION            VmmEventTypeEnum = 12
	WRMSR_INSTRUCTION_EXECUTION            VmmEventTypeEnum = 13
	IN_INSTRUCTION_EXECUTION               VmmEventTypeEnum = 14
	OUT_INSTRUCTION_EXECUTION              VmmEventTypeEnum = 15
	EXCEPTION_OCCURRED                     VmmEventTypeEnum = 16
	EXTERNAL_INTERRUPT_OCCURRED            VmmEventTypeEnum = 17
	DEBUG_REGISTERS_ACCESSED               VmmEventTypeEnum = 18
	TSC_INSTRUCTION_EXECUTION              VmmEventTypeEnum = 19
	PMC_INSTRUCTION_EXECUTION              VmmEventTypeEnum = 20
	VMCALL_INSTRUCTION_EXECUTION           VmmEventTypeEnum = 21
	CONTROL_REGISTER_MODIFIED              VmmEventTypeEnum = 22
	CONTROL_REGISTER_READ                  VmmEventTypeEnum = 23
	CONTROL_REGISTER_3_MODIFIED            VmmEventTypeEnum = 24
	TRAP_EXECUTION_MODE_CHANGED            VmmEventTypeEnum = 25
	TRAP_EXECUTION_INSTRUCTION_TRACE       VmmEventTypeEnum = 26
)

// @brief Type of Actions
type DebuggerEventActionTypeEnum int32

const (
	BREAK_TO_DEBUGGER DebuggerEventActionTypeEnum = 0
	RUN_SCRIPT        DebuggerEventActionTypeEnum = 1
	RUN_CUSTOM_CODE   DebuggerEventActionTypeEnum = 2
)

// @brief Type of handling !syscall or !sysret
type DebuggerEventSyscallSysretType int32

const (
	DEBUGGER_EVENT_SYSCALL_SYSRET_SAFE_ACCESS_MEMORY DebuggerEventSyscallSysretType = 0
	DEBUGGER_EVENT_SYSCALL_SYSRET_HANDLE_ALL_UD      DebuggerEventSyscallSysretType = 1
)

// @brief Type of mode change traps
type DebuggerEventModeType int32

const (
	DEBUGGER_EVENT_MODE_TYPE_USER_MODE_AND_KERNEL_MODE DebuggerEventModeType = 1
	DEBUGGER_EVENT_MODE_TYPE_USER_MODE                 DebuggerEventModeType = 3
	DEBUGGER_EVENT_MODE_TYPE_KERNEL_MODE               DebuggerEventModeType = 0
)

// @brief Type of tracing events
type DebuggerEventTraceType int32

const (
	DEBUGGER_EVENT_TRACE_TYPE_INVALID                 DebuggerEventTraceType = 0
	DEBUGGER_EVENT_TRACE_TYPE_STEP_IN                 DebuggerEventTraceType = 1
	DEBUGGER_EVENT_TRACE_TYPE_STEP_OUT                DebuggerEventTraceType = 2
	DEBUGGER_EVENT_TRACE_TYPE_INSTRUMENTATION_STEP_IN DebuggerEventTraceType = 3
)

// @brief different types of modifying events request (enable/disable/clear)
type DebuggerModifyEventsType int32

const (
	DEBUGGER_MODIFY_EVENTS_QUERY_STATE DebuggerModifyEventsType = 0
	DEBUGGER_MODIFY_EVENTS_ENABLE      DebuggerModifyEventsType = 1
	DEBUGGER_MODIFY_EVENTS_DISABLE     DebuggerModifyEventsType = 2
	DEBUGGER_MODIFY_EVENTS_CLEAR       DebuggerModifyEventsType = 3
)

// @brief Things to consider when applying resources
type ProtectedHvResourcesPassingOvers int32

const (
	PASSING_OVER_NONE                                  ProtectedHvResourcesPassingOvers = 0
	PASSING_OVER_UD_EXCEPTIONS_FOR_SYSCALL_SYSRET_HOOK ProtectedHvResourcesPassingOvers = 1
	PASSING_OVER_EXCEPTION_EVENTS                      ProtectedHvResourcesPassingOvers = 2
	PASSING_OVER_INTERRUPT_EVENTS                      ProtectedHvResourcesPassingOvers = 3
	PASSING_OVER_TSC_EVENTS                            ProtectedHvResourcesPassingOvers = 4
	PASSING_OVER_MOV_TO_HW_DEBUG_REGS_EVENTS           ProtectedHvResourcesPassingOvers = 5
	PASSING_OVER_MOV_TO_CONTROL_REGS_EVENTS            ProtectedHvResourcesPassingOvers = 6
)

// @brief Type of protected (multi-used) resources
type ProtectedHvResourcesType int32

const (
	PROTECTED_HV_RESOURCES_EXCEPTION_BITMAP              ProtectedHvResourcesType = 0
	PROTECTED_HV_RESOURCES_EXTERNAL_INTERRUPT_EXITING    ProtectedHvResourcesType = 1
	PROTECTED_HV_RESOURCES_RDTSC_RDTSCP_EXITING          ProtectedHvResourcesType = 2
	PROTECTED_HV_RESOURCES_MOV_TO_DEBUG_REGISTER_EXITING ProtectedHvResourcesType = 3
	PROTECTED_HV_RESOURCES_MOV_CONTROL_REGISTER_EXITING  ProtectedHvResourcesType = 4
	PROTECTED_HV_RESOURCES_MOV_TO_CR3_EXITING            ProtectedHvResourcesType = 5
)

// @brief Different action of hwdbg
//
// @warning This file should be changed along with hwdbg files
type HwdbgActionEnums int32

const (
	HWDBG_ACTION_SEND_INSTANCE_INFO      HwdbgActionEnums = 1
	HWDBG_ACTION_CONFIGURE_SCRIPT_BUFFER HwdbgActionEnums = 2
)

// @brief Different responses come from hwdbg
//
// @warning This file should be changed along with hwdbg files
type HwdbgResponseEnums int32

const (
	HWDBG_RESPONSE_SUCCESS_OR_ERROR_MESSAGE HwdbgResponseEnums = 1
	HWDBG_RESPONSE_INSTANCE_INFO            HwdbgResponseEnums = 2
)

// @brief Different success or error codes in hwdbg
//
// @warning This file should be changed along with hwdbg files
type HwdbgSuccessOrErrorEnums int32

const (
	HWDBG_OPERATION_WAS_SUCCESSFUL HwdbgSuccessOrErrorEnums = 2147483647
	HWDBG_ERROR_INVALID_PACKET     HwdbgSuccessOrErrorEnums = 1
)

// @brief different modes of reconstruct requests
type ReversingMachineReconstructMemoryMode int32

const (
	REVERSING_MACHINE_RECONSTRUCT_MEMORY_MODE_UNKNOWN     ReversingMachineReconstructMemoryMode = 0
	REVERSING_MACHINE_RECONSTRUCT_MEMORY_MODE_USER_MODE   ReversingMachineReconstructMemoryMode = 1
	REVERSING_MACHINE_RECONSTRUCT_MEMORY_MODE_KERNEL_MODE ReversingMachineReconstructMemoryMode = 2
)

// @brief different types of reconstruct requests
type ReversingMachineReconstructMemoryType int32

const (
	REVERSING_MACHINE_RECONSTRUCT_MEMORY_TYPE_UNKNOWN     ReversingMachineReconstructMemoryType = 0
	REVERSING_MACHINE_RECONSTRUCT_MEMORY_TYPE_RECONSTRUCT ReversingMachineReconstructMemoryType = 1
	REVERSING_MACHINE_RECONSTRUCT_MEMORY_TYPE_PATTERN     ReversingMachineReconstructMemoryType = 2
)

// @brief different types of prealloc requests
type DebuggerPreallocCommandType int32

const (
	DEBUGGER_PREALLOC_COMMAND_TYPE_THREAD_INTERCEPTION DebuggerPreallocCommandType = 0
	DEBUGGER_PREALLOC_COMMAND_TYPE_MONITOR             DebuggerPreallocCommandType = 1
	DEBUGGER_PREALLOC_COMMAND_TYPE_EPTHOOK             DebuggerPreallocCommandType = 2
	DEBUGGER_PREALLOC_COMMAND_TYPE_EPTHOOK2            DebuggerPreallocCommandType = 3
	DEBUGGER_PREALLOC_COMMAND_TYPE_REGULAR_EVENT       DebuggerPreallocCommandType = 4
	DEBUGGER_PREALLOC_COMMAND_TYPE_BIG_EVENT           DebuggerPreallocCommandType = 5
	DEBUGGER_PREALLOC_COMMAND_TYPE_REGULAR_SAFE_BUFFER DebuggerPreallocCommandType = 6
	DEBUGGER_PREALLOC_COMMAND_TYPE_BIG_SAFE_BUFFER     DebuggerPreallocCommandType = 7
)

// @brief different types of preactivate requests
type DebuggerPreactivateCommandType int32

const DEBUGGER_PREACTIVATE_COMMAND_TYPE_MODE DebuggerPreactivateCommandType = 0

// @brief different types of reading memory
type DebuggerReadReadingType int32

const (
	READ_FROM_KERNEL   DebuggerReadReadingType = 0
	READ_FROM_VMX_ROOT DebuggerReadReadingType = 1
)

// @brief different type of addresses
type DebuggerReadMemoryType int32

const (
	DEBUGGER_READ_PHYSICAL_ADDRESS DebuggerReadMemoryType = 0
	DEBUGGER_READ_VIRTUAL_ADDRESS  DebuggerReadMemoryType = 1
)

// @brief the way that debugger should show
// the details of memory or disassemble them
type DebuggerShowMemoryStyle int32

const (
	DEBUGGER_SHOW_COMMAND_DT            DebuggerShowMemoryStyle = 1
	DEBUGGER_SHOW_COMMAND_DISASSEMBLE64 DebuggerShowMemoryStyle = 2
	DEBUGGER_SHOW_COMMAND_DISASSEMBLE32 DebuggerShowMemoryStyle = 3
	DEBUGGER_SHOW_COMMAND_DB            DebuggerShowMemoryStyle = 4
	DEBUGGER_SHOW_COMMAND_DC            DebuggerShowMemoryStyle = 5
	DEBUGGER_SHOW_COMMAND_DQ            DebuggerShowMemoryStyle = 6
	DEBUGGER_SHOW_COMMAND_DD            DebuggerShowMemoryStyle = 7
	DEBUGGER_SHOW_COMMAND_DUMP          DebuggerShowMemoryStyle = 8
)

// @brief test query used for test purposed
type DebuggerTestQueryState int32

const (
	TEST_QUERY_HALTING_CORE_STATUS                                          DebuggerTestQueryState = 1
	TEST_QUERY_PREALLOCATED_POOL_STATE                                      DebuggerTestQueryState = 2
	TEST_QUERY_TRAP_STATE                                                   DebuggerTestQueryState = 3
	TEST_BREAKPOINT_TURN_OFF_BPS                                            DebuggerTestQueryState = 4
	TEST_BREAKPOINT_TURN_ON_BPS                                             DebuggerTestQueryState = 5
	TEST_BREAKPOINT_TURN_OFF_BPS_AND_EVENTS_FOR_COMMANDS_IN_REMOTE_COMPUTER DebuggerTestQueryState = 6
	TEST_BREAKPOINT_TURN_ON_BPS_AND_EVENTS_FOR_COMMANDS_IN_REMOTE_COMPUTER  DebuggerTestQueryState = 7
	TEST_SETTING_TARGET_TASKS_ON_HALTED_CORES_SYNCHRONOUS                   DebuggerTestQueryState = 8
	TEST_SETTING_TARGET_TASKS_ON_HALTED_CORES_ASYNCHRONOUS                  DebuggerTestQueryState = 9
	TEST_SETTING_TARGET_TASKS_ON_TARGET_HALTED_CORES                        DebuggerTestQueryState = 10
	TEST_BREAKPOINT_TURN_OFF_DBS                                            DebuggerTestQueryState = 11
	TEST_BREAKPOINT_TURN_ON_DBS                                             DebuggerTestQueryState = 12
)

// @brief different types of actions on MSRs
type DebuggerMsrActionType int32

const (
	DEBUGGER_MSR_READ  DebuggerMsrActionType = 0
	DEBUGGER_MSR_WRITE DebuggerMsrActionType = 1
)

// @brief different type of addresses for editing memory
type DebuggerEditMemoryType int32

const (
	EDIT_PHYSICAL_MEMORY DebuggerEditMemoryType = 0
	EDIT_VIRTUAL_MEMORY  DebuggerEditMemoryType = 1
)

// @brief size of editing memory
type DebuggerEditMemoryByteSize int32

const (
	EDIT_BYTE  DebuggerEditMemoryByteSize = 0
	EDIT_DWORD DebuggerEditMemoryByteSize = 1
	EDIT_QWORD DebuggerEditMemoryByteSize = 2
)

// @brief different types of address for searching on memory
type DebuggerSearchMemoryType int32

const (
	SEARCH_PHYSICAL_MEMORY              DebuggerSearchMemoryType = 0
	SEARCH_VIRTUAL_MEMORY               DebuggerSearchMemoryType = 1
	SEARCH_PHYSICAL_FROM_VIRTUAL_MEMORY DebuggerSearchMemoryType = 2
)

// @brief different sizes on searching memory
type DebuggerSearchMemoryByteSize int32

const (
	SEARCH_BYTE  DebuggerSearchMemoryByteSize = 0
	SEARCH_DWORD DebuggerSearchMemoryByteSize = 1
	SEARCH_QWORD DebuggerSearchMemoryByteSize = 2
)

// @brief different actions of switchings
type DebuggerAttachDetachUserModeProcessActionType int32

const (
	DEBUGGER_ATTACH_DETACH_USER_MODE_PROCESS_ACTION_ATTACH                                  DebuggerAttachDetachUserModeProcessActionType = 0
	DEBUGGER_ATTACH_DETACH_USER_MODE_PROCESS_ACTION_DETACH                                  DebuggerAttachDetachUserModeProcessActionType = 1
	DEBUGGER_ATTACH_DETACH_USER_MODE_PROCESS_ACTION_REMOVE_HOOKS                            DebuggerAttachDetachUserModeProcessActionType = 2
	DEBUGGER_ATTACH_DETACH_USER_MODE_PROCESS_ACTION_KILL_PROCESS                            DebuggerAttachDetachUserModeProcessActionType = 3
	DEBUGGER_ATTACH_DETACH_USER_MODE_PROCESS_ACTION_PAUSE_PROCESS                           DebuggerAttachDetachUserModeProcessActionType = 4
	DEBUGGER_ATTACH_DETACH_USER_MODE_PROCESS_ACTION_SWITCH_BY_PROCESS_OR_THREAD             DebuggerAttachDetachUserModeProcessActionType = 5
	DEBUGGER_ATTACH_DETACH_USER_MODE_PROCESS_ACTION_QUERY_COUNT_OF_ACTIVE_DEBUGGING_THREADS DebuggerAttachDetachUserModeProcessActionType = 6
)

// @brief different type of process or thread queries
type DebuggerQueryActiveProcessesOrThreadsTypes int32

const (
	DEBUGGER_QUERY_ACTIVE_PROCESSES_OR_THREADS_QUERY_PROCESS_COUNT   DebuggerQueryActiveProcessesOrThreadsTypes = 1
	DEBUGGER_QUERY_ACTIVE_PROCESSES_OR_THREADS_QUERY_THREAD_COUNT    DebuggerQueryActiveProcessesOrThreadsTypes = 2
	DEBUGGER_QUERY_ACTIVE_PROCESSES_OR_THREADS_QUERY_PROCESS_LIST    DebuggerQueryActiveProcessesOrThreadsTypes = 3
	DEBUGGER_QUERY_ACTIVE_PROCESSES_OR_THREADS_QUERY_THREAD_LIST     DebuggerQueryActiveProcessesOrThreadsTypes = 4
	DEBUGGER_QUERY_ACTIVE_PROCESSES_OR_THREADS_QUERY_CURRENT_PROCESS DebuggerQueryActiveProcessesOrThreadsTypes = 5
	DEBUGGER_QUERY_ACTIVE_PROCESSES_OR_THREADS_QUERY_CURRENT_THREAD  DebuggerQueryActiveProcessesOrThreadsTypes = 6
)

// @brief different actions on showing or querying list of process or threads
type DebuggerQueryActiveProcessesOrThreadsActions int32

const (
	DEBUGGER_QUERY_ACTIVE_PROCESSES_OR_THREADS_ACTION_SHOW_INSTANTLY     DebuggerQueryActiveProcessesOrThreadsActions = 1
	DEBUGGER_QUERY_ACTIVE_PROCESSES_OR_THREADS_ACTION_QUERY_COUNT        DebuggerQueryActiveProcessesOrThreadsActions = 2
	DEBUGGER_QUERY_ACTIVE_PROCESSES_OR_THREADS_ACTION_QUERY_SAVE_DETAILS DebuggerQueryActiveProcessesOrThreadsActions = 3
)

// @brief callstack showing method
type DebuggerCallstackDisplayMethod int32

const (
	DEBUGGER_CALLSTACK_DISPLAY_METHOD_WITHOUT_PARAMS DebuggerCallstackDisplayMethod = 0
	DEBUGGER_CALLSTACK_DISPLAY_METHOD_WITH_PARAMS    DebuggerCallstackDisplayMethod = 1
)

// @brief User-mode debugging actions
type DebuggerUdCommandActionType int32

const (
	DEBUGGER_UD_COMMAND_ACTION_TYPE_NONE         DebuggerUdCommandActionType = 0
	DEBUGGER_UD_COMMAND_ACTION_TYPE_PAUSE        DebuggerUdCommandActionType = 1
	DEBUGGER_UD_COMMAND_ACTION_TYPE_CONTINUE     DebuggerUdCommandActionType = 2
	DEBUGGER_UD_COMMAND_ACTION_TYPE_REGULAR_STEP DebuggerUdCommandActionType = 3
)

// @brief Debugger process switch and process details
type DebuggeeDetailsAndSwitchProcessType int32

const (
	DEBUGGEE_DETAILS_AND_SWITCH_PROCESS_GET_PROCESS_DETAILS DebuggeeDetailsAndSwitchProcessType = 0
	DEBUGGEE_DETAILS_AND_SWITCH_PROCESS_GET_PROCESS_LIST    DebuggeeDetailsAndSwitchProcessType = 1
	DEBUGGEE_DETAILS_AND_SWITCH_PROCESS_PERFORM_SWITCH      DebuggeeDetailsAndSwitchProcessType = 2
)

// @brief Debugger thread switch and thread details
type DebuggeeDetailsAndSwitchThreadType int32

const (
	DEBUGGEE_DETAILS_AND_SWITCH_THREAD_PERFORM_SWITCH     DebuggeeDetailsAndSwitchThreadType = 0
	DEBUGGEE_DETAILS_AND_SWITCH_THREAD_GET_THREAD_DETAILS DebuggeeDetailsAndSwitchThreadType = 1
	DEBUGGEE_DETAILS_AND_SWITCH_THREAD_GET_THREAD_LIST    DebuggeeDetailsAndSwitchThreadType = 2
)

// @brief stepping and tracking types
type DebuggerRemoteSteppingRequest int32

const (
	DEBUGGER_REMOTE_STEPPING_REQUEST_STEP_IN                              DebuggerRemoteSteppingRequest = 0
	DEBUGGER_REMOTE_STEPPING_REQUEST_INSTRUMENTATION_STEP_IN              DebuggerRemoteSteppingRequest = 1
	DEBUGGER_REMOTE_STEPPING_REQUEST_INSTRUMENTATION_STEP_IN_FOR_TRACKING DebuggerRemoteSteppingRequest = 2
	DEBUGGER_REMOTE_STEPPING_REQUEST_STEP_OVER                            DebuggerRemoteSteppingRequest = 3
	DEBUGGER_REMOTE_STEPPING_REQUEST_STEP_OVER_FOR_GU                     DebuggerRemoteSteppingRequest = 4
	DEBUGGER_REMOTE_STEPPING_REQUEST_STEP_OVER_FOR_GU_LAST_INSTRUCTION    DebuggerRemoteSteppingRequest = 5
)

// @brief breakpoint modification types
type DebuggeeBreakpointModificationRequest int32

const (
	DEBUGGEE_BREAKPOINT_MODIFICATION_REQUEST_LIST_BREAKPOINTS DebuggeeBreakpointModificationRequest = 0
	DEBUGGEE_BREAKPOINT_MODIFICATION_REQUEST_ENABLE           DebuggeeBreakpointModificationRequest = 1
	DEBUGGEE_BREAKPOINT_MODIFICATION_REQUEST_DISABLE          DebuggeeBreakpointModificationRequest = 2
	DEBUGGEE_BREAKPOINT_MODIFICATION_REQUEST_CLEAR            DebuggeeBreakpointModificationRequest = 3
)

// @brief Whether a jump is taken or not taken
type DebuggerConditionalJumpStatus int32

const (
	DEBUGGER_CONDITIONAL_JUMP_STATUS_ERROR                DebuggerConditionalJumpStatus = 0
	DEBUGGER_CONDITIONAL_JUMP_STATUS_NOT_CONDITIONAL_JUMP DebuggerConditionalJumpStatus = 1
	DEBUGGER_CONDITIONAL_JUMP_STATUS_JUMP_IS_TAKEN        DebuggerConditionalJumpStatus = 2
	DEBUGGER_CONDITIONAL_JUMP_STATUS_JUMP_IS_NOT_TAKEN    DebuggerConditionalJumpStatus = 3
)

type ListEntry struct {
	Flink *ListEntry
	Blink *ListEntry
}
type GuestRegs struct {
	Rax Uint64
	Rcx Uint64
	Rdx Uint64
	Rbx Uint64
	Rsp Uint64
	Rbp Uint64
	Rsi Uint64
	Rdi Uint64
	R8  Uint64
	R9  Uint64
	R10 Uint64
	R11 Uint64
	R12 Uint64
	R13 Uint64
	R14 Uint64
	R15 Uint64
}
type GuestExtraRegisters struct {
	Cs     Uint16
	Ds     Uint16
	Fs     Uint16
	Gs     Uint16
	Es     Uint16
	Ss     Uint16
	Rflags Uint64
	Rip    Uint64
}
type ScriptEngineVariablesList struct {
	TempList            *Uint64
	GlobalVariablesList *Uint64
	LocalVariablesList  *Uint64
}
type Cr3Type struct {
	Anon196_5
}
type Anon196_5 struct {
	Raw [1]int64
}
type Anon200_9 struct {
	Pcid            Uint64
	PageFrameNumber Uint64
	Reserved1       Uint64
	Reserved_2      Uint64
	PcidInvalidate  Uint64
}
type DebuggerRemotePacket struct {
	Checksum                   Byte
	Indicator                  Uint64
	TypeOfThePacket            DebuggerRemotePacketType
	RequestedActionOfThePacket DebuggerRemotePacketRequestedAction
}
type DebuggeeUserInputPacket struct {
	CommandLen           Uint32
	IgnoreFinishedSignal Boolean
	Result               Uint32
}
type DebuggeeEventAndActionHeaderForRemotePacket struct {
	Length Uint32
}
type DebuggerPausePacketReceived struct {
	Result Uint32
}
type DebuggerTriggeredEventDetails struct {
	Tag     Uint64
	Context unsafe.Pointer
	Stage   VmmCallbackEventCallingStageType
}
type DebuggeeKdPausedPacket struct {
	Rip                    Uint64
	IsProcessorOn32BitMode Boolean
	IgnoreDisassembling    Boolean
	PausingReason          DebuggeePausingReason
	CurrentCore            Ulong
	EventTag               Uint64
	EventCallingStage      VmmCallbackEventCallingStageType
	Rflags                 Uint64
	InstructionBytesOnRip  [16]Byte
	ReadInstructionLen     Uint16
}
type DebuggeeUdPausedPacket struct {
	Rip                   Uint64
	ProcessDebuggingToken Uint64
	Is32Bit               Boolean
	PausingReason         DebuggeePausingReason
	ProcessId             Uint32
	ThreadId              Uint32
	Rflags                Uint64
	EventTag              Uint64
	EventCallingStage     VmmCallbackEventCallingStageType
	InstructionBytesOnRip [16]Byte
	ReadInstructionLen    Uint16
	GuestRegs             GuestRegs
}
type DebuggeeMessagePacket struct {
	OperationCode Uint32
	Message       [4096]Char
}
type RegisterNotifyBuffer struct {
	Type   NotifyType
	hEvent unsafe.Pointer
}
type DirectVmcallParameters struct {
	OptionalParam1 Uint64
	OptionalParam2 Uint64
	OptionalParam3 Uint64
}
type EptHooksContext struct {
	HookingTag      Uint64
	PhysicalAddress Uint64
	VirtualAddress  Uint64
}
type EptHooksAddressDetailsForMemoryMonitor struct {
	StartAddress    Uint64
	EndAddress      Uint64
	SetHookForRead  Boolean
	SetHookForWrite Boolean
	SetHookForExec  Boolean
	MemoryType      DebuggerHookMemoryType
	Tag             Uint64
}
type EptHooksAddressDetailsForEpthook2 struct {
	TargetAddress unsafe.Pointer
	HookFunction  unsafe.Pointer
}
type EptSingleHookUnhookingDetails struct {
	CallerNeedsToRestoreEntryAndInvalidateEpt Boolean
	RemoveBreakpointInterception              Boolean
	PhysicalAddress                           SizeT
	OriginalEntry                             Uint64
}
type Anon1497_9 struct {
	Raw [1]int32
}
type Anon1499_5 struct {
	// [Bits 3:0] Segment type.
	Type Uint32
	// [Bit 4] S - Descriptor type (0 = system; 1 = code or data).
	DescriptorType Uint32
	// [Bits 6:5] DPL - Descriptor privilege level.
	DescriptorPrivilegeLevel Uint32
	// [Bit 7] P - Segment present.
	Present   Uint32
	Reserved1 Uint32
	// [Bit 12] AVL - Available for use by system software.
	AvailableBit Uint32
	// [Bit 13] Reserved (except for CS). L - 64-bit mode active (for CS only).
	LongMode Uint32
	// [Bit 14] D/B - Default operation size (0 = 16-bit segment; 1 = 32-bit segment).
	DefaultBig Uint32
	// [Bit 15] G - Granularity.
	Granularity Uint32
	// [Bit 16] Segment unusable (0 = usable; 1 = unusable).
	Unusable  Uint32
	Reserved2 Uint32
}
type VmxSegmentSelector struct {
	Selector   Uint16
	Attributes VmxSegmentAccessRightsType
	Limit      Uint32
	Base       Uint64
}
type DebuggerModifyEvents struct {
	Tag          Uint64
	KernelStatus Uint64
	TypeOfAction DebuggerModifyEventsType
	IsEnabled    Boolean
}
type DebuggerShortCircuitingEvent struct {
	KernelStatus      Uint64
	IsShortCircuiting Boolean
}
type DebuggerEventOptions struct {
	OptionalParam1 Uint64
	OptionalParam2 Uint64
	OptionalParam3 Uint64
	OptionalParam4 Uint64
	OptionalParam5 Uint64
	OptionalParam6 Uint64
}
type DebuggerGeneralEventDetail struct {
	CommandsEventList     ListEntry
	CreationTime          TimeT
	CoreId                Uint32
	ProcessId             Uint32
	IsEnabled             Boolean
	EnableShortCircuiting Boolean
	EventStage            VmmCallbackEventCallingStageType
	HasCustomOutput       Boolean
	OutputSourceTags      [5]Uint64
	CountOfActions        Uint32
	Tag                   Uint64
	EventType             VmmEventTypeEnum
	Options               DebuggerEventOptions
	CommandStringBuffer   unsafe.Pointer
	ConditionBufferSize   Uint32
}
type DebuggerGeneralAction struct {
	EventTag                Uint64
	ActionType              DebuggerEventActionTypeEnum
	ImmediateMessagePassing Boolean
	PreAllocatedBuffer      Uint32
	CustomCodeBufferSize    Uint32
	ScriptBufferSize        Uint32
	ScriptBufferPointer     Uint32
}
type DebuggerEventAndActionResult struct {
	IsSuccessful Boolean
	Error        Uint32
}
type HwdbgPortInformationItems struct {
	PortSize Uint32
}
type HwdbgInstanceInformation struct {
	Version                                    Uint32
	maximumNumberOfStages                      Uint32
	scriptVariableLength                       Uint32
	numberOfSupportedLocalAndGlobalVariables   Uint32
	numberOfSupportedTemporaryVariables        Uint32
	maximumNumberOfSupportedGetScriptOperators Uint32
	maximumNumberOfSupportedSetScriptOperators Uint32
	sharedMemorySize                           Uint32
	debuggerAreaOffset                         Uint32
	debuggeeAreaOffset                         Uint32
	numberOfPins                               Uint32
	numberOfPorts                              Uint32
	scriptCapabilities                         _HwdbgScriptCapabilities
	bramAddrWidth                              Uint32
	bramDataWidth                              Uint32
}
type _HwdbgScriptCapabilities struct {
	AssignLocalGlobalVar                        Uint64
	AssignRegisters                             Uint64
	AssignPseudoRegisters                       Uint64
	ConditionalStatementsAndComparisonOperators Uint64
	FuncOr                                      Uint64
	FuncXor                                     Uint64
	FuncAnd                                     Uint64
	FuncAsr                                     Uint64
	FuncAsl                                     Uint64
	FuncAdd                                     Uint64
	FuncSub                                     Uint64
	FuncMul                                     Uint64
	FuncDiv                                     Uint64
	FuncMod                                     Uint64
	FuncGt                                      Uint64
	FuncLt                                      Uint64
	FuncEgt                                     Uint64
	FuncElt                                     Uint64
	FuncEqual                                   Uint64
	FuncNeq                                     Uint64
	FuncJmp                                     Uint64
	FuncJz                                      Uint64
	FuncJnz                                     Uint64
	FuncMov                                     Uint64
	FuncPrintf                                  Uint64
}
type HwdbgScriptBuffer struct {
	scriptNumberOfSymbols Uint32
}
type DebuggerReadPageTableEntriesDetails struct {
	VirtualAddress      Uint64
	ProcessId           Uint32
	Pml4eVirtualAddress Uint64
	Pml4eValue          Uint64
	PdpteVirtualAddress Uint64
	PdpteValue          Uint64
	PdeVirtualAddress   Uint64
	PdeValue            Uint64
	PteVirtualAddress   Uint64
	PteValue            Uint64
	KernelStatus        Uint32
}
type DebuggerVa2paAndPa2vaCommands struct {
	VirtualAddress     Uint64
	PhysicalAddress    Uint64
	ProcessId          Uint32
	IsVirtual2Physical Boolean
	KernelStatus       Uint32
}
type DebuggerPageInRequest struct {
	VirtualAddressFrom Uint64
	VirtualAddressTo   Uint64
	ProcessId          Uint32
	PageFaultErrorCode Uint32
	KernelStatus       Uint32
}
type ReversingMachineReconstructMemoryRequest struct {
	ProcessId    Uint32
	Size         Uint32
	Mode         ReversingMachineReconstructMemoryMode
	Type         ReversingMachineReconstructMemoryType
	KernelStatus Uint32
}
type DebuggerDtCommandOptions struct {
	TypeName             *byte
	SizeOfTypeName       Uint64
	Address              Uint64
	IsStruct             Boolean
	BufferAddress        unsafe.Pointer
	TargetPid            Uint32
	AdditionalParameters *byte
}
type DebuggerPreallocCommand struct {
	Type         DebuggerPreallocCommandType
	Count        Uint32
	KernelStatus Uint32
}
type DebuggerPreactivateCommand struct {
	Type         DebuggerPreactivateCommandType
	KernelStatus Uint32
}
type DebuggerReadMemory struct {
	Pid            Uint32
	Address        Uint64
	Size           Uint32
	IsForDisasm    Boolean
	Is32BitAddress Boolean
	MemoryType     DebuggerReadMemoryType
	ReadingType    DebuggerReadReadingType
	DtDetails      PdebuggerDtCommandOptions
	Style          DebuggerShowMemoryStyle
	ReturnLength   Uint32
	KernelStatus   Uint32
}
type DebuggerFlushLoggingBuffers struct {
	KernelStatus                               Uint32
	CountOfMessagesThatSetAsReadFromVmxRoot    Uint32
	CountOfMessagesThatSetAsReadFromVmxNonRoot Uint32
}
type DebuggerDebuggerTestQueryBuffer struct {
	RequestType  DebuggerTestQueryState
	Context      Uint64
	KernelStatus Uint32
}
type DebuggerPerformKernelTests struct {
	KernelStatus Uint32
}
type DebuggerSendCommandExecutionFinishedSignal struct {
	KernelStatus Uint32
}
type DebuggeeSendGeneralPacketFromDebuggeeToDebugger struct {
	RequestedAction       DebuggerRemotePacketRequestedAction
	LengthOfBuffer        Uint32
	PauseDebuggeeWhenSent Boolean
	KernelResult          Uint32
}
type DebuggerSendUsermodeMessagesToDebugger struct {
	KernelStatus Uint32
	Length       Uint32
}
type DebuggerReadAndWriteOnMsr struct {
	Msr        Uint64
	CoreNumber Uint32
	ActionType DebuggerMsrActionType
	Value      Uint64
}
type DebuggerEditMemory struct {
	Result             Uint32
	Address            Uint64
	ProcessId          Uint32
	MemoryType         DebuggerEditMemoryType
	ByteSize           DebuggerEditMemoryByteSize
	CountOf64Chunks    Uint32
	FinalStructureSize Uint32
	KernelStatus       Uint32
}
type DebuggerSearchMemory struct {
	Address            Uint64
	Length             Uint64
	ProcessId          Uint32
	MemoryType         DebuggerSearchMemoryType
	ByteSize           DebuggerSearchMemoryByteSize
	CountOf64Chunks    Uint32
	FinalStructureSize Uint32
}
type DebuggerHideAndTransparentDebuggerMode struct {
	IsHide                               Boolean
	CpuidAverage                         Uint64
	CpuidStandardDeviation               Uint64
	CpuidMedian                          Uint64
	RdtscAverage                         Uint64
	RdtscStandardDeviation               Uint64
	RdtscMedian                          Uint64
	TrueIfProcessIdAndFalseIfProcessName Boolean
	ProcId                               Uint32
	LengthOfProcessName                  Uint32
	KernelStatus                         Uint64
}
type DebuggerPrepareDebuggee struct {
	PortAddress         Uint32
	Baudrate            Uint32
	NtoskrnlBaseAddress Uint64
	Result              Uint32
	OsName              [256]Char
}
type DebuggeeChangeCorePacket struct {
	NewCore Uint32
	Result  Uint32
}
type DebuggerAttachDetachUserModeProcess struct {
	IsStartingNewProcess                      Boolean
	ProcessId                                 Uint32
	ThreadId                                  Uint32
	CheckCallbackAtFirstInstruction           Boolean
	Is32Bit                                   Boolean
	IsPaused                                  Boolean
	Action                                    DebuggerAttachDetachUserModeProcessActionType
	CountOfActiveDebuggingThreadsAndProcesses Uint32
	Token                                     Uint64
	Result                                    Uint64
}
type DebuggeeProcessListNeededDetails struct {
	PsActiveProcessHead      Uint64
	ImageFileNameOffset      Ulong
	UniquePidOffset          Ulong
	ActiveProcessLinksOffset Ulong
}
type DebuggeeThreadListNeededDetails struct {
	ThreadListHeadOffset     Uint32
	ThreadListEntryOffset    Uint32
	CidOffset                Uint32
	PsActiveProcessHead      Uint64
	ActiveProcessLinksOffset Ulong
	Process                  Uint64
}
type DebuggeeProcessListDetailsEntry struct {
	Eprocess      Uint64
	ProcessId     Uint32
	Cr3           Uint64
	ImageFileName [16]Uchar
}
type DebuggeeThreadListDetailsEntry struct {
	Eprocess      Uint64
	Ethread       Uint64
	ProcessId     Uint32
	ThreadId      Uint32
	ImageFileName [16]Uchar
}
type DebuggerQueryActiveProcessesOrThreads struct {
	ProcessListNeededDetails DebuggeeProcessListNeededDetails
	ThreadListNeededDetails  DebuggeeThreadListNeededDetails
	QueryType                DebuggerQueryActiveProcessesOrThreadsTypes
	QueryAction              DebuggerQueryActiveProcessesOrThreadsActions
	Count                    Uint32
	Result                   Uint64
}
type DebuggerSingleCallstackFrame struct {
	IsStackAddressValid   Boolean
	IsValidAddress        Boolean
	IsExecutable          Boolean
	Value                 Uint64
	InstructionBytesOnRip [7]Byte
}
type DebuggerCallstackRequest struct {
	Is32Bit       Boolean
	KernelStatus  Uint32
	DisplayMethod DebuggerCallstackDisplayMethod
	Size          Uint32
	FrameCount    Uint32
	BaseAddress   Uint64
	BufferSize    Uint64
}
type UsermodeDebuggingThreadOrProcessStateDetails struct {
	ProcessId Uint32
	ThreadId  Uint32
	IsProcess Boolean
}
type DebuggerEventActionRunScriptConfiguration struct {
	ScriptBuffer                Uint64
	ScriptLength                Uint32
	ScriptPointer               Uint32
	OptionalRequestedBufferSize Uint32
}
type DebuggerEventRequestBuffer struct {
	EnabledRequestBuffer Boolean
	RequestBufferSize    Uint32
	RequstBufferAddress  Uint64
}
type DebuggerEventRequestCustomCode struct {
	CustomCodeBufferSize        Uint32
	CustomCodeBufferAddress     unsafe.Pointer
	OptionalRequestedBufferSize Uint32
}
type DebuggerUdCommandAction struct {
	ActionType     DebuggerUdCommandActionType
	OptionalParam1 Uint64
	OptionalParam2 Uint64
	OptionalParam3 Uint64
	OptionalParam4 Uint64
}
type DebuggerUdCommandPacket struct {
	UdAction                    DebuggerUdCommandAction
	ProcessDebuggingDetailToken Uint64
	TargetThreadId              Uint32
	ApplyToAllPausedThreads     Boolean
	Result                      Uint32
}
type DebuggeeDetailsAndSwitchProcessPacket struct {
	ActionType            DebuggeeDetailsAndSwitchProcessType
	ProcessId             Uint32
	Process               Uint64
	IsSwitchByClkIntr     Boolean
	ProcessName           [16]Uchar
	ProcessListSymDetails DebuggeeProcessListNeededDetails
	Result                Uint32
}
type DebuggeeDetailsAndSwitchThreadPacket struct {
	ActionType            DebuggeeDetailsAndSwitchThreadType
	ThreadId              Uint32
	ProcessId             Uint32
	Thread                Uint64
	Process               Uint64
	CheckByClockInterrupt Boolean
	ProcessName           [16]Uchar
	ThreadListSymDetails  DebuggeeThreadListNeededDetails
	Result                Uint32
}
type DebuggeeStepPacket struct {
	StepType                  DebuggerRemoteSteppingRequest
	IsCurrentInstructionACall Boolean
	CallLength                Uint32
}
type DebuggeeFormatsPacket struct {
	Value  Uint64
	Result Uint32
}
type DebuggeeSymbolRequestPacket struct {
	ProcessId Uint32
}
type DebuggeeBpPacket struct {
	Address           Uint64
	Pid               Uint32
	Tid               Uint32
	Core              Uint32
	RemoveAfterHit    Boolean
	CheckForCallbacks Boolean
	Result            Uint32
}
type DebuggeeBpListOrModifyPacket struct {
	BreakpointId Uint64
	Request      DebuggeeBreakpointModificationRequest
	Result       Uint32
}
type DebuggeeScriptPacket struct {
	ScriptBufferSize    Uint32
	ScriptBufferPointer Uint32
	IsFormat            Boolean
	Result              Uint32
}
type DebuggeeResultOfSearchPacket struct {
	CountOfResults Uint32
	Result         Uint32
}
type DebuggeeRegisterReadDescription struct {
	RegisterID   Uint32
	Value        Uint64
	KernelStatus Uint32
}
type ModuleSymbolDetail struct {
	IsSymbolDetailsFound   Boolean
	IsLocalSymbolPath      Boolean
	IsSymbolPDBAvaliable   Boolean
	IsUserMode             Boolean
	Is32Bit                Boolean
	BaseAddress            Uint64
	FilePath               [260]byte
	ModuleSymbolPath       [260]byte
	ModuleSymbolGuidAndAge [60]byte
}
type UsermodeLoadedModuleSymbols struct {
	BaseAddress Uint64
	Entrypoint  Uint64
	FilePath    [260]Rune
}
type UsermodeLoadedModuleDetails struct {
	ProcessId        Uint32
	OnlyCountModules Boolean
	Is32Bit          Boolean
	ModulesCount     Uint32
	Result           Uint32
}
type DebuggerUpdateSymbolTable struct {
	TotalSymbols       Uint32
	CurrentSymbolIndex Uint32
	SymbolDetailPacket ModuleSymbolDetail
}
type DebuggeeSymbolUpdateResult struct {
	KernelStatus Uint64
}
type (
	_Int128T           = any
	_Uint128T          = any
	__NSConstantString = any
	SizeT              = uint64
	_BuiltinMsVaList   = *byte
	_BuiltinVaList     = *byte
	Rune               = int32
	WintT              = int32
	Long               = int64
	PsizeT             = *uint64
	TimeT              = uint64
	Ntstatus           = uint64
	VaList             = *byte
	PlistEntry         = *ListEntry
	PrlistEntry        = ListEntry
)

// ///////////////////////////////////////////////
type (
	Qword    = uint64
	Uint64   = uint64
	Puint64  = *uint64
	Dword    = uint64
	Bool     = int32
	Byte     = uint8
	Word     = uint16
	Int      = int32
	Uint     = uint32
	Puint    = *uint32
	Ulong64  = uint64
	Pulong64 = *uint64
	Dword64  = uint64
	Pdword64 = *uint64
	Char     = byte
	Wchar    = Rune
	Uchar    = uint8
	Ushort   = uint16
	Ulong    = uint64
	Boolean  = Uchar
	Pboolean = *Boolean
	Int8     = int8
	Pint8    = *int8
	Int16    = int16
	Pint16   = *int16
	Int32    = int32
	Pint32   = *int32
	Int64    = int64
	Pint64   = *int64
	Uint8    = uint8
	Puint8   = *uint8
	Uint16   = uint16
	Puint16  = *uint16
	Uint32   = uint32
	Puint32  = *uint32

	PguestRegs = *GuestRegs
)

// @brief struct for extra registers
type PguestExtraRegisters = *GuestExtraRegisters

// @brief List of different variables
type PscriptEngineVariablesList = *ScriptEngineVariablesList

// @brief CR3 Structure
type Pcr3Type = *Cr3Type

// @brief The structure of remote packets in HyperDbg
type PdebuggerRemotePacket = *DebuggerRemotePacket

// @brief Callback type that can be used to be used
// as a custom ShowMessages function
type Callback = unsafe.Pointer

// @brief The structure of user-input packet in HyperDbg
type PdebuggeeUserInputPacket = *DebuggeeUserInputPacket

// @brief The structure of user-input packet in HyperDbg
type PdebuggeeEventAndActionHeaderForRemotePacket = *DebuggeeEventAndActionHeaderForRemotePacket

// @brief request to pause and halt the system
type PdebuggerPausePacketReceived = *DebuggerPausePacketReceived

// @brief The structure of detail of a triggered event in HyperDbg
//
// @details This structure is also used for transferring breakpoint ids, RIP as the context, etc.
type PdebuggerTriggeredEventDetails = *DebuggerTriggeredEventDetails

// @brief The structure of pausing packet in kHyperDbg
type PdebuggeeKdPausedPacket = *DebuggeeKdPausedPacket

// @brief The structure of pausing packet in uHyperDbg
type PdebuggeeUdPausedPacket = *DebuggeeUdPausedPacket

// @brief The structure of message packet in HyperDbg
type PdebuggeeMessagePacket = *DebuggeeMessagePacket

// @brief Used to register event for transferring buffer between user-to-kernel
type PregisterNotifyBuffer = *RegisterNotifyBuffer

// @brief Used for sending direct VMCALLs on the VMX root-mode
type PdirectVmcallParameters = *DirectVmcallParameters

// @brief Temporary $context used in some EPT hook commands
type PeptHooksContext = *EptHooksContext

// @brief Setting details for EPT Hooks (!monitor)
type PeptHooksAddressDetailsForMemoryMonitor = *EptHooksAddressDetailsForMemoryMonitor

// @brief Setting details for EPT Hooks (!epthook2)
type PeptHooksAddressDetailsForEpthook2 = *EptHooksAddressDetailsForEpthook2

// @brief Details of unhooking single EPT hooks
type PeptSingleHookUnhookingDetails = *EptSingleHookUnhookingDetails

// @brief Describe segment selector in VMX
//
// @details This structure is copied from ia32.h to the SDK to
// be used as a data type for functions
type VmxSegmentAccessRightsType = any

// @brief Segment selector
type PvmxSegmentSelector = *VmxSegmentSelector

// @brief request for modifying events (enable/disable/clear)
type PdebuggerModifyEvents = *DebuggerModifyEvents

// @brief request for performing a short-circuiting event
type PdebuggerShortCircuitingEvent = *DebuggerShortCircuitingEvent

// @brief request for performing a short-circuiting event
type PdebuggerEventOptions = *DebuggerEventOptions

// @brief Each command is like the following struct, it also used for
// tracing works in user mode and sending it to the kernl mode
//
// @details THIS IS NOT WHAT HYPERDBG SAVES FOR EVENTS IN KERNEL-MODE
type PdebuggerGeneralEventDetail = *DebuggerGeneralEventDetail

// @brief Each event can have multiple actions
//
// @details THIS STRUCTURE IS ONLY USED IN USER MODE
// WE USE SEPARATE STRUCTURE FOR ACTIONS IN
// KERNEL MODE
type PdebuggerGeneralAction = *DebuggerGeneralAction

// @brief Status of register buffers
type PdebuggerEventAndActionResult = *DebuggerEventAndActionResult

// @brief The structure of port information (each item) in hwdbg
type (
	PhwdbgPortInformationItems = *HwdbgPortInformationItems
	PhwdbgInstanceInformation  = *HwdbgInstanceInformation
)

// @brief The structure of script buffer in hwdbg
type PhwdbgScriptBuffer = *HwdbgScriptBuffer

// @brief request for !pte command
type PdebuggerReadPageTableEntriesDetails = *DebuggerReadPageTableEntriesDetails

// @brief requests for !va2pa and !pa2va commands
type PdebuggerVa2paAndPa2vaCommands = *DebuggerVa2paAndPa2vaCommands

// @brief requests for the '.pagein' command
type PdebuggerPageInRequest = *DebuggerPageInRequest

// @brief requests for !rev command
type PreversingMachineReconstructMemoryRequest = *ReversingMachineReconstructMemoryRequest

// @brief requests options for dt and struct command
type PdebuggerDtCommandOptions = *DebuggerDtCommandOptions

// @brief requests for the 'prealloc' command
type PdebuggerPreallocCommand = *DebuggerPreallocCommand

// @brief requests for the 'preactivate' command
type PdebuggerPreactivateCommand = *DebuggerPreactivateCommand

// @brief request for reading virtual and physical memory
type PdebuggerReadMemory = *DebuggerReadMemory

// @brief request for flushing buffers
type PdebuggerFlushLoggingBuffers = *DebuggerFlushLoggingBuffers

// @brief request for test query buffers
type PdebuggerDebuggerTestQueryBuffer = *DebuggerDebuggerTestQueryBuffer

// @brief request performing kernel tests
type PdebuggerPerformKernelTests = *DebuggerPerformKernelTests

// @brief request for send a signal that command execution finished
type PdebuggerSendCommandExecutionFinishedSignal = *DebuggerSendCommandExecutionFinishedSignal

// @brief request for send general packets from debuggee to debugger
type PdebuggeeSendGeneralPacketFromDebuggeeToDebugger = *DebuggeeSendGeneralPacketFromDebuggeeToDebugger

// @brief request for send a user-mode message to debugger
type PdebuggerSendUsermodeMessagesToDebugger = *DebuggerSendUsermodeMessagesToDebugger

// @brief request to read or write on MSRs
type PdebuggerReadAndWriteOnMsr = *DebuggerReadAndWriteOnMsr

// @brief request for edit virtual and physical memory
type PdebuggerEditMemory = *DebuggerEditMemory

// @brief request for searching memory
type PdebuggerSearchMemory = *DebuggerSearchMemory

// @brief request for enable or disable transparent-mode
type PdebuggerHideAndTransparentDebuggerMode = *DebuggerHideAndTransparentDebuggerMode

// @brief request to make this computer to a debuggee
type PdebuggerPrepareDebuggee = *DebuggerPrepareDebuggee

// @brief The structure of changing core packet in HyperDbg
type PdebuggeeChangeCorePacket = *DebuggeeChangeCorePacket

// @brief request for attaching user-mode process
type PdebuggerAttachDetachUserModeProcess = *DebuggerAttachDetachUserModeProcess

// @brief The structure of needed information to get the details
// of the process from nt!_EPROCESS and location of needed variables
type PdebuggeeProcessListNeededDetails = *DebuggeeProcessListNeededDetails

// @brief The structure of needed information to get the details
// of the thread from nt!_ETHREAD and location of needed variables
type PdebuggeeThreadListNeededDetails = *DebuggeeThreadListNeededDetails

// @brief The structure showing list of processes (details of each
// entry)
type PdebuggeeProcessListDetailsEntry = *DebuggeeProcessListDetailsEntry

// @brief The structure showing list of threads (details of each
// entry)
type PdebuggeeThreadListDetailsEntry = *DebuggeeThreadListDetailsEntry

// @brief request for query count of active processes and threads
type PdebuggerQueryActiveProcessesOrThreads = *DebuggerQueryActiveProcessesOrThreads

// @brief The structure for saving the callstack frame of one parameter
type PdebuggerSingleCallstackFrame = *DebuggerSingleCallstackFrame

// @brief request for callstack frames
type (
	PdebuggerCallstackRequest                     = *DebuggerCallstackRequest
	PusermodeDebuggingThreadOrProcessStateDetails = *UsermodeDebuggingThreadOrProcessStateDetails
)

// @brief Used for run the script
type PdebuggerEventActionRunScriptConfiguration = *DebuggerEventActionRunScriptConfiguration

// @brief used in the case of requesting a "request buffer"
type PdebuggerEventRequestBuffer = *DebuggerEventRequestBuffer

// @brief used in the case of custom code requests to the debugger
type PdebuggerEventRequestCustomCode = *DebuggerEventRequestCustomCode

// @brief Description of user-mode debugging actions
type PdebuggerUdCommandAction = *DebuggerUdCommandAction

// @brief The structure of command packet in uHyperDbg
type PdebuggerUdCommandPacket = *DebuggerUdCommandPacket

// @brief The structure of changing process and show process
// packet in HyperDbg
type PdebuggeeDetailsAndSwitchProcessPacket = *DebuggeeDetailsAndSwitchProcessPacket

// @brief The structure of changing thead and show thread
// packet in HyperDbg
type PdebuggeeDetailsAndSwitchThreadPacket = *DebuggeeDetailsAndSwitchThreadPacket

// @brief The structure of stepping packet in HyperDbg
type PdebuggeeStepPacket = *DebuggeeStepPacket

// @brief The structure of .formats result packet in HyperDbg
type PdebuggeeFormatsPacket = *DebuggeeFormatsPacket

// @brief The structure of .sym reload packet in HyperDbg
type PdebuggeeSymbolRequestPacket = *DebuggeeSymbolRequestPacket

// @brief The structure of bp command packet in HyperDbg
type PdebuggeeBpPacket = *DebuggeeBpPacket

// @brief The structure of breakpoint modification requests packet in HyperDbg
type PdebuggeeBpListOrModifyPacket = *DebuggeeBpListOrModifyPacket

// @brief The structure of script packet in HyperDbg
type PdebuggeeScriptPacket = *DebuggeeScriptPacket

// @brief The structure of result of search packet in HyperDbg
type PdebuggeeResultOfSearchPacket = *DebuggeeResultOfSearchPacket

// @brief Register Descriptor Structure to use in r command.
type PdebuggeeRegisterReadDescription = *DebuggeeRegisterReadDescription

// @brief structures for sending and saving details
// about each module and symbols details
type (
	PmoduleSymbolDetail          = *ModuleSymbolDetail
	PusermodeLoadedModuleSymbols = *UsermodeLoadedModuleSymbols
	PusermodeLoadedModuleDetails = *UsermodeLoadedModuleDetails
)

// @brief Callback type that should be used to add
// list of Addresses to ObjectNames
type SymbolMapCallback = unsafe.Pointer

// @brief request to add new symbol detail or update a previous
// symbol table entry
type PdebuggerUpdateSymbolTable = *DebuggerUpdateSymbolTable

// @brief request that shows, symbol reload process is finished
type PdebuggeeSymbolUpdateResult = *DebuggeeSymbolUpdateResult

var __imp_hyperdbg_u_detect_vmx_support bindlib.PreloadProc

// Gengo init function.
func init() {
	__imp_hyperdbg_u_detect_vmx_support = GengoLibrary.ImportNow("hyperdbg_u_detect_vmx_support")
	__imp_hyperdbg_u_read_vendor_string = GengoLibrary.ImportNow("hyperdbg_u_read_vendor_string")
	__imp_hyperdbg_u_load_vmm = GengoLibrary.ImportNow("hyperdbg_u_load_vmm")
	__imp_hyperdbg_u_unload_vmm = GengoLibrary.ImportNow("hyperdbg_u_unload_vmm")
	__imp_hyperdbg_u_install_vmm_driver = GengoLibrary.ImportNow("hyperdbg_u_install_vmm_driver")
	__imp_hyperdbg_u_uninstall_vmm_driver = GengoLibrary.ImportNow("hyperdbg_u_uninstall_vmm_driver")
	__imp_hyperdbg_u_stop_vmm_driver = GengoLibrary.ImportNow("hyperdbg_u_stop_vmm_driver")
	__imp_hyperdbg_u_interpreter = GengoLibrary.ImportNow("hyperdbg_u_interpreter")
	__imp_hyperdbg_u_show_signature = GengoLibrary.ImportNow("hyperdbg_u_show_signature")
	__imp_hyperdbg_u_set_text_message_callback = GengoLibrary.ImportNow("hyperdbg_u_set_text_message_callback")
	__imp_hyperdbg_u_script_read_file_and_execute_commandline = GengoLibrary.ImportNow("hyperdbg_u_script_read_file_and_execute_commandline")
	__imp_hyperdbg_u_continue_previous_command = GengoLibrary.ImportNow("hyperdbg_u_continue_previous_command")
	__imp_hyperdbg_u_check_multiline_command = GengoLibrary.ImportNow("hyperdbg_u_check_multiline_command")
	__imp_hyperdbg_u_set_custom_driver_path = GengoLibrary.ImportNow("hyperdbg_u_set_custom_driver_path")
	__imp_hyperdbg_u_use_default_driver_path = GengoLibrary.ImportNow("hyperdbg_u_use_default_driver_path")
	__imp_hyperdbg_u_connect_local_debugger = GengoLibrary.ImportNow("hyperdbg_u_connect_local_debugger")
	__imp_hyperdbg_u_connect_remote_debugger = GengoLibrary.ImportNow("hyperdbg_u_connect_remote_debugger")
	return
	__imp_hyperdbg_u_continue_debuggee = GengoLibrary.ImportNow("hyperdbg_u_continue_debuggee")
	__imp_hyperdbg_u_pause_debuggee = GengoLibrary.ImportNow("hyperdbg_u_pause_debuggee")
	__imp_hyperdbg_u_set_breakpoint = GengoLibrary.ImportNow("hyperdbg_u_set_breakpoint")
	__imp_ScriptEngineParse = GengoLibrary.ImportNow("ScriptEngineParse")
	__imp_PrintSymbolBuffer = GengoLibrary.ImportNow("PrintSymbolBuffer")
	__imp_PrintSymbol = GengoLibrary.ImportNow("PrintSymbol")
	__imp_RemoveSymbolBuffer = GengoLibrary.ImportNow("RemoveSymbolBuffer")
	__imp_FuncGetNumberOfOperands = GengoLibrary.ImportNow("FuncGetNumberOfOperands")
	__imp_ScriptEngineSetHwdbgInstanceInfo = GengoLibrary.ImportNow("ScriptEngineSetHwdbgInstanceInfo")
	__imp_ScriptEngineSetTextMessageCallback = GengoLibrary.ImportNow("ScriptEngineSetTextMessageCallback")
	__imp_ScriptEngineSymbolAbortLoading = GengoLibrary.ImportNow("ScriptEngineSymbolAbortLoading")
	__imp_ScriptEngineConvertNameToAddress = GengoLibrary.ImportNow("ScriptEngineConvertNameToAddress")
	__imp_ScriptEngineLoadFileSymbol = GengoLibrary.ImportNow("ScriptEngineLoadFileSymbol")
	__imp_ScriptEngineUnloadAllSymbols = GengoLibrary.ImportNow("ScriptEngineUnloadAllSymbols")
	__imp_ScriptEngineUnloadModuleSymbol = GengoLibrary.ImportNow("ScriptEngineUnloadModuleSymbol")
	__imp_ScriptEngineSearchSymbolForMask = GengoLibrary.ImportNow("ScriptEngineSearchSymbolForMask")
	__imp_ScriptEngineGetFieldOffset = GengoLibrary.ImportNow("ScriptEngineGetFieldOffset")
	__imp_ScriptEngineGetDataTypeSize = GengoLibrary.ImportNow("ScriptEngineGetDataTypeSize")
	__imp_ScriptEngineCreateSymbolTableForDisassembler = GengoLibrary.ImportNow("ScriptEngineCreateSymbolTableForDisassembler")
	__imp_ScriptEngineConvertFileToPdbPath = GengoLibrary.ImportNow("ScriptEngineConvertFileToPdbPath")
	__imp_ScriptEngineConvertFileToPdbFileAndGuidAndAgeDetails = GengoLibrary.ImportNow("ScriptEngineConvertFileToPdbFileAndGuidAndAgeDetails")
	__imp_ScriptEngineSymbolInitLoad = GengoLibrary.ImportNow("ScriptEngineSymbolInitLoad")
	__imp_ScriptEngineShowDataBasedOnSymbolTypes = GengoLibrary.ImportNow("ScriptEngineShowDataBasedOnSymbolTypes")
	__imp_SymSetTextMessageCallback = GengoLibrary.ImportNow("SymSetTextMessageCallback")
	__imp_SymbolAbortLoading = GengoLibrary.ImportNow("SymbolAbortLoading")
	__imp_SymConvertNameToAddress = GengoLibrary.ImportNow("SymConvertNameToAddress")
	__imp_SymLoadFileSymbol = GengoLibrary.ImportNow("SymLoadFileSymbol")
	__imp_SymUnloadAllSymbols = GengoLibrary.ImportNow("SymUnloadAllSymbols")
	__imp_SymUnloadModuleSymbol = GengoLibrary.ImportNow("SymUnloadModuleSymbol")
	__imp_SymSearchSymbolForMask = GengoLibrary.ImportNow("SymSearchSymbolForMask")
	__imp_SymGetFieldOffset = GengoLibrary.ImportNow("SymGetFieldOffset")
	__imp_SymGetDataTypeSize = GengoLibrary.ImportNow("SymGetDataTypeSize")
	__imp_SymCreateSymbolTableForDisassembler = GengoLibrary.ImportNow("SymCreateSymbolTableForDisassembler")
	__imp_SymConvertFileToPdbPath = GengoLibrary.ImportNow("SymConvertFileToPdbPath")
	__imp_SymConvertFileToPdbFileAndGuidAndAgeDetails = GengoLibrary.ImportNow("SymConvertFileToPdbFileAndGuidAndAgeDetails")
	__imp_SymbolInitLoad = GengoLibrary.ImportNow("SymbolInitLoad")
	__imp_SymShowDataBasedOnSymbolTypes = GengoLibrary.ImportNow("SymShowDataBasedOnSymbolTypes")
	__imp_SymQuerySizeof = GengoLibrary.ImportNow("SymQuerySizeof")
	__imp_SymCastingQueryForFiledsAndTypes = GengoLibrary.ImportNow("SymCastingQueryForFiledsAndTypes")
	bindlib.Validate((*ListEntry)(nil), 0x10, 0x8, "Flink", 0x0, "Blink", 0x8)
	bindlib.Validate((*GuestRegs)(nil), 0x80, 0x8, "Rax", 0x0, "Rcx", 0x8, "Rdx", 0x10, "Rbx", 0x18, "Rsp", 0x20, "Rbp", 0x28, "Rsi", 0x30, "Rdi", 0x38, "R8", 0x40, "R9", 0x48, "R10", 0x50, "R11", 0x58, "R12", 0x60, "R13", 0x68, "R14", 0x70, "R15", 0x78)
	bindlib.Validate((*GuestExtraRegisters)(nil), 0x20, 0x8, "Cs", 0x0, "Ds", 0x2, "Fs", 0x4, "Gs", 0x6, "Es", 0x8, "Ss", 0xa, "Rflags", 0x10, "Rip", 0x18)
	bindlib.Validate((*ScriptEngineVariablesList)(nil), 0x18, 0x8, "TempList", 0x0, "GlobalVariablesList", 0x8, "LocalVariablesList", 0x10)
	bindlib.Validate((*Cr3Type)(nil), 0x8, 0x8)
	bindlib.Validate((*Anon196_5)(nil), 0x8, 0x8)
	bindlib.Validate((*Anon200_9)(nil), 0x8, 0x8, "Pcid", 0xc, "PageFrameNumber", 0x30, "Reserved1", 0x3c, "Reserved_2", 0x3f, "PcidInvalidate", 0x40)
	bindlib.Validate((*DebuggerRemotePacket)(nil), 0x18, 0x8, "Checksum", 0x0, "Indicator", 0x8, "TypeOfThePacket", 0x10, "RequestedActionOfThePacket", 0x14)
	bindlib.Validate((*DebuggeeUserInputPacket)(nil), 0xc, 0x4, "CommandLen", 0x0, "IgnoreFinishedSignal", 0x4, "Result", 0x8)
	bindlib.Validate((*DebuggeeEventAndActionHeaderForRemotePacket)(nil), 0x4, 0x4, "Length", 0x0)
	bindlib.Validate((*DebuggerPausePacketReceived)(nil), 0x4, 0x4, "Result", 0x0)
	bindlib.Validate((*DebuggerTriggeredEventDetails)(nil), 0x18, 0x8, "Tag", 0x0, "Context", 0x8, "Stage", 0x10)
	bindlib.Validate((*DebuggeeKdPausedPacket)(nil), 0x48, 0x8, "Rip", 0x0, "IsProcessorOn32BitMode", 0x8, "IgnoreDisassembling", 0x9, "PausingReason", 0xc, "CurrentCore", 0x10, "EventTag", 0x18, "EventCallingStage", 0x20, "Rflags", 0x28, "InstructionBytesOnRip", 0x30, "ReadInstructionLen", 0x40)
	bindlib.Validate((*DebuggeeUdPausedPacket)(nil), 0xc8, 0x8, "Rip", 0x0, "ProcessDebuggingToken", 0x8, "Is32Bit", 0x10, "PausingReason", 0x14, "ProcessId", 0x18, "ThreadId", 0x1c, "Rflags", 0x20, "EventTag", 0x28, "EventCallingStage", 0x30, "InstructionBytesOnRip", 0x34, "ReadInstructionLen", 0x44, "GuestRegs", 0x48)
	bindlib.Validate((*DebuggeeMessagePacket)(nil), 0x1004, 0x4, "OperationCode", 0x0, "Message", 0x4)
	bindlib.Validate((*RegisterNotifyBuffer)(nil), 0x10, 0x8, "Type", 0x0, "hEvent", 0x8)
	bindlib.Validate((*DirectVmcallParameters)(nil), 0x18, 0x8, "OptionalParam1", 0x0, "OptionalParam2", 0x8, "OptionalParam3", 0x10)
	bindlib.Validate((*EptHooksContext)(nil), 0x18, 0x8, "HookingTag", 0x0, "PhysicalAddress", 0x8, "VirtualAddress", 0x10)
	bindlib.Validate((*EptHooksAddressDetailsForMemoryMonitor)(nil), 0x20, 0x8, "StartAddress", 0x0, "EndAddress", 0x8, "SetHookForRead", 0x10, "SetHookForWrite", 0x11, "SetHookForExec", 0x12, "MemoryType", 0x14, "Tag", 0x18)
	bindlib.Validate((*EptHooksAddressDetailsForEpthook2)(nil), 0x10, 0x8, "TargetAddress", 0x0, "HookFunction", 0x8)
	bindlib.Validate((*EptSingleHookUnhookingDetails)(nil), 0x18, 0x8, "CallerNeedsToRestoreEntryAndInvalidateEpt", 0x0, "RemoveBreakpointInterception", 0x1, "PhysicalAddress", 0x8, "OriginalEntry", 0x10)
	bindlib.Validate((*Anon1497_9)(nil), 0x4, 0x4)
	bindlib.Validate((*Anon1499_5)(nil), 0x4, 0x4, "Type", 0x4, "DescriptorType", 0x5, "DescriptorPrivilegeLevel", 0x7, "Present", 0x8, "Reserved1", 0xc, "AvailableBit", 0xd, "LongMode", 0xe, "DefaultBig", 0xf, "Granularity", 0x10, "Unusable", 0x11, "Reserved2", 0x20)
	bindlib.Validate((*VmxSegmentSelector)(nil), 0x18, 0x8, "Selector", 0x0, "Attributes", 0x4, "Limit", 0x8, "Base", 0x10)
	bindlib.Validate((*DebuggerModifyEvents)(nil), 0x18, 0x8, "Tag", 0x0, "KernelStatus", 0x8, "TypeOfAction", 0x10, "IsEnabled", 0x14)
	bindlib.Validate((*DebuggerShortCircuitingEvent)(nil), 0x10, 0x8, "KernelStatus", 0x0, "IsShortCircuiting", 0x8)
	bindlib.Validate((*DebuggerEventOptions)(nil), 0x30, 0x8, "OptionalParam1", 0x0, "OptionalParam2", 0x8, "OptionalParam3", 0x10, "OptionalParam4", 0x18, "OptionalParam5", 0x20, "OptionalParam6", 0x28)
	bindlib.Validate((*DebuggerGeneralEventDetail)(nil), 0xb0, 0x8, "CommandsEventList", 0x0, "CreationTime", 0x10, "CoreId", 0x18, "ProcessId", 0x1c, "IsEnabled", 0x20, "EnableShortCircuiting", 0x21, "EventStage", 0x24, "HasCustomOutput", 0x28, "OutputSourceTags", 0x30, "CountOfActions", 0x58, "Tag", 0x60, "EventType", 0x68, "Options", 0x70, "CommandStringBuffer", 0xa0, "ConditionBufferSize", 0xa8)
	bindlib.Validate((*DebuggerGeneralAction)(nil), 0x20, 0x8, "EventTag", 0x0, "ActionType", 0x8, "ImmediateMessagePassing", 0xc, "PreAllocatedBuffer", 0x10, "CustomCodeBufferSize", 0x14, "ScriptBufferSize", 0x18, "ScriptBufferPointer", 0x1c)
	bindlib.Validate((*DebuggerEventAndActionResult)(nil), 0x8, 0x4, "IsSuccessful", 0x0, "Error", 0x4)
	bindlib.Validate((*HwdbgPortInformationItems)(nil), 0x4, 0x4, "PortSize", 0x0)
	bindlib.Validate((*HwdbgInstanceInformation)(nil), 0x40, 0x4, "Version", 0x0, "maximumNumberOfStages", 0x4, "scriptVariableLength", 0x8, "numberOfSupportedLocalAndGlobalVariables", 0xc, "numberOfSupportedTemporaryVariables", 0x10, "maximumNumberOfSupportedGetScriptOperators", 0x14, "maximumNumberOfSupportedSetScriptOperators", 0x18, "sharedMemorySize", 0x1c, "debuggerAreaOffset", 0x20, "debuggeeAreaOffset", 0x24, "numberOfPins", 0x28, "numberOfPorts", 0x2c, "scriptCapabilities", 0x30, "bramAddrWidth", 0x38, "bramDataWidth", 0x3c)
	bindlib.Validate((*_HwdbgScriptCapabilities)(nil), 0x8, 0x4, "AssignLocalGlobalVar", 0x1, "AssignRegisters", 0x2, "AssignPseudoRegisters", 0x3, "ConditionalStatementsAndComparisonOperators", 0x4, "FuncOr", 0x5, "FuncXor", 0x6, "FuncAnd", 0x7, "FuncAsr", 0x8, "FuncAsl", 0x9, "FuncAdd", 0xa, "FuncSub", 0xb, "FuncMul", 0xc, "FuncDiv", 0xd, "FuncMod", 0xe, "FuncGt", 0xf, "FuncLt", 0x10, "FuncEgt", 0x11, "FuncElt", 0x12, "FuncEqual", 0x13, "FuncNeq", 0x14, "FuncJmp", 0x15, "FuncJz", 0x16, "FuncJnz", 0x17, "FuncMov", 0x18, "FuncPrintf", 0x19)
	bindlib.Validate((*HwdbgScriptBuffer)(nil), 0x4, 0x4, "scriptNumberOfSymbols", 0x0)
	bindlib.Validate((*DebuggerReadPageTableEntriesDetails)(nil), 0x58, 0x8, "VirtualAddress", 0x0, "ProcessId", 0x8, "Pml4eVirtualAddress", 0x10, "Pml4eValue", 0x18, "PdpteVirtualAddress", 0x20, "PdpteValue", 0x28, "PdeVirtualAddress", 0x30, "PdeValue", 0x38, "PteVirtualAddress", 0x40, "PteValue", 0x48, "KernelStatus", 0x50)
	bindlib.Validate((*DebuggerVa2paAndPa2vaCommands)(nil), 0x20, 0x8, "VirtualAddress", 0x0, "PhysicalAddress", 0x8, "ProcessId", 0x10, "IsVirtual2Physical", 0x14, "KernelStatus", 0x18)
	bindlib.Validate((*DebuggerPageInRequest)(nil), 0x20, 0x8, "VirtualAddressFrom", 0x0, "VirtualAddressTo", 0x8, "ProcessId", 0x10, "PageFaultErrorCode", 0x14, "KernelStatus", 0x18)
	bindlib.Validate((*ReversingMachineReconstructMemoryRequest)(nil), 0x14, 0x4, "ProcessId", 0x0, "Size", 0x4, "Mode", 0x8, "Type", 0xc, "KernelStatus", 0x10)
	bindlib.Validate((*DebuggerDtCommandOptions)(nil), 0x38, 0x8, "TypeName", 0x0, "SizeOfTypeName", 0x8, "Address", 0x10, "IsStruct", 0x18, "BufferAddress", 0x20, "TargetPid", 0x28, "AdditionalParameters", 0x30)
	bindlib.Validate((*DebuggerPreallocCommand)(nil), 0xc, 0x4, "Type", 0x0, "Count", 0x4, "KernelStatus", 0x8)
	bindlib.Validate((*DebuggerPreactivateCommand)(nil), 0x8, 0x4, "Type", 0x0, "KernelStatus", 0x4)
	bindlib.Validate((*DebuggerReadMemory)(nil), 0x38, 0x8, "Pid", 0x0, "Address", 0x8, "Size", 0x10, "IsForDisasm", 0x14, "Is32BitAddress", 0x15, "MemoryType", 0x18, "ReadingType", 0x1c, "DtDetails", 0x20, "Style", 0x28, "ReturnLength", 0x2c, "KernelStatus", 0x30)
	bindlib.Validate((*DebuggerFlushLoggingBuffers)(nil), 0xc, 0x4, "KernelStatus", 0x0, "CountOfMessagesThatSetAsReadFromVmxRoot", 0x4, "CountOfMessagesThatSetAsReadFromVmxNonRoot", 0x8)
	bindlib.Validate((*DebuggerDebuggerTestQueryBuffer)(nil), 0x18, 0x8, "RequestType", 0x0, "Context", 0x8, "KernelStatus", 0x10)
	bindlib.Validate((*DebuggerPerformKernelTests)(nil), 0x4, 0x4, "KernelStatus", 0x0)
	bindlib.Validate((*DebuggerSendCommandExecutionFinishedSignal)(nil), 0x4, 0x4, "KernelStatus", 0x0)
	bindlib.Validate((*DebuggeeSendGeneralPacketFromDebuggeeToDebugger)(nil), 0x10, 0x4, "RequestedAction", 0x0, "LengthOfBuffer", 0x4, "PauseDebuggeeWhenSent", 0x8, "KernelResult", 0xc)
	bindlib.Validate((*DebuggerSendUsermodeMessagesToDebugger)(nil), 0x8, 0x4, "KernelStatus", 0x0, "Length", 0x4)
	bindlib.Validate((*DebuggerReadAndWriteOnMsr)(nil), 0x18, 0x8, "Msr", 0x0, "CoreNumber", 0x8, "ActionType", 0xc, "Value", 0x10)
	bindlib.Validate((*DebuggerEditMemory)(nil), 0x28, 0x8, "Result", 0x0, "Address", 0x8, "ProcessId", 0x10, "MemoryType", 0x14, "ByteSize", 0x18, "CountOf64Chunks", 0x1c, "FinalStructureSize", 0x20, "KernelStatus", 0x24)
	bindlib.Validate((*DebuggerSearchMemory)(nil), 0x28, 0x8, "Address", 0x0, "Length", 0x8, "ProcessId", 0x10, "MemoryType", 0x14, "ByteSize", 0x18, "CountOf64Chunks", 0x1c, "FinalStructureSize", 0x20)
	bindlib.Validate((*DebuggerHideAndTransparentDebuggerMode)(nil), 0x50, 0x8, "IsHide", 0x0, "CpuidAverage", 0x8, "CpuidStandardDeviation", 0x10, "CpuidMedian", 0x18, "RdtscAverage", 0x20, "RdtscStandardDeviation", 0x28, "RdtscMedian", 0x30, "TrueIfProcessIdAndFalseIfProcessName", 0x38, "ProcId", 0x3c, "LengthOfProcessName", 0x40, "KernelStatus", 0x48)
	bindlib.Validate((*DebuggerPrepareDebuggee)(nil), 0x118, 0x8, "PortAddress", 0x0, "Baudrate", 0x4, "NtoskrnlBaseAddress", 0x8, "Result", 0x10, "OsName", 0x14)
	bindlib.Validate((*DebuggeeChangeCorePacket)(nil), 0x8, 0x4, "NewCore", 0x0, "Result", 0x4)
	bindlib.Validate((*DebuggerAttachDetachUserModeProcess)(nil), 0x28, 0x8, "IsStartingNewProcess", 0x0, "ProcessId", 0x4, "ThreadId", 0x8, "CheckCallbackAtFirstInstruction", 0xc, "Is32Bit", 0xd, "IsPaused", 0xe, "Action", 0x10, "CountOfActiveDebuggingThreadsAndProcesses", 0x14, "Token", 0x18, "Result", 0x20)
	bindlib.Validate((*DebuggeeProcessListNeededDetails)(nil), 0x18, 0x8, "PsActiveProcessHead", 0x0, "ImageFileNameOffset", 0x8, "UniquePidOffset", 0xc, "ActiveProcessLinksOffset", 0x10)
	bindlib.Validate((*DebuggeeThreadListNeededDetails)(nil), 0x28, 0x8, "ThreadListHeadOffset", 0x0, "ThreadListEntryOffset", 0x4, "CidOffset", 0x8, "PsActiveProcessHead", 0x10, "ActiveProcessLinksOffset", 0x18, "Process", 0x20)
	bindlib.Validate((*DebuggeeProcessListDetailsEntry)(nil), 0x28, 0x8, "Eprocess", 0x0, "ProcessId", 0x8, "Cr3", 0x10, "ImageFileName", 0x18)
	bindlib.Validate((*DebuggeeThreadListDetailsEntry)(nil), 0x28, 0x8, "Eprocess", 0x0, "Ethread", 0x8, "ProcessId", 0x10, "ThreadId", 0x14, "ImageFileName", 0x18)
	bindlib.Validate((*DebuggerQueryActiveProcessesOrThreads)(nil), 0x58, 0x8, "ProcessListNeededDetails", 0x0, "ThreadListNeededDetails", 0x18, "QueryType", 0x40, "QueryAction", 0x44, "Count", 0x48, "Result", 0x50)
	bindlib.Validate((*DebuggerSingleCallstackFrame)(nil), 0x18, 0x8, "IsStackAddressValid", 0x0, "IsValidAddress", 0x1, "IsExecutable", 0x2, "Value", 0x8, "InstructionBytesOnRip", 0x10)
	bindlib.Validate((*DebuggerCallstackRequest)(nil), 0x28, 0x8, "Is32Bit", 0x0, "KernelStatus", 0x4, "DisplayMethod", 0x8, "Size", 0xc, "FrameCount", 0x10, "BaseAddress", 0x18, "BufferSize", 0x20)
	bindlib.Validate((*UsermodeDebuggingThreadOrProcessStateDetails)(nil), 0xc, 0x4, "ProcessId", 0x0, "ThreadId", 0x4, "IsProcess", 0x8)
	bindlib.Validate((*DebuggerEventActionRunScriptConfiguration)(nil), 0x18, 0x8, "ScriptBuffer", 0x0, "ScriptLength", 0x8, "ScriptPointer", 0xc, "OptionalRequestedBufferSize", 0x10)
	bindlib.Validate((*DebuggerEventRequestBuffer)(nil), 0x10, 0x8, "EnabledRequestBuffer", 0x0, "RequestBufferSize", 0x4, "RequstBufferAddress", 0x8)
	bindlib.Validate((*DebuggerEventRequestCustomCode)(nil), 0x18, 0x8, "CustomCodeBufferSize", 0x0, "CustomCodeBufferAddress", 0x8, "OptionalRequestedBufferSize", 0x10)
	bindlib.Validate((*DebuggerUdCommandAction)(nil), 0x28, 0x8, "ActionType", 0x0, "OptionalParam1", 0x8, "OptionalParam2", 0x10, "OptionalParam3", 0x18, "OptionalParam4", 0x20)
	bindlib.Validate((*DebuggerUdCommandPacket)(nil), 0x40, 0x8, "UdAction", 0x0, "ProcessDebuggingDetailToken", 0x28, "TargetThreadId", 0x30, "ApplyToAllPausedThreads", 0x34, "Result", 0x38)
	bindlib.Validate((*DebuggeeDetailsAndSwitchProcessPacket)(nil), 0x48, 0x8, "ActionType", 0x0, "ProcessId", 0x4, "Process", 0x8, "IsSwitchByClkIntr", 0x10, "ProcessName", 0x11, "ProcessListSymDetails", 0x28, "Result", 0x40)
	bindlib.Validate((*DebuggeeDetailsAndSwitchThreadPacket)(nil), 0x68, 0x8, "ActionType", 0x0, "ThreadId", 0x4, "ProcessId", 0x8, "Thread", 0x10, "Process", 0x18, "CheckByClockInterrupt", 0x20, "ProcessName", 0x21, "ThreadListSymDetails", 0x38, "Result", 0x60)
	bindlib.Validate((*DebuggeeStepPacket)(nil), 0xc, 0x4, "StepType", 0x0, "IsCurrentInstructionACall", 0x4, "CallLength", 0x8)
	bindlib.Validate((*DebuggeeFormatsPacket)(nil), 0x10, 0x8, "Value", 0x0, "Result", 0x8)
	bindlib.Validate((*DebuggeeSymbolRequestPacket)(nil), 0x4, 0x4, "ProcessId", 0x0)
	bindlib.Validate((*DebuggeeBpPacket)(nil), 0x20, 0x8, "Address", 0x0, "Pid", 0x8, "Tid", 0xc, "Core", 0x10, "RemoveAfterHit", 0x14, "CheckForCallbacks", 0x15, "Result", 0x18)
	bindlib.Validate((*DebuggeeBpListOrModifyPacket)(nil), 0x10, 0x8, "BreakpointId", 0x0, "Request", 0x8, "Result", 0xc)
	bindlib.Validate((*DebuggeeScriptPacket)(nil), 0x10, 0x4, "ScriptBufferSize", 0x0, "ScriptBufferPointer", 0x4, "IsFormat", 0x8, "Result", 0xc)
	bindlib.Validate((*DebuggeeResultOfSearchPacket)(nil), 0x8, 0x4, "CountOfResults", 0x0, "Result", 0x4)
	bindlib.Validate((*DebuggeeRegisterReadDescription)(nil), 0x18, 0x8, "RegisterID", 0x0, "Value", 0x8, "KernelStatus", 0x10)
	bindlib.Validate((*ModuleSymbolDetail)(nil), 0x258, 0x8, "IsSymbolDetailsFound", 0x0, "IsLocalSymbolPath", 0x1, "IsSymbolPDBAvaliable", 0x2, "IsUserMode", 0x3, "Is32Bit", 0x4, "BaseAddress", 0x8, "FilePath", 0x10, "ModuleSymbolPath", 0x114, "ModuleSymbolGuidAndAge", 0x218)
	bindlib.Validate((*UsermodeLoadedModuleSymbols)(nil), 0x420, 0x8, "BaseAddress", 0x0, "Entrypoint", 0x8, "FilePath", 0x10)
	bindlib.Validate((*UsermodeLoadedModuleDetails)(nil), 0x10, 0x4, "ProcessId", 0x0, "OnlyCountModules", 0x4, "Is32Bit", 0x5, "ModulesCount", 0x8, "Result", 0xc)
	bindlib.Validate((*DebuggerUpdateSymbolTable)(nil), 0x260, 0x8, "TotalSymbols", 0x0, "CurrentSymbolIndex", 0x4, "SymbolDetailPacket", 0x8)
	bindlib.Validate((*DebuggeeSymbolUpdateResult)(nil), 0x8, 0x8, "KernelStatus", 0x0)
}

func DetectVmxSupport() Boolean {
	__res := bindlib.CCall0(__imp_hyperdbg_u_detect_vmx_support.Addr())
	return bindlib.UnmarshallSyscall[Boolean](__res)
}

var __imp_hyperdbg_u_read_vendor_string bindlib.PreloadProc

func ReadVendorString(b *Char) {
	bindlib.CCall1(__imp_hyperdbg_u_read_vendor_string.Addr(), bindlib.MarshallSyscall(b))
}

var __imp_hyperdbg_u_load_vmm bindlib.PreloadProc

func LoadVmm() Int {
	__res := bindlib.CCall0(__imp_hyperdbg_u_load_vmm.Addr())
	return bindlib.UnmarshallSyscall[Int](__res)
}

var __imp_hyperdbg_u_unload_vmm bindlib.PreloadProc

func UnloadVmm() Int {
	__res := bindlib.CCall0(__imp_hyperdbg_u_unload_vmm.Addr())
	return bindlib.UnmarshallSyscall[Int](__res)
}

var __imp_hyperdbg_u_install_vmm_driver bindlib.PreloadProc

func InstallVmmDriver() Int {
	__res := bindlib.CCall0(__imp_hyperdbg_u_install_vmm_driver.Addr())
	return bindlib.UnmarshallSyscall[Int](__res)
}

var __imp_hyperdbg_u_uninstall_vmm_driver bindlib.PreloadProc

func UninstallVmmDriver() Int {
	__res := bindlib.CCall0(__imp_hyperdbg_u_uninstall_vmm_driver.Addr())
	return bindlib.UnmarshallSyscall[Int](__res)
}

var __imp_hyperdbg_u_stop_vmm_driver bindlib.PreloadProc

func StopVmmDriver() Int {
	__res := bindlib.CCall0(__imp_hyperdbg_u_stop_vmm_driver.Addr())
	return bindlib.UnmarshallSyscall[Int](__res)
}

var __imp_hyperdbg_u_interpreter bindlib.PreloadProc

func Interpreter(command *Char) Int {
	__res := bindlib.CCall1(__imp_hyperdbg_u_interpreter.Addr(), bindlib.MarshallSyscall(command))
	return bindlib.UnmarshallSyscall[Int](__res)
}

var __imp_hyperdbg_u_show_signature bindlib.PreloadProc

func ShowSignature() { bindlib.CCall0(__imp_hyperdbg_u_show_signature.Addr()) }

var __imp_hyperdbg_u_set_text_message_callback bindlib.PreloadProc

func SetTextMessageCallback(handler Callback) {
	bindlib.CCall1(__imp_hyperdbg_u_set_text_message_callback.Addr(), bindlib.MarshallSyscall(handler))
}

var __imp_hyperdbg_u_script_read_file_and_execute_commandline bindlib.PreloadProc

func ScriptReadFileAndExecuteCommandline(argc Int, argv **Char) Int {
	__res := bindlib.CCall2(__imp_hyperdbg_u_script_read_file_and_execute_commandline.Addr(), bindlib.MarshallSyscall(argc), bindlib.MarshallSyscall(argv))
	return bindlib.UnmarshallSyscall[Int](__res)
}

var __imp_hyperdbg_u_continue_previous_command bindlib.PreloadProc

func ContinuePreviousCommand() Boolean {
	__res := bindlib.CCall0(__imp_hyperdbg_u_continue_previous_command.Addr())
	return bindlib.UnmarshallSyscall[Boolean](__res)
}

var __imp_hyperdbg_u_check_multiline_command bindlib.PreloadProc

func CheckMultilineCommand(current_command *Char, reset Boolean) Boolean {
	__res := bindlib.CCall2(__imp_hyperdbg_u_check_multiline_command.Addr(), bindlib.MarshallSyscall(current_command), bindlib.MarshallSyscall(reset))
	return bindlib.UnmarshallSyscall[Boolean](__res)
}

var __imp_hyperdbg_u_set_custom_driver_path bindlib.PreloadProc

func SetCustomDriverPath(DriverFilePath *Char, DriverName *Char) Boolean {
	__res := bindlib.CCall2(__imp_hyperdbg_u_set_custom_driver_path.Addr(), bindlib.MarshallSyscall(DriverFilePath), bindlib.MarshallSyscall(DriverName))
	return bindlib.UnmarshallSyscall[Boolean](__res)
}

var __imp_hyperdbg_u_use_default_driver_path bindlib.PreloadProc

func UseDefaultDriverPath() { bindlib.CCall0(__imp_hyperdbg_u_use_default_driver_path.Addr()) }

var __imp_hyperdbg_u_connect_local_debugger bindlib.PreloadProc

func ConnectLocalDebugger() { bindlib.CCall0(__imp_hyperdbg_u_connect_local_debugger.Addr()) }

var __imp_hyperdbg_u_connect_remote_debugger bindlib.PreloadProc

func ConnectRemoteDebugger(ip *Char, port *Char) Boolean {
	__res := bindlib.CCall2(__imp_hyperdbg_u_connect_remote_debugger.Addr(), bindlib.MarshallSyscall(ip), bindlib.MarshallSyscall(port))
	return bindlib.UnmarshallSyscall[Boolean](__res)
}

var __imp_hyperdbg_u_continue_debuggee bindlib.PreloadProc

func ContinueDebuggee() { bindlib.CCall0(__imp_hyperdbg_u_continue_debuggee.Addr()) }

var __imp_hyperdbg_u_pause_debuggee bindlib.PreloadProc

func PauseDebuggee() { bindlib.CCall0(__imp_hyperdbg_u_pause_debuggee.Addr()) }

var __imp_hyperdbg_u_set_breakpoint bindlib.PreloadProc

func SetBreakpoint(Address Uint64, Pid Uint32, Tid Uint32, CoreNumer Uint32) {
	bindlib.CCall4(__imp_hyperdbg_u_set_breakpoint.Addr(), bindlib.MarshallSyscall(Address), bindlib.MarshallSyscall(Pid), bindlib.MarshallSyscall(Tid), bindlib.MarshallSyscall(CoreNumer))
}

var __imp_ScriptEngineParse bindlib.PreloadProc

func ScriptEngineParse(str *byte) unsafe.Pointer {
	__res := bindlib.CCall1(__imp_ScriptEngineParse.Addr(), bindlib.MarshallSyscall(str))
	return bindlib.UnmarshallSyscall[unsafe.Pointer](__res)
}

var __imp_PrintSymbolBuffer bindlib.PreloadProc

func PrintSymbolBuffer(SymbolBuffer unsafe.Pointer) {
	bindlib.CCall1(__imp_PrintSymbolBuffer.Addr(), bindlib.MarshallSyscall(SymbolBuffer))
}

var __imp_PrintSymbol bindlib.PreloadProc

func PrintSymbol(Symbol unsafe.Pointer) {
	bindlib.CCall1(__imp_PrintSymbol.Addr(), bindlib.MarshallSyscall(Symbol))
}

var __imp_RemoveSymbolBuffer bindlib.PreloadProc

func RemoveSymbolBuffer(SymbolBuffer unsafe.Pointer) {
	bindlib.CCall1(__imp_RemoveSymbolBuffer.Addr(), bindlib.MarshallSyscall(SymbolBuffer))
}

var __imp_FuncGetNumberOfOperands bindlib.PreloadProc

func FuncGetNumberOfOperands(FuncType Uint64, NumberOfGetOperands *Uint32, NumberOfSetOperands *Uint32) Boolean {
	__res := bindlib.CCall3(__imp_FuncGetNumberOfOperands.Addr(), bindlib.MarshallSyscall(FuncType), bindlib.MarshallSyscall(NumberOfGetOperands), bindlib.MarshallSyscall(NumberOfSetOperands))
	return bindlib.UnmarshallSyscall[Boolean](__res)
}

var __imp_ScriptEngineSetHwdbgInstanceInfo bindlib.PreloadProc

func ScriptEngineSetHwdbgInstanceInfo(InstancInfo *HwdbgInstanceInformation) Boolean {
	__res := bindlib.CCall1(__imp_ScriptEngineSetHwdbgInstanceInfo.Addr(), bindlib.MarshallSyscall(InstancInfo))
	return bindlib.UnmarshallSyscall[Boolean](__res)
}

var __imp_ScriptEngineSetTextMessageCallback bindlib.PreloadProc

func ScriptEngineSetTextMessageCallback(Handler unsafe.Pointer) {
	bindlib.CCall1(__imp_ScriptEngineSetTextMessageCallback.Addr(), bindlib.MarshallSyscall(Handler))
}

var __imp_ScriptEngineSymbolAbortLoading bindlib.PreloadProc

func ScriptEngineSymbolAbortLoading() { bindlib.CCall0(__imp_ScriptEngineSymbolAbortLoading.Addr()) }

var __imp_ScriptEngineConvertNameToAddress bindlib.PreloadProc

func ScriptEngineConvertNameToAddress(FunctionOrVariableName *byte, WasFound Pboolean) Uint64 {
	__res := bindlib.CCall2(__imp_ScriptEngineConvertNameToAddress.Addr(), bindlib.MarshallSyscall(FunctionOrVariableName), bindlib.MarshallSyscall(WasFound))
	return bindlib.UnmarshallSyscall[Uint64](__res)
}

var __imp_ScriptEngineLoadFileSymbol bindlib.PreloadProc

func ScriptEngineLoadFileSymbol(BaseAddress Uint64, PdbFileName *byte, CustomModuleName *byte) Uint32 {
	__res := bindlib.CCall3(__imp_ScriptEngineLoadFileSymbol.Addr(), bindlib.MarshallSyscall(BaseAddress), bindlib.MarshallSyscall(PdbFileName), bindlib.MarshallSyscall(CustomModuleName))
	return bindlib.UnmarshallSyscall[Uint32](__res)
}

var __imp_ScriptEngineUnloadAllSymbols bindlib.PreloadProc

func ScriptEngineUnloadAllSymbols() Uint32 {
	__res := bindlib.CCall0(__imp_ScriptEngineUnloadAllSymbols.Addr())
	return bindlib.UnmarshallSyscall[Uint32](__res)
}

var __imp_ScriptEngineUnloadModuleSymbol bindlib.PreloadProc

func ScriptEngineUnloadModuleSymbol(ModuleName *byte) Uint32 {
	__res := bindlib.CCall1(__imp_ScriptEngineUnloadModuleSymbol.Addr(), bindlib.MarshallSyscall(ModuleName))
	return bindlib.UnmarshallSyscall[Uint32](__res)
}

var __imp_ScriptEngineSearchSymbolForMask bindlib.PreloadProc

func ScriptEngineSearchSymbolForMask(SearchMask *byte) Uint32 {
	__res := bindlib.CCall1(__imp_ScriptEngineSearchSymbolForMask.Addr(), bindlib.MarshallSyscall(SearchMask))
	return bindlib.UnmarshallSyscall[Uint32](__res)
}

var __imp_ScriptEngineGetFieldOffset bindlib.PreloadProc

func ScriptEngineGetFieldOffset(TypeName *Char, FieldName *Char, FieldOffset *Uint32) Boolean {
	__res := bindlib.CCall3(__imp_ScriptEngineGetFieldOffset.Addr(), bindlib.MarshallSyscall(TypeName), bindlib.MarshallSyscall(FieldName), bindlib.MarshallSyscall(FieldOffset))
	return bindlib.UnmarshallSyscall[Boolean](__res)
}

var __imp_ScriptEngineGetDataTypeSize bindlib.PreloadProc

func ScriptEngineGetDataTypeSize(TypeName *Char, TypeSize *Uint64) Boolean {
	__res := bindlib.CCall2(__imp_ScriptEngineGetDataTypeSize.Addr(), bindlib.MarshallSyscall(TypeName), bindlib.MarshallSyscall(TypeSize))
	return bindlib.UnmarshallSyscall[Boolean](__res)
}

var __imp_ScriptEngineCreateSymbolTableForDisassembler bindlib.PreloadProc

func ScriptEngineCreateSymbolTableForDisassembler(CallbackFunction unsafe.Pointer) Boolean {
	__res := bindlib.CCall1(__imp_ScriptEngineCreateSymbolTableForDisassembler.Addr(), bindlib.MarshallSyscall(CallbackFunction))
	return bindlib.UnmarshallSyscall[Boolean](__res)
}

var __imp_ScriptEngineConvertFileToPdbPath bindlib.PreloadProc

func ScriptEngineConvertFileToPdbPath(LocalFilePath *byte, ResultPath *byte) Boolean {
	__res := bindlib.CCall2(__imp_ScriptEngineConvertFileToPdbPath.Addr(), bindlib.MarshallSyscall(LocalFilePath), bindlib.MarshallSyscall(ResultPath))
	return bindlib.UnmarshallSyscall[Boolean](__res)
}

var __imp_ScriptEngineConvertFileToPdbFileAndGuidAndAgeDetails bindlib.PreloadProc

func ScriptEngineConvertFileToPdbFileAndGuidAndAgeDetails(LocalFilePath *byte, PdbFilePath *byte, GuidAndAgeDetails *byte, Is32BitModule Boolean) Boolean {
	__res := bindlib.CCall4(__imp_ScriptEngineConvertFileToPdbFileAndGuidAndAgeDetails.Addr(), bindlib.MarshallSyscall(LocalFilePath), bindlib.MarshallSyscall(PdbFilePath), bindlib.MarshallSyscall(GuidAndAgeDetails), bindlib.MarshallSyscall(Is32BitModule))
	return bindlib.UnmarshallSyscall[Boolean](__res)
}

var __imp_ScriptEngineSymbolInitLoad bindlib.PreloadProc

func ScriptEngineSymbolInitLoad(BufferToStoreDetails unsafe.Pointer, StoredLength Uint32, DownloadIfAvailable Boolean, SymbolPath *byte, IsSilentLoad Boolean) Boolean {
	__res := bindlib.CCall5(__imp_ScriptEngineSymbolInitLoad.Addr(), bindlib.MarshallSyscall(BufferToStoreDetails), bindlib.MarshallSyscall(StoredLength), bindlib.MarshallSyscall(DownloadIfAvailable), bindlib.MarshallSyscall(SymbolPath), bindlib.MarshallSyscall(IsSilentLoad))
	return bindlib.UnmarshallSyscall[Boolean](__res)
}

var __imp_ScriptEngineShowDataBasedOnSymbolTypes bindlib.PreloadProc

func ScriptEngineShowDataBasedOnSymbolTypes(TypeName *byte, Address Uint64, IsStruct Boolean, BufferAddress unsafe.Pointer, AdditionalParameters *byte) Boolean {
	__res := bindlib.CCall5(__imp_ScriptEngineShowDataBasedOnSymbolTypes.Addr(), bindlib.MarshallSyscall(TypeName), bindlib.MarshallSyscall(Address), bindlib.MarshallSyscall(IsStruct), bindlib.MarshallSyscall(BufferAddress), bindlib.MarshallSyscall(AdditionalParameters))
	return bindlib.UnmarshallSyscall[Boolean](__res)
}

var __imp_SymSetTextMessageCallback bindlib.PreloadProc

func SymSetTextMessageCallback(Handler unsafe.Pointer) {
	bindlib.CCall1(__imp_SymSetTextMessageCallback.Addr(), bindlib.MarshallSyscall(Handler))
}

var __imp_SymbolAbortLoading bindlib.PreloadProc

func SymbolAbortLoading() { bindlib.CCall0(__imp_SymbolAbortLoading.Addr()) }

var __imp_SymConvertNameToAddress bindlib.PreloadProc

func SymConvertNameToAddress(FunctionOrVariableName *byte, WasFound Pboolean) Uint64 {
	__res := bindlib.CCall2(__imp_SymConvertNameToAddress.Addr(), bindlib.MarshallSyscall(FunctionOrVariableName), bindlib.MarshallSyscall(WasFound))
	return bindlib.UnmarshallSyscall[Uint64](__res)
}

var __imp_SymLoadFileSymbol bindlib.PreloadProc

func SymLoadFileSymbol(BaseAddress Uint64, PdbFileName *byte, CustomModuleName *byte) Uint32 {
	__res := bindlib.CCall3(__imp_SymLoadFileSymbol.Addr(), bindlib.MarshallSyscall(BaseAddress), bindlib.MarshallSyscall(PdbFileName), bindlib.MarshallSyscall(CustomModuleName))
	return bindlib.UnmarshallSyscall[Uint32](__res)
}

var __imp_SymUnloadAllSymbols bindlib.PreloadProc

func SymUnloadAllSymbols() Uint32 {
	__res := bindlib.CCall0(__imp_SymUnloadAllSymbols.Addr())
	return bindlib.UnmarshallSyscall[Uint32](__res)
}

var __imp_SymUnloadModuleSymbol bindlib.PreloadProc

func SymUnloadModuleSymbol(ModuleName *byte) Uint32 {
	__res := bindlib.CCall1(__imp_SymUnloadModuleSymbol.Addr(), bindlib.MarshallSyscall(ModuleName))
	return bindlib.UnmarshallSyscall[Uint32](__res)
}

var __imp_SymSearchSymbolForMask bindlib.PreloadProc

func SymSearchSymbolForMask(SearchMask *byte) Uint32 {
	__res := bindlib.CCall1(__imp_SymSearchSymbolForMask.Addr(), bindlib.MarshallSyscall(SearchMask))
	return bindlib.UnmarshallSyscall[Uint32](__res)
}

var __imp_SymGetFieldOffset bindlib.PreloadProc

func SymGetFieldOffset(TypeName *Char, FieldName *Char, FieldOffset *Uint32) Boolean {
	__res := bindlib.CCall3(__imp_SymGetFieldOffset.Addr(), bindlib.MarshallSyscall(TypeName), bindlib.MarshallSyscall(FieldName), bindlib.MarshallSyscall(FieldOffset))
	return bindlib.UnmarshallSyscall[Boolean](__res)
}

var __imp_SymGetDataTypeSize bindlib.PreloadProc

func SymGetDataTypeSize(TypeName *Char, TypeSize *Uint64) Boolean {
	__res := bindlib.CCall2(__imp_SymGetDataTypeSize.Addr(), bindlib.MarshallSyscall(TypeName), bindlib.MarshallSyscall(TypeSize))
	return bindlib.UnmarshallSyscall[Boolean](__res)
}

var __imp_SymCreateSymbolTableForDisassembler bindlib.PreloadProc

func SymCreateSymbolTableForDisassembler(CallbackFunction unsafe.Pointer) Boolean {
	__res := bindlib.CCall1(__imp_SymCreateSymbolTableForDisassembler.Addr(), bindlib.MarshallSyscall(CallbackFunction))
	return bindlib.UnmarshallSyscall[Boolean](__res)
}

var __imp_SymConvertFileToPdbPath bindlib.PreloadProc

func SymConvertFileToPdbPath(LocalFilePath *byte, ResultPath *byte) Boolean {
	__res := bindlib.CCall2(__imp_SymConvertFileToPdbPath.Addr(), bindlib.MarshallSyscall(LocalFilePath), bindlib.MarshallSyscall(ResultPath))
	return bindlib.UnmarshallSyscall[Boolean](__res)
}

var __imp_SymConvertFileToPdbFileAndGuidAndAgeDetails bindlib.PreloadProc

func SymConvertFileToPdbFileAndGuidAndAgeDetails(LocalFilePath *byte, PdbFilePath *byte, GuidAndAgeDetails *byte, Is32BitModule Boolean) Boolean {
	__res := bindlib.CCall4(__imp_SymConvertFileToPdbFileAndGuidAndAgeDetails.Addr(), bindlib.MarshallSyscall(LocalFilePath), bindlib.MarshallSyscall(PdbFilePath), bindlib.MarshallSyscall(GuidAndAgeDetails), bindlib.MarshallSyscall(Is32BitModule))
	return bindlib.UnmarshallSyscall[Boolean](__res)
}

var __imp_SymbolInitLoad bindlib.PreloadProc

func SymbolInitLoad(BufferToStoreDetails unsafe.Pointer, StoredLength Uint32, DownloadIfAvailable Boolean, SymbolPath *byte, IsSilentLoad Boolean) Boolean {
	__res := bindlib.CCall5(__imp_SymbolInitLoad.Addr(), bindlib.MarshallSyscall(BufferToStoreDetails), bindlib.MarshallSyscall(StoredLength), bindlib.MarshallSyscall(DownloadIfAvailable), bindlib.MarshallSyscall(SymbolPath), bindlib.MarshallSyscall(IsSilentLoad))
	return bindlib.UnmarshallSyscall[Boolean](__res)
}

var __imp_SymShowDataBasedOnSymbolTypes bindlib.PreloadProc

func SymShowDataBasedOnSymbolTypes(TypeName *byte, Address Uint64, IsStruct Boolean, BufferAddress unsafe.Pointer, AdditionalParameters *byte) Boolean {
	__res := bindlib.CCall5(__imp_SymShowDataBasedOnSymbolTypes.Addr(), bindlib.MarshallSyscall(TypeName), bindlib.MarshallSyscall(Address), bindlib.MarshallSyscall(IsStruct), bindlib.MarshallSyscall(BufferAddress), bindlib.MarshallSyscall(AdditionalParameters))
	return bindlib.UnmarshallSyscall[Boolean](__res)
}

var __imp_SymQuerySizeof bindlib.PreloadProc

func SymQuerySizeof(StructNameOrTypeName *byte, SizeOfField *Uint32) Boolean {
	__res := bindlib.CCall2(__imp_SymQuerySizeof.Addr(), bindlib.MarshallSyscall(StructNameOrTypeName), bindlib.MarshallSyscall(SizeOfField))
	return bindlib.UnmarshallSyscall[Boolean](__res)
}

var __imp_SymCastingQueryForFiledsAndTypes bindlib.PreloadProc

func SymCastingQueryForFiledsAndTypes(StructName *byte, FiledOfStructName *byte, IsStructNamePointerOrNot Pboolean, IsFiledOfStructNamePointerOrNot Pboolean, NewStructOrTypeName **byte, OffsetOfFieldFromTop *Uint32, SizeOfField *Uint32) Boolean {
	__res := bindlib.CCall7(__imp_SymCastingQueryForFiledsAndTypes.Addr(), bindlib.MarshallSyscall(StructName), bindlib.MarshallSyscall(FiledOfStructName), bindlib.MarshallSyscall(IsStructNamePointerOrNot), bindlib.MarshallSyscall(IsFiledOfStructNamePointerOrNot), bindlib.MarshallSyscall(NewStructOrTypeName), bindlib.MarshallSyscall(OffsetOfFieldFromTop), bindlib.MarshallSyscall(SizeOfField))
	return bindlib.UnmarshallSyscall[Boolean](__res)
}

func (s Anon196_5) Flags() Uint64 {
	return bindlib.ReadBitcast[Uint64](unsafe.Add(unsafe.Pointer(unsafe.SliceData(s.Raw[:])), 0))
}

func (s *Anon196_5) SetFlags(v Uint64) {
	bindlib.WriteBitcast(unsafe.Add(unsafe.Pointer(unsafe.SliceData(s.Raw[:])), 0), v)
}

func (s Anon196_5) Fields() Anon200_9 {
	return bindlib.ReadBitcast[Anon200_9](unsafe.Add(unsafe.Pointer(unsafe.SliceData(s.Raw[:])), 0))
}

func (s *Anon196_5) SetFields(v Anon200_9) {
	bindlib.WriteBitcast(unsafe.Add(unsafe.Pointer(unsafe.SliceData(s.Raw[:])), 0), v)
}

func (s Anon1497_9) Fields() Anon1499_5 {
	return bindlib.ReadBitcast[Anon1499_5](unsafe.Add(unsafe.Pointer(unsafe.SliceData(s.Raw[:])), 0))
}

func (s *Anon1497_9) SetFields(v Anon1499_5) {
	bindlib.WriteBitcast(unsafe.Add(unsafe.Pointer(unsafe.SliceData(s.Raw[:])), 0), v)
}

func (s Anon1497_9) AsUInt() Uint32 {
	return bindlib.ReadBitcast[Uint32](unsafe.Add(unsafe.Pointer(unsafe.SliceData(s.Raw[:])), 0))
}

func (s *Anon1497_9) SetAsUInt(v Uint32) {
	bindlib.WriteBitcast(unsafe.Add(unsafe.Pointer(unsafe.SliceData(s.Raw[:])), 0), v)
}
