package Headers
//back\HyperDbgDev\hyperdbg\include\SDK\Headers\Events.h.back

const(
SIZEOF_DEBUGGER_MODIFY_EVENTS = sizeof(DEBUGGER_MODIFY_EVENTS) //col:80
)

type     HIDDEN_HOOK_READ_AND_WRITE uint32
const(
    HIDDEN_HOOK_READ_AND_WRITE DEBUGGER_EVENT_TYPE_ENUM = 1  //col:25
    HIDDEN_HOOK_READ DEBUGGER_EVENT_TYPE_ENUM = 2  //col:26
    HIDDEN_HOOK_WRITE DEBUGGER_EVENT_TYPE_ENUM = 3  //col:27
    HIDDEN_HOOK_EXEC_DETOURS DEBUGGER_EVENT_TYPE_ENUM = 4  //col:29
    HIDDEN_HOOK_EXEC_CC DEBUGGER_EVENT_TYPE_ENUM = 5  //col:30
    SYSCALL_HOOK_EFER_SYSCALL DEBUGGER_EVENT_TYPE_ENUM = 6  //col:32
    SYSCALL_HOOK_EFER_SYSRET DEBUGGER_EVENT_TYPE_ENUM = 7  //col:33
    CPUID_INSTRUCTION_EXECUTION DEBUGGER_EVENT_TYPE_ENUM = 8  //col:35
    RDMSR_INSTRUCTION_EXECUTION DEBUGGER_EVENT_TYPE_ENUM = 9  //col:37
    WRMSR_INSTRUCTION_EXECUTION DEBUGGER_EVENT_TYPE_ENUM = 10  //col:38
    IN_INSTRUCTION_EXECUTION DEBUGGER_EVENT_TYPE_ENUM = 11  //col:40
    OUT_INSTRUCTION_EXECUTION DEBUGGER_EVENT_TYPE_ENUM = 12  //col:41
    EXCEPTION_OCCURRED DEBUGGER_EVENT_TYPE_ENUM = 13  //col:43
    EXTERNAL_INTERRUPT_OCCURRED DEBUGGER_EVENT_TYPE_ENUM = 14  //col:44
    DEBUG_REGISTERS_ACCESSED DEBUGGER_EVENT_TYPE_ENUM = 15  //col:46
    TSC_INSTRUCTION_EXECUTION DEBUGGER_EVENT_TYPE_ENUM = 16  //col:48
    PMC_INSTRUCTION_EXECUTION DEBUGGER_EVENT_TYPE_ENUM = 17  //col:49
    VMCALL_INSTRUCTION_EXECUTION DEBUGGER_EVENT_TYPE_ENUM = 18  //col:51
    CONTROL_REGISTER_MODIFIED DEBUGGER_EVENT_TYPE_ENUM = 19  //col:53
)


type     BREAK_TO_DEBUGGER uint32
const(
    BREAK_TO_DEBUGGER DEBUGGER_EVENT_ACTION_TYPE_ENUM = 1  //col:63
    RUN_SCRIPT DEBUGGER_EVENT_ACTION_TYPE_ENUM = 2  //col:64
    RUN_CUSTOM_CODE DEBUGGER_EVENT_ACTION_TYPE_ENUM = 3  //col:65
)


type     DEBUGGER_EVENT_SYSCALL_SYSRET_SAFE_ACCESS_MEMORY = 0 uint32
const(
    DEBUGGER_EVENT_SYSCALL_SYSRET_SAFE_ACCESS_MEMORY  DEBUGGER_EVENT_SYSCALL_SYSRET_TYPE =  0  //col:75
    DEBUGGER_EVENT_SYSCALL_SYSRET_HANDLE_ALL_UD       DEBUGGER_EVENT_SYSCALL_SYSRET_TYPE =  1  //col:76
)


type     DEBUGGER_MODIFY_EVENTS_QUERY_STATE uint32
const(
    DEBUGGER_MODIFY_EVENTS_QUERY_STATE DEBUGGER_MODIFY_EVENTS_TYPE = 1  //col:88
    DEBUGGER_MODIFY_EVENTS_ENABLE DEBUGGER_MODIFY_EVENTS_TYPE = 2  //col:89
    DEBUGGER_MODIFY_EVENTS_DISABLE DEBUGGER_MODIFY_EVENTS_TYPE = 3  //col:90
    DEBUGGER_MODIFY_EVENTS_CLEAR DEBUGGER_MODIFY_EVENTS_TYPE = 4  //col:91
)



type DEBUGGER_MODIFY_EVENTS struct{
Tag uint64
KernelStatus uint64
DebuggerModifyEventsType DEBUGGER_MODIFY_EVENTS_TYPE
TypeOfAction byte
IsEnabled bool
}



type (
Events interface{
#define SIZEOF_DEBUGGER_MODIFY_EVENTS sizeof()(ok bool)//col:92
}
)

func NewEvents() { return & events{} }

func (e *events)#define SIZEOF_DEBUGGER_MODIFY_EVENTS sizeof()(ok bool){//col:92
/*#define SIZEOF_DEBUGGER_MODIFY_EVENTS sizeof(DEBUGGER_MODIFY_EVENTS)
 *
typedef enum _DEBUGGER_MODIFY_EVENTS_TYPE
{
    DEBUGGER_MODIFY_EVENTS_QUERY_STATE,
    DEBUGGER_MODIFY_EVENTS_ENABLE,
    DEBUGGER_MODIFY_EVENTS_DISABLE,
    DEBUGGER_MODIFY_EVENTS_CLEAR
} DEBUGGER_MODIFY_EVENTS_TYPE;*/
return true
}



