package Headers



const (

)

const (
	HIDDEN_HOOK_READ_AND_WRITE   = 1  //col:25
	HIDDEN_HOOK_READ             = 2  //col:26
	HIDDEN_HOOK_WRITE            = 3  //col:27
	HIDDEN_HOOK_EXEC_DETOURS     = 4  //col:29
	HIDDEN_HOOK_EXEC_CC          = 5  //col:30
	SYSCALL_HOOK_EFER_SYSCALL    = 6  //col:32
	SYSCALL_HOOK_EFER_SYSRET     = 7  //col:33
	CPUID_INSTRUCTION_EXECUTION  = 8  //col:35
	RDMSR_INSTRUCTION_EXECUTION  = 9  //col:37
	WRMSR_INSTRUCTION_EXECUTION  = 10 //col:38
	IN_INSTRUCTION_EXECUTION     = 11 //col:40
	OUT_INSTRUCTION_EXECUTION    = 12 //col:41
	EXCEPTION_OCCURRED           = 13 //col:43
	EXTERNAL_INTERRUPT_OCCURRED  = 14 //col:44
	DEBUG_REGISTERS_ACCESSED     = 15 //col:46
	TSC_INSTRUCTION_EXECUTION    = 16 //col:48
	PMC_INSTRUCTION_EXECUTION    = 17 //col:49
	VMCALL_INSTRUCTION_EXECUTION = 18 //col:51
	CONTROL_REGISTER_MODIFIED    = 19 //col:53
)

const (
	BREAK_TO_DEBUGGER = 1 //col:63
	RUN_SCRIPT        = 2 //col:64
	RUN_CUSTOM_CODE   = 3 //col:65
)

const (
	DEBUGGER_EVENT_SYSCALL_SYSRET_SAFE_ACCESS_MEMORY = 0 //col:75
	DEBUGGER_EVENT_SYSCALL_SYSRET_HANDLE_ALL_UD      = 1 //col:76
)

const (
	DEBUGGER_MODIFY_EVENTS_QUERY_STATE = 1 //col:88
	DEBUGGER_MODIFY_EVENTS_ENABLE      = 2 //col:89
	DEBUGGER_MODIFY_EVENTS_DISABLE     = 3 //col:90
	DEBUGGER_MODIFY_EVENTS_CLEAR       = 4 //col:91
)
