package Headers
//back\HyperDbgDev\hyperdbg\include\SDK\Headers\RequestStructures.h.back

const(
SIZEOF_DEBUGGER_READ_PAGE_TABLE_ENTRIES_DETAILS = sizeof(DEBUGGER_READ_PAGE_TABLE_ENTRIES_DETAILS) //col:1
SIZEOF_DEBUGGER_VA2PA_AND_PA2VA_COMMANDS = sizeof(DEBUGGER_VA2PA_AND_PA2VA_COMMANDS) //col:3
SIZEOF_DEBUGGER_DT_COMMAND_OPTIONS = sizeof(DEBUGGER_DT_COMMAND_OPTIONS) //col:5
SIZEOF_DEBUGGER_PREALLOC_COMMAND = sizeof(DEBUGGER_PREALLOC_COMMAND) //col:7
SIZEOF_DEBUGGER_READ_MEMORY = sizeof(DEBUGGER_READ_MEMORY) //col:9
SIZEOF_DEBUGGER_FLUSH_LOGGING_BUFFERS = sizeof(DEBUGGER_FLUSH_LOGGING_BUFFERS) //col:10
SIZEOF_DEBUGGER_TEST_QUERY_BUFFER = sizeof(DEBUGGER_TEST_QUERY_BUFFER) //col:12
SIZEOF_DEBUGGER_PERFORM_KERNEL_TESTS = sizeof(DEBUGGER_PERFORM_KERNEL_TESTS) //col:14
SIZEOF_DEBUGGER_SEND_COMMAND_EXECUTION_FINISHED_SIGNAL = sizeof(DEBUGGER_SEND_COMMAND_EXECUTION_FINISHED_SIGNAL) //col:16
SIZEOF_DEBUGGEE_KERNEL_AND_USER_TEST_INFORMATION = sizeof(DEBUGGEE_KERNEL_AND_USER_TEST_INFORMATION) //col:18
SIZEOF_DEBUGGEE_SEND_GENERAL_PACKET_FROM_DEBUGGEE_TO_DEBUGGER = sizeof(DEBUGGEE_SEND_GENERAL_PACKET_FROM_DEBUGGEE_TO_DEBUGGER) //col:20
SIZEOF_DEBUGGER_SEND_USERMODE_MESSAGES_TO_DEBUGGER = sizeof(DEBUGGER_SEND_USERMODE_MESSAGES_TO_DEBUGGER) //col:22
SIZEOF_DEBUGGER_READ_AND_WRITE_ON_MSR = sizeof(DEBUGGER_READ_AND_WRITE_ON_MSR) //col:24
SIZEOF_DEBUGGER_EDIT_MEMORY = sizeof(DEBUGGER_EDIT_MEMORY) //col:26
SIZEOF_DEBUGGER_SEARCH_MEMORY = sizeof(DEBUGGER_SEARCH_MEMORY) //col:27
SIZEOF_DEBUGGER_HIDE_AND_TRANSPARENT_DEBUGGER_MODE = sizeof(DEBUGGER_HIDE_AND_TRANSPARENT_DEBUGGER_MODE) //col:28
SIZEOF_DEBUGGER_PREPARE_DEBUGGEE = sizeof(DEBUGGER_PREPARE_DEBUGGEE) //col:30
SIZEOF_DEBUGGER_ATTACH_DETACH_USER_MODE_PROCESS = sizeof(DEBUGGER_ATTACH_DETACH_USER_MODE_PROCESS) //col:31
SIZEOF_DEBUGGER_QUERY_ACTIVE_PROCESSES_OR_THREADS = sizeof(DEBUGGER_QUERY_ACTIVE_PROCESSES_OR_THREADS) //col:33
SIZEOF_DEBUGGER_CALLSTACK_REQUEST = sizeof(DEBUGGER_CALLSTACK_REQUEST) //col:35
SIZEOF_USERMODE_DEBUGGING_THREAD_OR_PROCESS_STATE_DETAILS = sizeof(USERMODE_DEBUGGING_THREAD_OR_PROCESS_STATE_DETAILS) //col:37
SIZEOF_DEBUGGEE_DETAILS_AND_SWITCH_PROCESS_PACKET = sizeof(DEBUGGEE_DETAILS_AND_SWITCH_PROCESS_PACKET) //col:39
SIZEOF_DEBUGGEE_DETAILS_AND_SWITCH_THREAD_PACKET = sizeof(DEBUGGEE_DETAILS_AND_SWITCH_THREAD_PACKET) //col:41
)

const(
    DEBUGGER_PREALLOC_COMMAND_TYPE_MONITOR = 1  //col:3
    DEBUGGER_PREALLOC_COMMAND_TYPE_THREAD_INTERCEPTION = 2  //col:4
)


const(
    READ_FROM_KERNEL = 1  //col:8
    READ_FROM_VMX_ROOT = 2  //col:9
)


const(
    DEBUGGER_READ_PHYSICAL_ADDRESS = 1  //col:13
    DEBUGGER_READ_VIRTUAL_ADDRESS = 2  //col:14
)


const(
    DEBUGGER_SHOW_COMMAND_DT  =  1  //col:18
    DEBUGGER_SHOW_COMMAND_DISASSEMBLE64 = 2  //col:19
    DEBUGGER_SHOW_COMMAND_DISASSEMBLE32 = 3  //col:20
    DEBUGGER_SHOW_COMMAND_DB = 4  //col:21
    DEBUGGER_SHOW_COMMAND_DC = 5  //col:22
    DEBUGGER_SHOW_COMMAND_DQ = 6  //col:23
    DEBUGGER_SHOW_COMMAND_DD = 7  //col:24
)


const(
    DEBUGGER_MSR_READ = 1  //col:28
    DEBUGGER_MSR_WRITE = 2  //col:29
)


const(
    EDIT_PHYSICAL_MEMORY = 1  //col:33
    EDIT_VIRTUAL_MEMORY = 2  //col:34
)


const(
    EDIT_BYTE = 1  //col:38
    EDIT_DWORD = 2  //col:39
    EDIT_QWORD = 3  //col:40
)


const(
    SEARCH_PHYSICAL_MEMORY = 1  //col:44
    SEARCH_VIRTUAL_MEMORY = 2  //col:45
    SEARCH_PHYSICAL_FROM_VIRTUAL_MEMORY = 3  //col:46
)


const(
    SEARCH_BYTE = 1  //col:50
    SEARCH_DWORD = 2  //col:51
    SEARCH_QWORD = 3  //col:52
)


const(
    DEBUGGER_ATTACH_DETACH_USER_MODE_PROCESS_ACTION_ATTACH = 1  //col:56
    DEBUGGER_ATTACH_DETACH_USER_MODE_PROCESS_ACTION_DETACH = 2  //col:57
    DEBUGGER_ATTACH_DETACH_USER_MODE_PROCESS_ACTION_REMOVE_HOOKS = 3  //col:58
    DEBUGGER_ATTACH_DETACH_USER_MODE_PROCESS_ACTION_KILL_PROCESS = 4  //col:59
    DEBUGGER_ATTACH_DETACH_USER_MODE_PROCESS_ACTION_PAUSE_PROCESS = 5  //col:60
    DEBUGGER_ATTACH_DETACH_USER_MODE_PROCESS_ACTION_SWITCH_BY_PROCESS_OR_THREAD = 6  //col:61
    DEBUGGER_ATTACH_DETACH_USER_MODE_PROCESS_ACTION_QUERY_COUNT_OF_ACTIVE_DEBUGGING_THREADS = 7  //col:62
)


const(
    DEBUGGER_QUERY_ACTIVE_PROCESSES_OR_THREADS_QUERY_PROCESS_COUNT    =  1  //col:66
    DEBUGGER_QUERY_ACTIVE_PROCESSES_OR_THREADS_QUERY_THREAD_COUNT     =  2  //col:67
    DEBUGGER_QUERY_ACTIVE_PROCESSES_OR_THREADS_QUERY_PROCESS_LIST     =  3  //col:68
    DEBUGGER_QUERY_ACTIVE_PROCESSES_OR_THREADS_QUERY_THREAD_LIST      =  4  //col:69
    DEBUGGER_QUERY_ACTIVE_PROCESSES_OR_THREADS_QUERY_CURRENT_PROCESS  =  5  //col:70
    DEBUGGER_QUERY_ACTIVE_PROCESSES_OR_THREADS_QUERY_CURRENT_THREAD   =  6  //col:71
)


const(
    DEBUGGER_QUERY_ACTIVE_PROCESSES_OR_THREADS_ACTION_SHOW_INSTANTLY      =  1  //col:75
    DEBUGGER_QUERY_ACTIVE_PROCESSES_OR_THREADS_ACTION_QUERY_COUNT         =  2  //col:76
    DEBUGGER_QUERY_ACTIVE_PROCESSES_OR_THREADS_ACTION_QUERY_SAVE_DETAILS  =  3  //col:77
)


const(
    DEBUGGER_CALLSTACK_DISPLAY_METHOD_WITHOUT_PARAMS = 1  //col:81
    DEBUGGER_CALLSTACK_DISPLAY_METHOD_WITH_PARAMS = 2  //col:82
)


const(
    DEBUGGER_UD_COMMAND_ACTION_TYPE_NONE  =  0  //col:86
    DEBUGGER_UD_COMMAND_ACTION_TYPE_PAUSE = 2  //col:87
    DEBUGGER_UD_COMMAND_ACTION_TYPE_CONTINUE = 3  //col:88
    DEBUGGER_UD_COMMAND_ACTION_TYPE_REGULAR_STEP = 4  //col:89
)


const(
    DEBUGGEE_DETAILS_AND_SWITCH_PROCESS_GET_PROCESS_DETAILS = 1  //col:93
    DEBUGGEE_DETAILS_AND_SWITCH_PROCESS_GET_PROCESS_LIST = 2  //col:94
    DEBUGGEE_DETAILS_AND_SWITCH_PROCESS_PERFORM_SWITCH = 3  //col:95
)


const(
    DEBUGGEE_DETAILS_AND_SWITCH_THREAD_PERFORM_SWITCH = 1  //col:99
    DEBUGGEE_DETAILS_AND_SWITCH_THREAD_GET_THREAD_DETAILS = 2  //col:100
    DEBUGGEE_DETAILS_AND_SWITCH_THREAD_GET_THREAD_LIST = 3  //col:101
)


const(
    DEBUGGER_REMOTE_STEPPING_REQUEST_STEP_OVER = 1  //col:105
    DEBUGGER_REMOTE_STEPPING_REQUEST_STEP_IN = 2  //col:106
    DEBUGGER_REMOTE_STEPPING_REQUEST_INSTRUMENTATION_STEP_IN = 3  //col:107
)


const(
    DEBUGGEE_BREAKPOINT_MODIFICATION_REQUEST_LIST_BREAKPOINTS = 1  //col:111
    DEBUGGEE_BREAKPOINT_MODIFICATION_REQUEST_ENABLE = 2  //col:112
    DEBUGGEE_BREAKPOINT_MODIFICATION_REQUEST_DISABLE = 3  //col:113
    DEBUGGEE_BREAKPOINT_MODIFICATION_REQUEST_CLEAR = 4  //col:114
)


const(
    DEBUGGER_CONDITIONAL_JUMP_STATUS_ERROR  =  0  //col:118
    DEBUGGER_CONDITIONAL_JUMP_STATUS_NOT_CONDITIONAL_JUMP = 2  //col:119
    DEBUGGER_CONDITIONAL_JUMP_STATUS_JUMP_IS_TAKEN = 3  //col:120
    DEBUGGER_CONDITIONAL_JUMP_STATUS_JUMP_IS_NOT_TAKEN = 4  //col:121
)



type DEBUGGER_READ_PAGE_TABLE_ENTRIES_DETAILS struct{
VirtualAddress uint64
ProcessId UINT32
Pml4eVirtualAddress uint64
Pml4eValue uint64
PdpteVirtualAddress uint64
PdpteValue uint64
PdeVirtualAddress uint64
PdeValue uint64
PteVirtualAddress uint64
PteValue uint64
KernelStatus UINT32
}


type DEBUGGER_VA2PA_AND_PA2VA_COMMANDS struct{
VirtualAddress uint64
PhysicalAddress uint64
ProcessId UINT32
IsVirtual2Physical bool
KernelStatus UINT32
}


type DEBUGGER_DT_COMMAND_OPTIONS struct{
char const
SizeOfTypeName uint64
Address uint64
IsStruct bool
BufferAddress PVOID
TargetPid UINT32
char const
}


type DEBUGGER_PREALLOC_COMMAND struct{
Type DEBUGGER_PREALLOC_COMMAND_TYPE
Count uint64
KernelStatus UINT32
}


type DEBUGGER_READ_MEMORY struct{
Pid UINT32
Address uint64
Size UINT32
MemoryType DEBUGGER_READ_MEMORY_TYPE
ReadingType DEBUGGER_READ_READING_TYPE
DtDetails PDEBUGGER_DT_COMMAND_OPTIONS
Style DEBUGGER_SHOW_MEMORY_STYLE
ReturnLength UINT32
KernelStatus UINT32
}


type DEBUGGER_FLUSH_LOGGING_BUFFERS struct{
KernelStatus UINT32
CountOfMessagesThatSetAsReadFromVmxRoot UINT32
CountOfMessagesThatSetAsReadFromVmxNonRoot UINT32
}


type DEBUGGER_DEBUGGER_TEST_QUERY_BUFFER struct{
RequestIndex UINT32
KernelStatus UINT32
}


type DEBUGGER_PERFORM_KERNEL_TESTS struct{
KernelStatus UINT32
}


type DEBUGGER_SEND_COMMAND_EXECUTION_FINISHED_SIGNAL struct{
KernelStatus UINT32
}


type DEBUGGEE_KERNEL_AND_USER_TEST_INFORMATION struct{
Value uint64
Tag[32] char
}


type DEBUGGEE_SEND_GENERAL_PACKET_FROM_DEBUGGEE_TO_DEBUGGER struct{
RequestedAction DEBUGGER_REMOTE_PACKET_REQUESTED_ACTION
LengthOfBuffer UINT32
PauseDebuggeeWhenSent bool
KernelResult UINT32
}


type DEBUGGER_SEND_USERMODE_MESSAGES_TO_DEBUGGER struct{
KernelStatus UINT32
Length UINT32
}


type DEBUGGER_READ_AND_WRITE_ON_MSR struct{
Msr uint64
CoreNumber UINT32
DebuggerMsrActionType DEBUGGER_MSR_ACTION_TYPE
ActionType; byte
Value uint64
}


type DEBUGGER_EDIT_MEMORY struct{
Result UINT32
Address uint64
ProcessId UINT32
MemoryType DEBUGGER_EDIT_MEMORY_TYPE
ByteSize DEBUGGER_EDIT_MEMORY_BYTE_SIZE
CountOf64Chunks UINT32
FinalStructureSize UINT32
KernelStatus UINT32
}


type DEBUGGER_SEARCH_MEMORY struct{
Address uint64
Length uint64
ProcessId UINT32
MemoryType DEBUGGER_SEARCH_MEMORY_TYPE
ByteSize DEBUGGER_SEARCH_MEMORY_BYTE_SIZE
CountOf64Chunks UINT32
FinalStructureSize UINT32
}


type DEBUGGER_HIDE_AND_TRANSPARENT_DEBUGGER_MODE struct{
IsHide bool
CpuidAverage uint64
CpuidStandardDeviation uint64
CpuidMedian uint64
RdtscAverage uint64
RdtscStandardDeviation uint64
RdtscMedian uint64
TrueIfProcessIdAndFalseIfProcessName bool
ProcId UINT32
LengthOfProcessName UINT32
DebuggerErrorUnableToHideOrUnhideDebugger DEBUGGER_ERROR_UNABLE_TO_HIDE_OR_UNHIDE_DEBUGGER
}


type DEBUGGER_PREPARE_DEBUGGEE struct{
PortAddress UINT32
Baudrate UINT32
NtoskrnlBaseAddress uint64
Result UINT32
OsName[MAXIMUM_CHARACTER_FOR_OS_NAME] CHAR
}


type DEBUGGEE_CHANGE_CORE_PACKET struct{
NewCore UINT32
Result UINT32
}


type DEBUGGER_ATTACH_DETACH_USER_MODE_PROCESS struct{
IsStartingNewProcess bool
ProcessId UINT32
ThreadId UINT32
Is32Bit bool
IsPaused bool
Action DEBUGGER_ATTACH_DETACH_USER_MODE_PROCESS_ACTION_TYPE
CountOfActiveDebuggingThreadsAndProcesses UINT32
Token uint64
Result uint64
}


type DEBUGGEE_PROCESS_LIST_NEEDED_DETAILS struct{
PsActiveProcessHead uint64
ImageFileNameOffset ULONG
UniquePidOffset ULONG
ActiveProcessLinksOffset ULONG
}


type DEBUGGEE_THREAD_LIST_NEEDED_DETAILS struct{
ThreadListHeadOffset UINT32
ThreadListEntryOffset UINT32
CidOffset UINT32
PsActiveProcessHead uint64
ActiveProcessLinksOffset ULONG
Process uint64
}


type DEBUGGEE_PROCESS_LIST_DETAILS_ENTRY struct{
Eprocess uint64
Pid UINT32
Cr3 uint64
ImageFileName[15 UCHAR
}


type DEBUGGEE_THREAD_LIST_DETAILS_ENTRY struct{
Eprocess uint64
Ethread uint64
Pid uint64
Tid uint64
ImageFileName[15 UCHAR
}


type DEBUGGER_QUERY_ACTIVE_PROCESSES_OR_THREADS struct{
ProcessListNeededDetails DEBUGGEE_PROCESS_LIST_NEEDED_DETAILS
ThreadListNeededDetails DEBUGGEE_THREAD_LIST_NEEDED_DETAILS
QueryType DEBUGGER_QUERY_ACTIVE_PROCESSES_OR_THREADS_TYPES
QueryAction DEBUGGER_QUERY_ACTIVE_PROCESSES_OR_THREADS_ACTIONS
Count UINT32
Result uint64
}


type DEBUGGER_SINGLE_CALLSTACK_FRAME struct{
IsStackAddressValid bool
IsValidAddress bool
IsExecutable bool
Value uint64
InstructionBytesOnRip[MAXIMUM_CALL_INSTR_SIZE] BYTE
}


type DEBUGGER_CALLSTACK_REQUEST struct{
Is32Bit bool
KernelStatus UINT32
DisplayMethod DEBUGGER_CALLSTACK_DISPLAY_METHOD
Size UINT32
FrameCount UINT32
BaseAddress uint64
BufferSize uint64
}


type USERMODE_DEBUGGING_THREAD_OR_PROCESS_STATE_DETAILS struct{
ProcessId UINT32
ThreadId UINT32
IsProcess bool
}


type DEBUGGER_EVENT_ACTION_RUN_SCRIPT_CONFIGURATION struct{
ScriptBuffer uint64
ScriptLength UINT32
ScriptPointer UINT32
OptionalRequestedBufferSize UINT32
}


type DEBUGGER_EVENT_REQUEST_BUFFER struct{
EnabledRequestBuffer bool
RequestBufferSize UINT32
RequstBufferAddress uint64
}


type DEBUGGER_EVENT_REQUEST_CUSTOM_CODE struct{
CustomCodeBufferSize UINT32
CustomCodeBufferAddress PVOID
OptionalRequestedBufferSize UINT32
}


type DEBUGGER_UD_COMMAND_ACTION struct{
ActionType DEBUGGER_UD_COMMAND_ACTION_TYPE
OptionalParam1 uint64
OptionalParam2 uint64
OptionalParam3 uint64
OptionalParam4 uint64
}


type DEBUGGER_UD_COMMAND_PACKET struct{
UdAction DEBUGGER_UD_COMMAND_ACTION
ProcessDebuggingDetailToken uint64
TargetThreadId UINT32
ApplyToAllPausedThreads bool
Result UINT32
}


type DEBUGGEE_DETAILS_AND_SWITCH_PROCESS_PACKET struct{
ActionType DEBUGGEE_DETAILS_AND_SWITCH_PROCESS_TYPE
ProcessId UINT32
Process uint64
IsSwitchByClkIntr bool
ProcessName[16] UCHAR
ProcessListSymDetails DEBUGGEE_PROCESS_LIST_NEEDED_DETAILS
Result UINT32
}


type DEBUGGEE_DETAILS_AND_SWITCH_THREAD_PACKET struct{
ActionType DEBUGGEE_DETAILS_AND_SWITCH_THREAD_TYPE
ThreadId UINT32
ProcessId UINT32
Thread uint64
Process uint64
CheckByClockInterrupt bool
ProcessName[16] UCHAR
ThreadListSymDetails DEBUGGEE_THREAD_LIST_NEEDED_DETAILS
Result UINT32
}


type DEBUGGEE_STEP_PACKET struct{
StepType DEBUGGER_REMOTE_STEPPING_REQUEST
IsCurrentInstructionACall bool
CallLength UINT32
}


type DEBUGGEE_FORMATS_PACKET struct{
Value uint64
Result UINT32
}


type DEBUGGEE_SYMBOL_REQUEST_PACKET struct{
ProcessId UINT32
}


type DEBUGGEE_BP_PACKET struct{
Address uint64
Pid UINT32
Tid UINT32
Core UINT32
Result UINT32
}


type DEBUGGEE_BP_DESCRIPTOR struct{
BreakpointId uint64
BreakpointsList LIST_ENTRY
Enabled bool
Address uint64
PhysAddress uint64
Pid UINT32
Tid UINT32
Core UINT32
InstructionLength UINT16
PreviousByte BYTE
SetRflagsIFBitOnMtf bool
AvoidReApplyBreakpoint bool
}


type DEBUGGEE_BP_LIST_OR_MODIFY_PACKET struct{
BreakpointId uint64
Request DEBUGGEE_BREAKPOINT_MODIFICATION_REQUEST
Result UINT32
}


type DEBUGGEE_SCRIPT_PACKET struct{
ScriptBufferSize UINT32
ScriptBufferPointer UINT32
IsFormat bool
Result UINT32
}


type DEBUGGEE_RESULT_OF_SEARCH_PACKET struct{
CountOfResults UINT32
Result UINT32
}


type DEBUGGEE_REGISTER_READ_DESCRIPTION struct{
RegisterID UINT32
Value uint64
KernelStatus UINT32
}




