package Headers
//back\HyperDbgDev\hyperdbg\include\SDK\Headers\RequestStructures.h.back

const(
SIZEOF_DEBUGGER_READ_PAGE_TABLE_ENTRIES_DETAILS = sizeof(DEBUGGER_READ_PAGE_TABLE_ENTRIES_DETAILS) //col:14
SIZEOF_DEBUGGER_VA2PA_AND_PA2VA_COMMANDS = sizeof(DEBUGGER_VA2PA_AND_PA2VA_COMMANDS) //col:46
SIZEOF_DEBUGGER_DT_COMMAND_OPTIONS = sizeof(DEBUGGER_DT_COMMAND_OPTIONS) //col:66
SIZEOF_DEBUGGER_PREALLOC_COMMAND = sizeof(DEBUGGER_PREALLOC_COMMAND) //col:98
SIZEOF_DEBUGGER_READ_MEMORY = sizeof(DEBUGGER_READ_MEMORY) //col:116
SIZEOF_DEBUGGER_FLUSH_LOGGING_BUFFERS = sizeof(DEBUGGER_FLUSH_LOGGING_BUFFERS) //col:175
SIZEOF_DEBUGGER_TEST_QUERY_BUFFER = sizeof(DEBUGGER_TEST_QUERY_BUFFER) //col:193
SIZEOF_DEBUGGER_PERFORM_KERNEL_TESTS = sizeof(DEBUGGER_PERFORM_KERNEL_TESTS) //col:210
SIZEOF_DEBUGGER_SEND_COMMAND_EXECUTION_FINISHED_SIGNAL = sizeof(DEBUGGER_SEND_COMMAND_EXECUTION_FINISHED_SIGNAL) //col:226
SIZEOF_DEBUGGEE_KERNEL_AND_USER_TEST_INFORMATION = sizeof(DEBUGGEE_KERNEL_AND_USER_TEST_INFORMATION) //col:243
SIZEOF_DEBUGGEE_SEND_GENERAL_PACKET_FROM_DEBUGGEE_TO_DEBUGGER = sizeof(DEBUGGEE_SEND_GENERAL_PACKET_FROM_DEBUGGEE_TO_DEBUGGER) //col:261
SIZEOF_DEBUGGER_SEND_USERMODE_MESSAGES_TO_DEBUGGER = sizeof(DEBUGGER_SEND_USERMODE_MESSAGES_TO_DEBUGGER) //col:285
SIZEOF_DEBUGGER_READ_AND_WRITE_ON_MSR = sizeof(DEBUGGER_READ_AND_WRITE_ON_MSR) //col:307
SIZEOF_DEBUGGER_EDIT_MEMORY = sizeof(DEBUGGER_EDIT_MEMORY) //col:339
SIZEOF_DEBUGGER_SEARCH_MEMORY = sizeof(DEBUGGER_SEARCH_MEMORY) //col:382
SIZEOF_DEBUGGER_HIDE_AND_TRANSPARENT_DEBUGGER_MODE = sizeof(DEBUGGER_HIDE_AND_TRANSPARENT_DEBUGGER_MODE) //col:427
SIZEOF_DEBUGGER_PREPARE_DEBUGGEE = sizeof(DEBUGGER_PREPARE_DEBUGGEE) //col:461
SIZEOF_DEBUGGER_ATTACH_DETACH_USER_MODE_PROCESS = sizeof(DEBUGGER_ATTACH_DETACH_USER_MODE_PROCESS) //col:493
SIZEOF_DEBUGGER_QUERY_ACTIVE_PROCESSES_OR_THREADS = sizeof(DEBUGGER_QUERY_ACTIVE_PROCESSES_OR_THREADS) //col:533
SIZEOF_DEBUGGER_CALLSTACK_REQUEST = sizeof(DEBUGGER_CALLSTACK_REQUEST) //col:655
SIZEOF_USERMODE_DEBUGGING_THREAD_OR_PROCESS_STATE_DETAILS = sizeof(USERMODE_DEBUGGING_THREAD_OR_PROCESS_STATE_DETAILS) //col:691
SIZEOF_DEBUGGEE_DETAILS_AND_SWITCH_PROCESS_PACKET = sizeof(DEBUGGEE_DETAILS_AND_SWITCH_PROCESS_PACKET) //col:827
SIZEOF_DEBUGGEE_DETAILS_AND_SWITCH_THREAD_PACKET = sizeof(DEBUGGEE_DETAILS_AND_SWITCH_THREAD_PACKET) //col:865
)

const(
    DEBUGGER_PREALLOC_COMMAND_TYPE_MONITOR = 1  //col:94
    DEBUGGER_PREALLOC_COMMAND_TYPE_THREAD_INTERCEPTION = 2  //col:95
)


const(
    READ_FROM_KERNEL = 1  //col:124
    READ_FROM_VMX_ROOT = 2  //col:125
)


const(
    DEBUGGER_READ_PHYSICAL_ADDRESS = 1  //col:134
    DEBUGGER_READ_VIRTUAL_ADDRESS = 2  //col:135
)


const(
    DEBUGGER_SHOW_COMMAND_DT  =  1  //col:145
    DEBUGGER_SHOW_COMMAND_DISASSEMBLE64 = 2  //col:146
    DEBUGGER_SHOW_COMMAND_DISASSEMBLE32 = 3  //col:147
    DEBUGGER_SHOW_COMMAND_DB = 4  //col:148
    DEBUGGER_SHOW_COMMAND_DC = 5  //col:149
    DEBUGGER_SHOW_COMMAND_DQ = 6  //col:150
    DEBUGGER_SHOW_COMMAND_DD = 7  //col:151
)


const(
    DEBUGGER_MSR_READ = 1  //col:316
    DEBUGGER_MSR_WRITE = 2  //col:317
)


const(
    EDIT_PHYSICAL_MEMORY = 1  //col:347
    EDIT_VIRTUAL_MEMORY = 2  //col:348
)


const(
    EDIT_BYTE = 1  //col:357
    EDIT_DWORD = 2  //col:358
    EDIT_QWORD = 3  //col:359
)


const(
    SEARCH_PHYSICAL_MEMORY = 1  //col:390
    SEARCH_VIRTUAL_MEMORY = 2  //col:391
    SEARCH_PHYSICAL_FROM_VIRTUAL_MEMORY = 3  //col:392
)


const(
    SEARCH_BYTE = 1  //col:402
    SEARCH_DWORD = 2  //col:403
    SEARCH_QWORD = 3  //col:404
)


const(
    DEBUGGER_ATTACH_DETACH_USER_MODE_PROCESS_ACTION_ATTACH = 1  //col:502
    DEBUGGER_ATTACH_DETACH_USER_MODE_PROCESS_ACTION_DETACH = 2  //col:503
    DEBUGGER_ATTACH_DETACH_USER_MODE_PROCESS_ACTION_REMOVE_HOOKS = 3  //col:504
    DEBUGGER_ATTACH_DETACH_USER_MODE_PROCESS_ACTION_KILL_PROCESS = 4  //col:505
    DEBUGGER_ATTACH_DETACH_USER_MODE_PROCESS_ACTION_PAUSE_PROCESS = 5  //col:506
    DEBUGGER_ATTACH_DETACH_USER_MODE_PROCESS_ACTION_SWITCH_BY_PROCESS_OR_THREAD = 6  //col:507
    DEBUGGER_ATTACH_DETACH_USER_MODE_PROCESS_ACTION_QUERY_COUNT_OF_ACTIVE_DEBUGGING_THREADS = 7  //col:508
)


const(
    DEBUGGER_QUERY_ACTIVE_PROCESSES_OR_THREADS_QUERY_PROCESS_COUNT    =  1  //col:542
    DEBUGGER_QUERY_ACTIVE_PROCESSES_OR_THREADS_QUERY_THREAD_COUNT     =  2  //col:543
    DEBUGGER_QUERY_ACTIVE_PROCESSES_OR_THREADS_QUERY_PROCESS_LIST     =  3  //col:544
    DEBUGGER_QUERY_ACTIVE_PROCESSES_OR_THREADS_QUERY_THREAD_LIST      =  4  //col:545
    DEBUGGER_QUERY_ACTIVE_PROCESSES_OR_THREADS_QUERY_CURRENT_PROCESS  =  5  //col:546
    DEBUGGER_QUERY_ACTIVE_PROCESSES_OR_THREADS_QUERY_CURRENT_THREAD   =  6  //col:547
)


const(
    DEBUGGER_QUERY_ACTIVE_PROCESSES_OR_THREADS_ACTION_SHOW_INSTANTLY      =  1  //col:557
    DEBUGGER_QUERY_ACTIVE_PROCESSES_OR_THREADS_ACTION_QUERY_COUNT         =  2  //col:558
    DEBUGGER_QUERY_ACTIVE_PROCESSES_OR_THREADS_ACTION_QUERY_SAVE_DETAILS  =  3  //col:559
)


const(
    DEBUGGER_CALLSTACK_DISPLAY_METHOD_WITHOUT_PARAMS = 1  //col:664
    DEBUGGER_CALLSTACK_DISPLAY_METHOD_WITH_PARAMS = 2  //col:665
)


const(
    DEBUGGER_UD_COMMAND_ACTION_TYPE_NONE  =  0  //col:752
    DEBUGGER_UD_COMMAND_ACTION_TYPE_PAUSE = 2  //col:753
    DEBUGGER_UD_COMMAND_ACTION_TYPE_CONTINUE = 3  //col:754
    DEBUGGER_UD_COMMAND_ACTION_TYPE_REGULAR_STEP = 4  //col:755
)


const(
    DEBUGGEE_DETAILS_AND_SWITCH_PROCESS_GET_PROCESS_DETAILS = 1  //col:797
    DEBUGGEE_DETAILS_AND_SWITCH_PROCESS_GET_PROCESS_LIST = 2  //col:798
    DEBUGGEE_DETAILS_AND_SWITCH_PROCESS_PERFORM_SWITCH = 3  //col:799
)


const(
    DEBUGGEE_DETAILS_AND_SWITCH_THREAD_PERFORM_SWITCH = 1  //col:837
    DEBUGGEE_DETAILS_AND_SWITCH_THREAD_GET_THREAD_DETAILS = 2  //col:838
    DEBUGGEE_DETAILS_AND_SWITCH_THREAD_GET_THREAD_LIST = 3  //col:839
)


const(
    DEBUGGER_REMOTE_STEPPING_REQUEST_STEP_OVER = 1  //col:878
    DEBUGGER_REMOTE_STEPPING_REQUEST_STEP_IN = 2  //col:879
    DEBUGGER_REMOTE_STEPPING_REQUEST_INSTRUMENTATION_STEP_IN = 3  //col:880
)


const(
    DEBUGGEE_BREAKPOINT_MODIFICATION_REQUEST_LIST_BREAKPOINTS = 1  //col:973
    DEBUGGEE_BREAKPOINT_MODIFICATION_REQUEST_ENABLE = 2  //col:974
    DEBUGGEE_BREAKPOINT_MODIFICATION_REQUEST_DISABLE = 3  //col:975
    DEBUGGEE_BREAKPOINT_MODIFICATION_REQUEST_CLEAR = 4  //col:976
)


const(
    DEBUGGER_CONDITIONAL_JUMP_STATUS_ERROR  =  0  //col:1002
    DEBUGGER_CONDITIONAL_JUMP_STATUS_NOT_CONDITIONAL_JUMP = 2  //col:1003
    DEBUGGER_CONDITIONAL_JUMP_STATUS_JUMP_IS_TAKEN = 3  //col:1004
    DEBUGGER_CONDITIONAL_JUMP_STATUS_JUMP_IS_NOT_TAKEN = 4  //col:1005
)



type (
RequestStructures interface{
    sizeof()(ok bool)//col:40
    sizeof()(ok bool)//col:61
    sizeof()(ok bool)//col:83
    sizeof()(ok bool)//col:111
    sizeof()(ok bool)//col:188
    sizeof()(ok bool)//col:205
    sizeof()(ok bool)//col:221
    sizeof()(ok bool)//col:237
    sizeof()(ok bool)//col:255
    sizeof()(ok bool)//col:279
    sizeof()(ok bool)//col:301
    sizeof()(ok bool)//col:318
    sizeof()(ok bool)//col:455
    sizeof()(ok bool)//col:510
    sizeof()(ok bool)//col:549
    sizeof()(ok bool)//col:667
    sizeof()(ok bool)//col:700
    sizeof()(ok bool)//col:841
    sizeof()(ok bool)//col:882
}
)

func NewRequestStructures() { return & requestStructures{} }

func (r *requestStructures)    sizeof()(ok bool){//col:40
/*    sizeof(DEBUGGER_READ_PAGE_TABLE_ENTRIES_DETAILS)
typedef struct _DEBUGGER_READ_PAGE_TABLE_ENTRIES_DETAILS
{
    UINT64 VirtualAddress;
    UINT32 ProcessId;
    UINT64 Pml4eVirtualAddress;
    UINT64 Pml4eValue;
    UINT64 PdpteVirtualAddress;
    UINT64 PdpteValue;
    UINT64 PdeVirtualAddress;
    UINT64 PdeValue;
    UINT64 PteVirtualAddress;
    UINT64 PteValue;
    UINT32 KernelStatus;
} DEBUGGER_READ_PAGE_TABLE_ENTRIES_DETAILS,*/
return true
}

func (r *requestStructures)    sizeof()(ok bool){//col:61
/*    sizeof(DEBUGGER_VA2PA_AND_PA2VA_COMMANDS)
typedef struct _DEBUGGER_VA2PA_AND_PA2VA_COMMANDS
{
    UINT64  VirtualAddress;
    UINT64  PhysicalAddress;
    UINT32  ProcessId;
    BOOLEAN IsVirtual2Physical;
    UINT32  KernelStatus;
} DEBUGGER_VA2PA_AND_PA2VA_COMMANDS, *PDEBUGGER_VA2PA_AND_PA2VA_COMMANDS;*/
return true
}

func (r *requestStructures)    sizeof()(ok bool){//col:83
/*    sizeof(DEBUGGER_DT_COMMAND_OPTIONS)
typedef struct _DEBUGGER_DT_COMMAND_OPTIONS
{
    const char * TypeName;
    UINT64       SizeOfTypeName;
    UINT64       Address;
    BOOLEAN      IsStruct;
    PVOID        BufferAddress;
    UINT32       TargetPid;
    const char * AdditionalParameters;
} DEBUGGER_DT_COMMAND_OPTIONS, *PDEBUGGER_DT_COMMAND_OPTIONS;*/
return true
}

func (r *requestStructures)    sizeof()(ok bool){//col:111
/*    sizeof(DEBUGGER_PREALLOC_COMMAND)
typedef struct _DEBUGGER_PREALLOC_COMMAND
{
    DEBUGGER_PREALLOC_COMMAND_TYPE Type;
    UINT64                         Count;
    UINT32                         KernelStatus;
} DEBUGGER_PREALLOC_COMMAND, *PDEBUGGER_PREALLOC_COMMAND;*/
return true
}

func (r *requestStructures)    sizeof()(ok bool){//col:188
/*    sizeof(DEBUGGER_FLUSH_LOGGING_BUFFERS)
typedef struct _DEBUGGER_FLUSH_LOGGING_BUFFERS
{
    UINT32 KernelStatus;
    UINT32 CountOfMessagesThatSetAsReadFromVmxRoot;
    UINT32 CountOfMessagesThatSetAsReadFromVmxNonRoot;
} DEBUGGER_FLUSH_LOGGING_BUFFERS, *PDEBUGGER_FLUSH_LOGGING_BUFFERS;*/
return true
}

func (r *requestStructures)    sizeof()(ok bool){//col:205
/*    sizeof(DEBUGGER_TEST_QUERY_BUFFER)
typedef struct _DEBUGGER_DEBUGGER_TEST_QUERY_BUFFER
{
    UINT32 RequestIndex;
    UINT32 KernelStatus;
} DEBUGGER_DEBUGGER_TEST_QUERY_BUFFER, *PDEBUGGER_DEBUGGER_TEST_QUERY_BUFFER;*/
return true
}

func (r *requestStructures)    sizeof()(ok bool){//col:221
/*    sizeof(DEBUGGER_PERFORM_KERNEL_TESTS)
typedef struct _DEBUGGER_PERFORM_KERNEL_TESTS
{
    UINT32 KernelStatus;
} DEBUGGER_PERFORM_KERNEL_TESTS, *PDEBUGGER_PERFORM_KERNEL_TESTS;*/
return true
}

func (r *requestStructures)    sizeof()(ok bool){//col:237
/*    sizeof(DEBUGGER_SEND_COMMAND_EXECUTION_FINISHED_SIGNAL)
typedef struct _DEBUGGER_SEND_COMMAND_EXECUTION_FINISHED_SIGNAL
{
    UINT32 KernelStatus;
} DEBUGGER_SEND_COMMAND_EXECUTION_FINISHED_SIGNAL,*/
return true
}

func (r *requestStructures)    sizeof()(ok bool){//col:255
/*    sizeof(DEBUGGEE_KERNEL_AND_USER_TEST_INFORMATION)
typedef struct _DEBUGGEE_KERNEL_AND_USER_TEST_INFORMATION
{
    UINT64 Value;
    char   Tag[32];
} DEBUGGEE_KERNEL_AND_USER_TEST_INFORMATION,*/
return true
}

func (r *requestStructures)    sizeof()(ok bool){//col:279
/*    sizeof(DEBUGGEE_SEND_GENERAL_PACKET_FROM_DEBUGGEE_TO_DEBUGGER)
typedef struct _DEBUGGEE_SEND_GENERAL_PACKET_FROM_DEBUGGEE_TO_DEBUGGER
{
    DEBUGGER_REMOTE_PACKET_REQUESTED_ACTION RequestedAction;
    UINT32                                  LengthOfBuffer;
    BOOLEAN                                 PauseDebuggeeWhenSent;
    UINT32                                  KernelResult;
} DEBUGGEE_SEND_GENERAL_PACKET_FROM_DEBUGGEE_TO_DEBUGGER,*/
return true
}

func (r *requestStructures)    sizeof()(ok bool){//col:301
/*    sizeof(DEBUGGER_SEND_USERMODE_MESSAGES_TO_DEBUGGER)
typedef struct _DEBUGGER_SEND_USERMODE_MESSAGES_TO_DEBUGGER
{
    UINT32 KernelStatus;
    UINT32 Length;
} DEBUGGER_SEND_USERMODE_MESSAGES_TO_DEBUGGER,*/
return true
}

func (r *requestStructures)    sizeof()(ok bool){//col:318
/*    sizeof(DEBUGGER_READ_AND_WRITE_ON_MSR)
typedef enum _DEBUGGER_MSR_ACTION_TYPE
{
    DEBUGGER_MSR_READ,
    DEBUGGER_MSR_WRITE
} DEBUGGER_MSR_ACTION_TYPE;*/
return true
}

func (r *requestStructures)    sizeof()(ok bool){//col:455
/*    sizeof(DEBUGGER_HIDE_AND_TRANSPARENT_DEBUGGER_MODE)
typedef struct _DEBUGGER_HIDE_AND_TRANSPARENT_DEBUGGER_MODE
{
    BOOLEAN IsHide;
    UINT64 CpuidAverage;
    UINT64 CpuidStandardDeviation;
    UINT64 CpuidMedian;
    UINT64 RdtscAverage;
    UINT64 RdtscStandardDeviation;
    UINT64 RdtscMedian;
    BOOLEAN TrueIfProcessIdAndFalseIfProcessName;
    UINT32  ProcId;
                          DEBUGGER_ERROR_UNABLE_TO_HIDE_OR_UNHIDE_DEBUGGER
} DEBUGGER_HIDE_AND_TRANSPARENT_DEBUGGER_MODE,*/
return true
}

func (r *requestStructures)    sizeof()(ok bool){//col:510
/*    sizeof(DEBUGGER_ATTACH_DETACH_USER_MODE_PROCESS)
typedef enum _DEBUGGER_ATTACH_DETACH_USER_MODE_PROCESS_ACTION_TYPE
{
    DEBUGGER_ATTACH_DETACH_USER_MODE_PROCESS_ACTION_ATTACH,
    DEBUGGER_ATTACH_DETACH_USER_MODE_PROCESS_ACTION_DETACH,
    DEBUGGER_ATTACH_DETACH_USER_MODE_PROCESS_ACTION_REMOVE_HOOKS,
    DEBUGGER_ATTACH_DETACH_USER_MODE_PROCESS_ACTION_KILL_PROCESS,
    DEBUGGER_ATTACH_DETACH_USER_MODE_PROCESS_ACTION_PAUSE_PROCESS,
    DEBUGGER_ATTACH_DETACH_USER_MODE_PROCESS_ACTION_SWITCH_BY_PROCESS_OR_THREAD,
    DEBUGGER_ATTACH_DETACH_USER_MODE_PROCESS_ACTION_QUERY_COUNT_OF_ACTIVE_DEBUGGING_THREADS,
} DEBUGGER_ATTACH_DETACH_USER_MODE_PROCESS_ACTION_TYPE;*/
return true
}

func (r *requestStructures)    sizeof()(ok bool){//col:549
/*    sizeof(DEBUGGER_QUERY_ACTIVE_PROCESSES_OR_THREADS)
typedef enum _DEBUGGER_QUERY_ACTIVE_PROCESSES_OR_THREADS_TYPES
{
    DEBUGGER_QUERY_ACTIVE_PROCESSES_OR_THREADS_QUERY_PROCESS_COUNT   = 1,
    DEBUGGER_QUERY_ACTIVE_PROCESSES_OR_THREADS_QUERY_THREAD_COUNT    = 2,
    DEBUGGER_QUERY_ACTIVE_PROCESSES_OR_THREADS_QUERY_PROCESS_LIST    = 3,
    DEBUGGER_QUERY_ACTIVE_PROCESSES_OR_THREADS_QUERY_THREAD_LIST     = 4,
    DEBUGGER_QUERY_ACTIVE_PROCESSES_OR_THREADS_QUERY_CURRENT_PROCESS = 5,
    DEBUGGER_QUERY_ACTIVE_PROCESSES_OR_THREADS_QUERY_CURRENT_THREAD  = 6,
} DEBUGGER_QUERY_ACTIVE_PROCESSES_OR_THREADS_TYPES;*/
return true
}

func (r *requestStructures)    sizeof()(ok bool){//col:667
/*    sizeof(DEBUGGER_CALLSTACK_REQUEST)
typedef enum _DEBUGGER_CALLSTACK_DISPLAY_METHOD
{
    DEBUGGER_CALLSTACK_DISPLAY_METHOD_WITHOUT_PARAMS,
    DEBUGGER_CALLSTACK_DISPLAY_METHOD_WITH_PARAMS,
} DEBUGGER_CALLSTACK_DISPLAY_METHOD;*/
return true
}

func (r *requestStructures)    sizeof()(ok bool){//col:700
/*    sizeof(USERMODE_DEBUGGING_THREAD_OR_PROCESS_STATE_DETAILS)
typedef struct _USERMODE_DEBUGGING_THREAD_OR_PROCESS_STATE_DETAILS
{
    UINT32  ProcessId;
    UINT32  ThreadId;
    BOOLEAN IsProcess;
} USERMODE_DEBUGGING_THREAD_OR_PROCESS_STATE_DETAILS, *PUSERMODE_DEBUGGING_THREAD_OR_PROCESS_STATE_DETAILS;*/
return true
}

func (r *requestStructures)    sizeof()(ok bool){//col:841
/*    sizeof(DEBUGGEE_DETAILS_AND_SWITCH_PROCESS_PACKET)
typedef enum _DEBUGGEE_DETAILS_AND_SWITCH_THREAD_TYPE
{
    DEBUGGEE_DETAILS_AND_SWITCH_THREAD_PERFORM_SWITCH,
    DEBUGGEE_DETAILS_AND_SWITCH_THREAD_GET_THREAD_DETAILS,
    DEBUGGEE_DETAILS_AND_SWITCH_THREAD_GET_THREAD_LIST,
} DEBUGGEE_DETAILS_AND_SWITCH_THREAD_TYPE;*/
return true
}

func (r *requestStructures)    sizeof()(ok bool){//col:882
/*    sizeof(DEBUGGEE_DETAILS_AND_SWITCH_THREAD_PACKET)
typedef enum _DEBUGGER_REMOTE_STEPPING_REQUEST
{
    DEBUGGER_REMOTE_STEPPING_REQUEST_STEP_OVER,
    DEBUGGER_REMOTE_STEPPING_REQUEST_STEP_IN,
    DEBUGGER_REMOTE_STEPPING_REQUEST_INSTRUMENTATION_STEP_IN,
} DEBUGGER_REMOTE_STEPPING_REQUEST;*/
return true
}



