package Headers
const(
SIZEOF_DEBUGGER_READ_PAGE_TABLE_ENTRIES_DETAILS = sizeof(DEBUGGER_READ_PAGE_TABLE_ENTRIES_DETAILS) //col:14
SIZEOF_DEBUGGER_VA2PA_AND_PA2VA_COMMANDS = sizeof(DEBUGGER_VA2PA_AND_PA2VA_COMMANDS) //col:46
SIZEOF_DEBUGGER_DT_COMMAND_OPTIONS = sizeof(DEBUGGER_DT_COMMAND_OPTIONS) //col:66
SIZEOF_DEBUGGER_PREALLOC_COMMAND = sizeof(DEBUGGER_PREALLOC_COMMAND) //col:98
SIZEOF_DEBUGGER_READ_MEMORY = sizeof(DEBUGGER_READ_MEMORY) //col:116
SIZEOF_DEBUGGER_FLUSH_LOGGING_BUFFERS = sizeof(DEBUGGER_FLUSH_LOGGING_BUFFERS) //col:175
SIZEOF_DEBUGGER_TEST_QUERY_BUFFER = sizeof(DEBUGGER_TEST_QUERY_BUFFER) //col:193
SIZEOF_DEBUGGER_PERFORM_KERNEL_TESTS = sizeof(DEBUGGER_PERFORM_KERNEL_TESTS) //col:210
SIZEOF_DEBUGGER_SEND_COMMAND_EXECUTION_FINISHED_SIGNAL = sizeof(DEBUGGER_SEND_COMMAND_EXECUTION_FINISHED_SIGNAL) //col:226
SIZEOF_DEBUGGEE_KERNEL_AND_USER_TEST_INFORMATION = sizeof(DEBUGGEE_KERNEL_AND_USER_TEST_INFORMATION) //col:243
SIZEOF_DEBUGGEE_SEND_GENERAL_PACKET_FROM_DEBUGGEE_TO_DEBUGGER = sizeof(DEBUGGEE_SEND_GENERAL_PACKET_FROM_DEBUGGEE_TO_DEBUGGER) //col:261
SIZEOF_DEBUGGER_SEND_USERMODE_MESSAGES_TO_DEBUGGER = sizeof(DEBUGGER_SEND_USERMODE_MESSAGES_TO_DEBUGGER) //col:285
SIZEOF_DEBUGGER_READ_AND_WRITE_ON_MSR = sizeof(DEBUGGER_READ_AND_WRITE_ON_MSR) //col:307
SIZEOF_DEBUGGER_EDIT_MEMORY = sizeof(DEBUGGER_EDIT_MEMORY) //col:339
SIZEOF_DEBUGGER_SEARCH_MEMORY = sizeof(DEBUGGER_SEARCH_MEMORY) //col:382
SIZEOF_DEBUGGER_HIDE_AND_TRANSPARENT_DEBUGGER_MODE = sizeof(DEBUGGER_HIDE_AND_TRANSPARENT_DEBUGGER_MODE) //col:427
SIZEOF_DEBUGGER_PREPARE_DEBUGGEE = sizeof(DEBUGGER_PREPARE_DEBUGGEE) //col:461
SIZEOF_DEBUGGER_ATTACH_DETACH_USER_MODE_PROCESS = sizeof(DEBUGGER_ATTACH_DETACH_USER_MODE_PROCESS) //col:493
SIZEOF_DEBUGGER_QUERY_ACTIVE_PROCESSES_OR_THREADS = sizeof(DEBUGGER_QUERY_ACTIVE_PROCESSES_OR_THREADS) //col:533
SIZEOF_DEBUGGER_CALLSTACK_REQUEST = sizeof(DEBUGGER_CALLSTACK_REQUEST) //col:655
SIZEOF_USERMODE_DEBUGGING_THREAD_OR_PROCESS_STATE_DETAILS = sizeof(USERMODE_DEBUGGING_THREAD_OR_PROCESS_STATE_DETAILS) //col:691
SIZEOF_DEBUGGEE_DETAILS_AND_SWITCH_PROCESS_PACKET = sizeof(DEBUGGEE_DETAILS_AND_SWITCH_PROCESS_PACKET) //col:827
SIZEOF_DEBUGGEE_DETAILS_AND_SWITCH_THREAD_PACKET = sizeof(DEBUGGEE_DETAILS_AND_SWITCH_THREAD_PACKET) //col:865
)
type     DEBUGGER_PREALLOC_COMMAND_TYPE_MONITOR uint32
const(
    DEBUGGER_PREALLOC_COMMAND_TYPE_MONITOR DEBUGGER_PREALLOC_COMMAND_TYPE = 1  //col:94
    DEBUGGER_PREALLOC_COMMAND_TYPE_THREAD_INTERCEPTION DEBUGGER_PREALLOC_COMMAND_TYPE = 2  //col:95
)
type     READ_FROM_KERNEL uint32
const(
    READ_FROM_KERNEL DEBUGGER_READ_READING_TYPE = 1  //col:124
    READ_FROM_VMX_ROOT DEBUGGER_READ_READING_TYPE = 2  //col:125
)
type     DEBUGGER_READ_PHYSICAL_ADDRESS uint32
const(
    DEBUGGER_READ_PHYSICAL_ADDRESS DEBUGGER_READ_MEMORY_TYPE = 1  //col:134
    DEBUGGER_READ_VIRTUAL_ADDRESS DEBUGGER_READ_MEMORY_TYPE = 2  //col:135
)
type     DEBUGGER_SHOW_COMMAND_DT = 1 uint32
const(
    DEBUGGER_SHOW_COMMAND_DT  DEBUGGER_SHOW_MEMORY_STYLE =  1  //col:145
    DEBUGGER_SHOW_COMMAND_DISASSEMBLE64 DEBUGGER_SHOW_MEMORY_STYLE = 2  //col:146
    DEBUGGER_SHOW_COMMAND_DISASSEMBLE32 DEBUGGER_SHOW_MEMORY_STYLE = 3  //col:147
    DEBUGGER_SHOW_COMMAND_DB DEBUGGER_SHOW_MEMORY_STYLE = 4  //col:148
    DEBUGGER_SHOW_COMMAND_DC DEBUGGER_SHOW_MEMORY_STYLE = 5  //col:149
    DEBUGGER_SHOW_COMMAND_DQ DEBUGGER_SHOW_MEMORY_STYLE = 6  //col:150
    DEBUGGER_SHOW_COMMAND_DD DEBUGGER_SHOW_MEMORY_STYLE = 7  //col:151
)
type     DEBUGGER_MSR_READ uint32
const(
    DEBUGGER_MSR_READ DEBUGGER_MSR_ACTION_TYPE = 1  //col:316
    DEBUGGER_MSR_WRITE DEBUGGER_MSR_ACTION_TYPE = 2  //col:317
)
type     EDIT_PHYSICAL_MEMORY uint32
const(
    EDIT_PHYSICAL_MEMORY DEBUGGER_EDIT_MEMORY_TYPE = 1  //col:347
    EDIT_VIRTUAL_MEMORY DEBUGGER_EDIT_MEMORY_TYPE = 2  //col:348
)
type     EDIT_BYTE uint32
const(
    EDIT_BYTE DEBUGGER_EDIT_MEMORY_BYTE_SIZE = 1  //col:357
    EDIT_DWORD DEBUGGER_EDIT_MEMORY_BYTE_SIZE = 2  //col:358
    EDIT_QWORD DEBUGGER_EDIT_MEMORY_BYTE_SIZE = 3  //col:359
)
type     SEARCH_PHYSICAL_MEMORY uint32
const(
    SEARCH_PHYSICAL_MEMORY DEBUGGER_SEARCH_MEMORY_TYPE = 1  //col:390
    SEARCH_VIRTUAL_MEMORY DEBUGGER_SEARCH_MEMORY_TYPE = 2  //col:391
    SEARCH_PHYSICAL_FROM_VIRTUAL_MEMORY DEBUGGER_SEARCH_MEMORY_TYPE = 3  //col:392
)
type     SEARCH_BYTE uint32
const(
    SEARCH_BYTE DEBUGGER_SEARCH_MEMORY_BYTE_SIZE = 1  //col:402
    SEARCH_DWORD DEBUGGER_SEARCH_MEMORY_BYTE_SIZE = 2  //col:403
    SEARCH_QWORD DEBUGGER_SEARCH_MEMORY_BYTE_SIZE = 3  //col:404
)
type     DEBUGGER_ATTACH_DETACH_USER_MODE_PROCESS_ACTION_ATTACH uint32
const(
    DEBUGGER_ATTACH_DETACH_USER_MODE_PROCESS_ACTION_ATTACH DEBUGGER_ATTACH_DETACH_USER_MODE_PROCESS_ACTION_TYPE = 1  //col:502
    DEBUGGER_ATTACH_DETACH_USER_MODE_PROCESS_ACTION_DETACH DEBUGGER_ATTACH_DETACH_USER_MODE_PROCESS_ACTION_TYPE = 2  //col:503
    DEBUGGER_ATTACH_DETACH_USER_MODE_PROCESS_ACTION_REMOVE_HOOKS DEBUGGER_ATTACH_DETACH_USER_MODE_PROCESS_ACTION_TYPE = 3  //col:504
    DEBUGGER_ATTACH_DETACH_USER_MODE_PROCESS_ACTION_KILL_PROCESS DEBUGGER_ATTACH_DETACH_USER_MODE_PROCESS_ACTION_TYPE = 4  //col:505
    DEBUGGER_ATTACH_DETACH_USER_MODE_PROCESS_ACTION_PAUSE_PROCESS DEBUGGER_ATTACH_DETACH_USER_MODE_PROCESS_ACTION_TYPE = 5  //col:506
    DEBUGGER_ATTACH_DETACH_USER_MODE_PROCESS_ACTION_SWITCH_BY_PROCESS_OR_THREAD DEBUGGER_ATTACH_DETACH_USER_MODE_PROCESS_ACTION_TYPE = 6  //col:507
    DEBUGGER_ATTACH_DETACH_USER_MODE_PROCESS_ACTION_QUERY_COUNT_OF_ACTIVE_DEBUGGING_THREADS DEBUGGER_ATTACH_DETACH_USER_MODE_PROCESS_ACTION_TYPE = 7  //col:508
)
type     DEBUGGER_QUERY_ACTIVE_PROCESSES_OR_THREADS_QUERY_PROCESS_COUNT   = 1 uint32
const(
    DEBUGGER_QUERY_ACTIVE_PROCESSES_OR_THREADS_QUERY_PROCESS_COUNT    DEBUGGER_QUERY_ACTIVE_PROCESSES_OR_THREADS_TYPES =  1  //col:542
    DEBUGGER_QUERY_ACTIVE_PROCESSES_OR_THREADS_QUERY_THREAD_COUNT     DEBUGGER_QUERY_ACTIVE_PROCESSES_OR_THREADS_TYPES =  2  //col:543
    DEBUGGER_QUERY_ACTIVE_PROCESSES_OR_THREADS_QUERY_PROCESS_LIST     DEBUGGER_QUERY_ACTIVE_PROCESSES_OR_THREADS_TYPES =  3  //col:544
    DEBUGGER_QUERY_ACTIVE_PROCESSES_OR_THREADS_QUERY_THREAD_LIST      DEBUGGER_QUERY_ACTIVE_PROCESSES_OR_THREADS_TYPES =  4  //col:545
    DEBUGGER_QUERY_ACTIVE_PROCESSES_OR_THREADS_QUERY_CURRENT_PROCESS  DEBUGGER_QUERY_ACTIVE_PROCESSES_OR_THREADS_TYPES =  5  //col:546
    DEBUGGER_QUERY_ACTIVE_PROCESSES_OR_THREADS_QUERY_CURRENT_THREAD   DEBUGGER_QUERY_ACTIVE_PROCESSES_OR_THREADS_TYPES =  6  //col:547
)
type     DEBUGGER_QUERY_ACTIVE_PROCESSES_OR_THREADS_ACTION_SHOW_INSTANTLY     = 1 uint32
const(
    DEBUGGER_QUERY_ACTIVE_PROCESSES_OR_THREADS_ACTION_SHOW_INSTANTLY      DEBUGGER_QUERY_ACTIVE_PROCESSES_OR_THREADS_ACTIONS =  1  //col:557
    DEBUGGER_QUERY_ACTIVE_PROCESSES_OR_THREADS_ACTION_QUERY_COUNT         DEBUGGER_QUERY_ACTIVE_PROCESSES_OR_THREADS_ACTIONS =  2  //col:558
    DEBUGGER_QUERY_ACTIVE_PROCESSES_OR_THREADS_ACTION_QUERY_SAVE_DETAILS  DEBUGGER_QUERY_ACTIVE_PROCESSES_OR_THREADS_ACTIONS =  3  //col:559
)
type     DEBUGGER_CALLSTACK_DISPLAY_METHOD_WITHOUT_PARAMS uint32
const(
    DEBUGGER_CALLSTACK_DISPLAY_METHOD_WITHOUT_PARAMS DEBUGGER_CALLSTACK_DISPLAY_METHOD = 1  //col:664
    DEBUGGER_CALLSTACK_DISPLAY_METHOD_WITH_PARAMS DEBUGGER_CALLSTACK_DISPLAY_METHOD = 2  //col:665
)
type     DEBUGGER_UD_COMMAND_ACTION_TYPE_NONE = 0 uint32
const(
    DEBUGGER_UD_COMMAND_ACTION_TYPE_NONE  DEBUGGER_UD_COMMAND_ACTION_TYPE =  0  //col:752
    DEBUGGER_UD_COMMAND_ACTION_TYPE_PAUSE DEBUGGER_UD_COMMAND_ACTION_TYPE = 2  //col:753
    DEBUGGER_UD_COMMAND_ACTION_TYPE_CONTINUE DEBUGGER_UD_COMMAND_ACTION_TYPE = 3  //col:754
    DEBUGGER_UD_COMMAND_ACTION_TYPE_REGULAR_STEP DEBUGGER_UD_COMMAND_ACTION_TYPE = 4  //col:755
)
type     DEBUGGEE_DETAILS_AND_SWITCH_PROCESS_GET_PROCESS_DETAILS uint32
const(
    DEBUGGEE_DETAILS_AND_SWITCH_PROCESS_GET_PROCESS_DETAILS DEBUGGEE_DETAILS_AND_SWITCH_PROCESS_TYPE = 1  //col:797
    DEBUGGEE_DETAILS_AND_SWITCH_PROCESS_GET_PROCESS_LIST DEBUGGEE_DETAILS_AND_SWITCH_PROCESS_TYPE = 2  //col:798
    DEBUGGEE_DETAILS_AND_SWITCH_PROCESS_PERFORM_SWITCH DEBUGGEE_DETAILS_AND_SWITCH_PROCESS_TYPE = 3  //col:799
)
type     DEBUGGEE_DETAILS_AND_SWITCH_THREAD_PERFORM_SWITCH uint32
const(
    DEBUGGEE_DETAILS_AND_SWITCH_THREAD_PERFORM_SWITCH DEBUGGEE_DETAILS_AND_SWITCH_THREAD_TYPE = 1  //col:837
    DEBUGGEE_DETAILS_AND_SWITCH_THREAD_GET_THREAD_DETAILS DEBUGGEE_DETAILS_AND_SWITCH_THREAD_TYPE = 2  //col:838
    DEBUGGEE_DETAILS_AND_SWITCH_THREAD_GET_THREAD_LIST DEBUGGEE_DETAILS_AND_SWITCH_THREAD_TYPE = 3  //col:839
)
type     DEBUGGER_REMOTE_STEPPING_REQUEST_STEP_OVER uint32
const(
    DEBUGGER_REMOTE_STEPPING_REQUEST_STEP_OVER DEBUGGER_REMOTE_STEPPING_REQUEST = 1  //col:878
    DEBUGGER_REMOTE_STEPPING_REQUEST_STEP_IN DEBUGGER_REMOTE_STEPPING_REQUEST = 2  //col:879
    DEBUGGER_REMOTE_STEPPING_REQUEST_INSTRUMENTATION_STEP_IN DEBUGGER_REMOTE_STEPPING_REQUEST = 3  //col:880
)
type     DEBUGGEE_BREAKPOINT_MODIFICATION_REQUEST_LIST_BREAKPOINTS uint32
const(
    DEBUGGEE_BREAKPOINT_MODIFICATION_REQUEST_LIST_BREAKPOINTS DEBUGGEE_BREAKPOINT_MODIFICATION_REQUEST = 1  //col:973
    DEBUGGEE_BREAKPOINT_MODIFICATION_REQUEST_ENABLE DEBUGGEE_BREAKPOINT_MODIFICATION_REQUEST = 2  //col:974
    DEBUGGEE_BREAKPOINT_MODIFICATION_REQUEST_DISABLE DEBUGGEE_BREAKPOINT_MODIFICATION_REQUEST = 3  //col:975
    DEBUGGEE_BREAKPOINT_MODIFICATION_REQUEST_CLEAR DEBUGGEE_BREAKPOINT_MODIFICATION_REQUEST = 4  //col:976
)
type     DEBUGGER_CONDITIONAL_JUMP_STATUS_ERROR = 0 uint32
const(
    DEBUGGER_CONDITIONAL_JUMP_STATUS_ERROR  DEBUGGER_CONDITIONAL_JUMP_STATUS =  0  //col:1002
    DEBUGGER_CONDITIONAL_JUMP_STATUS_NOT_CONDITIONAL_JUMP DEBUGGER_CONDITIONAL_JUMP_STATUS = 2  //col:1003
    DEBUGGER_CONDITIONAL_JUMP_STATUS_JUMP_IS_TAKEN DEBUGGER_CONDITIONAL_JUMP_STATUS = 3  //col:1004
    DEBUGGER_CONDITIONAL_JUMP_STATUS_JUMP_IS_NOT_TAKEN DEBUGGER_CONDITIONAL_JUMP_STATUS = 4  //col:1005
)
type (
RequestStructures interface{
    sizeof()(ok bool)//col:40
    sizeof()(ok bool)//col:61
    sizeof()(ok bool)//col:83
    sizeof()(ok bool)//col:111
#define SIZEOF_DEBUGGER_READ_MEMORY sizeof()(ok bool)//col:126
    sizeof()(ok bool)//col:188
    sizeof()(ok bool)//col:205
    sizeof()(ok bool)//col:221
    sizeof()(ok bool)//col:237
    sizeof()(ok bool)//col:255
    sizeof()(ok bool)//col:279
    sizeof()(ok bool)//col:301
    sizeof()(ok bool)//col:318
#define SIZEOF_DEBUGGER_EDIT_MEMORY sizeof()(ok bool)//col:349
#define SIZEOF_DEBUGGER_SEARCH_MEMORY sizeof()(ok bool)//col:394
    sizeof()(ok bool)//col:455
#define SIZEOF_DEBUGGER_PREPARE_DEBUGGEE sizeof()(ok bool)//col:475
    sizeof()(ok bool)//col:510
    sizeof()(ok bool)//col:549
    sizeof()(ok bool)//col:667
    sizeof()(ok bool)//col:700
    sizeof()(ok bool)//col:841
    sizeof()(ok bool)//col:882
}

)
func NewRequestStructures() { return & requestStructures{} }
func (r *requestStructures)    sizeof()(ok bool){//col:40
return true
}

func (r *requestStructures)    sizeof()(ok bool){//col:61
return true
}

func (r *requestStructures)    sizeof()(ok bool){//col:83
return true
}

func (r *requestStructures)    sizeof()(ok bool){//col:111
return true
}

func (r *requestStructures)#define SIZEOF_DEBUGGER_READ_MEMORY sizeof()(ok bool){//col:126
return true
}

func (r *requestStructures)    sizeof()(ok bool){//col:188
return true
}

func (r *requestStructures)    sizeof()(ok bool){//col:205
return true
}

func (r *requestStructures)    sizeof()(ok bool){//col:221
return true
}

func (r *requestStructures)    sizeof()(ok bool){//col:237
return true
}

func (r *requestStructures)    sizeof()(ok bool){//col:255
return true
}

func (r *requestStructures)    sizeof()(ok bool){//col:279
return true
}

func (r *requestStructures)    sizeof()(ok bool){//col:301
return true
}

func (r *requestStructures)    sizeof()(ok bool){//col:318
return true
}

func (r *requestStructures)#define SIZEOF_DEBUGGER_EDIT_MEMORY sizeof()(ok bool){//col:349
return true
}

func (r *requestStructures)#define SIZEOF_DEBUGGER_SEARCH_MEMORY sizeof()(ok bool){//col:394
return true
}

func (r *requestStructures)    sizeof()(ok bool){//col:455
return true
}

func (r *requestStructures)#define SIZEOF_DEBUGGER_PREPARE_DEBUGGEE sizeof()(ok bool){//col:475
return true
}

func (r *requestStructures)    sizeof()(ok bool){//col:510
return true
}

func (r *requestStructures)    sizeof()(ok bool){//col:549
return true
}

func (r *requestStructures)    sizeof()(ok bool){//col:667
return true
}

func (r *requestStructures)    sizeof()(ok bool){//col:700
return true
}

func (r *requestStructures)    sizeof()(ok bool){//col:841
return true
}

func (r *requestStructures)    sizeof()(ok bool){//col:882
return true
}

