go run mvdan.cc/gofumpt@latest -w .
go fix ./...
go run mvdan.cc/gofumpt@latest -w .
go fix ./...
go run mvdan.cc/gofumpt@latest -w .
go fix ./...
go run mvdan.cc/gofumpt@latest -w .
go fix ./...
go run mvdan.cc/gofumpt@latest -w .
go fix ./...
go run mvdan.cc/gofumpt@latest -w .
go fix ./...
go run mvdan.cc/gofumpt@latest -w .
go fix ./...
go run mvdan.cc/gofumpt@latest -w .
go fix ./...
go run mvdan.cc/gofumpt@latest -w .
go fix ./...
go run mvdan.cc/gofumpt@latest -w .
go fix ./...
go run mvdan.cc/gofumpt@latest -w .
go fix ./...
go run mvdan.cc/gofumpt@latest -w .
go fix ./...
go run mvdan.cc/gofumpt@latest -w .
go fix ./...
go run mvdan.cc/gofumpt@latest -w .
go fix ./...
go run mvdan.cc/gofumpt@latest -w .
go fix ./...
go run mvdan.cc/gofumpt@latest -w .
go fix ./...
go run mvdan.cc/gofumpt@latest -w .
go fix ./...
go run mvdan.cc/gofumpt@latest -w .
go fix ./...
go run mvdan.cc/gofumpt@latest -w .
go fix ./...
go run mvdan.cc/gofumpt@latest -w .
go fix ./...
go run mvdan.cc/gofumpt@latest -w .
go fix ./...
go run mvdan.cc/gofumpt@latest -w .
go fix ./...
go run mvdan.cc/gofumpt@latest -w .
go fix ./...
go run mvdan.cc/gofumpt@latest -w .
go fix ./...
go run mvdan.cc/gofumpt@latest -w .
go fix ./...
go run mvdan.cc/gofumpt@latest -w .
go fix ./...
go run mvdan.cc/gofumpt@latest -w .
go fix ./...
go run mvdan.cc/gofumpt@latest -w .
go fix ./...
go run mvdan.cc/gofumpt@latest -w .
go fix ./...
go run mvdan.cc/gofumpt@latest -w .
go fix ./...
go run mvdan.cc/gofumpt@latest -w .
go fix ./...
go run mvdan.cc/gofumpt@latest -w .
go fix ./...
go run mvdan.cc/gofumpt@latest -w .
go run mvdan.cc/gofumpt@latest -w .
go fix ./...
go run mvdan.cc/gofumpt@latest -w .
go fix ./...
go run mvdan.cc/gofumpt@latest -w .
go fix ./...
go run mvdan.cc/gofumpt@latest -w .
go fix ./...
go run mvdan.cc/gofumpt@latest -w .
go fix ./...
go run mvdan.cc/gofumpt@latest -w .
go fix ./...
go run mvdan.cc/gofumpt@latest -w .
go fix ./...
go run mvdan.cc/gofumpt@latest -w .
go fix ./...
go run mvdan.cc/gofumpt@latest -w .
go fix ./...
