package debugger

type ErrorCode uint32

const (
	DEBUGGER_OPERATION_WAS_SUCCESSFUL ErrorCode = 0xFFFFFFFF

	DEBUGGER_ERROR_TAG_NOT_EXISTS                                                  ErrorCode = 0xc0000000
	DEBUGGER_ERROR_INVALID_ACTION_TYPE                                             ErrorCode = 0xc0000001
	DEBUGGER_ERROR_ACTION_BUFFER_SIZE_IS_ZERO                                      ErrorCode = 0xc0000002
	DEBUGGER_ERROR_EVENT_TYPE_IS_INVALID                                           ErrorCode = 0xc0000003
	DEBUGGER_ERROR_UNABLE_TO_CREATE_EVENT                                          ErrorCode = 0xc0000004
	DEBUGGER_ERROR_INVALID_ADDRESS                                                 ErrorCode = 0xc0000005
	DEBUGGER_ERROR_INVALID_CORE_ID                                                 ErrorCode = 0xc0000006
	DEBUGGER_ERROR_EXCEPTION_INDEX_EXCEED_FIRST_32_ENTRIES                         ErrorCode = 0xc0000007
	DEBUGGER_ERROR_INTERRUPT_INDEX_IS_NOT_VALID                                    ErrorCode = 0xc0000008
	DEBUGGER_ERROR_UNABLE_TO_HIDE_OR_UNHIDE_DEBUGGER                               ErrorCode = 0xc0000009
	DEBUGGER_ERROR_DEBUGGER_ALREADY_HIDE                                           ErrorCode = 0xc000000a
	DEBUGGER_ERROR_EDIT_MEMORY_STATUS_INVALID_PARAMETER                            ErrorCode = 0xc000000b
	DEBUGGER_ERROR_EDIT_MEMORY_STATUS_INVALID_ADDRESS_BASED_ON_CURRENT_PROCESS     ErrorCode = 0xc000000c
	DEBUGGER_ERROR_EDIT_MEMORY_STATUS_INVALID_ADDRESS_BASED_ON_OTHER_PROCESS       ErrorCode = 0xc000000d
	DEBUGGER_ERROR_MODIFY_EVENTS_INVALID_TAG                                       ErrorCode = 0xc000000e
	DEBUGGER_ERROR_MODIFY_EVENTS_INVALID_TYPE_OF_ACTION                            ErrorCode = 0xc000000f
	DEBUGGER_ERROR_STEPPING_INVALID_PARAMETER                                      ErrorCode = 0xc0000010
	DEBUGGER_ERROR_STEPPINGS_EITHER_THREAD_NOT_FOUND_OR_DISABLED                   ErrorCode = 0xc0000011
	DEBUGGER_ERROR_PREPARING_DEBUGGEE_INVALID_BAUDRATE                             ErrorCode = 0xc0000012
	DEBUGGER_ERROR_PREPARING_DEBUGGEE_INVALID_SERIAL_PORT                          ErrorCode = 0xc0000013
	DEBUGGER_ERROR_PREPARING_DEBUGGEE_INVALID_CORE_IN_REMOTE_DEBUGGE               ErrorCode = 0xc0000014
	DEBUGGER_ERROR_PREPARING_DEBUGGEE_UNABLE_TO_SWITCH_TO_NEW_PROCESS              ErrorCode = 0xc0000015
	DEBUGGER_ERROR_PREPARING_DEBUGGEE_TO_RUN_SCRIPT                                ErrorCode = 0xc0000016
	DEBUGGER_ERROR_INVALID_REGISTER_NUMBER                                         ErrorCode = 0xc0000017
	DEBUGGER_ERROR_MAXIMUM_BREAKPOINT_WITHOUT_CONTINUE                             ErrorCode = 0xc0000018
	DEBUGGER_ERROR_BREAKPOINT_ALREADY_EXISTS_ON_THE_ADDRESS                        ErrorCode = 0xc0000019
	DEBUGGER_ERROR_BREAKPOINT_ID_NOT_FOUND                                         ErrorCode = 0xc000001a
	DEBUGGER_ERROR_BREAKPOINT_ALREADY_DISABLED                                     ErrorCode = 0xc000001b
	DEBUGGER_ERROR_BREAKPOINT_ALREADY_ENABLED                                      ErrorCode = 0xc000001c
	DEBUGGER_ERROR_MEMORY_TYPE_INVALID                                             ErrorCode = 0xc000001d
	DEBUGGER_ERROR_INVALID_PROCESS_ID                                              ErrorCode = 0xc000001e
	DEBUGGER_ERROR_EVENT_IS_NOT_APPLIED                                            ErrorCode = 0xc000001f
	DEBUGGER_ERROR_DETAILS_OR_SWITCH_PROCESS_INVALID_PARAMETER                     ErrorCode = 0xc0000020
	DEBUGGER_ERROR_DETAILS_OR_SWITCH_THREAD_INVALID_PARAMETER                      ErrorCode = 0xc0000021
	DEBUGGER_ERROR_MAXIMUM_BREAKPOINT_FOR_A_SINGLE_PAGE_IS_HIT                     ErrorCode = 0xc0000022
	DEBUGGER_ERROR_PRE_ALLOCATED_BUFFER_IS_EMPTY                                   ErrorCode = 0xc0000023
	DEBUGGER_ERROR_EPT_COULD_NOT_SPLIT_THE_LARGE_PAGE_TO_4KB_PAGES                 ErrorCode = 0xc0000024
	DEBUGGER_ERROR_EPT_FAILED_TO_GET_PML1_ENTRY_OF_TARGET_ADDRESS                  ErrorCode = 0xc0000025
	DEBUGGER_ERROR_EPT_MULTIPLE_HOOKS_IN_A_SINGLE_PAGE                             ErrorCode = 0xc0000026
	DEBUGGER_ERROR_COULD_NOT_BUILD_THE_EPT_HOOK                                    ErrorCode = 0xc0000027
	DEBUGGER_ERROR_COULD_NOT_FIND_ALLOCATION_TYPE                                  ErrorCode = 0xc0000028
	DEBUGGER_ERROR_INVALID_TEST_QUERY_INDEX                                        ErrorCode = 0xc0000029
	DEBUGGER_ERROR_UNABLE_TO_ATTACH_TO_TARGET_USER_MODE_PROCESS                    ErrorCode = 0xc000002a
	DEBUGGER_ERROR_UNABLE_TO_REMOVE_HOOKS_ENTRYPOINT_NOT_REACHED                   ErrorCode = 0xc000002b
	DEBUGGER_ERROR_UNABLE_TO_REMOVE_HOOKS                                          ErrorCode = 0xc000002c
	DEBUGGER_ERROR_FUNCTIONS_FOR_INITIALIZING_PEB_ADDRESSES_ARE_NOT_INITIALIZED    ErrorCode = 0xc000002d
	DEBUGGER_ERROR_UNABLE_TO_DETECT_32_BIT_OR_64_BIT_PROCESS                       ErrorCode = 0xc000002e
	DEBUGGER_ERROR_UNABLE_TO_KILL_THE_PROCESS                                      ErrorCode = 0xc000002f
	DEBUGGER_ERROR_INVALID_THREAD_DEBUGGING_TOKEN                                  ErrorCode = 0xc0000030
	DEBUGGER_ERROR_UNABLE_TO_PAUSE_THE_PROCESS_THREADS                             ErrorCode = 0xc0000031
	DEBUGGER_ERROR_UNABLE_TO_ATTACH_TO_AN_ALREADY_ATTACHED_PROCESS                 ErrorCode = 0xc0000032
	DEBUGGER_ERROR_THE_USER_DEBUGGER_NOT_ATTACHED_TO_THE_PROCESS                   ErrorCode = 0xc0000033
	DEBUGGER_ERROR_UNABLE_TO_DETACH_AS_THERE_ARE_PAUSED_THREADS                    ErrorCode = 0xc0000034
	DEBUGGER_ERROR_UNABLE_TO_SWITCH_PROCESS_ID_OR_THREAD_ID_IS_INVALID             ErrorCode = 0xc0000035
	DEBUGGER_ERROR_UNABLE_TO_SWITCH_THERE_IS_NO_THREAD_ON_THE_PROCESS              ErrorCode = 0xc0000036
	DEBUGGER_ERROR_UNABLE_TO_GET_MODULES_OF_THE_PROCESS                            ErrorCode = 0xc0000037
	DEBUGGER_ERROR_UNABLE_TO_GET_CALLSTACK                                         ErrorCode = 0xc0000038
	DEBUGGER_ERROR_UNABLE_TO_QUERY_COUNT_OF_PROCESSES_OR_THREADS                   ErrorCode = 0xc0000039
	DEBUGGER_ERROR_USING_SHORT_CIRCUITING_EVENT_WITH_POST_EVENT_MODE_IS_FORBIDDEDN ErrorCode = 0xc000003a
	DEBUGGER_ERROR_UNKNOWN_TEST_QUERY_RECEIVED                                     ErrorCode = 0xc000003b
	DEBUGGER_ERROR_READING_MEMORY_INVALID_PARAMETER                                ErrorCode = 0xc000003c
	DEBUGGER_ERROR_THE_TRAP_FLAG_LIST_IS_FULL                                      ErrorCode = 0xc000003d
	DEBUGGER_ERROR_UNABLE_TO_KILL_THE_PROCESS_DOES_NOT_EXISTS                      ErrorCode = 0xc000003e
	DEBUGGER_ERROR_MODE_EXECUTION_IS_INVALID                                       ErrorCode = 0xc000003f
)

func (e ErrorCode) String() string {
	switch e {
	case DEBUGGER_OPERATION_WAS_SUCCESSFUL:
		return "操作成功"
	case DEBUGGER_ERROR_TAG_NOT_EXISTS:
		return "标签不存在"
	case DEBUGGER_ERROR_INVALID_ACTION_TYPE:
		return "无效的操作类型"
	case DEBUGGER_ERROR_ACTION_BUFFER_SIZE_IS_ZERO:
		return "操作缓冲区大小为零"
	case DEBUGGER_ERROR_EVENT_TYPE_IS_INVALID:
		return "事件类型无效"
	case DEBUGGER_ERROR_UNABLE_TO_CREATE_EVENT:
		return "无法创建事件"
	case DEBUGGER_ERROR_INVALID_ADDRESS:
		return "无效地址（可能已换出或页表中不可用）"
	case DEBUGGER_ERROR_INVALID_CORE_ID:
		return "无效的核心ID"
	case DEBUGGER_ERROR_EXCEPTION_INDEX_EXCEED_FIRST_32_ENTRIES:
		return "异常索引超过前32项"
	case DEBUGGER_ERROR_INTERRUPT_INDEX_IS_NOT_VALID:
		return "中断索引无效"
	case DEBUGGER_ERROR_UNABLE_TO_HIDE_OR_UNHIDE_DEBUGGER:
		return "无法隐藏或取消隐藏调试器"
	case DEBUGGER_ERROR_DEBUGGER_ALREADY_HIDE:
		return "调试器已处于隐藏模式"
	case DEBUGGER_ERROR_EDIT_MEMORY_STATUS_INVALID_PARAMETER:
		return "编辑内存请求参数无效"
	case DEBUGGER_ERROR_EDIT_MEMORY_STATUS_INVALID_ADDRESS_BASED_ON_CURRENT_PROCESS:
		return "基于当前进程的地址无效"
	case DEBUGGER_ERROR_EDIT_MEMORY_STATUS_INVALID_ADDRESS_BASED_ON_OTHER_PROCESS:
		return "基于其他进程的地址无效"
	case DEBUGGER_ERROR_MODIFY_EVENTS_INVALID_TAG:
		return "修改事件时标签无效"
	case DEBUGGER_ERROR_MODIFY_EVENTS_INVALID_TYPE_OF_ACTION:
		return "修改事件时操作类型无效"
	case DEBUGGER_ERROR_STEPPING_INVALID_PARAMETER:
		return "单步执行参数无效"
	case DEBUGGER_ERROR_STEPPINGS_EITHER_THREAD_NOT_FOUND_OR_DISABLED:
		return "线程未找到或已禁用"
	case DEBUGGER_ERROR_PREPARING_DEBUGGEE_INVALID_BAUDRATE:
		return "波特率无效"
	case DEBUGGER_ERROR_PREPARING_DEBUGGEE_INVALID_SERIAL_PORT:
		return "串口无效"
	case DEBUGGER_ERROR_PREPARING_DEBUGGEE_INVALID_CORE_IN_REMOTE_DEBUGGE:
		return "远程调试目标中选择的核心无效"
	case DEBUGGER_ERROR_PREPARING_DEBUGGEE_UNABLE_TO_SWITCH_TO_NEW_PROCESS:
		return "无法切换到新进程"
	case DEBUGGER_ERROR_PREPARING_DEBUGGEE_TO_RUN_SCRIPT:
		return "无法在远程调试目标上运行脚本"
	case DEBUGGER_ERROR_INVALID_REGISTER_NUMBER:
		return "寄存器编号无效"
	case DEBUGGER_ERROR_MAXIMUM_BREAKPOINT_WITHOUT_CONTINUE:
		return "已达到最大断点数，需要继续执行或重新分配缓冲区"
	case DEBUGGER_ERROR_BREAKPOINT_ALREADY_EXISTS_ON_THE_ADDRESS:
		return "目标地址上已存在断点"
	case DEBUGGER_ERROR_BREAKPOINT_ID_NOT_FOUND:
		return "断点ID未找到"
	case DEBUGGER_ERROR_BREAKPOINT_ALREADY_DISABLED:
		return "断点已禁用"
	case DEBUGGER_ERROR_BREAKPOINT_ALREADY_ENABLED:
		return "断点已启用"
	case DEBUGGER_ERROR_MEMORY_TYPE_INVALID:
		return "内存类型无效"
	case DEBUGGER_ERROR_INVALID_PROCESS_ID:
		return "进程ID无效"
	case DEBUGGER_ERROR_EVENT_IS_NOT_APPLIED:
		return "事件未应用"
	case DEBUGGER_ERROR_DETAILS_OR_SWITCH_PROCESS_INVALID_PARAMETER:
		return "进程切换或详情参数无效"
	case DEBUGGER_ERROR_DETAILS_OR_SWITCH_THREAD_INVALID_PARAMETER:
		return "线程切换或详情参数无效"
	case DEBUGGER_ERROR_MAXIMUM_BREAKPOINT_FOR_A_SINGLE_PAGE_IS_HIT:
		return "单页最大断点数已达到"
	case DEBUGGER_ERROR_PRE_ALLOCATED_BUFFER_IS_EMPTY:
		return "预分配缓冲区为空"
	case DEBUGGER_ERROR_EPT_COULD_NOT_SPLIT_THE_LARGE_PAGE_TO_4KB_PAGES:
		return "EPT无法将大页拆分为4KB页"
	case DEBUGGER_ERROR_EPT_FAILED_TO_GET_PML1_ENTRY_OF_TARGET_ADDRESS:
		return "EPT无法获取目标地址的PML1条目"
	case DEBUGGER_ERROR_EPT_MULTIPLE_HOOKS_IN_A_SINGLE_PAGE:
		return "单页中存在多个EPT Hook"
	case DEBUGGER_ERROR_COULD_NOT_BUILD_THE_EPT_HOOK:
		return "无法构建EPT Hook"
	case DEBUGGER_ERROR_COULD_NOT_FIND_ALLOCATION_TYPE:
		return "无法找到分配类型"
	case DEBUGGER_ERROR_INVALID_TEST_QUERY_INDEX:
		return "测试查询索引无效"
	case DEBUGGER_ERROR_UNABLE_TO_ATTACH_TO_TARGET_USER_MODE_PROCESS:
		return "无法附加到目标用户模式进程"
	case DEBUGGER_ERROR_UNABLE_TO_REMOVE_HOOKS_ENTRYPOINT_NOT_REACHED:
		return "无法移除Hook，入口点尚未到达"
	case DEBUGGER_ERROR_UNABLE_TO_REMOVE_HOOKS:
		return "无法移除Hook"
	case DEBUGGER_ERROR_FUNCTIONS_FOR_INITIALIZING_PEB_ADDRESSES_ARE_NOT_INITIALIZED:
		return "初始化PEB地址的函数未初始化"
	case DEBUGGER_ERROR_UNABLE_TO_DETECT_32_BIT_OR_64_BIT_PROCESS:
		return "无法检测进程是32位还是64位"
	case DEBUGGER_ERROR_UNABLE_TO_KILL_THE_PROCESS:
		return "无法终止进程"
	case DEBUGGER_ERROR_INVALID_THREAD_DEBUGGING_TOKEN:
		return "线程调试令牌无效"
	case DEBUGGER_ERROR_UNABLE_TO_PAUSE_THE_PROCESS_THREADS:
		return "无法暂停进程线程"
	case DEBUGGER_ERROR_UNABLE_TO_ATTACH_TO_AN_ALREADY_ATTACHED_PROCESS:
		return "无法附加到已附加的进程"
	case DEBUGGER_ERROR_THE_USER_DEBUGGER_NOT_ATTACHED_TO_THE_PROCESS:
		return "用户调试器未附加到进程"
	case DEBUGGER_ERROR_UNABLE_TO_DETACH_AS_THERE_ARE_PAUSED_THREADS:
		return "无法分离，存在暂停的线程"
	case DEBUGGER_ERROR_UNABLE_TO_SWITCH_PROCESS_ID_OR_THREAD_ID_IS_INVALID:
		return "无法切换，进程ID或线程ID无效"
	case DEBUGGER_ERROR_UNABLE_TO_SWITCH_THERE_IS_NO_THREAD_ON_THE_PROCESS:
		return "无法切换，进程中没有线程"
	case DEBUGGER_ERROR_UNABLE_TO_GET_MODULES_OF_THE_PROCESS:
		return "无法获取进程模块"
	case DEBUGGER_ERROR_UNABLE_TO_GET_CALLSTACK:
		return "无法获取调用栈"
	case DEBUGGER_ERROR_UNABLE_TO_QUERY_COUNT_OF_PROCESSES_OR_THREADS:
		return "无法查询进程或线程计数"
	case DEBUGGER_ERROR_USING_SHORT_CIRCUITING_EVENT_WITH_POST_EVENT_MODE_IS_FORBIDDEDN:
		return "禁止在事件后模式中使用短路事件"
	case DEBUGGER_ERROR_UNKNOWN_TEST_QUERY_RECEIVED:
		return "收到未知测试查询"
	case DEBUGGER_ERROR_READING_MEMORY_INVALID_PARAMETER:
		return "读取内存参数无效"
	case DEBUGGER_ERROR_THE_TRAP_FLAG_LIST_IS_FULL:
		return "陷阱标志列表已满"
	case DEBUGGER_ERROR_UNABLE_TO_KILL_THE_PROCESS_DOES_NOT_EXISTS:
		return "无法终止进程，进程不存在"
	case DEBUGGER_ERROR_MODE_EXECUTION_IS_INVALID:
		return "执行模式无效"
	default:
		return "未知错误"
	}
}

func ShowErrorMessage(errorCode uint32) string {
	e := ErrorCode(errorCode)
	return e.String() + " (0x" + formatHex(errorCode) + ")"
}

func formatHex(v uint32) string {
	const hex = "0123456789ABCDEF"
	var b [8]byte
	for i := 7; i >= 0; i-- {
		b[i] = hex[v&0xF]
		v >>= 4
	}
	return string(b[:])
}
