package debugger

const (
	FILE_DEVICE_UNKNOWN = 0x00000022
	FILE_ANY_ACCESS     = 0
	METHOD_BUFFERED     = 0
)

func CTL_CODE(deviceType, function, method, access uint32) uint32 {
	return (deviceType << 16) | (access << 14) | (function << 2) | method
}

const (
	IOCTL_REGISTER_EVENT = iota + 0x800
	IOCTL_RETURN_IRP_PENDING_PACKETS_AND_DISALLOW_IOCTL
	IOCTL_TERMINATE_VMX
	IOCTL_DEBUGGER_READ_MEMORY
	IOCTL_DEBUGGER_READ_OR_WRITE_MSR
	IOCTL_DEBUGGER_READ_PAGE_TABLE_ENTRIES_DETAILS
	IOCTL_DEBUGGER_REGISTER_EVENT
	IOCTL_DEBUGGER_ADD_ACTION_TO_EVENT
	IOCTL_DEBUGGER_HIDE_AND_UNHIDE_TO_TRANSPARENT_THE_DEBUGGER
	IOCTL_DEBUGGER_VA2PA_AND_PA2VA_COMMANDS
	IOCTL_DEBUGGER_EDIT_MEMORY
	IOCTL_DEBUGGER_SEARCH_MEMORY
	IOCTL_DEBUGGER_MODIFY_EVENTS
	IOCTL_DEBUGGER_FLUSH_LOGGING_BUFFERS
	IOCTL_DEBUGGER_ATTACH_DETACH_USER_MODE_PROCESS
	IOCTL_DEBUGGER_PRINT
	IOCTL_PREPARE_DEBUGGEE
	IOCTL_PAUSE_PACKET_RECEIVED
	IOCTL_SEND_SIGNAL_EXECUTION_IN_DEBUGGEE_FINISHED
	IOCTL_SEND_USERMODE_MESSAGES_TO_DEBUGGER
	IOCTL_SEND_GENERAL_BUFFER_FROM_DEBUGGEE_TO_DEBUGGER
	IOCTL_PERFORM_KERNEL_SIDE_TESTS
	IOCTL_RESERVE_PRE_ALLOCATED_POOLS
	IOCTL_SEND_USER_DEBUGGER_COMMANDS
	IOCTL_GET_DETAIL_OF_ACTIVE_THREADS_AND_PROCESSES
	IOCTL_GET_USER_MODE_MODULE_DETAILS
	IOCTL_QUERY_COUNT_OF_ACTIVE_PROCESSES_OR_THREADS
	IOCTL_GET_LIST_OF_THREADS_AND_PROCESSES
	IOCTL_QUERY_CURRENT_PROCESS
	IOCTL_QUERY_CURRENT_THREAD
	IOCTL_REQUEST_REV_MACHINE_SERVICE
	IOCTL_DEBUGGER_BRING_PAGES_IN
	IOCTL_PREACTIVATE_FUNCTIONALITY
	IOCTL_PCIE_ENDPOINT_ENUM
	IOCTL_PERFORM_ACTIONS_ON_APIC
	IOCTL_PCIDEVINFO_ENUM
	IOCTL_QUERY_IDT_ENTRY
	IOCTL_SET_BREAKPOINT_USER_DEBUGGER
	IOCTL_PERFORM_SMI_OPERATION
	IOCTL_SWITCH_PROCESS
	IOCTL_SWITCH_THREAD
	IOCTL_READ_CONTROL_REGISTER
	IOCTL_KILL_PROCESS
	IOCTL_RESTART_PROCESS
	IOCTL_EVALUATE_EXPRESSION
)

type IoctlCode uint32

var IoctlNames = map[IoctlCode]string{
	IOCTL_REGISTER_EVENT: "IOCTL_REGISTER_EVENT",
	IOCTL_RETURN_IRP_PENDING_PACKETS_AND_DISALLOW_IOCTL: "IOCTL_RETURN_IRP_PENDING_PACKETS_AND_DISALLOW_IOCTL",
	IOCTL_TERMINATE_VMX:                                        "IOCTL_TERMINATE_VMX",
	IOCTL_DEBUGGER_READ_MEMORY:                                 "IOCTL_DEBUGGER_READ_MEMORY",
	IOCTL_DEBUGGER_READ_OR_WRITE_MSR:                           "IOCTL_DEBUGGER_READ_OR_WRITE_MSR",
	IOCTL_DEBUGGER_READ_PAGE_TABLE_ENTRIES_DETAILS:             "IOCTL_DEBUGGER_READ_PAGE_TABLE_ENTRIES_DETAILS",
	IOCTL_DEBUGGER_REGISTER_EVENT:                              "IOCTL_DEBUGGER_REGISTER_EVENT",
	IOCTL_DEBUGGER_ADD_ACTION_TO_EVENT:                         "IOCTL_DEBUGGER_ADD_ACTION_TO_EVENT",
	IOCTL_DEBUGGER_HIDE_AND_UNHIDE_TO_TRANSPARENT_THE_DEBUGGER: "IOCTL_DEBUGGER_HIDE_AND_UNHIDE_TO_TRANSPARENT_THE_DEBUGGER",
	IOCTL_DEBUGGER_VA2PA_AND_PA2VA_COMMANDS:                    "IOCTL_DEBUGGER_VA2PA_AND_PA2VA_COMMANDS",
	IOCTL_DEBUGGER_EDIT_MEMORY:                                 "IOCTL_DEBUGGER_EDIT_MEMORY",
	IOCTL_DEBUGGER_SEARCH_MEMORY:                               "IOCTL_DEBUGGER_SEARCH_MEMORY",
	IOCTL_DEBUGGER_MODIFY_EVENTS:                               "IOCTL_DEBUGGER_MODIFY_EVENTS",
	IOCTL_DEBUGGER_FLUSH_LOGGING_BUFFERS:                       "IOCTL_DEBUGGER_FLUSH_LOGGING_BUFFERS",
	IOCTL_DEBUGGER_ATTACH_DETACH_USER_MODE_PROCESS:             "IOCTL_DEBUGGER_ATTACH_DETACH_USER_MODE_PROCESS",
	IOCTL_DEBUGGER_PRINT:                                       "IOCTL_DEBUGGER_PRINT",
	IOCTL_PREPARE_DEBUGGEE:                                     "IOCTL_PREPARE_DEBUGGEE",
	IOCTL_PAUSE_PACKET_RECEIVED:                                "IOCTL_PAUSE_PACKET_RECEIVED",
	IOCTL_SEND_SIGNAL_EXECUTION_IN_DEBUGGEE_FINISHED:           "IOCTL_SEND_SIGNAL_EXECUTION_IN_DEBUGGEE_FINISHED",
	IOCTL_SEND_USERMODE_MESSAGES_TO_DEBUGGER:                   "IOCTL_SEND_USERMODE_MESSAGES_TO_DEBUGGER",
	IOCTL_SEND_GENERAL_BUFFER_FROM_DEBUGGEE_TO_DEBUGGER:        "IOCTL_SEND_GENERAL_BUFFER_FROM_DEBUGGEE_TO_DEBUGGER",
	IOCTL_PERFORM_KERNEL_SIDE_TESTS:                            "IOCTL_PERFORM_KERNEL_SIDE_TESTS",
	IOCTL_RESERVE_PRE_ALLOCATED_POOLS:                          "IOCTL_RESERVE_PRE_ALLOCATED_POOLS",
	IOCTL_SEND_USER_DEBUGGER_COMMANDS:                          "IOCTL_SEND_USER_DEBUGGER_COMMANDS",
	IOCTL_GET_DETAIL_OF_ACTIVE_THREADS_AND_PROCESSES:           "IOCTL_GET_DETAIL_OF_ACTIVE_THREADS_AND_PROCESSES",
	IOCTL_GET_USER_MODE_MODULE_DETAILS:                         "IOCTL_GET_USER_MODE_MODULE_DETAILS",
	IOCTL_QUERY_COUNT_OF_ACTIVE_PROCESSES_OR_THREADS:           "IOCTL_QUERY_COUNT_OF_ACTIVE_PROCESSES_OR_THREADS",
	IOCTL_GET_LIST_OF_THREADS_AND_PROCESSES:                    "IOCTL_GET_LIST_OF_THREADS_AND_PROCESSES",
	IOCTL_QUERY_CURRENT_PROCESS:                                "IOCTL_QUERY_CURRENT_PROCESS",
	IOCTL_QUERY_CURRENT_THREAD:                                 "IOCTL_QUERY_CURRENT_THREAD",
	IOCTL_REQUEST_REV_MACHINE_SERVICE:                          "IOCTL_REQUEST_REV_MACHINE_SERVICE",
	IOCTL_DEBUGGER_BRING_PAGES_IN:                              "IOCTL_DEBUGGER_BRING_PAGES_IN",
	IOCTL_PREACTIVATE_FUNCTIONALITY:                            "IOCTL_PREACTIVATE_FUNCTIONALITY",
	IOCTL_PCIE_ENDPOINT_ENUM:                                   "IOCTL_PCIE_ENDPOINT_ENUM",
	IOCTL_PERFORM_ACTIONS_ON_APIC:                              "IOCTL_PERFORM_ACTIONS_ON_APIC",
	IOCTL_PCIDEVINFO_ENUM:                                      "IOCTL_PCIDEVINFO_ENUM",
	IOCTL_QUERY_IDT_ENTRY:                                      "IOCTL_QUERY_IDT_ENTRY",
	IOCTL_SET_BREAKPOINT_USER_DEBUGGER:                         "IOCTL_SET_BREAKPOINT_USER_DEBUGGER",
	IOCTL_PERFORM_SMI_OPERATION:                                "IOCTL_PERFORM_SMI_OPERATION",
	IOCTL_SWITCH_PROCESS:                                       "IOCTL_SWITCH_PROCESS",
	IOCTL_SWITCH_THREAD:                                        "IOCTL_SWITCH_THREAD",
	IOCTL_READ_CONTROL_REGISTER:                                "IOCTL_READ_CONTROL_REGISTER",
	IOCTL_KILL_PROCESS:                                         "IOCTL_KILL_PROCESS",
	IOCTL_RESTART_PROCESS:                                      "IOCTL_RESTART_PROCESS",
	IOCTL_EVALUATE_EXPRESSION:                                  "IOCTL_EVALUATE_EXPRESSION",
}

func (c IoctlCode) String() string {
	if name, ok := IoctlNames[c]; ok {
		return name
	}
	return "IOCTL_UNKNOWN"
}
