name: Build and Test on Windows

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Download latest HyperDbg release
      run: |
        curl -s https://api.github.com/repos/HyperDbg/HyperDbg/releases/latest `
        | jq -r '.assets[] | select(.name | test("\\.zip$")) | .browser_download_url' `
        | % { Invoke-WebRequest $_ -OutFile 'hyperdbg.zip' }

    - name: Unzip HyperDbg
      run: |
        Expand-Archive -Path hyperdbg.zip -DestinationPath hyperdbg

    - name: List contents of HyperDbg
      run: |
        Get-ChildItem -Path hyperdbg -Recurse

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: '1.22.4'

    - name: Install dependencies
      run: go mod tidy

    - name: Copy SDK directory and bin to target path,latest remove
      run: |
#        remove HyperDbg/release/SDK/Libraries
#        xcopy hyperdbg\SDK\* .\gui\sdk\bindgen\SDK\ /E /H /Y
        xcopy HyperDbg\SDK\* .\gui\sdk\bindgen\SDK\ /E /H /Y
#        copy  ".exe", ".dll", ".sys" from HyperDbg/release into sdk/bin
#    remove HyperDbg.zip and HyperDbg folder

# now merge into pre-release.yml for generating GitHub Changelog Generator  and release etc

#    - name: Run tests for auto bind sdk
#      run: go test ./...
#
#    - name: Build the project
#      run: go build ./...
#      pack HyperDbg.exe to HyperDbg.zip
#      upload HyperDbg.zip to release