name: go-mod-ci

on:
  push:
    branches:
      - master
      - dev
    tags:
      - 'v*'

env:
  RELEASE_ZIP_FILE_NAME: ux

jobs:
  test-on-multiple-os:
    name: Test on multiple OS
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ windows-latest ]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.25.0-rc.1'

      # manjaro linux
      # gioui提示vulkan构建约束被排除的原因是没有安装gcc，termux可以试试是不是这个原因
      # sudo pacman -S pkg-config vulkan-headers gcc clang cmake
      # yay -S android-sdk-build-tools  android-sdk-platform-tools
      # yay -S android-platform
      # go env -w GOPROXY=https://goproxy.cn,direct
      # go run 需要sudo

      - name: Install C library dependencies on Ubuntu
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt install gcc pkg-config libwayland-dev libx11-dev libx11-xcb-dev libxkbcommon-x11-dev libgles2-mesa-dev libegl1-mesa-dev libffi-dev libxcursor-dev libvulkan-dev

      #      - name: Install C library dependencies on macOS
      #        if: matrix.os == 'macos-latest'
      #        run: |
      #          brew update
      #          brew install xcode

      - name: Install Go dependencies
        run: go mod tidy

      - name: Run tests
        run: go run golang.org/x/tools/gopls/internal/analysis/modernize/cmd/modernize@latest -diff ./...  &&  go run golang.org/x/tools/gopls/internal/analysis/modernize/cmd/modernize@latest -fix ./...


  package-and-release:
    if: startsWith(github.ref, 'refs/tags/v')
    needs: test-on-multiple-os
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.25.0-rc.1'

      - name: Install dependencies
        run: go mod tidy

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0.0'

      - name: Install GitHub Changelog Generator
        run: gem install github_changelog_generator

      - name: Generate Changelog
        run: github_changelog_generator --user ${{ github.repository_owner }} --project ${{ github.event.repository.name }} --token ${{ secrets.GITHUB_TOKEN }}

      - name: Create source code archive
        run: zip -r ${{ env.RELEASE_ZIP_FILE_NAME }}-${{ github.ref_name }}.zip . -x '.git/**'

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ${{ env.RELEASE_ZIP_FILE_NAME }}-${{ github.ref_name }}.zip
          body_path: CHANGELOG.md
        env:
          GITHUB_TOKEN: ${{ secrets.tk }}
